### ISSUE TITLE
Updater non-functional

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1000]
The Updater will not take input from anything. It should take input from any box that has instantiated model within it:   an IM box; an Estimation box; a Simulation box.

**Comment by chirayukong** [comment]
The updater can take input from IM and being created. Can take from the estimator box but got the error message. Won't connect to the simulation box at all.
<img width="1038" alt="Screen Shot 2019-03-25 at 3 03 06 PM" src="https://user-images.githubusercontent.com/4652250/54946884-72c30d00-4f0f-11e9-88fa-a61e1d9e7f6e.png">

I'm looking to it.

**Comment by cg09** [comment]
Dear Kong and Greg

Joe, Madelyn and I have just spent some time with the Classifier box. We
recommend that it be removed from the interface.  Aside from bugs, it is
not actually a classifier in the usual sense, and does nothing we can
imagine would ever be useful.  It takes the IM of a Bayes model, and a data
set, and then uses the model to change the value in each row of a user
specified value to the value predicted by the Bayes net model from the
values for that row of every other variable.

Clark, Joe and Madelyn

**Comment by jdramsey** [comment]
The estimator->updator issue is working for me. Maybe it was fixed by someone.

**Comment by cg09** [comment]
Have you tried it on a mac?

**Comment by jdramsey** [comment]
Yeah, that's all I have. I think maybe Kong fixed it. I grabbed another Tetrad using Jeremy's magic link.

**Comment by cg09** [comment]
Thanks for doing and checking all this today.

**Comment by cg09** [comment]
Joe,  I don't know what the "Ensemble" parameter does for BPC and FOFC, but
the only parameter value that works is "0" which is called "preserve."
Please see attached 6.7.0-0 session.

Clark

**Comment by chirayukong** [comment]
The IM -> updator and the estimator -> updator are working on the single dataset, not multiple ones. I'm looking at the simulator one.
<img width="900" alt="Screen Shot 2019-04-03 at 2 28 24 PM" src="https://user-images.githubusercontent.com/4652250/55503503-c541af00-561c-11e9-9e59-2dda9ee91907.png">
