### ISSUE TITLE
Can't connect Simulation and IM to (Bayes and SEM) Estimator

### ISSUE THREAD

**Issue by chirayukong** [cmu-phil/tetrad#1001]
<img width="983" alt="Screen Shot 2019-03-25 at 12 43 26 PM" src="https://user-images.githubusercontent.com/4652250/54937945-cc214100-4efb-11e9-834e-025c280735e9.png">

**Comment by chirayukong** [comment]
https://github.com/cmu-phil/tetrad/pull/1010

**Comment by jdramsey** [comment]
This is fixed.
