### ISSUE TITLE
No arrowheads on added/removed edges in edgewise comparisons

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#1003]
In the edgewise comparisons function, added/removed edges show up as undirected, even though the added/removed edges are generally directed. I think this may have been an intentional choice made at some point (added/removed edges used to show up oriented in the same direction that they were in the graph) to distinguish between entire edges that are different and the orientations that are different in the reorientation section, but in practice it ends up looking as though one of the graphs has some actual undirected edges that the other does not. (Which is, of course, also a possibility!) I think, and Clark agrees, that arrowheads should be added back onto the edges in the added/removed edges sections.

**Comment by kvb2univpitt** [comment]
I agree.  I'll work on this.

**Comment by kvb2univpitt** [comment]
Fixed.
![arrowhead](https://user-images.githubusercontent.com/10729309/55023414-204b2480-4fd3-11e9-87d5-d8346e6fd80e.png)

**Comment by mglymour** [comment]
Awesome, thank you!
