### ISSUE TITLE
MImbuild does not work in 6.7.0-0. 

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1015]

**Comment by jdramsey** [comment]
This works, I think. It does for me.

**Comment by kvb2univpitt** [comment]
@cg09 Can you please provide a screenshot of the error?

**Comment by cg09** [comment]
Kevin,

To which error do you refer?

**Comment by kvb2univpitt** [comment]
@cg09 Hi Clark.  The error that shows MImbuild not working in 6.7.0-0.  Are you talking about the MImbuild from the algorithm list or from the pipline?

**Comment by cg09** [comment]
Sorry, I don't remember.

**Comment by yuanzhou** [comment]
Close this one since MimBuild has been put into FOFC.
