### ISSUE TITLE
Add CFI and RMSEA to Tetrad

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#103]
Joe, I'm glad you might be able to help me with my question about getting additional fit indices from a causal path analysis with tetrad (I'm thinking CFI and RMSEA). Do you know how to do that?

RMSEA is computed as e / (df * (N-1)), with e being the error of approximation of the model,and df being the degrees of freedom, and N being sample size.

CFI is computed as (d(Null Model) - d(Proposed Model)) / d(Null Model), with d = Chi-square - df.

I'm attaching the tetrad file, which contains the two models for which I need these indices (not sure if you need those). Please let me know if you need anything else,

e is the sum of the residuals.

**Comment by jdramsey** [comment]
What is the null model for CFI? Is it the model with no edges in it?

**Comment by ps7z** [comment]
I am not sure of the context for the question. In terms of comparing output to a standard model to calculate a chi-squared, we usually compare it to a complete model, as we do with patterns.

Peter

**Comment by jdramsey** [comment]
Thanks, I'll do it that way.

Joe

On Wed, Dec 23, 2015 at 4:49 PM, ps7z <notifications@github.com> wrote:

> I am not sure of the context for the question. In terms of comparing
> output to a standard model to calculate a chi-squared, we usually compare
> it to a complete model, as we do with patterns.
>
> Peter
>
>
> From: Joseph Ramsey <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: cmu-phil/tetrad <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Wednesday, December 23, 2015 at 11:55 AM
> To: cmu-phil/tetrad <tetrad@noreply.github.com<mailto:
> tetrad@noreply.github.com>>
> Subject: Re: [tetrad] Add CFI and RMSEA to Tetrad (#103)
>
>
> What is the null model for CFI? Is it the model with no edges in it?
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/cmu-phil/tetrad/issues/103#issuecomment-166958011>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/103#issuecomment-166997668>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Conversation ensured in email. Using this website: http://davidakenny.net/cm/fit.htm for definitions of scores with this website: http://zencaroline.blogspot.com/2007/08/null-model-in-sem.html for definitions of various SEM-related models. Done. Closing. Needs to be posted at some point.
