### ISSUE TITLE
Add a facility for the tabular comparison to let users choose the statistics they want to display.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1034]
There are quite a number of statistics that can be display; a simple interface that lets the user pick from these to construct an ordered list of statistics to display would help. Otherwise, they're stuck with the built-in choices. This could benefit from some HCI input.

**Comment by jdramsey** [comment]
We want instead to replace the tabular editor with just a list of statistics.

**Comment by cg09** [comment]
Ok with me.
