### ISSUE TITLE
GraphUtils.loadGraphTxt() Load in the Wrong Type of Node

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#104]
The static method GraphUtils.loadGraphTxt(File file) reads in the node as GraphNode.  However, the static method DataWriter.writeRectangularData() expects the node of type ContinuousVariable or DiscreteVariable.  Thus, you can create simulated dataset by reading a Graph from a file but CANNOT write the dataset to a file.

**Comment by jdramsey** [comment]
Do you have a unit test for this that I can play with?

**Comment by kvb2univpitt** [comment]
Yes, I do.  The test method is testSimulateDatasetFromGraph() and it's in  edu.cmu.tetrad.cli.data.SimulateDataFromGraphCliTest class in the tetrad-cli module.

I actually wrote a method GraphFactory.loadGraphAsContinuousVariables() to solve this problem.  You can close this issue now.

**Comment by jdramsey** [comment]
Oh cool! :) OK, closing. Sorry, I thought this was more work for me.
