### ISSUE TITLE
Logistic regression tool assumes binary discrete varaibles.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1040]
That's not the problem; the sort of logistic regression being done is the sort that assumes binary discrete variables with additional continuous variables. The target needs to be binary. The other discrete variables need to be binary as well. 

The problem is that this is unobvious to users, who try to use the tool with any sort of mixed data. The solution is to check the dataset for this tool and throw an exception if it contains any discrete variables that aren't binary.

**Comment by cg09** [comment]
Do you mean that the set up requires: binary or continuous or both
predictors; and binary outcome?

**Comment by jdramsey** [comment]
Precisely

**Comment by jdramsey** [comment]
Fixed. https://github.com/cmu-phil/tetrad/pull/1059
