### ISSUE TITLE
Inconsistency of Bayes variables more than two from IM

### ISSUE THREAD

**Issue by chirayukong** [cmu-phil/tetrad#1042]
Two cases: 1) If a simulation box for Bayes net was run and re-run (without destroying the model) for a single simulation (single run), the IM box will have a wrong number of categories for some of the variables.
2) If a sim box was run for multiple simulations (say 10), the IM box will have a wrong number of categories.
The saved session is also attached here.

[Inconsistency_var_categories.tet.zip](https://github.com/cmu-phil/tetrad/files/3048881/Inconsistency_var_categories.tet.zip)
<img width="568" alt="Screen Shot 2019-04-05 at 12 32 30 PM" src="https://user-images.githubusercontent.com/4652250/55643310-d4ea0080-57a0-11e9-9652-411be3d8ba72.png">
<img width="597" alt="Screen Shot 2019-04-05 at 12 32 45 PM" src="https://user-images.githubusercontent.com/4652250/55643311-d4ea0080-57a0-11e9-81ff-f8a360069c94.png">

**Comment by jdramsey** [comment]
Hmm... well, this can't be good...

<img width="816" alt="Screen Shot 2019-04-05 at 1 48 56 PM" src="https://user-images.githubusercontent.com/9853255/55646647-b76d6480-57a9-11e9-83e6-47535a8cf0e9.png">

Seems like the bayes IM is not being set in Simulation.

**Comment by jdramsey** [comment]
The small change in branch broken.bayesim.problem fixes the left hand problem (single Bayes net). The right hand problem still is eluding me.

@chirayukong

**Comment by chirayukong** [comment]
It works. Thanks @jdramsey.

**Comment by jdramsey** [comment]
I think I just solved the other one. 

https://github.com/cmu-phil/tetrad/pull/1045

**Comment by jdramsey** [comment]
@chirayukong Is this OK now? It seems to work for me. Can I close it?

**Comment by chirayukong** [comment]
Yes, it does. @jdramsey You can close this issue.

**Comment by jdramsey** [comment]
Awesome! Thanks! Progress! :)
