### ISSUE TITLE
Delta tetrad test not giving Bollen's chi square values anymore.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#105]
See the test; Bollen's answers are in the comments. Read Bollen and Ting's paper too.

**Comment by jdramsey** [comment]
The main issue for 

    // Bollen and Ting p. 167 (Confirmatory Tetrad Analysis). Union Sentiment.

seems to be the sign of the second term in this formula:

double _ss = sxy(e, g) * sxy(f, h) + sxy(e, h) * sxy(f, g);   // + or -? Different advise. + in the code.

Different formulas are given in different parts of the paper, but it we get closer to their figures if it's - instead of +. FOFC results seem to be more accurate as well, though I'm not completely sure. We had discussed this before and set it to +. Need to be sure.

Note that the numbers don't come out *exactly* as Bollen and Ting's, just very close. I'm not sure why we don't get exactly their figures.

**Comment by ps7z** [comment]
Joe,

The attached article by BOllen and Ting has the same formula as the 1993 article, except with the minus sign. One problem with the minus sign is that it introduces an asymmetry into the formula that I am not sure make sense. I will look into this further.

Peter

**Comment by ps7z** [comment]
Joe,


Someone needs to check out the following article which should have the correct answer:

Browne, M. W. 1984. "Asymptotic Distribution Free Methods in Analysis of

Covariance Structures." British Journal of Mathematical and Statistical Psychology

37:62-8.3.


Peter

**Comment by jdramsey** [comment]
Thanks--I look for this in a bit.

Joe

On Thu, Dec 24, 2015 at 11:52 AM, ps7z <notifications@github.com> wrote:

> Joe,
>
>
> Someone needs to check out the following article which should have the
> correct answer:
>
> Browne, M. W. 1984. "Asymptotic Distribution Free Methods in Analysis of
>
> Covariance Structures." British Journal of Mathematical and Statistical
> Psychology
>
> 37:62-8.3.
>
>
> Peter
>
> From: Joseph Ramsey <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: cmu-phil/tetrad <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Thursday, December 24, 2015 at 9:12 AM
> To: cmu-phil/tetrad <tetrad@noreply.github.com<mailto:
> tetrad@noreply.github.com>>
> Subject: Re: [tetrad] Delta tetrad test not giving Bollen's chi square
> values anymore. (#105)
>
>
> The main issue for
>
> // Bollen and Ting p. 167 (Confirmatory Tetrad Analysis). Union Sentiment.
>
>
> seems to be the sign of the second term in this formula:
>
> double _ss = sxy(e, g) * sxy(f, h) + sxy(e, h) * sxy(f, g); // + or -?
> Different advise. + in the code.
>
> Different formulas are given in different parts of the paper, but it we
> get closer to their figures if it's - instead of +. FOFC results seem to be
> more accurate as well, though I'm not completely sure. We had discussed
> this before and set it to +. Need to be sure.
>
> Note that the numbers don't come out exactly as Bollen and Ting's, just
> very close. I'm not sure why we don't get exactly their figures.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/cmu-phil/tetrad/issues/105#issuecomment-167122473>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/105#issuecomment-167136370>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Peter,

Do you happen to have a copy of that article you recommended? The Google Scholar link is dead. If you I'll find another way.

Thanks,

Joe

**Comment by ps7z** [comment]
Joe,

I don't have it or I would have looked it up myself. I could not find one online, but the library should have the journal in hard-copy.

Peter

**Comment by jdramsey** [comment]
Great, thanks--I'll head over to the library when I get a chance.

Joe

On Thu, Dec 24, 2015 at 3:25 PM, ps7z <notifications@github.com> wrote:

> Joe,
>
> I don't have it or I would have looked it up myself. I could not find one
> online, but the library should have the journal in hard-copy.
>
> Peter
>
>
> From: Joseph Ramsey <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: cmu-phil/tetrad <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Thursday, December 24, 2015 at 2:01 PM
> To: cmu-phil/tetrad <tetrad@noreply.github.com<mailto:
> tetrad@noreply.github.com>>
> Cc: User <ps7z@andrew.cmu.edu<mailto:ps7z@andrew.cmu.edu>>
> Subject: Re: [tetrad] Delta tetrad test not giving Bollen's chi square
> values anymore. (#105)
>
>
> Peter,
>
> Do you happen to have a copy of that article you recommended? The Google
> Scholar link is dead. If you I'll find another way.
>
> Thanks,
>
> Joe
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/cmu-phil/tetrad/issues/105#issuecomment-167154800>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/105#issuecomment-167155953>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I did some more experiments; it actually doesn't seem to matter to the accuracy of FOFC whether this is a + or a -.
