### ISSUE TITLE
Bayes IM Observed Vars Only will not simulate

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#1054]
In 6.7.0-0, using a Bayes IM with observed variables only to simulate results in a simulation that contains 0s for all datapoints. (Or whatever non-numerical value has been associated with 0, for non-ordered data.)

[bayesimobserved.tet.zip](https://github.com/cmu-phil/tetrad/files/3056071/bayesimobserved.tet.zip)

**Comment by cg09** [comment]
What is your point?

**Comment by mglymour** [comment]
Instead of simulating varied data, it simulates all zeroes. Is that the intended functionality?

**Comment by jdramsey** [comment]
@mglymour @cg09 Yeah I think this needs to be removed, if only on the grounds that none of us remembers what it was supposed to do anymore.

I looked in the code; it doesn't seems to be doing anything helpful.

@yuanzhou I think this just needs to be commented out of the spec--do you want me to do it?

**Comment by yuanzhou** [comment]
@jdramsey please do.
