### ISSUE TITLE
Unchecking "Pick new random values" box in Bayes IM does not work

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#1063]
In 6.7.0-0, when creating a Bayes IM, if you choose to randomly assign probability values, there is a check box that says, "Pick new random values every time this Bayes IM is re-initialized." This check box does not appear to do anything. Whether it is checked or unchecked, the probability values change every time the IM is re-initialized.

Similarly, there's a check box in the SEM IM that says "Pick new random values each time this SEM IM is initialized." It also does not do anything.
<img width="595" alt="Screen Shot 2019-04-10 at 3 01 26 PM" src="https://user-images.githubusercontent.com/15677053/55906226-bf5e4780-5ba1-11e9-8788-caf7ab2ba92b.png">

**Comment by jdramsey** [comment]
I think these checkboxes can simply be removed from the interface without any ill effects.
