### ISSUE TITLE
DEfault parameters in IM Box

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1067]
In the SEM IM interface, the default values for error covariances should be 0.0 to 0.0.  That indicates no correlated errors, and is the most common assumption

**Comment by jdramsey** [comment]
See https://github.com/cmu-phil/tetrad/issues/1065.

**Comment by jdramsey** [comment]
@cg09 I guess I can work on these default parameters now. I'll reset all of the default parameters in https://github.com/cmu-phil/tetrad/issues/1065.

**Comment by jdramsey** [comment]
@cg09 My other pull request covers this.
