### ISSUE TITLE
Estimator

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1068]
If you enter a model  without a latent variable into an Estimator box and  select EM, you get an error message--"EM requires models with a latent variable".   Ok, that's an arbitrary limitation but we can live with it.  BUT when you delete the contents of the Estimator box and reopen it, where you should get an interface with the a choice of estimators, you instead get the same error message, even though no estimator has been selected.  6.7.0

**Comment by jdramsey** [comment]
This was fixed. Works now.
