### ISSUE TITLE
Bayes Parametric Model Variable Ordering

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1084]
The ordering of selected node is incorrect.  The ordering goes from X1 -> X10 -> X2 instead of X1 -> X2 -> X10

![ordering](https://user-images.githubusercontent.com/10729309/56302534-f683aa00-6107-11e9-92d3-f8f5abcb880f.png)

**Comment by jdramsey** [comment]
@kvb2univpitt This doesn't happen on my machine.

**Comment by yuanzhou** [comment]
I did see the same incorrect ordering with the latest development. When clicked the down arrow next to the "Next" button, I saw X1 -> X10 -> X2 ...

![d](https://user-images.githubusercontent.com/195873/56367835-2abca080-61c4-11e9-9af9-39c4b8498786.jpg)

**Comment by kvb2univpitt** [comment]
@jdramsey I should have made it clear that it was the JComboBox that's had incorrect ordering, as @yuanzhou screenshot shown above.

**Comment by kvb2univpitt** [comment]
Fixed.

![Screenshot from 2019-04-18 11-30-34](https://user-images.githubusercontent.com/10729309/56373526-20ec6a80-61cf-11e9-8b36-f5ce9bfd9111.png)

**Comment by jdramsey** [comment]
Yay!
