### ISSUE TITLE
limit number of threads

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#109]
Is there a flag or parameter to limit the number of threads used in FGS?

**Comment by espinoj** [comment]
found it setNumProcessors in Fgs.java

**Comment by jdramsey** [comment]
Yeah that's it.

On Thu, Dec 17, 2015 at 10:08 AM, Jeremy Espino <notifications@github.com>
wrote:

> Closed #109 <https://github.com/cmu-phil/tetrad/issues/109>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/109#event-494778436>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey
