### ISSUE TITLE
Suggested defaults for discrete searches

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1090]
Based on simulations with variables with 3 categories using the algorithm comparison tool, some recommended defaults:

* Alpha for discrete variable searches with PC algorithms = 0.05

   - This is apparently different from continuous searches, so need a separate parameter under the hood.

* Collider discover rule for PC searches = CPC

  - For very small searches, PC-Max

* Conflict rule for PC searches = prioritize existing colliders

* Sample prior for FGES/BDeu searches = 20

* Structure prior = depends on the density but a default might be 3

**Comment by jdramsey** [comment]
Note that our current defaults for sample prior and structure prior for FGES/BDeu lead to some very bad searches, so this should be changed soon. On it.

**Comment by jdramsey** [comment]
Looking at models with 2-4 categories randomly across variables. The advice holds up pretty well. Maybe a default of 15 instead of 20 for FGES/BDeu is better. Also, PC-Max is better for sample size 100 as well, so the advice should be that for small sample sizes PC-Max is better; for sample sizes > 100 CPC. (I checked sample size 200--CPC was better.)

**Comment by jdramsey** [comment]
I left out one search option--FGES/Discrete BIC. I ran a comparison of FGES/BDeu against FGES/Discrete BIC. Usually the BDeu option is better, with the default sample and structure priors above, but discrete BIC is almost as good. The best penalty discount for it is clearly 1 (every time). Maybe we should just remove the penalty discount option for this.

**Comment by jdramsey** [comment]
Also, penalty discount for discrete BIC should according to all of my result always be set to 1 (standard BIC). We can effectively remove penalty discount as a parameter for this score.

**Comment by cg09** [comment]
what does "very small" searches mean--variables or samples and how small,
roughly of course.

**Comment by jdramsey** [comment]
@cg09 I mean by "very small" sample sizes of 100 or less. I know not everything thinks that's small, but from the point of view of our searches it definitely is.
