### ISSUE TITLE
Search Box Only Shows One Algorithm on Graph Import

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1093]
Search box only shows TsIMages for graph input.
![algo_search](https://user-images.githubusercontent.com/10729309/56524251-1572a980-6517-11e9-8663-07fd568156dc.png)

**Comment by kvb2univpitt** [comment]
@yuanzhou We missed this edge case.

**Comment by yuanzhou** [comment]
Good catch!
