### ISSUE TITLE
Bootstrap error when running search on a graph

### ISSUE THREAD

**Issue by yuanzhou** [cmu-phil/tetrad#1096]
Noticed this error when running GFCI with bootstrap on a graph with D-Separation. It works fine without bootstrap.

![Capture](https://user-images.githubusercontent.com/195873/56759542-329db700-6767-11e9-9e31-d95c1ffe0837.PNG)

After clicking the "Run Search" button you won't see any popups in GUI. But the console has this error:

![Capture2](https://user-images.githubusercontent.com/195873/56759543-35001100-6767-11e9-9a8b-14cf894f1654.PNG)

**Comment by yuanzhou** [comment]
@chirayukong can you take a look since you know best about the bootstrap coding?

**Comment by chirayukong** [comment]
Could you give me the parameters in the simulation box? @yuanzhou

**Comment by chirayukong** [comment]
Oh, in the bootstrapping mode, it can run only with dataset(s) input, not a graph. How could we do subsampling when there is no data?

**Comment by yuanzhou** [comment]
@chirayukong if bootstraping is only supposed to run with dataset input, should we hide the bootstraping parameters when there's only graph input? Otherwise it'll confuse the users in both tetrad and cytoscape tetrad-express. I noticed this behavior when testing the cytoscape tetrad-express with graph input. And it turned out to be the cause in tetrad.

@kvb2univpitt any thoughts?

**Comment by chirayukong** [comment]
I think so. We should hide the bootstrapping parameters when there is no dataset input.

**Comment by kvb2univpitt** [comment]
@yuanzhou @chirayukong Fixed!  Bootstrap parameters are removed from search on graph.

Search on data:
![data_search](https://user-images.githubusercontent.com/10729309/56853173-ffd3fa00-68f1-11e9-8f6b-7b0ad4ecb85c.png)

Search on graph:
![graph_search](https://user-images.githubusercontent.com/10729309/56853174-03678100-68f2-11e9-9bed-54226092ff4b.png)

**Comment by chirayukong** [comment]
Superb!

**Comment by yuanzhou** [comment]
@kvb2univpitt Thanks Kevin! I'm looking at the pull request now.
