### ISSUE TITLE
parameter defaults are giving grief

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1097]
Earlier today I cloned the development branch.  When running the algorithm comparison tool, the parameter defaults appear to not be working. When you leave certain parameters blank, my understanding is that the tool will go grab them from elsewhere, but that no longer seems to be working and I have to specify them all manually.

**Comment by bja43** [comment]
Nevermind, the issue was fixed by running Maven clean and Maven compile.

**Comment by yuanzhou** [comment]
FYI @bja43 we redesigned the parameters, and now the GUI goes to the HTML manual to fetch the descriptions as well as default values. You are right, you have to do a clean build so the HTML manual gets included into the jar file.

**Comment by cg09** [comment]
Madelyn should be done soon with putting Manual revisions into HTML.  Of
course, what we have written is already a little out of date!
