### ISSUE TITLE
Why No Resampling/Bootstrap for MimBuild?

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1100]
It would be good to have resampling for all search algorithms. I find better behavior for MimBuild with resampling

**Comment by yuanzhou** [comment]
I remember @jdramsey moved MimBuild into FOFC as an option. And there's resampling parameters.

![Capture](https://user-images.githubusercontent.com/195873/56903741-e0aca800-6a6a-11e9-9523-621ee5fff49c.PNG)

**Comment by cg09** [comment]
Thanks.

**Comment by jdramsey** [comment]
Fixed.
