### ISSUE TITLE
MImBuild Interface Error

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1101]
MimBuild has a "Washdown" algorithm alternative that no longer exists. See picture
<img width="858" alt="Screen Shot 2019-04-27 at 7 02 09 PM" src="https://user-images.githubusercontent.com/16354745/56855976-1c3a5b80-691f-11e9-8037-f5b32d9771a4.png">

**Comment by jdramsey** [comment]
This must be an old version of Tetrad...

**Comment by jdramsey** [comment]
This interface has been removed.
