### ISSUE TITLE
question about edge probability output

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1104]

**Comment by cg09** [comment]
Running FAS I obtain an X1 - X5 edge.  The edge probability table says:

<img width="365" alt="Screen Shot 2019-04-28 at 7 37 31 PM" src="https://user-images.githubusercontent.com/16354745/56871537-638f1d80-69ed-11e9-8743-3f8466353028.png">

Why does "no edge" have the same probability as "ensemble", and why is the probability of "no edge" equal to .9901? No resampling was done with the search.

**Comment by chirayukong** [comment]
It was a bug on the "preserved" ensemble method that always picks the max probability. Fixed https://github.com/cmu-phil/tetrad/pull/1105.

**Comment by chirayukong** [comment]
<img width="825" alt="Screen Shot 2019-04-29 at 10 58 40 AM" src="https://user-images.githubusercontent.com/4652250/56905574-76960200-6a6e-11e9-8ae7-cac0459b936b.png">
