### ISSUE TITLE
Only show edge type probabilities columns when there's a bootstraping

### ISSUE THREAD

**Issue by yuanzhou** [cmu-phil/tetrad#1107]
Currently, in the Graph box, we have a table under the graph that shows the edges and edge type probabilities. Those edge type probabilities columns will confuse users since there's no bootstraping. 

![Capture](https://user-images.githubusercontent.com/195873/56976016-0192fd00-6b40-11e9-9c86-bc4047d54974.PNG)

And similarly,  in the search resulting graph panel.

![Capture](https://user-images.githubusercontent.com/195873/56976056-1c657180-6b40-11e9-8d8d-eee88c29605c.PNG)

Since we can also connect a graph box to a search box, we should only show the edge type probabilities columns when the search has bootstraping.

**Comment by kvb2univpitt** [comment]
Fixed.  Also, add stripped rows for easy reading.

Without Bootstrap:
![no_bootstrap](https://user-images.githubusercontent.com/10729309/57089438-71d18800-6cd2-11e9-9a0c-1295994de985.png)

With Bootstrapping:
![boostrap](https://user-images.githubusercontent.com/10729309/57089484-8746b200-6cd2-11e9-84a7-fa0db357e967.png)

**Comment by jdramsey** [comment]
Nice.

**Comment by yuanzhou** [comment]
I'm looking at the fix now, thanks @kvb2univpitt
