### ISSUE TITLE
Some issues getting verbose output to work for algorithms.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1109]
Verbose output should work for the following algorithms if the verbose flag is set to true (some of these already work):

1. PC (already works)

2. FCI (already works)

3. FGES 

- I just adjusted the FGES class for this--it was still using the old logger methods. Need to push it.

4. FOFC

- The pure tetrad should be printed out. This used to work.

Also, the verbose flag should alway occur LAST in the list of parameters. Just need to go through and make this the case.

Also, make this version available to @cg09 and @ps7z so they can use it.

@cg09 @ps7z @mglymour Did I get everything?

**Comment by jdramsey** [comment]
I marked some algorithms as for continuous data only: R3, Skew, RSkew, LiNGAM, GLASSO.

**Comment by jdramsey** [comment]
Just a note: In a couple of cases, the verbose parameter was coming up from another source and had to be removed from the list and re-added to get it to come out as last.

This all works now for me (I think). OK, I'll do the pull request.

**Comment by yuanzhou** [comment]
Addressed via #1110
