### ISSUE TITLE
EM estimator cannot output to updater

### ISSUE THREAD

**Issue by GottM** [cmu-phil/tetrad#1111]
https://github.com/cmu-phil/tetrad/issues/958#issuecomment-445913349
I think that the point was missed when answering this issue. Indeed ML Bayes models do work when linking their output to an updater. The problem is with EM Bayes models. And it looks like a bug as the estimator successfully calculates all CPT even for latent variables. Still, the updater somehow fails when receiving the EM estimator output…

**Comment by jdramsey** [comment]
Fixed in joe.few.changes.from.issues.

**Comment by jdramsey** [comment]
Fixed.
