### ISSUE TITLE
Knowledge Does Not Work in GFCI and GES (potentially others)

### ISSUE THREAD

**Issue by esherma** [cmu-phil/tetrad#1112]
Hello,

I am working in the GUI and have found that when adding knowledge, these constraints are violated in the resulting CPDAG/PAG after running GES/GFCI. Specifically, I have done things like put Age in the top tier and all other variables in tier(s) below Age and the returned graph has directed edges into Age (see below). Unfortunately I cannot share the data (and thus the relevant tet file) since I only have access to it via a data use agreement that restricts sharing. Note: @dmalinsk has seen the bug and can attest to it's "weirdness" :)

![image](https://user-images.githubusercontent.com/14189016/57168552-3ddc8c80-6dd0-11e9-9663-d7200af85852.png)

**Comment by cg09** [comment]
Try a later version of the program.  We have done some work on Knowledge
since 6.5 versions.

**Comment by jdramsey** [comment]
Clark is right--I recall complaints about this I think two years ago, which were fixed.

**Comment by jdramsey** [comment]
I think this has been fixed, at least in the development branch. I added a unit test to check for problems like this.
