### ISSUE TITLE
Simulation doesn't remember type if external graph changes.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1114]
This is easily reproducible. Make a simulation box and give it a graph box as input. Make a random graph in the graph box. In the simulation box pick Linear Fisher. Maybe you need to simulate a dataset, not sure. Close the simulation box and re-open the Graph box, make another random graph. Close, and reopen the Simulation box. The simulation type *shows* as Linear Fisher, but the parameters are all for a Bayes Net simulation, and if you simulate you get discrete data.

<img width="324" alt="Screen Shot 2019-05-08 at 11 06 44 AM" src="https://user-images.githubusercontent.com/9853255/57386323-1c89f080-7182-11e9-981d-6a3f691636ed.png">
<img width="834" alt="Screen Shot 2019-05-08 at 11 07 06 AM" src="https://user-images.githubusercontent.com/9853255/57386327-1e53b400-7182-11e9-8f9f-a1036b9d4ebf.png">
<img width="812" alt="Screen Shot 2019-05-08 at 11 07 21 AM" src="https://user-images.githubusercontent.com/9853255/57386332-20b60e00-7182-11e9-9cbb-56371712f55c.png">
<img width="839" alt="Screen Shot 2019-05-08 at 11 07 48 AM" src="https://user-images.githubusercontent.com/9853255/57386337-23186800-7182-11e9-92e1-c254f7edc87f.png">
<img width="811" alt="Screen Shot 2019-05-08 at 11 08 05 AM" src="https://user-images.githubusercontent.com/9853255/57386349-26135880-7182-11e9-876f-593fbb378ca1.png">

**Comment by kvb2univpitt** [comment]
@jdramsey Seems like we have a refreshing issue.  I'll take a look at that.
