### ISSUE TITLE
Bootstrap may fail to terminate running FASK (Tetrad GUI 6.7.0-0)

### ISSUE THREAD

**Issue by MikeKonrad** [cmu-phil/tetrad#1119]
I have successfully run Bootstrap with 10 bootstrap samples repeatedly with FASK (with BIC SEM [as opposed to Fisher Z] Test, Penalty Discount = 100) and it will terminate in about 5 seconds, but if I try to boost the # of bootstraps up to 40 or so, it fails to terminate (hangs with no answer for at least an hour). Sometimes even 20 is uncertain.

Among moderately-correlated variables, which  I have in my datasets, I probably require Bootstrap to search at least 100 bootstrap samples.

**Comment by MikeKonrad** [comment]
> 
> 
> I have successfully run Bootstrap with 10 bootstrap samples repeatedly with FASK (with BIC SEM [as opposed to Fisher Z] Test, Penalty Discount = 100) and it will terminate in about 5 seconds, but if I try to boost the # of bootstraps up to 40 or so, it fails to terminate (hangs with no answer for at least an hour). Sometimes even 20 is uncertain.
> 
> Among moderately-correlated variables, which I have in my datasets, I probably require Bootstrap to search at least 100 bootstrap samples.

I'm sorry, this is NOT a correct statement of the problem! But there is still a problem.

I discovered that **a variable in my dataset was almost constant**, so all it took was a resampling that omitted the few inconsistent values and FASK would hang on that bootstrap sample, fail to terminate, get my blood pressure up, etc. 

Is there a simple way to automatically check for constant columns before running a search (any algorithm); especially within Bootstrap?? When you have a moderate number of variables, manual checking (and remembering to check, for example, when you split your dataset into multiple subsets and want to search each one individually) is painful to remember to do.

**Comment by cg09** [comment]
Yes there is a simple way, but up to the systems staff to create and
install.

**Comment by jdramsey** [comment]
@MikeKonrad Does this still behave badly in tetrad 7?

**Comment by jdramsey** [comment]
There is a data manipulation called Remove Constant Columns. I think that should do the trick if it's not currently working as is.
