### ISSUE TITLE
A Switch to Show Experimental Algorithms, Tests, and Scores

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1127]
Experimental algorithms, tests, scores, and parameters should never show up in Tetrad GUI.  However, for testing purposes, these experimental classes need to be shown in the GUI during the development process.  As discussed with @jdramsey, tetrad-gui needs a command switch to expose experiment classes in the GUI.

Example of how to turn on experiment switch:
```
java tetrad-gui-6.7.0-SNAPSHOT-launch.jar --experimental
```

**Comment by yuanzhou** [comment]
We may also need this for simulations. @jdramsey uses some of the simulation classes for his own purposes.

**Comment by kvb2univpitt** [comment]
Algorithms, test, and scores that are annotated experimental will show up in the GUI when using the switch "--experimental"

Show experimental algorithms, tests, and scores:
![exp](https://user-images.githubusercontent.com/10729309/58582369-97917480-821f-11e9-9e81-75b9c94af7f9.png)

Hide experimental algorithms, tests, and scores:
![nonexp](https://user-images.githubusercontent.com/10729309/58582433-b6900680-821f-11e9-86cb-79d57c185a43.png)

**Comment by jdramsey** [comment]
Awesome!
