### ISSUE TITLE
Atmospheric time series

### ISSUE THREAD

**Issue by jecampagne** [cmu-phil/tetrad#1128]
Dear developpers
I have a set of 14 variables that describe some atmospheric parameters samples every hour (4 monthes of data). By any chance can you tell me which kind of algorithm(s) can be suited to tell me which casual relationships link the different variables to eachother?
Nice tool anyhow.
Jean-Eric

**Comment by cg09** [comment]
First check whether the variables are Gaussian or non-Gaussian with skew.
Are there unobserved common causes?

Cg

**Comment by jecampagne** [comment]
Hi Cg,
Ho! I guess there are certainly not Gaussian at all, at there is no reason for that.
JE

**Comment by cg09** [comment]
Next, are the time series stationary?

**Comment by jecampagne** [comment]
Hum! you know some atmospheric variables evolve like that
![image](https://user-images.githubusercontent.com/20539759/58430866-87f11f00-80ab-11e9-9a5f-0c0edefd7c80.png)

**Comment by cg09** [comment]
PS looks to have a trend. It should be detrended.

**Comment by jecampagne** [comment]
ok but after? which kind of algo do you think may give some results on these time series ?

**Comment by cg09** [comment]
FASK

**Comment by jecampagne** [comment]
ok thanks
