### ISSUE TITLE
Null Pointer Exception For "Conditional Correlation Independence (CCI) Test"

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1132]
A java.lang.NullPointerException is thrown when selecting running algorithm using CCI.  This occurs because the ParamDescription class for the parameter "fastFDR", which is part of the CCI, does not exist.

The ParamDescriptions class pulls the parameters from the documentation.  However, "fastFDR" is not in the documentation.  Thus, the ParamDescriptions returns null for "fastFDR".

@yuanzhou The parameter names are hard-coded in the tests and scores.  I thought they were replaced with constants?  The parameter "fastFDR" is not even in the edu.cmu.tetrad.util.Params class.

**Comment by jdramsey** [comment]
@kvb2univpitt Sorry, I missed that one. That parameter should be removed for CciTest, from the list of parameters. Shall I do it?

**Comment by yuanzhou** [comment]
Any tests/scores parameters that are not defined in the `edu.cmu.tetrad.util.Params` class won't have a description in HTML manual, thus I left them hard-coded like before in the tests/scores classes.

**Comment by kvb2univpitt** [comment]
@yuanzhou I see that Param constant is used for algorithms and simulations but not for test and scores.  Parameters for tests and scores are still hard-coded.

**Comment by kvb2univpitt** [comment]
@jdramsey We can do.  We still need to fix some of the hard-coded parameters for tests and scores.

**Comment by kvb2univpitt** [comment]
@jdramsey It seems like the "Conditional Correlation Independence (CCI) Test" and "Conditional Correlation Independence (CCI) Score" were recently added.  We don't have any documentation on any of their parameters.  You are probably still working on the descriptions for those parameters.  Is it possible to get the min value, max value and the default value for each of these parameters first?  Without the default values, both CCI test and score will throw a  NullPointerException in the GUI.

**Comment by yuanzhou** [comment]
Yup, the "value type" and "default type " of each parameter must be defined in order to render the parameters panel. "short description" and "long description" can wait since they don't break the GUI.
