### ISSUE TITLE
causal-cmd and FASK

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1135]
In the causal-cmd version 1.0.0
@kvb2univpitt @jdramsey 

For the FASK algorithm, the parameter:

--useFasAdjacencies 

is set as "No" as default. It should be "Yes" as default.

and the paremeter

--useCorrDiffAdjacencies 

is set as "Yes" as default, and even if the user sets it as "No", it stay fixed as "Yes", ie. its value cannot be override by the user.

**Comment by jdramsey** [comment]
Hmm... those parameters adjust fine in the interface. Does causalcmd have free will? :)

**Comment by kvb2univpitt** [comment]
@jdramsey @rubenSaro causal-cmd gets its parameters from tetrad-lib.  Let me take a look.

**Comment by kvb2univpitt** [comment]
@rubenSaro @jdramsey 

>  --useFasAdjacencies is set as "No" as default. It should be "Yes" as default.

Generally in command-line program, you provide a particular flag to turn on a feature.  The default should be "No" for all parameters in order for the command-line version to work correctly.  If the default is set to "Yes", how would you turn off the feature in via command-line?  You would have to introduce a flag that's not in tetrad.

I can't reproduce the issue with the "--useCorrDiffAdjacencies" flag.

If I ran Fask without ```--useCorrDiffAdjacencies```, I get **useCorrDiffAdjacencies: no**
```
--dataset sim_data_continuous_20var_100case.txt --delimiter tab --data-type continuous --algorithm fask --score fisher-z --verbose
```
```
Algorithm Parameters
--------------------------------------------------------------------------------
addOriginalDataset: no
alpha: 0.01
depth: -1
extraEdgeThreshold: 0.3
faskDelta: -0.2
numberResampling: 0
percentResampleSize: 100
resamplingEnsemble: 1
resamplingWithReplacement: no
twoCycleAlpha: 1.0E-6
useCorrDiffAdjacencies: no
useFasAdjacencies: no
verbose: yes
```
If I ran Fask with ```--useCorrDiffAdjacencies```, I get **useCorrDiffAdjacencies: yes**
```
--dataset sim_data_continuous_20var_100case.txt --delimiter tab --data-type continuous --algorithm fask --score fisher-z --useCorrDiffAdjacencies --verbose
```
```
Algorithm Parameters
--------------------------------------------------------------------------------
addOriginalDataset: no
alpha: 0.01
depth: -1
extraEdgeThreshold: 0.3
faskDelta: -0.2
numberResampling: 0
percentResampleSize: 100
resamplingEnsemble: 1
resamplingWithReplacement: no
twoCycleAlpha: 1.0E-6
useCorrDiffAdjacencies: yes
useFasAdjacencies: no
verbose: yes
```
If you would like to set useCorrDiffAdjacencies to no, just don't provide the "--useCorrDiffAdjacencies" flag.

**Comment by rubenSaro** [comment]
Thanks, that is the confusing part, reading the help documentation it seems
that you should input

--useCorrDiffAdjacencies Yes

or

--useCorrDiffAdjacencies No


Ruben
