### ISSUE TITLE
Fask doesn't properly take an initial graph as input.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1140]
In the GUI you should be able to give FASK an initial graph (by drawing an edge from a Graph box to the Search box, in addition to the Data box). It should use that in place of the FAS search. Ruben complains this isn't happening.

This is very easy to fix, which I will forthwith do. I have a working version of the FASK wrapper in another branch, which I'll just copy over and push.

@rubencmu @yuanzhou @kvb2univpitt

**Comment by yuanzhou** [comment]
Merged via #1141
