### ISSUE TITLE
Simulation Does Not Work on Graph Change

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1143]
Simulating data using graph as source, as shown below:
![2](https://user-images.githubusercontent.com/10729309/59043735-cd031700-884a-11e9-9bd6-6c907b0fcafc.png)

Make changes to the graph source. The simulation editor does not re-simulate data when clicking "Execute":
![1](https://user-images.githubusercontent.com/10729309/59043967-34b96200-884b-11e9-9581-cc4564ebae76.png)

**Comment by jdramsey** [comment]
Yay!

**Comment by yuanzhou** [comment]
Merged fix via #1144
