### ISSUE TITLE
Generate PAG from DAG is erroneous

### ISSUE THREAD

**Issue by aminjaber** [cmu-phil/tetrad#1146]
Attached are the constructed DAG with latents and the generated PAG. X3 and X4 should be adjacent in the PAG since there exist an inducing path <X3,X2,X1,X4> in the DAG.
Also, if you delete a node in the DAG, save the change, and hit execute to rerun the FCI algorithm, the deleted node appears in both the DAG and PAG without its previous adjacencies.

<img width="475" alt="PAG" src="https://user-images.githubusercontent.com/13186289/59118977-9814c400-891f-11e9-9c40-c567a86c45a0.png">
<img width="500" alt="DAG w latents" src="https://user-images.githubusercontent.com/13186289/59118978-98ad5a80-891f-11e9-8853-f4dff60d4bda.png">

Note: I'm using a mac if it matters. Also, version 5.3.0 didn't have this issue.

**Comment by jdramsey** [comment]
@ps7z Can you suggest what might be going wrong here?

**Comment by jdramsey** [comment]
@ps7z @aminjaber 

Never mind, this has been solved in the most recent version. I just tried. It's the difference between DagToPag (which has been deprecated) and DagToPag2.

Just get the most recent development version.

https://cloud.ccd.pitt.edu/latest-dev-tetrad.html

Joe

**Comment by aminjaber** [comment]
Great! Thanks for the link.
