### ISSUE TITLE
Data Reader Code Migration

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1148]
Need to move the data-reader project into the Tetrad project as part of the tetrad module.

**Comment by kvb2univpitt** [comment]
@jdramsey The data-reader will read the data directly into tetrad dataset object.  This means we wouldn't be needing DataConvertUtils.

**Comment by kvb2univpitt** [comment]
@espinoj Should we wait until the next release before migrating the data-reader?

**Comment by kvb2univpitt** [comment]
Done.

**Comment by espinoj** [comment]
FYI: data-reader project is now archived
