### ISSUE TITLE
Unable to Delete Node the First Time

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1152]
Delete a selected node, as shown below:
![1](https://user-images.githubusercontent.com/10729309/59385963-807c7780-8d33-11e9-82fd-981c6e01fd52.png)

Close the graph and reopen the graph editor.  The node is not delete but edges are.
![2](https://user-images.githubusercontent.com/10729309/59386001-9db14600-8d33-11e9-823d-d4d58d341931.png)

Select the node and delete it again.  Now the node is permanently deleted.
![3](https://user-images.githubusercontent.com/10729309/59386048-bde10500-8d33-11e9-8379-796e81277669.png)

**Comment by jdramsey** [comment]
Thanks. :)
