### ISSUE TITLE
causal-cmd question

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1154]
@kvb2univpitt 

One question, is it possible for me to make changes to some algorithm and then compile a command line version... I am browsing through the files in the github repository (https://github.com/bd2kccd/causal-cmd) but I cannot find the files I usually modify in the regular tetrad-development from (https://github.com/cmu-phil/tetrad)

Thanks,

Ruben

**Comment by kvb2univpitt** [comment]
@rubenSaro Absolutely!  Causal-cmd is a wrapper that wraps around tetrad-lib.  Make your changes in tetrad-lib.  Do a maven clean install on tetrad-lib.  Do and maven clean package on causal-cmd.  The causal-cmd now wraps around the new tetrad-lib.

**Comment by rubenSaro** [comment]
It is the first time I do this and not very familiar with maven, can you give me more specific instructions. I was expecting a tetrad-lib in the cmd repository, but haven't found any. I guess my question is how causal-cmd knows which tetrad-lib to wrap around ?

**Comment by kvb2univpitt** [comment]
@rubenSaro The tetrad-lib version in causal-cmd has to match with the version of tetrad-lib you are making the changes to.  The current tetrad-lib version the development branch of causal-cmd is **6.6.0**.  You will need to change it to **6.7.0-SNAPSHOT** in the causal-cmd pom.xml file to match with tetrad-lib in the development branch.

Change this:
```xml
<dependency>
    <groupId>edu.cmu</groupId>
    <artifactId>tetrad-lib</artifactId>
    <version>6.6.0</version>
    <exclusions>
        <exclusion>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </exclusion>
        <exclusion>
            <groupId>edu.pitt.dbmi</groupId>
            <artifactId>data-reader</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
To this:
```xml
<dependency>
    <groupId>edu.cmu</groupId>
    <artifactId>tetrad-lib</artifactId>
    <version>6.7.0-SNAPSHOT</version>
    <exclusions>
        <exclusion>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </exclusion>
        <exclusion>
            <groupId>edu.pitt.dbmi</groupId>
            <artifactId>data-reader</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

If you need help with Maven, see their documentations here: https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

**Comment by rubenSaro** [comment]
Perfect, thanks a lot.

Ruben

**Comment by rubenSaro** [comment]
Ok, so all the changes have to be pushed to the github repositories, no way to do it locally ?

**Comment by kvb2univpitt** [comment]
@rubenSaro Are you around DBMI today?  I can explain to you how Maven works.

**Comment by rubenSaro** [comment]
Sorry Kevin, not in Pittsburgh anymore. Now post-doc-ing in Rutgers-Newark

**Comment by kvb2univpitt** [comment]
@rubenSaro OK. Try the following:
1. Checkout tetrad from the development branch (6.7.0-SNAPSHOT).
2. Make changes to tetrad-lib.
3. Go into the tetrad-lib folder and execute `mvn clean install`.  This will install tetrad-lib locally.
4. Checkout causal-cmd from the development branch (1.1.0-SNAPSHOT)
5. Go into the causal-cmd folder and open up the pom.xml file.
6. Change the tetrad-lib version in the pom.xml file from **6.6.0** to **6.7.0-SNAPSHOT**, as described previously above.
7. Execute the command `mvn clean package`

Causal-cmd should now wraps tetrad-lib version 6.7.0-SNAPSHOT.

**Comment by rubenSaro** [comment]
awesome, thanks a lot.
