### ISSUE TITLE
Tetrad GUI (6.7.0) data loader won't accept text for discrete values

### ISSUE THREAD

**Issue by MikeKonrad** [cmu-phil/tetrad#1158]
With earlier versions of Tetrad (at least through 6.5.4; not sure about 6.6) it was possible to load in a dataset having discrete variables with text values (e.g., Political.Party with values Democrat, Republican, Independent). Now it seems I need to replace such values with numeric values to get the data to load successfully.

**Comment by kvb2univpitt** [comment]
@MikeKonrad You should still be able to do that.  Can you attach the dataset?

**Comment by cg09** [comment]
Unfortunately, our improvements sometimes come with unintended
consequences.  Another is that the BPC and FOFC algorithms as implemented
are both fallacious. Very early versions ob BPC were, I think, correct. The
error can be compensated for by other methods in the program, but the
general user would have no idea.

**Comment by MikeKonrad** [comment]
The datasets we are using can't be shared; however, here is a synthetic mixed dataset that Madelyn helped me create from within Tetrad that we saved and then tried to load back in but were unable to for the same reason.
[tmp6.txt](https://github.com/cmu-phil/tetrad/files/3291866/tmp6.txt)

**Comment by kvb2univpitt** [comment]
@MikeKonrad OK.  Now I see the problem.  The problem is with the data validation.  Thank you for reporting this.  We will fix the bug.  In the meantime, you can bypass the data validation by removing the following lines (573-580) in `edu.cmu.tetradapp.editor.LoadDataDialog` of **tetrad-gui**
![a](https://user-images.githubusercontent.com/10729309/59533630-1d691d00-8eba-11e9-9a41-790fc2bb8455.png)

**Comment by kvb2univpitt** [comment]
@MikeKonrad Don't forge to select 'mixed' data and set 'max discrete categories' to 4.
![b](https://user-images.githubusercontent.com/10729309/59533947-ec3d1c80-8eba-11e9-847a-5c4d29e949ef.png)

Data loaded:
![aa](https://user-images.githubusercontent.com/10729309/59533959-f4955780-8eba-11e9-90c7-60cde723ebe4.png)
