### ISSUE TITLE
graph box used to generate data changed by results of search

### ISSUE THREAD

**Issue by ps7z** [cmu-phil/tetrad#1160]
When the output of a search and an independently created graph box are both fed into a compare box, the compare box changes the graph in the graph box to be the same as the output of the search.

**Comment by jdramsey** [comment]
I just tried this; it doesn't seem to be doing that. Maybe it was fixed. Or maybe I'm not doing it right. @ps7z

**Comment by jdramsey** [comment]
Can't reproduce. I think it was fixed.
