### ISSUE TITLE
BPC is missing a critical check

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1162]
Both BPC and FOFC require a preprocessing step that checks to see whether the marginal graphical model on the measured variables is complete--or nearly so--and only runs the latent variable search of BPC or FOFC if it is complete.  I have asked Madelyn to look into this problem, but we may have to hand it off.

I fixed this for FOFC--jdramsey

**Comment by jdramsey** [comment]
@cg09 @mglymour Was this fixed? If so, in what branch? Thanks.

**Comment by jdramsey** [comment]
@cg09 @mglymour Asking again, was this fixed? I know it was fixed in Madelyn's code, but was that ever pushed to development?

**Comment by cg09** [comment]
Only Madelyn would know.

**Comment by cg09** [comment]
No, we have not implemented a satisfactory check, although we have sketched
a procedure.

**Comment by jdramsey** [comment]
OK. I shall wait for truth to be divulged.

**Comment by jdramsey** [comment]
Making a new branch, check_bpc_and_fofc, to start doing these checks.

**Comment by jdramsey** [comment]
I added the alpha parameter back in to the interface in this branch.

**Comment by jdramsey** [comment]
@cg09 You know, there is a much better option available in the FOFC code than checking completeness of PC models for clusters--this was an idea Peter had had, which was to check the _significance_ of the clusters. Let me expose that parameter in the interface for you to play with. I don't know if BPC has that parameter or not, I'll have to check, but it would be feasible to add I think. I think I can just copy the code over from FOFC.

**Comment by cg09** [comment]
It might be better if we had a test for *sets *of tetrad equations. I don't
think we do. A test of a single common cause model will depend on
linearity. It is not clear that the implication of vanishing tetrads is so
restricted.

**Comment by jdramsey** [comment]
I do fear that the significance of a set of tetrad equations may be very hard to make significant...

**Comment by jdramsey** [comment]
But I agree with the idea...

**Comment by cg09** [comment]
Thanks. Which branch?

**Comment by cg09** [comment]
Then Peter's proposal would not work very well, I think.

**Comment by jdramsey** [comment]
.... I could have sworn BPC checked significance of clusters somewhere but it does not appear to be a thing... hmm... let me see if I can figure out some place to put such a check...

**Comment by jdramsey** [comment]
Oh I see, for FOFC, significance of clusters was only being printed out at th end. I added a step to check significance of clusters are they being created.

**Comment by jdramsey** [comment]
... I can't figure out where to add that check in BPC; the code is so complex. Will ponder further. Anyway it's in FOFC now.

**Comment by cg09** [comment]
I complained about that many times to no effect. But there is a simple
check I use: run a search algorithm on the measured variables in the
cluster and see if the result is a complete graph. If not, there is
something wrong with the single common unmeasured cause representation.

**Comment by jdramsey** [comment]
it's the right idea but it's not working with any of the algorithm I'm trying. I never get complete models for the clusters I know should be there, not even close in many cases. Which is why I thought calculating the model significance of the cluster might be a better idea--then you'd get a single p-value that you can compare to alpha.

Maybe I should you what the test of model significance is; I think once you saw what was being done you'd agree to it. The idea is, say you think {x1, x2, x3, x4} is a cluster. So add a latent, L->{x1, x2, x3, x4}, form that SEM model, estimate it, and return its p-value.

I think it's a sensible thing to do in any case.

What I did just now was to factor out all of the cluster-significance-related code from FOFC into a separate class, ClusterSignificance. That way, if I could figure out how to do the checks in BPC I could just call that same code. And if a better way of testing cluster or clustering or model significance occurs, that could be programmed up as well.

**Comment by jdramsey** [comment]
Of course now that those checks are moved to a separate file, it would be relatively straightforward to do a clique test instead to see if it's better. Off the top of my head it seems not, but maybe it might work, if you give it only the variables in the cluster itself and and not all the variables in the whole model.

**Comment by jdramsey** [comment]
There is a method in BPC called "filterAndOrderClusterings"--that looks like a likely place to put a significance check...

**Comment by jdramsey** [comment]
OK, there's a variables called 'baseListOfClusterings' in the 'filterAndOrderClusterings' method, and we look inside of that to get 'baseClustering's. A 'baseClustering' consists of 'cluster's. We go through each of these clusters and see if they pass some tests. What I'm doing is adding a new criterion to this check--in addition to all of Ricardo's checks, I also check the p-value of each cluster, and if the p-value is below significance I skip the cluster and don't add it to any new clustierngs to print out.

I am about 50% sure that this strategy is OK given the way the code is written, which is hard to understand. I tried it in the GUI and it seems to be helping.

OK, now in ClusterSignificance I will try to add a clique test of some sort as an alternative option and see if that helps.

**Comment by jdramsey** [comment]
Well it's not an awful option. Let me clean up the code a bit and put the option in the interface for both algorithms. I don't know if I can get you a version today, as there as some pull requests in the queue to accept before development is OK, but hopefully soon.

**Comment by cg09** [comment]
No. you generally do not get a complete graph, but you do almost always get
a graph specifying conditional independence relations that are impossible
with a single common cause.  That should be a caution about introducing
such a common cause.

On Sat, Feb 4, 2023 at 5:37 PM Joseph Ramsey ***@***.***>
wrote:

> it' The idea is, say you think {x1, x2, x3, x4} is a cluster. So add a
> latent, L->{x1, x2, x3, x4}, form that SEM model, estimate it, and return
> its p-value.
>

And what do you do if there are only 3 variables in a cluster? Or only two?

**Comment by cg09** [comment]
I would like to have the option of testing each of the clusters produced by
BPC.

**Comment by jdramsey** [comment]
Pull request: https://github.com/cmu-phil/tetrad/pull/1486

**Comment by jdramsey** [comment]
I suppose I could print those out at the end. I don't want to add new GUI features.

**Comment by cg09** [comment]
A clique test is less informative than running, say, a grasp search. A
grasp search could help identify a proper subset of a cluster that is a
clique.when the whole set is not a clique.

**Comment by cg09** [comment]
Would it make sense to add a separate function (a new box, or a new menu
item in the Estimate box) for testing linear one factor models?  What does
the FOFC significance test actually test?

**Comment by jdramsey** [comment]
I disagree about the GRaSP search over the set of variables; I spent time trying to do that and didn't get _any_ cliques.

**Comment by jdramsey** [comment]
That is, on my problems I didn't get any cliques for latent clusters I knew were there. It was totally uninformative.

**Comment by jdramsey** [comment]
I think you missed the one message: I'll repeat:

"Maybe I should you what the test of model significance is; I think once you saw what was being done you'd agree to it. The idea is, say you think {x1, x2, x3, x4} is a cluster. So add a latent, L->{x1, x2, x3, x4}, form that SEM model, estimate it, and return its p-value."

**Comment by cg09** [comment]
It is a mathematical necessity that when there is a common unmeasured
cause of N variables that there are no conditional independencies among the
N variables, and the marginal graph on the N variables is adjacency
complete. Chance of course may create some conditional independencies, but
we cannot defeat chance. So, if you have a 1 factor measurement model and
there are conditional independencies among the variables, then chance is at
work. But if you find *any* conditional independencies and want to infer a
common cause model, then the presence of marginal conditional independence
presents a choice: Either you have had bad luck or the common cause model
is false. Of course, if we had error probabilities for the whole sequence
of tetrad tests, and likewise for the whole sequence of partial correlation
tests, we could go with the alternative with the smaller total error
probability. But we do not have such error probabilities.

**Comment by cg09** [comment]
Yes, I understood that.

**Comment by jdramsey** [comment]
Well, in any case what I think I've done in my current branch for this is to insist that FAS applied just to the measures you think are in the cluster return a clique. You can play with it, tell me what you think. I suppose I could make you a snapshot build. I want to print out the evaluation of each final cluster before doing so and the model p-value if it's a legit model, so I guess after I do that. That will be printed to the log.

**Comment by jdramsey** [comment]
I mean, I understand why in principle you need to get a clique for each single-latent cluster, and from d-separation you do of course--but from any of our algorithms (GRaSP included) you don't even come close to that ideal if you put all of the variables into the same analysis. Many edges that _must_ be there go missing.

**Comment by cg09** [comment]
Because the parameters for the common cause are too small.

**Comment by jdramsey** [comment]
Yeah. BTW I'm starting to think about your idea of adding a menu item to check significance of a single-latent model with the measures you choose in the graph... maybe...

**Comment by jdramsey** [comment]
@cg09 I'm not sure where to put that functionality yet. The 'isSignificant" method requires a dataset, a cluster, and an alpha. So basically you need as input a dataset/covariance matrix and a set of variables in a variables for that data model, and an alpha. That's it.

Maybe it just does as a menu item in the Data Editor. Not sure.

**Comment by jdramsey** [comment]
Hmm... I think this is a great idea to put somewhere but I think it's going to take more than haphazard thought, so maybe I'll put it on the wish list and not try to get it into the upcoming release. What I can do for the moment is to print p-values of each cluster in the BPC and FOFC output to the log (and maybe whether they form FAS cliques)..

**Comment by jdramsey** [comment]
OK, I've added a printout of the p-value of each cluster that is output by BPC or FOFC; this goes to the log, so you'll need to turn logging on to see them. A few other things are printing to the log as well, which are a nuisance; I'll see if I can track down who's printing that stuff. But it is usable.

**Comment by cg09** [comment]
Great! Thanks.

**Comment by cg09** [comment]
What test do you use/

**Comment by cg09** [comment]
In the Estimator Box?

**Comment by jdramsey** [comment]
Same test I described earlier. Form the model L->{x1, x2, x2, x4} and estimate it from the data, then report the model p-value.

I'm thinking the estimator box is not the right place, because that assumes as particular SEM PM, which this function does not.

**Comment by jdramsey** [comment]
@cg09 Bryan says he'll review this code change so there will be at least one other pair of eyes on it. We do have a few more issues we'd like to get into the next release, but I think it should be ready soon.

**Comment by jdramsey** [comment]
Fixed

https://github.com/cmu-phil/tetrad/pull/1486

Closing.
