### ISSUE TITLE
Simulation box will not open

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#1163]
In the latest development branch (downloaded today) the simulation box produces a blank error dialogue rather than opening. It does this no matter what kind of graph is input, or whether it is the child of an IM, PM, or graph box.

**Comment by jdramsey** [comment]
Just a couple of ideas from recent experience (this is not my code, but this worked for me as of yesterday):

1. In the Maven tab, click the button to reload dependencies. It looks like a little recycle button, two arrows pointing in a circle.

2. Double click clean

3. Double click compile

4. Launch Tetrad again.

**Comment by mglymour** [comment]
I had done that prior to compiling the code, but I'll try again.

**Comment by kvb2univpitt** [comment]
@mglymour I just downloaded from the development.  It works for me.  Try Joe's suggestion.
![a](https://user-images.githubusercontent.com/10729309/59695486-4e966580-91b8-11e9-9acb-0319283a3c64.png)

**Comment by mglymour** [comment]
And now it's working. Must have missed a button somewhere.
