### ISSUE TITLE
Make variable name separator for txt graph format read-in a character class

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1168]
Unfortunately we now have text graph outputs that use various separators for the variable names. This seems to be the only difference between them. Can we solve this by simply making the parsing separator a character class? This is in GraphUtils. The example below allows either a comma or a semicolon (String[] tokens = line.split("[,;]");), which solves most of the current problems.

    public static Graph readerToGraphTxt(Reader reader) throws IOException {
        BufferedReader in = new BufferedReader(reader);

        while (!in.readLine().trim().equals("Graph Nodes:")) ;

        String line;
        Graph graph = new EdgeListGraph();

        while (!(line = in.readLine().trim()).equals("")) {
            String[] tokens = line.split("[,;]");

            for (String token : tokens) {
                graph.addNode(new GraphNode(token));
            }
        }

**Comment by kvb2univpitt** [comment]
@jdramsey

> we now have text graph outputs that use various separators for the variable names.

What are all the possible separators besides semicolon and comma?

**Comment by jdramsey** [comment]
So far as I know, it's just semicolons and commas. I haven't seen any others.

@kvb2univpitt

**Comment by kvb2univpitt** [comment]
@jdramsey Ok.  We'll make it work for semicolons and commas for now.
