### ISSUE TITLE
Need an FCI Variants to parallel PC Variants.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1170]
Basically, we need to port over the options for max, stable, conservative, etc. to FCI. Requested by Peter.

@kvb2univpitt @yuanzhou @chirayukong @espinoj Should I work on this?

**Comment by kvb2univpitt** [comment]
@jdramsey This is related to algorithm.  I would say yes, since we are not comfortable at modifying or enhancing any algorithm.

**Comment by jdramsey** [comment]
@kvb2univpitt OK.
