### ISSUE TITLE
command line version --choose-dag-in-pattern

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1172]
@chirayukong 

A new option added in cmd-1.0.0 is the --choose-dag-in-pattern, nevertheless it is not clear how to use it.

As a flag in an algorithm run ?, and thus two outputs are required: the pattern and the dag.

As a procedure, using as input a graph in txt file ?

Can you provide more info. about how to use this option. 

Thanks a lot.

**Comment by chirayukong** [comment]
It is, in fact, a flag in an algorithm run.

Not only --choose-dag-in-pattern but also these options:

--choose-mag-in-pag,
--genereate-pattern-from-dag,
--genereate-pag-from-dag,
--genereate-pag-from-tsdag,
--make-bidirected-undirected,
--make-undirected-bidirected,
--make-all-edges-undirected,
--generate-complete-graph,
--extract-struct-model

would apply to the output graph from the search algorithm. The causal-cmd CLI runs only the search, at least, in the current development stage.

**Comment by rubenSaro** [comment]
ok. so it is not implemented yet.

R.

**Comment by chirayukong** [comment]
It is implemented but it would run only as an add-in to a graph output from the search. The link provided is the code implemented.

https://github.com/bd2kccd/causal-cmd/blob/f9184cc2c02bdf5bb60b4eee0aff20cb9a9298a1/src/main/java/edu/pitt/dbmi/causal/cmd/tetrad/TetradRunner.java#L157
