### ISSUE TITLE
Port new covaraince code over to an accessible branch.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1175]
There is some new, well-tested covariance code (including code from Kevin). This needs to be ported to an accessible branch and cleaned up. If OK, it can be moved to development.

**Comment by kvb2univpitt** [comment]
@jdramsey Since my CovarianceOnTheFly class is really not "on the fly," let's rename it.

**Comment by jdramsey** [comment]
@kvb2univpitt What should we name it? I was calling it "KevinCovariances" but maybe not that. :)

**Comment by jdramsey** [comment]
I'll work on that stuff now. The tricky part (other than naming :)) is to see whether I can get rid of some methods that are only used in one place in the code, to make the API easy.

I've got standard covariances and Kevin covariances, for doubles and floats. The current covariancematrix on the fly I just made wrap the other covariancematrix; we can just get rid of it once I find a way to delete the extra methods in that. @kvb2univpitt

**Comment by jdramsey** [comment]
@kvb2univpitt OK, I'm calling the standard calculation "standard" and yours "alternative". Feel free to rename.

The extra methods I was worried about are never used, so I deleted them. Now CovMatrixOnTheFly just wraps CovarianceMatrix and can be factored into nonexistence. I'll do that in the branch I'm making. I realized your calculation even without the parallelization was faster than CovMatrixOnTheFly, so there didn't seem a need for it anymore. I we find a need we can always re-make it, we are that ingenious.

So the basic port will be the following classes:

CovarianceMatrix (recoded)
CovariancesFloatStandard
CovarianceDoubleStandard (please no puns)
CovariancesFloatAlt
CovairnacesDoubleAlt

Also,

CovianceMatrixOnTheFly,

which will be refactored out of the code.

I think there are a few other ways of calculating covariances in the code, which should be replaced by these.

Like I said, I'm just sketching out an API; feel free to adjust it.

Also, when you get your parallelized alt implementation done, you can just add it as a new module. I suggest we keep all implementations around until it becomes clear which are the best performers.

I'll make a branch called joe.covariances.port off of development and move this stuff over.

**Comment by jdramsey** [comment]
This is done.
