### ISSUE TITLE
Build instructions, and or Makefile?

### ISSUE THREAD

**Issue by freckletonj** [cmu-phil/tetrad#1178]
I'd love to play around with this, but the link to the latest doesn't work. (On http://www.phil.cmu.edu/tetrad/downloads.html, the link to https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/cmu/tetrad-gui/6.4.0/tetrad-gui-6.4.0-launch.jar). 

I found an older jar to play around with, but any chance you could add some IDE-agnostic build instructions?

**Comment by espinoj** [comment]
Tetrad is built using maven so this is easy via command line.  Here's a wiki guide - https://github.com/cmu-phil/tetrad/wiki/Building-Tetrad-using-Command-Line

**Comment by freckletonj** [comment]
Cool, thanks!
