### ISSUE TITLE
Figure out how to post tetrad to the central repository.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#118]
Still a few issues left.

**Comment by jdramsey** [comment]
Jeremy, I just saw this old issue, which I'd given up on because I couldn't figure out how to do it. But it sounds like you had a plan. let me know if I can help out.

**Comment by espinoj** [comment]
Once I get this working with TravisCI and our private maven repository I'll figure it out with Maven Central.   BTW: My plan is that we post tetrad-lib to maven central.
