### ISSUE TITLE
Search Does Not Work on Discrete Data

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1184]
This problem exists in branch **joe.work.2019.8**.

1. Simulate discrete dataset.
2. Select any search algorithm and run.

![setup_algo](https://user-images.githubusercontent.com/10729309/62225253-1329b200-b386-11e9-8ea2-7280d5127c04.png)

![graph](https://user-images.githubusercontent.com/10729309/62225267-17ee6600-b386-11e9-90ea-417a7294ab26.png)

**Comment by jdramsey** [comment]
Oh!

**Comment by jdramsey** [comment]
This one I can't debug using an iPad sorry

**Comment by jdramsey** [comment]
OK, PC with chi square or g square works. FCI with same works. But FGES with BDeu doesn't work. FGES with discrete BIC works! :? Note also that the discrete estimator doesn't work; it freezes up on one variable. So... long stroking of non-existent beard... the problem is BDeu?

**Comment by jdramsey** [comment]
No, the problem here was that the structure prior was set to 0, leading to negatively infinite scores. I'll set the default for the structure prior to 1 and bound it away from zero.

**Comment by jdramsey** [comment]
I found the problem.  This, line 120 in BayesEstimatorEditorWizard:

            setCurrentNode(node);

should have been this:

            setCurrentNode((Node) varNamesComboBox.getSelectedItem());

Not sure how that got changed...

**Comment by jdramsey** [comment]
OK I judge this a success! Will look for other bugs from @kvb2univpitt and if none will do a pull request.

**Comment by jdramsey** [comment]
Fixed.
