### ISSUE TITLE
Data Loader README

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#1186]
A link to the Data Loader README file should be placed somewhere in the Tetrad Github. Also the README needs to include some documentation of how to convert Data objects into DataSet/DataModel objects using DataConvertUtils.

**Comment by kvb2univpitt** [comment]
@mglymour The [README](https://github.com/cmu-phil/tetrad/blob/development/data-reader/README.md) file for the data reader is already in the Tetrad Github repository in the data-reader module.  I will include some documentation on how to use the DataConvertUtils in the README file.

**Comment by jdramsey** [comment]
This looks good to me.

**Comment by kvb2univpitt** [comment]
Done.
