### ISSUE TITLE
Backward compatability for opening Tetrad sessions

### ISSUE THREAD

**Issue by MikeKonrad** [cmu-phil/tetrad#1194]
Unfortunately, Tetrad sessions created under an earlier version of Tetrad (6.5.4 in this case) will not open in Tetrad 6.6.n or 6.7.0. Ouch!

Is there any way of accomplishing the above so that an entire session does not need to be created from scratch?

We've been working with research collaborators at USC and they need the very nice sortable edge statistics table that now appears under the search result (say after running bootstrap) (a great feature by the way!!) but it is only available in Tetrad 6.6.0 and later.

**Comment by cg09** [comment]
Backward compatibility is a huge problem. Microsoft, for all its billions,
can't do it. We sure can't, so far as I know.

Clark
