### ISSUE TITLE
FCI is giving me a cycle!

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1196]
I ran FCI with default parameters on the newly released version of TETRAD (6.7.0). Please email me for the data I used.

![image](https://user-images.githubusercontent.com/16494809/63185433-0664b980-c028-11e9-9434-9c46bb4a4ed2.png)

**Comment by jdramsey** [comment]
If that's the data I think it is, it's not clear it's a DAG model.

**Comment by jdramsey** [comment]
Also, FCI doesn't have a cycle checker.
