### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by mahnaz-qafari** [cmu-phil/tetrad#1199]
Greetings,
It is mentioned that there are Javadocs for  the Tetrad API in [here](https://www.ccd.pitt.edu//wiki/index.php?title=Documentation_on_using_the_causal-cmd_software#Use_as_an_API). They provide this [link](http://cmu-phil.github.io/tetrad/tetrad-lib-apidocs/) for that, but it is not working. 
As I need to work with the Tetrad using an API, my current plan is to discover the correct sequence of the method calls through inspecting the GUI of Tetrad.  
My questions are:
1- Is there any Java API for Tetrad? If so, where can I find it? If not, do you have any plane to release one in near future?
2- For the moment, do you have any suggestion how to call Tetrad in a program?
Best,
Mahnaz

**Comment by mahnaz-qafari** [comment]
Thank you both for answering. 
An update on the example of using the API can be quite helpful. 
After that I can find my way using test units.
Cheers,
Mahnaz

**Comment by mehranmehr** [comment]
It would be nice if an explicit API was designed for Tetrad. In its current state, one need to read the code, the javadoc (not all the classes have Javadoc), and the unit tests to use it. Moreover, his code might not work with the later versions of Tetrad as developer can easily change everything.

With an explicit API (separate jar file) with a backward compatibility property and proper versioning strategy, one can easily write code (just by reading the API doc) that works with Tetrad and he can be sure that his code works with newer versions of Tetrad with a compatible API.
