### ISSUE TITLE
GUI 6.7.0 set parameters menu for FASK is incomplete and redundant

### ISSUE THREAD

**Issue by MikeKonrad** [cmu-phil/tetrad#1201]
If in the public release of 6.7.0 GUI, in the Search Box's Choose Algorithm menu,  I specify FASK, when I click on Set Parameters, I do not see a panel for setting Bootstrap parameters. It's gone!

Also, no matter what independence test I specify in the first menu, in the Set Parameters menu, the panel for that test redundantly offers the same parameters as already provided in the FASK panel part of the menu.

**Comment by espinoj** [comment]
fixed in #1207
