### ISSUE TITLE
Add degenerate gaussian score method

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#1203]
Bryan implemented and published the degenerate gaussian score which can be used with mixed datatypes.  Should merge to development.  It's in: 
https://github.com/cmu-phil/tetrad/tree/degenerateGaussian

**Comment by jdramsey** [comment]
@espinoj Would you like me to do this? I think I understand Bryan's code...

**Comment by espinoj** [comment]
in #1216
