### ISSUE TITLE
Why to use the gui tetrad from the CCD webpage must I install a JDK developer kit?  That's what the thing requires.

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1208]

**Comment by jdramsey** [comment]
No, that's a good point. It just requires a JRE. I think.

**Comment by cg09** [comment]
Right, but the sign says the jdk. Works, of course, with the jdk, but the
JRE ought to suffice.

**Comment by kvb2univpitt** [comment]
JDK developer kit is required to compile Tetrad.  Tetrad can be run using either JDK or JRE.  I think we need to make that clarification.

**Comment by espinoj** [comment]
Where and what page does it say that?

**Comment by jdramsey** [comment]
@kvb2univpitt This is fixed, right?

**Comment by kvb2univpitt** [comment]
I still can't find the page where it says that.

**Comment by jdramsey** [comment]
I will close it thank. Thanks!
