### ISSUE TITLE
Need to distinguish the two structure priors.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1209]
Small bit of detective work. I just realized that the structure prior coefficient of BDeu is being conflated with the structure prior coefficient of SEM BIC. That's why the default had been set to zero, then one, then zero, then one. These two parameters need to be distinguished. The structure prior for BDeu should by default be 1 (definitely, or the search will return no edges!), but the structure prior of SEM BIC should be default be 0 (i.e., no bias).

**Comment by cg09** [comment]
Nobody (except Greg) understands them. What are they, how do they differ,
can the searches be run without giving them values?

**Comment by jdramsey** [comment]
That's a different issue. The problem here was that "structure prior" was referring to two totally different concept, so I made two parameters to distinguish them so they could be given different defaults.
