### ISSUE TITLE
Knowledge box not accepting Data box as input

### ISSUE THREAD

**Issue by LizMcQuillan** [cmu-phil/tetrad#1212]
V 6.7.0-0
The "Help" text for the Knowledge Box, Forbidden Graph lists Data as an acceptable input. However, when I select Forbidden Graph it results in the following error: "I couldn't find a parent graph".

**Comment by jdramsey** [comment]
Sorry I missed this. That's a good point. Forbidden Graph can't take data as input. It needs to take knowledge as input. Try knowledge instead. We'll correct the manual.
