### ISSUE TITLE
FCI and GFCI either do not run or take too long

### ISSUE THREAD

**Issue by khaisieu1995** [cmu-phil/tetrad#1215]
To whom this may concern,
I am working on a causal search for a real-world dataset. Unfortunately, I cannot share the dataset here due to confidentiality issue, but here is a description of the dataset:
1. It has 25000 rows and 20 (mixed) variables
2. About 10 of the variables are continuous, potentially multivariate, and potentially dependent on the discrete variables.
3. About 10 of the variables are discrete (5 binary, the other five with no more than 6 categories).
4. No missing values. Most data point are possible with an exception of one continuous variable with some negative values.

Since the dataset is mixed, when running FCI we are left with CG Likelihood Ratio Test. Similarly, we are left with CG Likelihood Ratio Test and BIC Score when running GFCI. We have tried specifying that "continuous variables should NOT be discretize if child is discrete". We have also tried lowering the max degree to as low as 5. Nevertheless, these algorithm is taking too long (matters of hours). It appears that the GFCI hangs while trying to do FGES. 

I do not believe this dataset is particularly complex or large. Nevertheless, the algorithms are not running as fast as expected. 

Would you please look into these algorithms and offer us any insights? If we can run any test or acquire any statistics on the data to help resolve the issue, we are more than happy to do so.

**Comment by jdramsey** [comment]
Well, one thing is you have discrete variables with up to 100 categories. That can lead to some rather sizeable tables.

**Comment by khaisieu1995** [comment]
Dear jdramsey,
I have corrected that typo. I meant there are only 6 categories for each discrete variables.
Sieu

**Comment by bja43** [comment]
The CG score/test is failing in this case because it is repeatedly partitioning your 25,000 instances according to the various settings of your discrete variables. Another score, the degenerate Gaussian (DG) score, was recently developed for this case since it is a known failure case for the CG score. 

Unfortunately, I am not sure if the DG score is in the published version of TETRAD yet and I know that DG has not been adapted into a conditional independence test. The latter issue is easily resolved. 

@espinoj, are we able to share a version of TETRAD with these methods included (after I code up DG as a test)?

**Comment by espinoj** [comment]
Checking with @chirayukong to see where he is in terms of pulling this into development.

**Comment by chirayukong** [comment]
Give me a moment. Let me check out this branch.

**Comment by chirayukong** [comment]
https://github.com/cmu-phil/tetrad/pull/1216

**Comment by chirayukong** [comment]
@khaisieu1995 the degenerate Gaussian independent test and score are merged into the development branch. You can try the new test/score for GFCI and a test for FCI.

**Comment by khaisieu1995** [comment]
Thank you very much for responding so quickly and for all of your help. I will test this new version and report any additional issues if I found any.

**Comment by jdramsey** [comment]
@khaisieu1995 It seems this is fixed, so I'm going to close it. Complain if not.
