### ISSUE TITLE
Unknown Question Boxes for Model Statistics in IM

### ISSUE THREAD

**Issue by hsmith1123** [cmu-phil/tetrad#1219]
When running a SEM instantiated model from our SEM parametric model and looking at the model statistics tab we are running into a few questions. First, the degrees of freedom continually changes when we make small changes to our data which should not effect the df. Second, where we should see model statistics we only see question mark boxes which are unexplained. Here is a screenshot of what we are seeing 
![Screen Shot 2019-10-01 at 4 30 09 PM](https://user-images.githubusercontent.com/55963575/65998342-1cf49200-e469-11e9-897a-0c720950a529.png)

**Comment by jdramsey** [comment]
Curious, is it possible there is any of the following situation with your data?

* Missing values

* Constant column

* Singularity

**Comment by jdramsey** [comment]
I take it this was fixed... complain if not.
