### ISSUE TITLE
Put CStar in the interface.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1226]
So CStaR is still basically working. It needs to be cleaned up a little to put in the interface, but I forgot about one thing (sorry, It's been a while). The problem is, a more or less meaningless graph is being displayed currently for this. What we need instead of a graph is just a text box. The text table to display in the text box is already calculated; we just need to be able to display is in the interface.

There are a couple of niceties that would help, like letting the user know when they haven't specified any targets, which is a little confusing now, or when qFrom is before qTo erroneusly. Other than that it's good to do. I'll commit it shortly.

**Comment by jdramsey** [comment]
Oh, the class is called CStaS (Causal Stability Selection); the CStaR table (which is what should be displayed) is easy to print out. There's a method for that in CStaS.

I'm renaming the CStaS algorithm wrapper to CStaR.

**Comment by jdramsey** [comment]
OK I pushed it. There may be some outstanding issues still; I haven't looked at this in a while, but just getting the CStaR table in the interface would be a coup.

**Comment by MikeKonrad** [comment]
Yes, it would be wonderful to have CStaR accessible from the GUI. Our team of Tetrad users here would really benefit from this added functionality!!

Mike Konrad

**Comment by jdramsey** [comment]
I realize this is going to require an explanation. The text giving in the previous annotation description tag is a little helpful:

Performs a CStaS analysis of the given dataset (Stekhoven, Daniel J., et al. Causal stability ranking. Bioinformatics 28.21 (2012): 2819-2823) and returns a graph in which all selected variables are shown as into the targets.

That's fine, except we need to replace the graph with a table. The columns in the table are defined in that article (and are complicated to explain), but maybe a brief explanation would be good.

**Comment by jdramsey** [comment]
Duplicates another issue...

**Comment by cg09** [comment]
Yeah, but is C-star in the interface?

**Comment by jdramsey** [comment]
I have my doubts as to whether that's even a good idea anymore. It would be more useful having CStaR as part o the command line tool. it's not really an interface type of algorihtms...

**Comment by cg09** [comment]
Data Box -> Loop K times (Search algorithm (PC or FGES) -> Least
squares estimator -> Minimal effect size estimator -> Subsample -> Search
Alogrithm...) -> Edge Ranking
