### ISSUE TITLE
TsFCI description in search box not available, but it's in the manual.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1227]
Got a report that when you select TSFCI in the search box, the description box is empty. The algorithm is described in the manual (which I pointed out), but still, should this text box be displaying something? In 6.8.0.

**Comment by kvb2univpitt** [comment]
@jdramsey The problem is that the value of the attribute _id_ of the div tag in the manual is incorrect.  It should be this `ts-fci` and not `tsfci`.
I can fix that.  I'll send you a pull request.

**Comment by jdramsey** [comment]
Thanks. @kvb2univpitt

**Comment by kvb2univpitt** [comment]
Fixed.
