### ISSUE TITLE
Unable to Load Saved Knowledge File Containing Forbidden Edges

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1232]
1. Create a knowledge box and add forbidden edges, as shown below.
![add_forbidden](https://user-images.githubusercontent.com/10729309/68057481-66d0d200-fccc-11e9-939f-a15b06b6962f.png)
2. Save the knowledge to a file.
3. Load the knowledge file and got the following error:
![error](https://user-images.githubusercontent.com/10729309/68057571-b4e5d580-fccc-11e9-8103-38717ea4e86a.png)

This also happens in the previous version of Tetrad.

**Comment by jdramsey** [comment]
Fixed in fixes branch.

**Comment by jdramsey** [comment]
SpinnerNumberModel spinnerNumberModel = new SpinnerNumberModel(
                Math.max(getNumTiers(), 2), 2, 100, 1);

in KnowledgeBoxEditor. 

Problem was there were not tiers in this setting.
