### ISSUE TITLE
Data Simulation: Variables Out of Order

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1233]
In the previous version, the variables are ordered from X1, X2, X3,...,Xn when simulating data, as shown below.
![data1](https://user-images.githubusercontent.com/10729309/68057847-97fdd200-fccd-11e9-8b77-5e1f4a87da47.png)

In the current version, the variables are not ordered from X1, X2, X3,...Xn when simulating data:
![data2](https://user-images.githubusercontent.com/10729309/68057912-caa7ca80-fccd-11e9-8441-c2eebc6e3d3b.png)

**Comment by jdramsey** [comment]
@kvb2univpitt I think this is fixed, isn't it?

**Comment by kvb2univpitt** [comment]
I don't think so.  I haven't had time yet.  Sorry.

**Comment by kvb2univpitt** [comment]
It turns out that there is an option to randomize the variables.  It was selected by default.  It's not a bug.  It's a feature!

**Comment by jdramsey** [comment]
Yes, I should have caught that. You're right, that should be set to true by default. The reason is that some algorithms do especially well when variables are in causal order, and they shouldn't be given this advantage, since in search we have no idea what the causal order of the variables is.

**Comment by kvb2univpitt** [comment]
Ah...that makes sense now.  I was wondering why we even have that feature.  Got it now! :)
