### ISSUE TITLE
Allow estimator to run if model has a subset of variables in data set.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#125]
When I try and run the estimator in your session from a PM using the original graph, and the original data it says: Number of variables does not equal the number of dimensions of the matrix. (This is from both the covariance matrix and the raw data.

I mean that I don’t want some of the measured variables included in the model at all. If the output of FTFC has some variables not in any cluster, I would like to create a graph and PM without those variables, and use the original data (which included those variables) to estimate the parameters.

**Comment by jdramsey** [comment]
Actually there is one issue and one bug (I think). The problem with the “Number of variables does not equal the number of dimensions” shows up in the current version whether I select a subset of variables or not. I got that when using the full data set and the full variable set in the graph in the tetrad session that you sent.

**Comment by ps7z** [comment]
Joe,

In older versions of the program, there is no problem with removing a vertex from a graph and using the data set with the full set of variables in the estimator. So I think this is not a feature that needs to be added in the sag version, but a  bug that needs to be fixed.

Peter

**Comment by jdramsey** [comment]
Peter,

I just tried it now with a simple and it seems to work (attaching--). Must
be some other detail...

This session may only work if you pull from fofc_sag_revision again. I just
pushed my changes.

J

On Fri, Jan 1, 2016 at 11:37 AM, ps7z <notifications@github.com> wrote:

> Joe,
>
> In older versions of the program, there is no problem with removing a
> vertex from a graph and using the data set with the full set of variables
> in the estimator. So I think this is not a feature that needs to be added
> in the sag version, but a bug that needs to be fixed.
>
> Peter
>
>
> From: Joseph Ramsey <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: cmu-phil/tetrad <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Thursday, December 31, 2015 at 7:47 PM
> To: cmu-phil/tetrad <tetrad@noreply.github.com<mailto:
> tetrad@noreply.github.com>>
> Subject: Re: [tetrad] Allow estimator to run if model has a subset of
> variables in data set. (#125)
>
>
> Actually there is one issue and one bug (I think). The problem with the
> "Number of variables does not equal the number of dimensions" shows up in
> the current version whether I select a subset of variables or not. I got
> that when using the full data set and the full variable set in the graph in
> the tetrad session that you sent.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/cmu-phil/tetrad/issues/125#issuecomment-168273761>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/125#issuecomment-168315522>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by ps7z** [comment]
Joe,

When you add latent variables, it does not work any more. I have attached a modification of the session you sent me.

Peter

**Comment by jdramsey** [comment]
What is the desired behavior? Should it treat latent variables as missing
or try to find data for them?

Joe

On Fri, Jan 1, 2016 at 4:46 PM, ps7z <notifications@github.com> wrote:

> Joe,
>
> When you add latent variables, it does not work any more. I have attached
> a modification of the session you sent me.
>
> Peter
>
> From: Joseph Ramsey <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: cmu-phil/tetrad <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Friday, January 1, 2016 at 2:14 PM
> To: cmu-phil/tetrad <tetrad@noreply.github.com<mailto:
> tetrad@noreply.github.com>>
> Cc: User <ps7z@andrew.cmu.edu<mailto:ps7z@andrew.cmu.edu>>
> Subject: Re: [tetrad] Allow estimator to run if model has a subset of
> variables in data set. (#125)
>
> Peter,
>
> I just tried it now with a simple and it seems to work (attaching--). Must
> be some other detail...
>
> This session may only work if you pull from fofc_sag_revision again. I just
> pushed my changes.
>
> J
>
> On Fri, Jan 1, 2016 at 11:37 AM, ps7z <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> > Joe,
> >
> > In older versions of the program, there is no problem with removing a
> > vertex from a graph and using the data set with the full set of variables
> > in the estimator. So I think this is not a feature that needs to be added
> > in the sag version, but a bug that needs to be fixed.
> >
> > Peter
> >
> >
> > From: Joseph Ramsey <notifications@github.com<mailto:
> notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>>
> > Reply-To: cmu-phil/tetrad <reply@reply.github.com<mailto:
> reply@reply.github.com><mailto:
> > reply@reply.github.com<mailto:reply@reply.github.com>>>
> > Date: Thursday, December 31, 2015 at 7:47 PM
> > To: cmu-phil/tetrad <tetrad@noreply.github.com<mailto:
> tetrad@noreply.github.com><mailto:
> > tetrad@noreply.github.com<mailto:tetrad@noreply.github.com>>>
> > Subject: Re: [tetrad] Allow estimator to run if model has a subset of
> > variables in data set. (#125)
> >
> >
> > Actually there is one issue and one bug (I think). The problem with the
> > "Number of variables does not equal the number of dimensions" shows up in
> > the current version whether I select a subset of variables or not. I got
> > that when using the full data set and the full variable set in the graph
> in
> > the tetrad session that you sent.
> >
> > -
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cmu-phil/tetrad/issues/125#issuecomment-168273761>.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cmu-phil/tetrad/issues/125#issuecomment-168315522>.
> >
>
>
>
> --
> Joseph D. Ramsey
> Special Faculty and Director of Research Computing
> Department of Philosophy
> 135 Baker Hall
> Carnegie Mellon University
> Pittsburgh, PA 15213
>
> jsph.ramsey@gmail.com<mailto:jsph.ramsey@gmail.com>
> Office: (412) 268-8063
> http://www.andrew.cmu.edu/user/jdramsey
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/cmu-phil/tetrad/issues/125#issuecomment-168335507>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/125#issuecomment-168340098>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by ps7z** [comment]
Joe,

It should estimate all of the parameters of the model without those variables using just the data in the subset of measured variables. It should also count the dof etc as if they are not there. For example, if the model is latent L causes X1 through X6, and I create the model L causes X1 through X5, it should estimate the 5 edges using that data from X1 through X5, and the dof for that model.

Peter

**Comment by jdramsey** [comment]
I found the problem--it's when I calculated the independence model in the SEM IM for Richard. I used the wrong variables. The DOF are find--they are what they were before. I just pushed the change to the fofc_sag_revision branch.
