### ISSUE TITLE
BIC-SEM not showing in the options

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1252]
In the GUI, the BIC-SEM test is not available in the Search box options, for FAS, FASK and multiFASK.

**Comment by jdramsey** [comment]
I found no advantage for it in testing. Did you?

**Comment by rubenSaro** [comment]
-A reason to have it there is that we used it in the feedbacks paper, and thus if someone wants to replicate our methods, she won't be able to do it...
-I remember the reason to use BIC in the first place was those cases where computing the p-values for Fisher's, in the extremes of the tails was problematic, and that the BIC was a good alternative.

**Comment by jdramsey** [comment]
Those are good reasons. OK, I'll try to convince folks to add it back.

**Comment by jdramsey** [comment]
Added back in to the current fixes branch. This will go into development soon.
