### ISSUE TITLE
Solving Categorical problem in Tetrad

### ISSUE THREAD

**Issue by vaishkiva** [cmu-phil/tetrad#1260]
I am having a dataset that predicts whether the person has heart disease or not based on several factors. How to perform the classification problem given there is only a regression box in Tetrad?

**Comment by cg09** [comment]
If you want classification algorithms, which seems to be what you describe,
TETRAD is not the right software suite for you.

**Comment by vaishkiva** [comment]
So can Tetrad solve only regression-based problems only?

**Comment by vaishkiva** [comment]
May I know the steps to solve at least regression problem. I am finding it difficult to move ahead. should the data be encoded before feeding into data box? and after feeding data into the data box I convert the numerical discrete to continuous to get regression results. is this procedure correct?

**Comment by cg09** [comment]
Tetrad is a suite of multiple search algorithms for causal relations and a
simulation facility. Regression is used only for parameter estimation in
the Tetrad software suite.

**Comment by cg09** [comment]
I don't know what you mean by "encoded." You can enter categorical data or
mixed categorical and continuous data and then within the program convert
categorical variables to real valued variables. Conversely, you can
discretize real variables.

**Comment by vaishkiva** [comment]
As a beginner, I am really confused on which algorithm should be used, given more than 20 algorithms. So which algorithms are generally used for a beginner to try on causal relations?

**Comment by vaishkiva** [comment]
Yeah, I understand. Let's say I wanted to find the causal relations on house price prediction data.how do I do that. Should I directly feed in data without preprocessing giving mixed and searching for causal relations?. And if we give convert numerical discrete to continuous for binary values in the dataset , will that make sense?

**Comment by jdramsey** [comment]
Did I send you the paper for Conditional Gaussian? I thought I did. If not, I can send it again.

**Comment by cg09** [comment]
I have never seen it. Do send.
