### ISSUE TITLE
what does a negative BIC score indicate?

### ISSUE THREAD

**Issue by jimluther** [cmu-phil/tetrad#1269]
Degrees of Freedom = 4
Chi Square = 3.6613
P Value = 0.4538
BIC Score = -11.4755
CFI = 1.0042
RMSEA = �

![model](https://user-images.githubusercontent.com/62432961/77171081-4f835d00-6a92-11ea-9bcc-294e9ac3e575.png)

**Comment by jdramsey** [comment]
BIC scores are relative; for our software, higher BIC scores are better. Negative or positive doesn't matter; you just want the maximum. You could try changing things about your model to see if you can do any better.
