### ISSUE TITLE
Is the chi-square independence test working correctly?

### ISSUE THREAD

**Issue by dmalinsk** [cmu-phil/tetrad#1270]
I'm using FCI with the chi-square independence test on some binary data, with alpha=0.05.

If you look at the logging output below, it says that 
h_bar _||_ v_bar | rectangle score = -2.67E-2
But 0.0267 < 0.05 so it should reject the null, i.e., decide that h_bar and v_bar are *dependent* given rectangle. (Assuming this is indeed a p-value, despite the use of "score." I'm not sure what the negative sign is doing here.)

Or am I misunderstanding something here?

Log output from Tetrad:
****
Starting FCI algorithm.
Independence test = Chi Square, alpha = 0.0500.
Starting Fast Adjacency Search.
h_bar _||_ circle score = -9.06E-1
h_bar _||_ y score = -5.44E-1
v_bar _||_ circle score = -7.79E-1
v_bar _||_ rectangle score = -7.90E-1
**h_bar _||_ v_bar | rectangle score = -2.67E-2**
rectangle _||_ y | circle score = -4.89E-1
Finishing Fast Adjacency Search.
Starting BK Orientation.
Finishing BK Orientation.
Step CI C: 0.0s
Starting BK Orientation.
Finishing BK Orientation.
****

Comparison with tests in R:
***using chi-square CI test in package gRim***
> ciTest(df,set=c("v_bar","h_bar","rectangle"))
set: [1] "v_bar"     "h_bar"     "rectangle"
Testing v_bar _|_ h_bar | rectangle 
Statistic (DEV):    5.136 df: 1 p-value: 0.0234 method: CHISQ
*** so null should be rejected ***

***using logistic regression***
> summary(glm(v_bar~h_bar+rectangle,family="binomial",data=df))

Call:
glm(formula = v_bar ~ h_bar + rectangle, family = "binomial", 
    data = df)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.5240  -1.4573   0.8824   0.8824   0.9376  

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  0.59414    0.06325   9.394   <2e-16 &&&
h_bar        0.14827    0.06545   2.265   0.0235 &  
rectangle    0.04331    0.06256   0.692   0.4887    
---
Signif. codes:  0 ‘&&&’ 0.001 ‘&&’ 0.01 ‘&’ 0.05 ‘.’ 0.1 ‘ ’ 1

***so, again, null of conditional independence should be rejected at the 0.05 level in this model***

Interestingly, if I use the statistically saturated regression model instead, with h_bar, rectangle, and two-way interaction term, then the logistic regression test does find them to be conditionally independent. Why should this disagree with the chi-squared test result?

**Comment by jdramsey** [comment]
I'm not sure where it's printing "score =" yet here...

**Comment by jdramsey** [comment]
It's printing the amount the p-value falls below the alpha level. This is to make it compatible with scoring algorithms.

A negative value indicates independence.

    public double getScore() {
        return -(getPValue() - getAlpha());
    }

**Comment by cg09** [comment]
Should put that information in the manual, please

**Comment by dmalinsk** [comment]
Ah I see, thanks Joe. I didn't realize it was printing the amount the p-value falls below the alpha level, and not just the p-value (as it used to do).

So then score=-0.0267 means the p-value for the test was 0.0767?
I'm still a bit perplexed then because the p-value for the "same" chi-square test is .0234 in R. But that isn't necessarily a Tetrad problem of course.
