### ISSUE TITLE
Single cell seq data for Tetrad

### ISSUE THREAD

**Issue by rb56** [cmu-phil/tetrad#1273]
Hi everyone,
I'm new to Tetrad and am trying to run a search algorithm (GFCI) on my single seq data. The alogorithm has been exceuting for >20 hrs and just cannot generate a graph for the data. I've tried running the same algorithm on smaller datasets, and could get a graph, but when I load the entire .csv file, it is taking like forever.
Would be grateful to receive any insight on this.
Thanks!

**Comment by jdramsey** [comment]
Hi, usually when that happens the graph is extremely dense. You're probably tried this already, but have you tried running it with tighter constraints, like a smaller alpha value?

Also, can you tell me how many variables you have and what the sample size is?

Hope all is healthy,

Joe

**Comment by rb56** [comment]
Hi Joe,

Thanks for the input. I'm running the data set with alpha = 0.01. My sample size is 44 and close to 17000 variables. The dataset is very sparse as well as it has a lot of 0's. Do you think that might have an effect ?

Thanks,
Rithika

**Comment by jdramsey** [comment]
Could you describe the variables?

**Comment by rb56** [comment]
the variables are different mRNA  expression levels of different genes, where 0 is no expression.

**Comment by jdramsey** [comment]
They're continuous with sample size 44, with lots of zeroes? I don't understand yet why it's taking so long. The initial step should remove most of the adjacencies... or so I imagine...

**Comment by jdramsey** [comment]
Are there missing values?

**Comment by jdramsey** [comment]
How many adjacencies in *that* graph?

**Comment by rb56** [comment]
0

**Comment by cg09** [comment]
Oh, Joe, you want him to describe 17,000 variables with his 44 data points?
Tell him he is wasting his time.

**Comment by jdramsey** [comment]
I guess I was curious as to where the edges were that it's finding. It seems to be finding enough edges to cause GFCI to hang. I thought maybe it was reading the data in as discrete, but apparently that's not true...

Wait, how are the data being read in?

**Comment by cg09** [comment]
Yes, that is what I think. If you run pc and set the alpha at .1 or .2 for
10 variables, you might get a graph. But 44 data points for 17,000
variables is unlikely to give you anything much not matter what you do.

**Comment by cg09** [comment]
PC and FCI, for example, are doing tests to reject hypotheses of
independence. At a sample size of 44, a dependence would have to be VERY
strong in order for the null to be rejected. My guess is that the writer is
getting no graph because no hypotheses of independence can be rejected. So
the PC algorithm comes up with an empty graph, as does FCI. I am not sure
what GES does in such a case.

**Comment by rb56** [comment]
The data is discrete. I tried using FGES with a higher penalty, and it could generate a graph with nodes.

**Comment by jdramsey** [comment]
Ah! Can you describe the discrete data? I it binary?

**Comment by rb56** [comment]
No it isn't binary. It's in the form of counts, representing the frequency of occurrence.

**Comment by cg09** [comment]
So one variable might have a large number of possible values, most of which
are not instantiated in the data?

**Comment by rb56** [comment]
Yes, that's correct

**Comment by cg09** [comment]
Ok, sorry to say you have no chance of finding relationships with 17,000
variables many of which are of that kind.  Especially not with a sample of
44.

**Comment by rb56** [comment]
Thanks for all the help! I'm kinda new into this domain so I'm still learning and appreciate all the help!
