### ISSUE TITLE
IMaGES  Continuous Setting Bug

### ISSUE THREAD

**Issue by ZhongSiming** [cmu-phil/tetrad#1281]
I'm using tetrad-gui-6.7.1-launch.jar on windows
When selecting parameters for IMaGES Continuous:
If "Yes if verbose output should be printed or logged" is set to "Yes", the "Run Search & Generate Graph >" button will not function. I can click and watch it depress, but nothing happens. If I click on "Done", it will warn me that no analysis has been run and ask if I want to continue or cancel. If the option is set to "No" it will begin execution.

**Comment by kvb2univpitt** [comment]
Hello.  What version of Java are you running Tetrad on?  How large is your dataset?  Can you please provide a screenshot?  Thanks.

**Comment by ZhongSiming** [comment]
I'm using Java 8 update 201. I have 5 equally sized datasets with 3,217 rows and 401 columns.
![image](https://user-images.githubusercontent.com/35843055/80740236-c9712200-8ae5-11ea-8c3c-760a9c9bf56a.png)

**Comment by kvb2univpitt** [comment]
Can you please do me a favor?  Can you please set the "The number of bootstrap/resampling iteration (min=0)" option back to 0 and run it?  Does it work?

**Comment by ZhongSiming** [comment]
It appears to work regardless of all settings except "Yes if verbose output should be printed or logged". If that is set to "Yes" it will not allow me to press "Run Search & Generate Graph >". If it is set to "No" the program begins executing. I'm waiting for it to finish executing, but my guess is that it is going to take quite a while (days) before it does finish.

**Comment by kvb2univpitt** [comment]
It seems like you have a large workload, especially if you're doing bootstrapping 10 times on large dataset.  Let's see how it goes for now.
