### ISSUE TITLE
Problems in validation of data

### ISSUE THREAD

**Issue by rb56** [cmu-phil/tetrad#1282]
Anybody facing problems in validating data which loading a .csv file?

**Comment by kvb2univpitt** [comment]
Hello.  Can you please elaborate on that?  What version of Java are you using, what version of Tetrad, etc.

**Comment by rb56** [comment]
Hi,
I'm trying to load a .csv file with around 650 variables, but I can never get past the validation step. 
I'm using Tetrad 6.4.0 and Java 8. I've had no problems in the past loading data with upto 2100 variables, so I'm unsure of what is happening now.

**Comment by kvb2univpitt** [comment]
What is the error message saying?

**Comment by rb56** [comment]
There's no error message. There's a bar which shows that the data is being validated. Here's a snippet.
![Screen Shot 2020-04-30 at 12 54 49 PM](https://user-images.githubusercontent.com/62675463/80737632-d3912180-8ae1-11ea-8601-023d658137af.png)

**Comment by kvb2univpitt** [comment]
The Tetrad GUI is not helpful in outputting program errors.  Can you please run tetrad using a command-line terminal and load the data again?  For an example,
```
java -jar tetrad-gui-6.4.0-SNAPSHOT-launch.jar
```
The terminal will give you the error message.   Also, I noticed that you're not using the latest, stable version of Tetrad.  Can you please try using version 6.7.1?  There's a lot of bug fixes in that release.
https://github.com/cmu-phil/tetrad/releases/tag/v6.7.1

**Comment by rb56** [comment]
I tried running it on version 6.7.1 and it works!! 
Thanks a lot!

**Comment by kvb2univpitt** [comment]
Awesome!  I am glad it's working now.

**Comment by hickman-santini** [comment]
I just had this problem with 6.8.0 when my data looked like the OP's (header line began with comma because observations have names/indices). I got the error: `ERROR edu.pitt.dbmi.data.reader.tabular.TabularColumnFileReader - Missing variable name on line 1 at column 1.`

Easily solved by removing the index column from the data; just a small nuissance and not an uncommon situation, I think! So I thought I'd post.
