### ISSUE TITLE
Can't get Tetrad to recognize time series data

### ISSUE THREAD

**Issue by ZhongSiming** [cmu-phil/tetrad#1285]
I have census data from 5 years (1970, 1980, 1990, 2000, & 2010). When I try to get Tetrad to convert it to time-series data, it won't. I also tried to create my own time series using what I thought was the Tetrad format, by creating lagged variables of the format varname:N where N is the lag number. That also did not work. I've scoured the manuals, but cannot find any instructions on how the data should be formatted or what Tetrad needs in order to convert to time series data. Please help. :)

**Comment by jdramsey** [comment]
Ah, sorry I missed this. The usual thing to do is load the data normally and then draw another data box, connected Data1 -> Data2, then double click Data2 and select Time Lag Data.

That's why I was asking if you could load it at all.

**Comment by jdramsey** [comment]
Well, one thing I can do is note this is a duplicate issue:

https://github.com/cmu-phil/tetrad/issues/1353
