### ISSUE TITLE
Algorithmic Error in FGES

### ISSUE THREAD

**Issue by EPronovost** [cmu-phil/tetrad#1286]
I believe I've found an algorithmic error in FGES.  tl;dr the checks we do to decide if an arrow is valid are highly correlated but not equivalent to the correct checks.

For context, here's a short summary of insert op tracking.  We store possible operations as `Arrow`s which for an edge `x --> y` also [stores](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L1399-L1407) the set `T` (for insert) or `H` (for delete), `naYX := {z : z is an undirected neighbor of y and adjacent to x}`, and `TNeighbors := {z : z is an undirected neighbor of y not adjacent to x}`.  In `calculateArrowsForward`, we check a set of [necessary but not sufficient conditions](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L1234-L1273) for a valid insert and add all those that pass.  At the start of a forward step, we check the top arrow to [see if it is valid](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L952-L977), and insert it if it is.

In these checks at the start of a fes step, we test that
* `x` and `y` are not already adjacent
* Neither `x` nor `y` has a max degree already
* The stored `naYX` is still correct
* The stored `TNeighbors` is still correct
* The insert is still [valid](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L1669-L1688)
    - `T union naYX` is a clique
    - Every semi-directed path from `y` to `x` goes through `T union naYX`
    - The insert doesn't violate the supplied `Knowledge`

This last bullet point comes from Table 1 of Chickering (2002b).

From my understanding, the necessary and sufficient conditions for an arrow to still be valid are:
* `x` and `y` are not already adjacent
* Neither `x` nor `y` has a max degree already
* The insert is still valid (i.e. `T union naYX` is a clique and captures every semi-directed path from `y` to `x`)
* The stored bump value is still correct

The stored bump is [computed](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L1518-L1527) as `SemScore(x, y | cond_set)` where `cond_set := T union naYX union paY` (where `paY = parents(y)`).  Thus, for the bump to still be valid, we need this set `T union naYX union paY` to still be accurate.  `T` is defined as part of the `Arrow`, and we check that `naYX` is the still accurate.  However, we don't explicitly check that `paY` is still accurate.  If there were a new parent, it would no longer be a `TNeighbors`, and so we would detect that change.  However, it is possible for the set `TNeighbors` to change without `paY` changing if an undirected neighbor becomes a child.  If this occurs, we will incorrectly conclude that the arrow bump is no longer accurate and skip it.

Normally this isn't an issue because we tend to recompute all valid insert ops when the neighbors of a node changes.  However, I've been able to create a test case that manifests this error.  Consider the following graph and edge weights (two unshielded colliders with an edge between the two).  The edge weights are chosen to induce a specific ordering of the arrows.

<img width="538" alt="Screen Shot 2020-05-19 at 10 06 32 PM" src="https://user-images.githubusercontent.com/8582453/82407091-1a0cd880-9a1d-11ea-8507-5b866868e039.png">

We first insert `X2 --- X3` and `X4 --- X5`, and recompute all possible insert operations that add an edge incident on these four edges.  At this time, for the edge between `x = X3` and `y = X4`, `naYX = {}`, `TNeighbors = {X5}`, and `paY = {}`.

We then insert `X1 --- X2` and `X5 --- X6`.  Both of these induce unshielded coliders `X1 --> X2 <-- X3` and `X4 --> X5 <-- X6`.  Now, for the edge between `x = X3` and `y = X4`, `naYX = {}`, `TNeighbors = {}`, and `paY = {}`.  However, we don't recompute valid insert operations between these two nodes.

We then consider the edge between `X3` and `X4`.  Note that since `T union naYX union paY` has not changed, this arrow is still valid.  However, because the stored `TNeighbors` does not match the current `TNeighbors` we skip this arrow in error.  In the end, the FGES algorithm outputs two disjoint unshielded colliders.  

<img width="444" alt="Screen Shot 2020-05-19 at 10 15 32 PM" src="https://user-images.githubusercontent.com/8582453/82407555-4aa14200-9a1e-11ea-9783-5fb91b9828af.png">

This happens even in the large sample limit with low noise on the variables.

I believe there are several ways to address this.  We could modify the `MeekRules` to more aggressively recompute arrows.  We could also modify the checks in the fes step.  I'd like to hear your thoughts on this analysis, and on potential solutions.

**Comment by EPronovost** [comment]
cc: @eberharf

**Comment by jdramsey** [comment]
Thanks for sending this. I'll go through it when I get a chance. I guess the reason we thought it was correct was that it passes a very difficult unit test, where we check there result against the true pattern calculated using PC with d-separation facts for many random DAGs in sequence, but maybe there's an issue with that test.

Joe

**Comment by jdramsey** [comment]
Let me think. Your worry is that t neighbors can change even if parents don't change. But the question isn't whether parents change, is it? It's whether the parents in any possible DAG in the pattern change, no?

Also, what do you mean when you say that Meek rules should be more aggressive? The Meek rules are the Meek rules; unless you're not already in a pattern, they can only orient one way. Unless they're coded wrong...?

**Comment by EPronovost** [comment]
After each step of FGES we run the Meek rules to obtain the complete PDAG of the current state, so I believe any directed edge should be directed in all possible DAGs of the current equivalence class, right?

Sorry for the unclear statement about the Meek rules.  I agree the actual edge updates are what they are.  The current `MeekRules` implementation keeps a list of [`visited` nodes](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/MeekRules.java#L69-L70) which are [used to decide which nodes to update](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L985-L1000) in FGES.  In this counter-example, when we do the insert `Insert( X1, X2, {X3})`, the adjacencies of `X3` change (`X2` goes from being a neighbor to child), but we don't recompute arrows for `X3`.  My comment about more aggressively recomputing arrows was to say that we should have updated `X3` in this case.  Thinking about it some more, I think what we should do instead of modifying the `MeekRules` is to simply add the set `T` to the set `toProcess`, along with `x` and `y`, since every node in `T` has by definition had its neighbors changed.  I believe such a change would fix the specific counter-example I shared above.

What do you think about that?

**Comment by jdramsey** [comment]
The "visited nodes" are just to avoid redundancy; they're not making the rules any less correct. This is something I should have written up somewhere. It's a way to apply Meek rules on a large graph without having do any more steps then you need to, locally about  set of specified nodes. It orients only the edges using the Meek rules that are needed and no more, so it doesn't have to visit the entire graph, and it doesn't have to duplicate work.

I have to think about your other point. You mean just the oriented parents, not the possible parents of a node. Is that right?

**Comment by jdramsey** [comment]
How you coming with this?

**Comment by EPronovost** [comment]
Yes the visited nodes capture the nodes whose adjacencies are modified by the application of Meek Rules.  The nodes passed to `reevaluateForward` [here](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fges.java#L1000) should include _all_ nodes whose adjacencies have been modified in this step.  The two places we modify edges are in the insert op and the Meek rules.  The insert op modifies `x`, `y`, and each node in `TSet`.  The Meek rules modifies each node in `visited` (by definition).  However, we only consider `x`, `y`, and `visited` to create the `toProcess` list.  Often times, the nodes in `TSet` may also be in `visited`, but not necessarily.  To be correct we should add `TSet` to `toProcess`.

**Comment by jdramsey** [comment]
Well, it certainly can't hurt to add T to the toProcess list. Let me try. The only reason I'm a little dubious is that FGES is currently passing a rather stringent unit test from d-separation, so I'm inclined to think the algorithm, from the point of view of d-separation, is correct. But maybe there's another reason to suspect it's messing up that can't be captured by d-separation. Let me try.

**Comment by jdramsey** [comment]
I had also added the set of common adjacents to the toProcess list. If I replace this with the T set nodes, the unit test still passes. Let me think.
