### ISSUE TITLE
Tetrad Command Line - PC error

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1288]
Hi,
This is for Tetrad command line, version: causal-cmd-1.1.3
These bootstrap options are not recognized when running --algorithm pc-all 
--addOriginalDataset 
--resamplingWithReplacement 
--percentResampleSize 100 
--numberResampling 10 
--resamplingEnsemble 2

In contrast, the bootstrap works when using the GUI

Thanks,

Ruben

**Comment by kvb2univpitt** [comment]
@rubenSaro Yeah, this is an issue.  Bootstrapping is currently not working at the moment.  I will fix this in the next release.  Thanks.
