### ISSUE TITLE
Why named tetrad？

### ISSUE THREAD

**Issue by MiyeonQAQ** [cmu-phil/tetrad#1317]
Hi!
I have always been curious: why named a causal inference software 'tetrad'? 
BTW, GOAT tool for causal inference！Good job!

**Comment by cg09** [comment]
Hello,

Good question.  Many years ago, in the 1980s, when we were first exploring
the possibility of automated search, we pursued ideas introduced at the
beginning of the 20th century by Charles Spearman, an English psychologist.
Spearman had figured out that a single linear cause of four measured
variables entails three quadratic relations among four correlations of the
measured variables, which he called "tetrad equations."  Our earliest
software was a program for calculating these relations and using them in
model search. So we called the software "TETRAD."  As the software became
more elaborate and more sophisticated and evolved into a suite of
algorithms, we didn't bother to change the name. Too late now.

Clark Glymour
