### ISSUE TITLE
Problem with latest release 6.8.1

### ISSUE THREAD

**Issue by Udayanda** [cmu-phil/tetrad#1320]
Hi
I installed the jar file 6.8.1 today. 
It seems to have a bug since the "validate" step is running endlessly.
The same data file on the 6.8.0 release was validated successfully.
Thank you for your attention to this problem
Regards
Udayan

**Comment by kvb2univpitt** [comment]
@Udayanda Hello.  Are you able to provide the dataset so that I can reproduce the error?
