### ISSUE TITLE
Outputting the results

### ISSUE THREAD

**Issue by bio7420** [cmu-phil/tetrad#1321]
Greetings,
I've done an analysis using FASK for search algorithm and SEM as a parametric model for the rfMRI data.
Is there any way that I can output this result as a matrix format (e.g. .txt, .csv, etc.) so that I can use the result in the MATLAB?

Best regards,

**Comment by jdramsey** [comment]
Wait, is this closed or open? :)

**Comment by bio7420** [comment]
It's closed :)
I'm trying to get the answer myself first, but then encountered another
question so I opened a new issue

**Comment by jdramsey** [comment]
I see! OK.
