### ISSUE TITLE
R3 not working in 6.9.0

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1325]
Hi,

I tried to run a R3 algorithm search (attaching the proper undirected graph + data boxes) and it output an error (attached below).

<img width="315" alt="image" src="https://user-images.githubusercontent.com/40474901/120044115-356cd500-bfdb-11eb-9342-a7f76e37be3a.png">

**Comment by jdramsey** [comment]
Sorry I missed this. I'll try to fix it.

**Comment by cg09** [comment]
What?
