### ISSUE TITLE
How to run R3 on command line

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1326]
Hi,

In the GUI to run the R3 algorithm, you need an undirected graph box (for example, from FAS) and a dataset box. How can a R3 search be done, if possible, in Tetrad Command Line? 

Thanks

**Comment by jdramsey** [comment]
Ruben, was this ever made to work for you?

**Comment by rubenSaro** [comment]
no.

**Comment by jdramsey** [comment]
Problem is, there's a skeleton crew working on that, but I may be able to create a "funnel". You want to run FGES and then R3? I could make an algorithm that just does that. Wouldn't involve any new syntax.

**Comment by jdramsey** [comment]
Yeah tell me exactly what you need and I'll make it.

**Comment by rubenSaro** [comment]
that is a good idea...it was actually a user asking about how to run R3 in
command line, a while ago...and I remember I couldn't do it when command
line tetrad first was published. Maybe wait for the crew to make it
available in the future? or make available FGES + R3 as an option as you
are suggesting?

**Comment by jdramsey** [comment]
Either is fine, although the second is easier for me to do on my own.

**Comment by jdramsey** [comment]
@kvb2univpitt I'm not sure whether this issue is yours or mine, since there are two ways to do it:

1. Add parameters to the pattern algorithms to do a subsequent pairwise orientation step (my issue).
2. Add a way in the command line to give an external graph as input to the pairwise algorithms (your issue).

Which way should we go?

**Comment by jdramsey** [comment]
I'm more and more thinking that there should be a flag in causal-cmd for this, that makes causal-cmd read in a graph from a file as an “external graph” and pass it to the algorithm, if the algorithm takes and external graph, like --externalgraph [path_to_external_graph.txt].

**Comment by jdramsey** [comment]
I think this issue is very old now; I'm going to close it for now, but @rubenSaro if you need me to look at it again re-open it for me. Sorry, I've just run out of time to address all of the issues.
