### ISSUE TITLE
cannot run tetrad-gui-6.9.0-launch on macOS

### ISSUE THREAD

**Issue by jjiantong** [cmu-phil/tetrad#1328]
Hi,

I am trying to use the latest release v6.9.0. I am using macOS 11.4 and Java 16.0.1. I followed the instructions in "Building Tetrad using Command Line" in your Wiki to build the package, and I successfully generated the jar executable file "tetrad-gui-6.9.0-launch.jar" in "tetrad-gui/target". Then can I just double click the executable file? It has been stuck on the "Loading Tetrad ..." when I do this. Thanks for your time.

**Comment by jdramsey** [comment]
Just a dumb question: Do you happen to have another copy of Tetrad open somewhere else? Because that's exactly the effect that would have... I may be wrong, but it's the first thing to check. If so, close the other one and try again.

**Comment by jjiantong** [comment]
> Just a dumb question: Do you happen to have another copy of Tetrad open somewhere else? Because that's exactly the effect that would have... I may be wrong, but it's the first thing to check. If so, close the other one and try again.

Thanks for your reply. I have checked and tried again, but it is not the reason for my case unfortunately. I just tried the causal-cmd 5 minutes ago and it worked. I am not bothered by this problem anymore. :-)

**Comment by jdramsey** [comment]
Oh that's good. Well anyway, I am sitting here running Tetrad on a Mac, so I'm sure we can figure it out if you change you're mind.

**Comment by jjiantong** [comment]
> Oh that's good. Well anyway, I am sitting here running Tetrad on a Mac, so I'm sure we can figure it out if you change you're mind.

Oh, that's wonderful. So if I download `tetrad-gui-6.9.0-launch.jar` from [https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/cmu/tetrad-gui/6.9.0/](url), should I just try double click it to let it work? Thanks again.

**Comment by jjiantong** [comment]
Hi, I just solved this problem by changing Java 16 to Java 8. It seems that Tetrad v6.9.0 and Java 8 are not compatible.
