### ISSUE TITLE
Can't create model from knowledge box

### ISSUE THREAD

**Issue by ko56** [cmu-phil/tetrad#133]
The manual needs to be updated to say that if using a knowledge box, a search box needs both a knowledge box and a data or data manipulation box as inputs.

**Comment by jdramsey** [comment]
Noted. Sorry so slow, been busy.

**Comment by jdramsey** [comment]
Actually in the branch 'experimental' I'm putting the knowledge editor directly inside the algorithms editor to make this more intuitive. So I'll close this.
