### ISSUE TITLE
Increasing the # of threads

### ISSUE THREAD

**Issue by MEl3dwi** [cmu-phil/tetrad#1332]
Hi--

First, thank you very much for the wonderful tools. 

I just have a question about increasing the speed of the tool. I have fairly large data, and I am trying to use the GFCI algorithm. The tool has been running for 3 weeks now. I utilization of my CPU is very low, around 5%. I was wondering if there is a way to increase the # of threads or something to speed up the process. I know there something mentioned in the documentation about using remote supercomputers.

Thank you.

**Comment by cg09** [comment]
The runtime complexity depends on the number of variables and the density
of the unknown true dependencies. I suggest starting by setting the penalty
for FGES very high and the significance level for FCI very low as a first
pass.

**Comment by MEl3dwi** [comment]
Thank you for the reply. I will give it a try.

**Comment by jdramsey** [comment]
How many variables are you using?

**Comment by jjiantong** [comment]
Hello, I wanna know how the default # of threads is? Thank you.

**Comment by jdramsey** [comment]
The default # of threads for the adjacency search is 10 * # available processors.

**Comment by jdramsey** [comment]
It took me a minute to remember that algorithm. It is mine, but my memory is not as good as it could be. The idea is that on uses a multi-dataset version of the fGES algorithm to find the adjacencies and then uses a multi-dataset version of FASK to get the orientations. In the code, in case you're looking, it's called FaskVote. The problem, I think, is in the FGES step. There's only so much parallelization one can do in FGES, and I think I managed to parallelize all fo the possible places. There's an initial step where on considers all possible edges to add to an empty graph. That's can easily be parallelized. After that is a long series of steps that must be treated serially. Within each step, some parallelization can be done, but the steps as a whole much follow one another in sequence. My guess is that you've gotten into a state where this second step is much longer than the first. Is that possible?

**Comment by MEl3dwi** [comment]
Thanks for the information. Actually, I am using GFCI not FGES. But, after
the first step, each step take days. The workstation had been running for 3
weeks with no results before IT restarted all PCs. I am open to take a look
at the code; I would appreciate it if you give me a hint on where to look
for it. Thanks.

Mahmoud

**Comment by jdramsey** [comment]
Sorry I responded to the wrong ticket. I'll have to copy my comment over. Right, GFCI. Still, GFCI uses FGES as an initial estimate of the graph, then corrects the discrepancies and proceeds with FCI. You'll get a drag from the serial step of FGES, and then also the FCI part has some steps that can be quite slow--see the possible d-sep step. (Possibly you could turn that off--I think there's a switch for that.)

You're welcome to look at the code. You already know where the repository is; did you just want a class path?

**Comment by cg09** [comment]
How many variables do you have in your dataset?

**Comment by MEl3dwi** [comment]
@jdramsey: Thanks. I will be good, I thought it would be easier if you reference a specific part that might need improvement. 

@cg09: 1500 variables cont and discrt

**Comment by MEl3dwi** [comment]
Another inquiry is I tested the GES algorithm using the MS WinMine tool on the same dataset and it took only 5 min to generate the graph. Why would you think there might be this difference in time? Is it because GES is simpler?

**Comment by cg09** [comment]
FGES should be faster than GES. But FCI is VERY slow.
