### ISSUE TITLE
TETRAD GES doesn't work for discrete datatype

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#134]
Hi Dr. Ramsey, 

I tried to run TETRAD command line GES search like this

> java -jar lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar -data inputfile.tsv-p **-datatype discrete** -algorithm ges -depth -1 -significance 0.01

Then, I got an error message that input data is 'not continuous data'. So, I changed the values in the input file with continuous values, and ran again.  Then, it works.   (-datatype discrete/continous  in the parameter doesn't matter.)  It is strange..  I attached an example of input file. 
[example_input.txt](https://github.com/cmu-phil/tetrad/files/125485/example_input.txt)

GES doesn't work for discrete data?   Could you help me how I can fix this or which source file I should look up? 

Thank you,
Sanghoon

**Comment by jdramsey** [comment]
Sorry Sanghoon. This was solved some time ago. I hope you've been able to use FGS with discrete data.

Joe

**Comment by biotech25** [comment]
Yes, we can use FGS -discrete.  Thank you for your help!

Sanghoon
