### ISSUE TITLE
fges rcausal spawns too many threads

### ISSUE THREAD

**Issue by sthawinke** [cmu-phil/tetrad#1354]
The fges algorithm works well on preliminary tests, but when running it on a centox linux server, it spawns a large number of threads, eventually crashing the entire server. I set the option --thread 3 but this does not seem to work. Is there a way around this?

**Comment by jdramsey** [comment]
I spend sometime revising this code so that the theads = 1 option works correctly. I believe with the next published version this should work. Sorry for the delay--short-handed.

**Comment by jdramsey** [comment]
I have just revised the FGES code to enforce that if numThreads = 1 a single thread is used; once this gets pushed to Tetrad-Cmd, this issue should be resolved.
