### ISSUE TITLE
Causal-cmd documentation has outdated examples

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#1356]
From a causal-cmd user.

The provided example:
java -jar causal-cmd-1.0.0-jar-with-dependencies.jar --algorithm fges --data-type continuous --dataset Retention.txt --delimiter tab --score sem-bic
Works when changed to:
java -jar causal-cmd-1.3.0-jar-with-dependencies.jar --algorithm fges --data-type continuous --dataset Retention.txt --delimiter tab --score sem-bic-score --skip-latest
Because:
Error: Unable to access jarfile causal-cmd-1.0.0-jar-with-dependencies.jar
No such score 'sem-bic'.
Running version 1.3.0 but the latest version is 1.2.0.  To disable checking use the skip-latest option.
 
Also, I was unable to understand the file containing priors based on the information given on the help page.  The included Retention.prior file does not look the same as the example that is shown on the help page.

**Comment by jdramsey** [comment]
@kvb2univpitt Do you know if this was every fixed? I'm guessing yes...

**Comment by kvb2univpitt** [comment]
@jdramsey No.  This issue has not been fixed.  The code in Tetrad is changing a lot.  I'll wait until the next official release of Tetrad to update the causal-cmd to use the latest tetrad-lib.  Once that's done, I'll update the documentation.  If I do it now, I will have to do it again later if anything else changes.

**Comment by jdramsey** [comment]
Maybe this documentation should be put in the causal-cmd repository. (@kvb2univpitt you had suggested this.)

**Comment by jdramsey** [comment]
Moving this issue to causal-cmd: https://github.com/bd2kccd/causal-cmd/issues/87
