### ISSUE TITLE
non-Gaussian orientations

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1362]
In the Tetrad release 6.9.0, the non-Gaussian orientation methods do not work.

**Comment by jdramsey** [comment]
Hmm.. what method are you using and what GUI hookup?

**Comment by rubenSaro** [comment]
RSkew, connect the search to a FAS output and to the Simulation box.
I am using a two variable X-->Y model with structural linear parameterization
And Gaussian data (because I want to see that indeed Rskew random guesses with Gaussian data)

**Comment by jdramsey** [comment]
Have you tried hooking up like this? It works for me, but it's possible I fixed something. I'm in my own branch at the moment.

<img width="411" alt="Screen Shot 2022-01-14 at 3 59 52 PM" src="https://user-images.githubusercontent.com/9853255/149584469-d24f2473-d427-4b6e-9ca7-30d3f235947e.png">

**Comment by rubenSaro** [comment]
I tried it. Got this

![image](https://user-images.githubusercontent.com/40474901/149599507-45b7eaab-9de8-4452-bfd0-eebbe639bae7.png)

**Comment by jdramsey** [comment]
Let me load up the development branch and see if I can spot the problem.

**Comment by jdramsey** [comment]
Oh geez, that's odd--in that line the row/column indices were reversed. Why did this ever work? I'll send you a version later with the right order. 

Please don't close this issue--it'll remind me to fix this in the published version next time.

**Comment by rubenSaro** [comment]
sure. thanks for checking on this.

**Comment by jdramsey** [comment]
Fixed in tetrad-fixes-joe-20220203
