### ISSUE TITLE
Visual Graph

### ISSUE THREAD

**Issue by ahadda5** [cmu-phil/tetrad#1367]
Open the gui jar tetrad (vs 6.9.0-0)  and create a DAG graph. 
Add the nodes one by one.  Two issues

1) If you change a variable(node) name, all the edges created after that point will be disappear. 
2) Cannot add any edges anymore, in the current session.

**Comment by ahadda5** [comment]
Windows 10. RAM 32 GB
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)


For now, i just stick with the given names and build the graph, bypassing that issue.

**Comment by jdramsey** [comment]
OK, though I am curious whether I fixed it. I remember seeing that issue some time ago and thought I fixed it, so I hold out hope that the issue will go away with the next published version.

**Comment by jdramsey** [comment]
Mike tells me the bug doesn't exist on my current (repository) build, so I must have fixed it!

**Comment by jdramsey** [comment]
By the way, I'm closing this issue since it's fixed in my branch, but if you'd like to try my current version send me an email and send it to you.

**Comment by MikeKonrad** [comment]
Hi Joe, I ran into the same issue (just trying to duplicate the error). Here’s what I’m running:

Windows 10, RAM 64 GB java version:
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

I opened a Tetrad session, inserted a graph box (rest of palette is blank), choosing a DAG in the pop-up, opened the graph box, put down about three nodes, connected them a bit, then added three more connected them. Along the way on 3-4 occasions, I’d change the name of a node. Nothing happened for the first two nodes, which I changed 1-3 times each.

But then I changed the very first node “X1”, which originally was connected to a node called “X2” but had been changed to “X2.11” (second name change for that node) and tried to change “X1” to “ashortname” and presto: all 7-ish edges disappeared! I then seemed unable to visually see any of the added edges, though opening Graph Properties showed they were there. And trying to add an edge did increment the Graph Properties edge count (thus the 8 vs. the 7 reported earlier).

***@***.***

But then I hung a graph box (DAG) off the first one, and in the second box the entire graph (including invisibly added edges) appeared correctly, went back to the first graph, re-opened it, and it appeared exactly as it should be:

***@***.***

And that includes the new 9th edge I added. So the problem does go away, though unclear why it happens at all.

Mike

**Comment by jdramsey** [comment]
Huh. I'll have to think about that.

Joe

**Comment by MikeKonrad** [comment]
Hi Joe, that’s curious! That’s an old email message but it is timestamped “Oct 11, 2022 at 5:26”. I was not yet out of bed so I couldn’t have sent it then!

I think this is an old email from March of this year (note the longer email thread)!

Don’t know how that happened.

Mike

**Comment by jdramsey** [comment]
Huh! OK! :) But we did have edge disappearing cases happening in the
session workbench a short time ago; I thought it might be related. :)

Interesting. :)
