### ISSUE TITLE
Adjust score/test chooser to give a choice of "Linear/Gaussian", "Mixed Discrete/Continuous", "General", and "All"

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1368]

**Comment by kvb2univpitt** [comment]
Fixed.

**With no missing data:**
![no-missing-data](https://user-images.githubusercontent.com/10729309/159214621-9b365308-a638-45d4-b5b0-a28dbdfba945.png)

**With missing data:**
![missing-data](https://user-images.githubusercontent.com/10729309/159214630-a1008d3e-030b-41cf-8d93-f37f78a2d6d3.png)

**Comment by jdramsey** [comment]
Fixed.
