### ISSUE TITLE
Debug why the JunctionTree updater throws up an error message about missing indices.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1369]

**Comment by jdramsey** [comment]
<img width="730" alt="Screen Shot 2022-03-20 at 7 22 08 PM" src="https://user-images.githubusercontent.com/9853255/159190449-3227aa4b-778d-49ba-8f69-77cb8a34bcac.png">

**Comment by jdramsey** [comment]
I will make a session.

**Comment by jdramsey** [comment]
[JunctionTreeIssue.tet.zip](https://github.com/cmu-phil/tetrad/files/8312393/JunctionTreeIssue.tet.zip)

This shows the problem. I'm using the branch tetrad-fixes-joe-2022-02-28.

**Comment by kvb2univpitt** [comment]
Fixed.  The problem was because the JunctionTreeUpdater calls get conditional probability when there is no parent.

![jta_updater](https://user-images.githubusercontent.com/10729309/159550515-3a575bc5-e338-478f-a465-27ff33f24487.png)

**Comment by jdramsey** [comment]
Done.
