### ISSUE TITLE
Error in ExampleCompareSimulation.java

### ISSUE THREAD

**Issue by hsnowsunny** [cmu-phil/tetrad#1371]
Hi,
I want to compare the performance of different algorithms. Run ExampleCompareSimulation.java in the package edu.cmu.tetrad.algcomparison.examples; 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/24354465/159250158-e3be7bd4-80e1-449f-880c-13dd3149a6b6.png">

There is an error:
Parameter connected was not actually boolean.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/24354465/159250438-4e80862c-6364-4ff6-ac71-df1f1aed1f58.png">

How can I fix it?
Thanks

**Comment by jdramsey** [comment]
You need to do a Maven clean compile to get the manual (index.html in the docs folder) copied to the right place. The parameters definitions are read from that file. I need to remember to document that.

**Comment by jdramsey** [comment]
By the way, I assume since you're asking me a question of this nature that you know what I'm talking about. If not, let me know and I can give you more pointers.

**Comment by jdramsey** [comment]
I assume this is OK now so I'm closing it. Re-open if not.
