### ISSUE TITLE
In Search box, score and test choices do not get preserved in cases where algorithm choices do and all parameters do.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1373]
Branch tetrad-fixes-joe-2022-02-28. This procedure.

Put Simulation-->Search on the workbench.
Double click Simulation, select Structural Equation Model, click Simulation, Done.
Double click Search, select FGES, select EBIC Score, click Select Parameters, Run Search & Generate Graph,  Done.
Double click Search, click Set Parameters, Choose Algorithm, see that EBIC is still selected and FGES is still selected, click Done.
Double click Simulation, click Simulate, click OK, click OK, click Done.
Click Execute.
Double click Search, click Set Parameters, Choose Algorithm, see that FGES is still selected but EBIC Score has now reverted to SEM BIC Score.

**Comment by kvb2univpitt** [comment]
Fixed.

**Comment by jdramsey** [comment]
Thanks!
