### ISSUE TITLE
Junction tree updates sometimes not updating.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1374]
Make Graph->PM->IM->Updater.
Double click Graph, make random graph.
Double click PM, make Bayes PM, random.
Double click IM, make ML Bayes IM, random.
Double click Updater, choose Junction Tree Updater.
Double click Junction Tree Updater, set evidence X1 = 0.
Click Do Update.
Note that the X1 = 0 does not have 100% probability.

Attaching session.

Please grab latest branch for tetrad-fixes-joe-2022-02-28.

[juncttreeexample.tet.zip](https://github.com/cmu-phil/tetrad/files/8344080/juncttreeexample.tet.zip)

**Comment by kvb2univpitt** [comment]
Fixed.
