### ISSUE TITLE
How to run a single algorithm?

### ISSUE THREAD

**Issue by williamty** [cmu-phil/tetrad#1383]
I need to use Degenerate Gaussian BIC Score to calculate the BIC score for my real world data. But after downloading the tetrad-gui-6.9.0-launch.jar, I don't know how to run DG algorithm. Can I use it through command line?

**Comment by jdramsey** [comment]
You can do it using causal-cmd. Let me know if you're not able to find that.

BTW we're trying to release a new version of Tetrad. Hopefully soon. Once that's released we'll hopefully be able to release a new version of tetrad-cmd as well.

**Comment by jdramsey** [comment]
BTW we have released 7.1.0--check i t out...

**Comment by williamty** [comment]
Thank you for your reply! I'll try the new version and close this issue  first. Thank you again.
