### ISSUE TITLE
Can it use GPU or CUDA to run those algorithms?

### ISSUE THREAD

**Issue by williamty** [cmu-phil/tetrad#1385]

**Comment by jdramsey** [comment]
Hmm.. yeah not so far. I think the main hurdle is I don't have a Mac with an extra graphics card. Maybe I'll look into that. Also a lot of algorithm in Tetrad aren't exactly linear algebra style algorithms. Not to say GPU couldn't help, but I'd have to think about it.

Several of the algorithms are parallelized, and I'm intending to work on more parallelization sometime later this year. Would this help? Do you have access to a supercomputer or some machine with many processors? It might be more effective than a GPU in any case...

What did you have in mind?

**Comment by jdramsey** [comment]
Also isn't CUDA more machine-specific? Can I do that from Mac? Looks like it wouldn't be very much not pure Java...

**Comment by jdramsey** [comment]
Another issue that's prevented me from going in that direction in the past is that the scaleups I've mainly been aiming at in my own work have been for data that don't git into a GPU, and I haven't found any good way to get around that yet... any ideas?

**Comment by jdramsey** [comment]
Anyway this is worth thinking about. Also, maybe some specialized JDK can already do it?

**Comment by williamty** [comment]
Yes, I think you're right. I'll close this issue. :-)

Those algorithm in Tetrad dont need GPU. Another causal toolkit called causal discovery tool, which implemented some big data algorithms, mainly runs on GPU. Different situations, different solutions.

**Comment by cg09** [comment]
A student suggested graphics cards to me years ago. I don't think it is
even close to rational to put in the the effort it would require to
reprogram our algorithms for gpus for the few users would would need them.
Let those who need them do it themselves.
