### ISSUE TITLE
Problem setting the Search parameters in Tetrad 7.1.0

### ISSUE THREAD

**Issue by f-arab** [cmu-phil/tetrad#1386]
Hi, 
I have a problem setting the search parameters in the Tetrad GUI. I know that all the parameters of each search method are explained in the Online Manual. I used that and tried to set the parameter values accordingly, but when I hit the "Run Search and Generate Graph " button, it gives me an error like this, for example,  "Parameter precomputeCovariances was not actually boolean" and changing the parameter values does not make it work.

I tried to use the video tutorials for Tetrad to follow the steps but the search parameters and how we set them in the most recent version seem to be different from those versions explained there. I would appreciate it if you could help me figure out what could be the problem with my setting that may have caused this.

**Comment by jdramsey** [comment]
Problem is all of the parameter info is read in from the manual XML so that manual itself need to be copied to the right place. The above procedure does that

**Comment by jdramsey** [comment]
Also we just released a new version, 7.1.0, I hope you're using it

**Comment by f-arab** [comment]
Thank you so much @jdramsey. It works fine now.

**Comment by f-arab** [comment]
And yes, I'm using the newest version. Thanks a lot.
