### ISSUE TITLE
Some issue doing graph copy/pasting on Windows

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1387]
Richard reported this on his machine. I grabbed a Windows 10 machine, installed IntelliJ and the Corretto 1.8 JDK did didn't have a problem, so now we need to figure out why Richard is having a problem.

Here's the issue. Make a session graph (or a graph in a Graph box). Select a subset of the graph, select copy, then paste, On Richard's machine nothing happens. On my mac and on the Windows machine I tested you get a copy of the nodes you selected.

**Comment by jdramsey** [comment]
Hmmm.. I jumped through the hoops of downloading Oracle JRE 1.8 and ran Tetrad 7.1.0 using the java -jar command, and copy/pasting for graphs and sessions is working.

**Comment by jdramsey** [comment]
Anyone else out there having trouble with copy/pasting for graphs? Are you using version 1.8 for the JRE/JDK or some other version?

**Comment by jdramsey** [comment]
OK, Mike C. tested it and has no issue.

**Comment by jdramsey** [comment]
Richard found the cause, closing.

**Comment by cg09** [comment]
I can't copy and paste a graph into the same graph box or into a new one.
Using the latest you sent me. I can save a graph out and reload it.
