### ISSUE TITLE
Come up with a better wording for the third stat in this picture.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1392]
![unnamed](https://user-images.githubusercontent.com/9853255/172058841-943bd7e4-f98a-4648-9327-99388e37afdf.png)

**Comment by cg09** [comment]
Replace the third line with the total number of true adjacencies.

**Comment by jdramsey** [comment]
Good idea. Sorry I'm not on these things today; I had another pressing
problem to solve, which was keeping Kevin Bui from being able to release a
new tetrad-cmd.

BTW even though I had nothing to do with it (or because?) I feel I should
definitely brag about Bryan's Python translation of GRaSP. A thing of real
beauty. As fast as Java and as accurate. Maybe even faster than Java; Java
could learn a thing or two from the way he managed to do it (given that
Python is inherently a slower language!).

**Comment by jdramsey** [comment]
This has been fixed; the Compare box has been considerably reworked in 7.1.3-1 and should be a lot clear. Try it out.
