### ISSUE TITLE
Is there something error with Fisher-Z test?

### ISSUE THREAD

**Issue by williamty** [cmu-phil/tetrad#1396]
When using 7.1.2 to calculate causal graph of 12 continuous variables, I got this undirected graph:
![image](https://user-images.githubusercontent.com/4222336/175806616-1d9ae368-318e-4675-a159-d8c08e0e09ae.png)
here's the settings:
![image](https://user-images.githubusercontent.com/4222336/175806651-21bf291f-e08a-4a2d-bab5-8021f1ffae1f.png)

When using 7.1.0 to calculate the same graph with the same settings, I got this graph (same data which I can't upload, but the data file is definitely the same):
![image](https://user-images.githubusercontent.com/4222336/175806698-a4d59b78-36c7-42b5-837b-05c402afaee2.png)

And I'm sure both of the above graphs are wrong, cause here's the pearson correlation between those variables:
![image](https://user-images.githubusercontent.com/4222336/175806738-9973a16a-886a-4bf2-9e00-1bbd0e01b1a3.png)

So, did I use the wrong algorithm or set some wrong parameters?

**Comment by jdramsey** [comment]
I'm wondering, if you use the GRaSP algorithm what do you get?

**Comment by jdramsey** [comment]
Oh, also, it occurs to me, are all the p-values defined? I'm wondering if there is a singularity exception somewhere? Do you have missing values maybe?

**Comment by jdramsey** [comment]
Hmm... the correlation matrix makes it look like the variables are almost perfectly correlated with just some very small off-diagonal correlations--yeah I'm wondering what GRaSP does with this. BTW, GRaSP is a new algorithm that's being published in UAI this year--does better with denser graphs than the other algorithms. Here's arXiv version (UAI is forthcoming):

https://arxiv.org/abs/2206.05421

**Comment by williamty** [comment]
Thank you! yes, there are missing data which denoted by stars.
here's the result after using GRaSP with Fisher-Z and Sem BIC score:
![image](https://user-images.githubusercontent.com/4222336/175814683-8158990d-9883-42bf-8d25-0635f0de0e6c.png)

What's the reason of this problem? Is it caused by missing data?

**Comment by cg09** [comment]
Recall that Fisher Z is undefined when r = 1.

**Comment by jdramsey** [comment]
Well, the variables are all highly correlated--it doesn't surprise me that GRaSP finds a dense graph. How were the data measured?

**Comment by cg09** [comment]
Joe, you wrote that the correlations are close to 1, so Fisher Z is
operating at the far tails of the distribution, subject to round off errors
in computation or in tables, whichever TETRAD uses.

**Comment by williamty** [comment]
I don't understand. According to my correlation matrix, the number is pearson correlation coefficient, the stars denotes significance(the more the better). So most pearson correlation coefficient in the matrix are under 0.3, many are under 0.1. In my opinion, they are not correlated at all. Am I wrong?

**Comment by jdramsey** [comment]
Could you send me this data by email?

**Comment by williamty** [comment]
the correlation data? no problem. wait a second.

**Comment by williamty** [comment]
> Thanks. What is the sample size?

more than 20000, about ... 22000

**Comment by jdramsey** [comment]
Let me set it to that...

**Comment by jdramsey** [comment]
OK I'm sending you back a covariance matrix formatted for Tetrad...I'm wondering it this helps?

**Comment by jdramsey** [comment]
For instance is age exogenous? This a fairly dense graph--are you not expecting that?

**Comment by jdramsey** [comment]
Also, dense graph searches are difficult--as you can tell from the paper I sent, GRaSP is probably the only (now-)published algorithm using independence testing or BIC scores that can handle them at all. The graph I sent has a density of 0.53, which is pretty dense. Orientations can be a bit difficult to assess at that density. We're working on the problem.

**Comment by jdramsey** [comment]
Yeah that's what I thought--if I delete the search box and re-do the search with GRaSP I get different orientations. I'm not sure this is a solvable problem, and I'm not sure it's wrong. With very dense graphs especially there may be multiple graphs that are consistent with the available information.

**Comment by jdramsey** [comment]
Let me think for a little bit about this. Unfortunately I have a couple of meetings today so I may not be able to get to it right away.

**Comment by williamty** [comment]
Thank you! Appologising for my always disturbing.  I will learn and think about your words. Thank you again!

**Comment by williamty** [comment]
But if I mixed them with some discrete variables, then there will be no causal relations between them. interesting

**Comment by jdramsey** [comment]
Let's talk more about this offline...I have more ideas but I have a meeting now...

**Comment by williamty** [comment]
> Let's talk more about this offline...I have more ideas but I have a meeting now...

OK, I'll wait.I also have many meetings in office. THANK YOU!
