### ISSUE TITLE
Is there an implementation of CAM or ANM in Tetrad? what is the principle of adding algorithms in Tetrad Search?

### ISSUE THREAD

**Issue by williamty** [cmu-phil/tetrad#1397]

**Comment by jdramsey** [comment]
What did you have in mind? We don't have CAM. We do have an ANM search if you want to try it, what what ANM method did you have in mind?

I don't think there's a principle, except that I end up having to code most of the algorithms myself and don't have an enormous amount of extra time for it. (I am being paid to do other work, believe it or not! :))

**Comment by jdramsey** [comment]
Did you want to try coding up some algorithms? :)

**Comment by jdramsey** [comment]
By the way, just a belated comment on this @williamty I am trying my best to simplify Tetrad, so hopefully at some point in the near future I can afford to have a principle for adding algorithms. :) Tetrad has gotten to be a very large project, so simplifying it is very helpful.

My goal of late has been to try to make algorithms that are as _accurate_ as possible for doing what they do while being reasonably _scalable_. Some of these algorithms are starting to come out, as they become clearer.

**Comment by cg09** [comment]
What are CAM and ANM?

Clark

**Comment by jdramsey** [comment]
Well, ANM is additive noise model.

**Comment by cg09** [comment]
???  We generate simulated additive noise models all the time, and most of
the search procedures we use assume additive noise.  What is he talking
about?

**Comment by jdramsey** [comment]
I already said we had anm... but I think what people mean by anm is general anm models, like y = f(x) + e, where f is an arbitrary function. We have one independence test for specifically that case, but I've never been convinced of its accuracy. I'd like to find something better.
