### ISSUE TITLE
Causal cmd

### ISSUE THREAD

**Issue by Mahdi34118** [cmu-phil/tetrad#1398]
I have made some changes to algorithms in the .java files in (https://github.com/cmu-phil/tetrad). then I need to Run them using Causal cmd. I read your instructions in (https://github.com/cmu-phil/tetrad/issues/1154) and tried to implement them based on their latest versions. but unfortunately, due to some errors( "some test failures") that happen when I run  'mvn install'  for 'tetrad-lib', I can not run my changes on causal cmd. it would be great if you can help me with that.

thank you in advance,

Mehdi

**Comment by jdramsey** [comment]
I'm not getting test failures in the current development branch of Tetrad...

**Comment by jdramsey** [comment]
@Mahdi34118 If this is still an issue for you, please re-open and comment. In the latest version 1.5.0, we've carefully checked to make sure all tests pass on Mac and Linux. We'll be coming out with new versions of causal-cmd and Tetrad soon, so check again in the coming weeks.

Closing for now.
