### ISSUE TITLE
Enhancement: Include an Instance-Specific GFCI (IGFci) Algorithm in the Main Tetrad Release

### ISSUE THREAD

**Issue by mruderman** [cmu-phil/tetrad#1403]
Please consider incorporating the implementation of IGFci by @fattaneh into an official Tetrad release.
[https://github.com/fattaneh/tetrad-IGFci](https://github.com/fattaneh/tetrad-IGFci)
Thank you for your time.

**Comment by jdramsey** [comment]
@mruderman Sorry, just got done releasing 7.1.3-1 and am now going back through unresolved issues,. You know, let me talk with Fattaneh about this to see if there's updated code for it. The logistical problem of course is that a separate dataset as input I think (if I recall correctly) so may not be compatible with the current Tetrad GUI, but maybe there's a clever way to deal with that that I'm not thinking about at the moment.

**Comment by jdramsey** [comment]
This is in the wist list items; trying to clear out the the issues list for the next release.

**Comment by mruderman** [comment]
Thank you @jdramsey for working this into the next release. In the interim, if you are aware of documentation or a vignette to help an end user run IS-GFCI (using Fattaneh's existing tetrad-IGFci) I would be grateful.

**Comment by jdramsey** [comment]
I actually have no idea. Perhaps Greg Cooper would be able to help point you to an informative person?

Putting Fatteneh's algorithm into Tetrad is on the wish list, but I'm not sure when I'll be able to get to it. The wish list has 32 items on it currently. :(

One thing at a time; first we need to get the new release out.

**Comment by mruderman** [comment]
100%, thank you for even including it on the wishlist. I'll reach out to
Greg, thanks for the tip! -Mike
