### ISSUE TITLE
Discrepancies between final result and edge-probabilities in bootsrapping. Which is true?

### ISSUE THREAD

**Issue by yasu-sh** [cmu-phil/tetrad#1409]
Hi developers,

I have concerned if the result is correct or not in bootstrapping. 
When you use the small-size benchmark dataset, there are 3 discrepancies in the edge list. 

Could you check the probabilities calculation or some data output process?
I guess the node order is determined by alphabetical order in probability list ex. [D --> E] , [E o-> L].

compared with verbose
![image](https://user-images.githubusercontent.com/89838961/206110892-7ba8d8b7-0aab-4ec1-b3b5-7822fe785a46.png)

At first, I thought it came from causal-cmd, but I concluded that this issue comes from the tetrad-lib.
## https://github.com/bd2kccd/causal-cmd/issues/79
--- 
Graph Edges:
1. B o-> D [B o-> D]:1.0000;
2. B o-o S [B o-o S]:1.0000;
3. **E --> D [D --> E]:1.0000;**
4. E --> X [E --> X]:1.0000;
5. **L o-> E [E o-> L]:1.0000;**
6. L o-o S [L o-o S]:1.0000;
7. **T o-> E [E o-> T]:1.0000;**
``
I compared the same dataset and setting at TETRAD-GUI ver. 7.1.2-2
![image](https://user-images.githubusercontent.com/89838961/206109298-550271c3-8e67-4091-a757-1dbde4535f7c.png)

data: asia.csv (created from bnlearn, data(asia))
[asia.csv](https://github.com/bd2kccd/causal-cmd/files/10172677/asia.csv)

> java  -version
java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

- verbose is here:
[tetrad-gui-asia-log.txt](https://github.com/cmu-phil/tetrad/files/10173499/tetrad-gui-asia-log.txt)

- organized json data with R 
```
> ls.edgelist.json <- ls.graph.json$edgesSet
> df.edges <- data.frame(
   node1 = sapply(ls.edgelist.json, function(x)
     x$node1$name),
   node2 = sapply(ls.edgelist.json, function(x)
     x$node2$name) ,
   edge1 = sapply(ls.edgelist.json, function(x)
     x$endpoint1$ordinal),
   edge2 = sapply(ls.edgelist.json, function(x)
     x$endpoint2$ordinal),
   prob1 = sapply(ls.edgelist.json, function(x)
     x$edgeTypeProbabilities[[1]]$edgeType)
 )
> df.edges
  node1 node2 edge1 edge2 prob1
1     E     X     0     1    ta
2     T     E     2     1    ca
3     L     E     2     1    ca
4     B     S     2     2    cc
5     B     D     2     1    ca
6     L     S     2     2    cc
7     E     D     0     1    ta

```

**Comment by jdramsey** [comment]
@yasu-sh Found the bug. You're right, someone had tried to alphabetize the node order, unhelpfully. OK, I'm going to start putting together a new version to publish; there have been numerous fixes; I'll have to go through and try to list them all. I'll try to remember to come back and tell you when I've done that.

**Comment by jdramsey** [comment]
@yasu-sh By the way, the bug here was that the edge in the square brackets had its nodes put into alphabetical order, so the edge not in square brackets was right. (You asked.)

**Comment by jdramsey** [comment]
@yasu-sh Also, this bug only affect the text output when bootstrap graphs were saved out as text, not the Tetrad interface

**Comment by yasu-sh** [comment]
@jdramsey Thank you for quick action and confirmation! I also think this bug affects to only for the text log. GUI is okay.
I can use bootstrapping in trust. (In past I made code for bootsrapping by myself in R since I noticed this happened at r-causal.)

**Comment by jdramsey** [comment]
@yasu-sh Yeah we haven't been keeping R-causal up to date since the person maintaining that left us. I may try to revisit that myself at some point if I can figure out the code.

**Comment by yasu-sh** [comment]
@jdramsey No problem. I decided to use causal-cmd already. 
it is reasonable that r-causal is not maintained now and it's not neccesary for me now. 

R-causal package includes causal-cmd ver. 1.2.1 DEV, while current 1.4.1. 
r-causal is early-release and debugger-access is limited on java side and hard(R - JNI(C) - Java). 
Causal-cmd would be better for developers since the debugger in IDE(Java code) is available(time-consuming debug is unhappy for everybody). 

Therefore I made a comments as above.

**Comment by jdramsey** [comment]
I see. Thanks for letting me know!

Joe

**Comment by jdramsey** [comment]
@yasu-sh This has been fixed in 7.1.3-1, released yesterday. The causal command version 1.5.0 corresponding to this will be available soon.

**Comment by yasu-sh** [comment]
@jdramsey This is the surely expected function I wanted. I have checked the GUI and it works. 
Now I am checking the causal-cmd 1.5.0 also.  I greatly appreciate everything you've done.

**Comment by jdramsey** [comment]
I'm so glad this is working for you now! Yeah, between Kevin @kvb2univpitt and myself, we put a fair amount of effort into. bootstrapping and fixed multiple issues. Let me know about causal-cmd--Kevin paid a lot of attention to that I know.

**Comment by jdramsey** [comment]
By the way @yasu-sh in the back of my mind I do want to get back to looking at r-causal; a lot of people have asked about that. I'm just so overwhelmed with projects; having a small development team has its drawbacks. But I know a number of people would like to use it.
