### ISSUE TITLE
Add Edge Probabilities to Bootstrapping

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1412]
Currently, bootstrapping gives edge-type probabilities.  Add a function to bootstrap to give edge probabilities.

**Comment by kvb2univpitt** [comment]
Done.

![Screenshot from 2023-01-06 02-10-06](https://user-images.githubusercontent.com/10729309/210950394-49b841e8-d9d7-465d-8897-f66fd168bb7d.png)

**Comment by jdramsey** [comment]
Beautiful! let me grab the branch and try it...

**Comment by kvb2univpitt** [comment]
Done.

**Comment by jdramsey** [comment]
Yay!
