### ISSUE TITLE
Allow Seed to Be Set For Creating Bootstrap Dataset

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1413]
Create another method getBootstrapSample with the parameter ***seed*** to allow user to set seed for randomly select data for bootstrap dataset.

**Comment by cg09** [comment]
Kevin,

Thank you for working on this.  Happy New Year.

Clark

**Comment by kvb2univpitt** [comment]
@cg09 You're welcome, Clark.  Happy New Year!!!
