### ISSUE TITLE
Unable to Import Bootstrap Search Result Graph From File

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1425]
A result graph can be exported after running search using bootstrapping, as shown here:

![Screenshot from 2023-01-10 10-05-37](https://user-images.githubusercontent.com/10729309/211587282-f5506338-b0b6-4029-bb75-365c7c3567d5.png)

However, the exported graph could not be imported into a Graph Node.

> Note that a result graph obtained from running search **without** bootstrapping can be exported and imported without any problem.

**Comment by kvb2univpitt** [comment]
@MikeKonrad Yes, you are correct!  It seems like the parser doesn't know how to parse additional information from bootstrapping.

**Comment by jdramsey** [comment]
This has been fixed, all! :-D @kvb2univpitt I hope you don't mind my closing it. See release 7.1.3-1,
