### ISSUE TITLE
Data loader in GUI on a Mac doesn't show any files.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1453]
See https://github.com/cmu-phil/tetrad/wiki/Dealing-with-Tetrad-on-a-Mac--security-issues .

**Comment by cg09** [comment]
Maybe instruct to use an old java?

**Comment by jdramsey** [comment]
That's not the issue I don't think--it's Mac's new security model, not a
Java problem. What I need to do is figure out how to get Java to come up
with those dialogs asking whether you give permission to access this or
that directory. There must be. way; IntelliJ does it.

**Comment by jdramsey** [comment]
I have created a Wiki entry on our Github site explaining how to deal with Mac security issues, here:

https://github.com/cmu-phil/tetrad/wiki/Dealing-with-Tetrad-on-a-Mac--security-issues

If more security issues come up, I will add to this explanation.

**Comment by jdramsey** [comment]
Closing this--hopefully if you have this issue you'll see it in the closed issues or in the list of Wiki pages. -JR
