### ISSUE TITLE
Estimator box

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1458]
It would be nice to have options to:
- Save Graph Image in an Estimator box (so images of graphs with coefficients can be generated);
- Save the IM to a text file from an Estimator box.

**Comment by cg09** [comment]
Yes, it would. I have sometimes wished...

**Comment by jdramsey** [comment]
@bja43 Your wish is my comment, assigning myself to this.

**Comment by jdramsey** [comment]
Fixed https://github.com/cmu-phil/tetrad/pull/1459
