### ISSUE TITLE
Switch from wall time to CPU time throughout the code.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1478]
This change was made in algcomparison, but it needs to be done everywhere for consistency.

**Comment by jdramsey** [comment]
Actually a better approach would be to create (or find) a Timer class. The idea would be this:

```
Timer timer = new Timer();
timer.start();
...
timer.stop();
double cpuTme = timer.getCpuTime();
double userTime = timer.getUsertime()'
double wallTime = timer.getWallTime();
```

where the times are given in seconds with millisecond precision, ready to be printed out. What do you think @kvb2univpitt ?

**Comment by jdramsey** [comment]
This change has been requested for _years_ now, should be done as soon as possible.

**Comment by jdramsey** [comment]
PR: https://github.com/cmu-phil/tetrad/pull/1490

**Comment by kvb2univpitt** [comment]
@jdramsey That sounds good.  Sorry for the late reply.  I must have missed the notification.

**Comment by jdramsey** [comment]
Fixed, merged.
