### ISSUE TITLE
Impossible to drag variables into tiers in Knowledge window

### ISSUE THREAD

**Issue by davidmosca** [cmu-phil/tetrad#1482]
OS: both on Mac and PC
Version: tetrad-gui-7.1.3-1-launch.jar
When I try to drag variables from the "Not in tier" box to one of the Tier boxes, nothing happens (the variable changes colour and becomes orange, but does not move).

**Comment by jdramsey** [comment]
I wil try this in a bit.

**Comment by jdramsey** [comment]
@davidmosca Hmm.... I'm not having this difficulty. @cg09 checked it too and didn't.  Can you give me more inforamation, like what type of computer you're using, what OS, what version of Java, that sort of thing?

**Comment by jdramsey** [comment]
Hmm... you said both Mac and PC... sorry... but what OS versions, and what Java versions? Is there anything special about the model you were trying to make knowledge for, like many variables or such?

**Comment by davidmosca** [comment]
Sure:
Mac mini (2018)
Mac OS 12.5.1
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

I'm using the Boston dataset: https://github.com/selva86/datasets/blob/master/BostonHousing.csv

**Comment by jdramsey** [comment]
Oh, I'm wondering if the quote marks are throwing it off...could you reload the data, specifying " as the quotation mark character? Or strip the quotation marks from the data header? Like this?

https://raw.githubusercontent.com/cmu-phil/example-causal-datasets/main/real/boston-housing/data/boston-housing.continuous.txt

**Comment by davidmosca** [comment]
Yes, works now, thanks!

**Comment by jdramsey** [comment]
Nice! You know what I'll do--I'll add a check in the knowledge editor to make sure variable names are of the right sort and warn the user if not. That should be easy enough to do and will avoid this sort of problem for others...

I'll close out this issue; if you have any other problems, let me know.. :)

**Comment by cg09** [comment]
I think the Boston Housing Data, which I have looked at recently, has
unobserved common causes--latent variables. To search for such models in
TETRAD (e.g., using Build Pure Clusters) you don't need or want the
variables in tiers.

**Comment by davidmosca** [comment]
Thanks for the tip. But the BPC produces undirected edges and I get this error:
![image](https://user-images.githubusercontent.com/20925702/216790818-1fb19abd-e592-4c3a-a0b1-1a2d7676bb76.png)
How can I fix it?

**Comment by cg09** [comment]
Dunno. I have never got that kind of error message. Send me your email
and I will send you a little draft paper that treats the Boston Housing
Market
data.

Clark Glymour   ***@***.***

**Comment by jdramsey** [comment]
I think you're getting the undirected edge because there is a CPDAG over the latents, and a CPDAG algorithm is unable to tell you the orientation of that edge. (Let me know if you need a reference for that.) From information about conditional independence alone, you can't tell the direction of that edge. Both models, _L1->_L2 and _L1<-_L2 are possible.

**Comment by davidmosca** [comment]
@jdramsey I can see the reason for the problem but I cannot find an algorithm suitable for an SEM parametric model, i.e. an algorithm that produces exclusively directed edges. Of course I can build a graph from scratch, but I also wanted to see how well (or badly) a model produced by search could explain the data.

**Comment by davidmosca** [comment]
@cg09 could you please send the paper to david441 at mail.com. Thanks.
