### ISSUE TITLE
Algorithm Comparison Tool not working correctly for sims with different graphs

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1491]
If you set up a simulation with the parameter for different graph equal to true (and more than one run), then the stats returned are (artificially) garbage.

**Comment by jdramsey** [comment]
I notice that in my lvswap simulation, which is comparing PAG outputs to true PAGs, if I set different graphs to true, the average for -->-Prec drops from like 0.85 to 0.2 for most of the algorithms.

**Comment by jdramsey** [comment]
Fixed, PR https://github.com/cmu-phil/tetrad/pull/1492
