### ISSUE TITLE
How to specify an initial graph for FASK in causal-cmd?

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1498]
The question is simply how to get FASK to recognize an "external graph" in causal-cmd... this is just a matter of specifying the initial graph (for any search that takes one)...

This is independent of the question of getting FGES to be followed by a non-Gaussian orientation, sorry.

@rubencmu @kvb2univpitt

**Comment by kvb2univpitt** [comment]
I can add that feature in causal-cmd by creating a parameter **_--external-graph_** to specify the initial graph.  We do need another annotation in Tetrad to indicate that an algorithm can take external graph.

**Comment by jdramsey** [comment]
Awesome! I made the issue in causal-cmd as well:

https://github.com/bd2kccd/causal-cmd/issues/85

**Comment by jdramsey** [comment]
Let me know if I can help make the annotation--I've never done that before but am willing to learn.

**Comment by jdramsey** [comment]
This is solved in causal-command 1.6.0
