### ISSUE TITLE
Mark PyCausal and RCausal as deprecated

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1501]
PyCausal (and RCausal) have not seen active development in over 5 year. I think it should mark as deprecated and users should be pointed to CausalCmd (which can be called from Python).

**Comment by jdramsey** [comment]
Agreed to update the algcompy file showing how to run causal-cmd in Python. I'll make a Wiki article for how to do this.

**Comment by jdramsey** [comment]
Ha, they've already been removed from the CCD page! Good!

**Comment by jdramsey** [comment]
These have also now been archived, so it should be clear that they shouldn't be used. Closing.
