### ISSUE TITLE
Calculation problem of self.tn in the class AdjacencyConfusion

### ISSUE THREAD

**Issue by huiouyang16** [cmu-phil/tetrad#1547]
In the class [AdjacencyConfusion](https://github.com/cmu-phil/tetrad/blob/f892abf67b06322d193239f450d3badba8aede88/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/AdjacencyConfusion.java), is there a problem with this.tn calculation?

**Line 54:** `this.tn = allEdges - this.fn;`

According to my understanding, in the confusion matrix, tn (true negative) is equal to "total (all undirected edges) - tp (true positive) - fp (false positive) - fn (false negative)"

Based on this, is the `allEdges - this.fn - this.fp - this.fn;` correct, or is there something else wrong with my understanding?

**Comment by jdramsey** [comment]
OK, here is the diagram:

https://developers.google.com/machine-learning/crash-course/classification/true-false-positive-negative#:~:text=A%20true%20positive%20is%20an,incorrectly%20predicts%20the%20positive%20class.

Oh, you know I think you're right! You are right! I'll change that for the next version.

Thanks!

**Comment by jdramsey** [comment]
Added this to the list of forthcoming fixes:

https://github.com/cmu-phil/tetrad/wiki/Forthcoming-fixes

**Comment by jdramsey** [comment]
BTW we'll publish that in maybe another week or so; we have some more things to include before we do it...

**Comment by jdramsey** [comment]
Could you close this issue if you think it's solved? Thanks -Joe
