### ISSUE TITLE
Bootstrap: Percentage of Resampling Should Be 100.

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1552]
Currently, the default percentage of resampling is 90, which means it only uses 90% of the dataset for resampling.  It should use 100% by default.

**Comment by cg09** [comment]
???? When one resamples, one takes a subset of the original data. 100%
would be just using the original data again, which would be pointless.

**Comment by jdramsey** [comment]
@cg09 Actually, it's a bootstrap sample, not a subsample, so records are selected randomly and with replacement until the full sample size is reached. So there may be duplicates.

**Comment by cg09** [comment]
Thanks for the correction. Suppose I want to subsample, as in IDA, not
bootstrap?

**Comment by jdramsey** [comment]
It is a bootstrapping tool, so it uses bootstrapping theory. We have subsampling methods in Tetrad; I'll have to see if they're in the interface somewhere. If not, I suppose I could put them there.

For instance, we have a bootstrap sampling tool. I could add a switch (maybe it's there already?) to do a subsample instead. I'll check.

**Comment by jdramsey** [comment]
@cg09 Hold on there's much better answer to your question! It's an _option_ in the bootstrapping tool already; you can opt to create samples without replacement. In that case using 100% sample is not the most useful thing to do. :-D

![image](https://user-images.githubusercontent.com/9853255/225455397-2bf36470-57ae-4ed7-9e32-0f25373b4281.png)

**Comment by kvb2univpitt** [comment]
@jdramsey That is true.  Using sampling **_without replacement_** on a full dataset (100%) will not be useful.  However, sampling **_with_** replacement on 90% is not that great either.  So, should we just leave it the way it is?

**Comment by jdramsey** [comment]
https://github.com/cmu-phil/tetrad/pull/1553

**Comment by jdramsey** [comment]
@kvb2univpitt Actually up date and try again.

**Comment by kvb2univpitt** [comment]
@jdramsey Ok.  I saw the new file.  Thanks.

**Comment by jdramsey** [comment]
This was merged, closing.
