### ISSUE TITLE
"Matrix is singular" notification appears when applying SEM estimator on panel data

### ISSUE THREAD

**Issue by barrynuqoba** [cmu-phil/tetrad#1571]
Hi @jdramsey, I apply causal discovery using GRaSP on panel data, and it works well. Afterward, I input the causal graph into the SEM estimator, but it could not work. "matrix is singular" notification appeared.

Previously, I tried the same on cross-sectional data, and all worked well.

What should I do?

I appreciate any help you can provide.

**Comment by jdramsey** [comment]
@barrynuqoba Could you give me more details on how to reproduce this?

**Comment by barrynuqoba** [comment]
Hi @jdramsey , thank you very much for your kind reply. Below are some details of my experiment:

1. I apply GRaSP (with 100 times bootstrapping) on three months of data, and each month consists of 20 variables (i.e., nine demographic variables, one outcome variable, and ten regular variables).

2. For the GRaSP, I use a knowledge box with the following rules, (i) forbid all causality to any variables in the previous month, (ii) forbid demographic variable -> another demographic variable (in the same month and future), (iii) forbid regular variable -> demographic variable (in the same month and future), (iv) forbid outcome variable -> demographic variable (in the same month and future), and (v) forbid outcome variable -> regular variable (in the same month).

3. After applying the GRaSP, I run the SEM by including edges from the GRaSP output having an edge appearance of more than 50%.

4. The "Matrix is Singular" notification appears when I run the SEM. Previously, I used cross-sectional data, and all ran smoothly.

I hope it clarifies.

**Comment by jdramsey** [comment]
Oh! This is a little complicated; let me see if I can do it.

**Comment by barrynuqoba** [comment]
Hi @jdramsey, I will send the exact nodes and edges I used in the SEM. Hopefully, it can help to reproduce the results.

**Comment by jdramsey** [comment]
One problem is that the bootstrap contains several non-edges (edges for which bootstrap information is available but which are not included in the majority graph. If you save the graph to a file, you can see these; they are marked "..." and you can delete them all, re-load the graph, and make an SEM PM from it and the estimate.

I had yet to think of this issue. The SEM PM should ignore the non-edges. Let me think about that.

**Comment by jdramsey** [comment]
But please send me the example so I can try it. Can you make it in the new version, 7.3.4? If not, please tell me what version you're using, and I'll save the data and knowledge and load them back in.

**Comment by jdramsey** [comment]
Let me make an issue for adding a gadget to strip the non-edges from the graph. Not hard.

**Comment by jdramsey** [comment]
(Not where whether this is a bug actually.)

**Comment by cg09** [comment]
Nor am I sure it is a bug either. What is the data format and how are the
variables identified?

**Comment by barrynuqoba** [comment]
Hi @jdramsey , I am sorry for the late reply. I just arrived at my school. I use TETRAD 7.3.0. Moreover, the data administrator told me I could not export the data from the server. I will try to request again whether I can export (i) the textfile containing my knowledge box, (ii) the textfile containing the GRaSP bootstrapping result, and (iii) the textfile containing edges selected for the SEM PM (I included only edges have more than 50% appearances, and ignored the non-edges). Hopefully, it can still help to reproduce the results.

**Comment by barrynuqoba** [comment]
The data format is .csv. All variables are discrete. Social scientists identify the variables.

**Comment by jdramsey** [comment]
You know, I am getting more and more used to people not being able to share their data, though it makes debugging difficult. Se la vie, I say! We must be creative!

**Comment by cg09** [comment]
NO!  If people want you to solve their problems, they need to share a data
sample. They can rename variables. Otherwise tell 'em tough luck, I say.

**Comment by barrynuqoba** [comment]
I apologize, I have requested to export the data, but the administrator did not approve it. They said I could only export the results from the server.

**Comment by barrynuqoba** [comment]
Hi @jdramsey , attached are the following:

1. Textfile loaded to my knowledge box (Knowledge_Box.txt)
2. Textfile containing copy from the table in the GRaSP result (Grasp_Output.txt)
3. Textfile loaded to the SEM graph (SEM_Edges.txt)

I am sorry, I have no user privilege to export the data.

Have a great weekend, Joe!
Thanks in advance.

[Grasp_Output.txt](https://github.com/cmu-phil/tetrad/files/11232105/Grasp_Output.txt)
[Knowledge_Box.txt](https://github.com/cmu-phil/tetrad/files/11232106/Knowledge_Box.txt)
[SEM_Edges.txt](https://github.com/cmu-phil/tetrad/files/11232107/SEM_Edges.txt)

**Comment by jdramsey** [comment]
@barrynuqoba Thanks; I'll see what I can do. I mean Clark's right, it's usually very difficult to debug an issue like a singularity exception without data (which could itself be causing the singularity exception) but let me see. If it's a bonafide singularity exception, it's because there's some variable in the data that's a linear combination of other variables in the data, without noise. An approach that might work to find the culprit(s) is to remove variables from the analysis in some kind of systematic way to see if you can find a "minimal" variable set without the singularity exception.

Let me look at what you sent though.

**Comment by jdramsey** [comment]
Boy, it's so hard to tell from what you sent what the culprit might be. If you know what the variables mean, would it make sense to say that any are calculated in terms of others and not strictly measured? You don't have to tell me, but try removing those variables from the SEM estimation analysis and see if the singularity resolves itself.

**Comment by barrynuqoba** [comment]
Hi @jdramsey, thank you very much for your kind reply. Each variable in the dataset comes from different survey questions, and none come from aggregation from others. I hope it clarifies.

**Comment by barrynuqoba** [comment]
For your information, I conducted the GRaSP + SEM experiments in eight different datasets. When I applied the SEM Estimator, all generated the same notification (Graph is singular). Moreover, previously I conducted the GRaSP + SEM experiments in eight different datasets (the same variables as in the panel data), and all can run smoothly.

**Comment by barrynuqoba** [comment]
Thank you very much for your kind suggestions, @MikeKonrad and @jdramsey.

**Comment by jdramsey** [comment]
@barrynuqoba When did you do the analysis that succeeded? Maybe I can do a diff on the code...

**Comment by barrynuqoba** [comment]
By the way, I edited my previous comments, as I missed giving information about panel data and cross-sectional data experiments. The successful experiments are on cross-sectional data.

**Comment by jdramsey** [comment]
You have three time points. Do you still get the singularity if you give it two time points?

**Comment by barrynuqoba** [comment]
Two datasets in my panel data experiments consist of two time points. The SEM estimator showed the same "Graph is singular" notification.

**Comment by MikeKonrad** [comment]
Is this correct: with only 2 or 3 timepoints, assuming you have more variables than timepoints, you will automatically have a singular covariance matrix, right?

From: barrynuqoba ***@***.***>
Reply-To: cmu-phil/tetrad ***@***.***>
Date: Friday, April 14, 2023 at 9:21 AM
To: cmu-phil/tetrad ***@***.***>
Cc: Michael Konrad ***@***.***>, Mention ***@***.***>
Subject: Re: [cmu-phil/tetrad] "Matrix is singular" notification appears when applying SEM estimator on panel data (Issue #1571)


Two datasets in my panel data experiments consist of two time points. The SEM estimator showed the same "Graph is singular" notification.

**Comment by jdramsey** [comment]
Hold on, what's your sample size? I neglected to ask.

**Comment by jdramsey** [comment]
Let me look at the SEM estimator code.

**Comment by barrynuqoba** [comment]
@jdramsey The sample size is around 6000.

**Comment by barrynuqoba** [comment]
@MikeKonrad I am sorry, I do not understand it.

**Comment by jdramsey** [comment]
It looks like it's the default.

**Comment by barrynuqoba** [comment]
The notification directly appeared after I double-clicked the SEM Estimator box.

**Comment by jdramsey** [comment]
I should have asked, do you have a stack trace?

**Comment by barrynuqoba** [comment]
No, I do not have it.

**Comment by jdramsey** [comment]
I hate to give up on other suggestions, but there's not enough information yet about the data itself, and only you can access that. 

If I tell you why singularity exceptions happen, perhaps you'll see how to debug it. At some, the program tries to invert a matrix where some variable is a linear combination of other variables, and this causes the exception. This could happen because the sample size is too small, so it's guaranteed that you'll get that scenario, but your sample size is 10 times the number of variables.

Also, I'm not sure (because I can't see the stack trace) where the exception is being thrown in the code. In my toy example that I made according to your instructions, this doesn't happen, so that code _can in principle_ succeed.

The estimator itself may be causing the problem, or the statistics calculation may be causing it. 

Mike is right; you could remove the variables in chunks from the estimation (not the search) to see where the problem is. 

Perhaps checking first whether the cross-sectional analysis succeeds for all three time points separately might give a clue. Then the issue would simply be why combining all three time points causes the singularity. Perhaps some variable does not vary by time point or is a function of previous time points?

**Comment by MikeKonrad** [comment]
@barrynuqoba<https://github.com/barrynuqoba> Sorry, I wasn’t following too closely, but having experienced tracking down the causes of singular covariance matrices before, I thought that was perhaps what was happening. In what I did read, I might have gotten sample size and number of timepoints conflated, and so I’m not sure I was helping any. What I was trying to say is that there are some simple cases where you obtain singularity. Obviously, one is where one variable is a non-zero linear combination of a subset of the others. Or one is a multiple of another.

Here’s a Python script showing how the other problem I was mentioning can produce a singular covariance matrix:


>>> import torch

>>> x = torch.tensor([[-5,29], [-106,1], [-12,32]])

>>> x

tensor([[  -5,   29],

        [-106,    1],

        [ -12,   32]])

>>> xc = torch.cov(x)

>>> xc

tensor([[ 578.0000, 1819.0000,  748.0000],

        [1819.0000, 5724.5000, 2354.0000],

        [ 748.0000, 2354.0000,  968.0000]])

>>> torch.linalg.det(xc)

tensor(-0.)





In the above, I’m typing what follows “>>>” into a Python interpreter. I then set up a simple (somewhat arbitrary) example for x, making it a 3x2 matrix (tensor). Then I take the covariance to get a 3x3 matrix. And then I compute the determinant. Note the determinant is 0.

Mike

From: barrynuqoba ***@***.***>
Reply-To: cmu-phil/tetrad ***@***.***>
Date: Friday, April 14, 2023 at 9:37 AM
To: cmu-phil/tetrad ***@***.***>
Cc: Michael Konrad ***@***.***>, Mention ***@***.***>
Subject: Re: [cmu-phil/tetrad] "Matrix is singular" notification appears when applying SEM estimator on panel data (Issue #1571)


@MikeKonrad<https://github.com/MikeKonrad> I am sorry, I do not understand it.

**Comment by barrynuqoba** [comment]
Hi @jdramsey and @MikeKonrad, thank you very much for your kind helps and clarifications. I just realized that my demographic variables tend to have the same values between time points (e.g., age will remain the same between months). I will try your suggestions to remove those variables from the SEM estimation.

I think my issue has been solved now. Should I close this issue? :)

**Comment by jdramsey** [comment]
@barrynuqoba Well, if it's been solved, sure. I can wait.

**Comment by barrynuqoba** [comment]
Yes, it is solved. Including demographic variables in the SEM Estimator is the problem, as their values rarely change between months.

Thank you very much, @jdramsey and @MikeKonrad

**Comment by jdramsey** [comment]
That's great! :-)
