### ISSUE TITLE
Rename: Adjust Markov and Faithfulness checks in the Markov Checker to include more comparisons.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1576]
Request from Mike Konrad--not absolutely sure this can be done but should at least think about it and do it if it's feasible.

**Comment by cg09** [comment]
What is the request?

**Comment by jdramsey** [comment]
We have a Markov checker now that will check all X _||_ Y | Z where des(X,
Y | Z) in a given graph and print out violations.

The question is whether it's feasible to have a checker that checks X _||_
Y | Z for some relatively relevant X, Y, and Z and then prints out
violations where is it not the case that dsep(X, Y | Z) in the graph.

The issue I see is that the set of such independence facts may be quite
large, so maybe we'd want to subset it somehow.

**Comment by MikeKonrad** [comment]
Hi Clark, it’s actually Joe’s idea but I like it: the request is to add a Faithfulness check to the Markov checker tool that currently (only) checks for the Casual Markov Condition. Inputs are a graph, a dataset, and some kind of score method (independence test) ideally different from the one used to obtain the graph from the dataset.

**Comment by cg09** [comment]
I wonder about the number of tests that would be required.

**Comment by cg09** [comment]
And because the set is quite large, there will almost surely be some test
failures somewhere.

**Comment by kunwuz** [comment]
I will personally be more than excited if a faithfulness check could be adopted reliably without too much extra computation :)

**Comment by jdramsey** [comment]
OK let me think about this one for a bit, see if the sunshine relaxes my brain into a solution...

**Comment by jdramsey** [comment]
I do have some faithfulness checks. These are Markov checks, looking to see if a variable is independent of its non-descendants given its parents:

![image](https://github.com/cmu-phil/tetrad/assets/9853255/092adee8-d42d-4502-83b3-979457c810b3)

But these are faithfulness checks, looking to see whether a variables is _dependent_ on its _desdendants_ given its parents:

![image](https://github.com/cmu-phil/tetrad/assets/9853255/3300f180-d0ba-4cc0-b0ca-1fd542034fdb)

The Markov check is complete, but there are many more independencies to check for the faithfulness checks. Is there a good characterization that would give us interesting ones, other than the above?

**Comment by jdramsey** [comment]
By the way the DAG for the above is this:

![image](https://github.com/cmu-phil/tetrad/assets/9853255/c2921d1a-a2f2-447d-a276-4165aa355574)

**Comment by jdramsey** [comment]
OK, I am changing the output of the Markov checker as follows. For the "Should be independent" tab, I now output X _||_ Y | parents(X)) for dsep(X, Y | parents(X)). For the "Should be dependent" tab, I now output X ~_||_ Y | parents(X) for dconn(X, Y | parents(X)). That's doing all of the checks in the graph assuming the parents of each variable are correct, checking against the distribution.

I think that's good enough, but I'll think about it for a while longer.

So now I get this comparison. These are the "should be independent" guys (i.e., the Markov check):

![image](https://github.com/cmu-phil/tetrad/assets/9853255/0aac61e7-b2d9-4432-9a57-4d9a6a2394b2)

And these are the "should be dependent" guys (i.e., the faithfulness check):

![image](https://github.com/cmu-phil/tetrad/assets/9853255/238ce675-61de-4bcd-853c-c34e2cb35fab)

Here is the graph:

![image](https://github.com/cmu-phil/tetrad/assets/9853255/d850ec29-9069-44f2-b071-6ed461aeaf33)

Comments welcome.

**Comment by cg09** [comment]
Reminds me of our early tetrad search output.

**Comment by jdramsey** [comment]
Huh, interesting.

**Comment by jdramsey** [comment]
@cg09 So I asked Peter about this. He did not complain about the idea so much as the scalability of it. I take that's why the Markov check was reduced the way it was to X _||_ Y | parents(X) for Y not a descendant of X. He recommended a paper by someone and Lauritzen about checking faithfulness. As soon as he or I can figure out who that someone was and which paper it was I'll look at it and see if I can incorporate that instead.

**Comment by jdramsey** [comment]
@cg09 Another issue is that the d-separation check is still slower than I'd like. I want to look into that and see if I can't speed it up. It would help a lot of stuff., not just this.

**Comment by jdramsey** [comment]
@cg09 Another issue, which maybe I'll try to address today or tomorrow, for the Markov check is that the actual inputs to the Markov check are a graph, a dataset, and an independence test. Unfortunately, it's currently a graph and a search box containing an independence test with a dataset as a parent. So currently, it's a bit confusing and requires n unintuitive explanation. What's needed to fix this is a gadget inside the Markov check to let you choose an independence test, like the independence test chooser in the Search box. It does not seem out of bounds of reason to fix this, just a bit of time is all to transfer the necessary bits over to the Markov checker, so I'll work on that.

**Comment by jdramsey** [comment]
Sped up d-separation in Tetrad some. Now the (current) M-F interface is pretty fast.

Peter recommends this paper for trying to improve it from here: 

Journal of Machine Learning Research 23 (2022) 1-34  Conditions and Assumptions for Constraint-based Causal Structure Learning Kayvan Sadeghi [k.sadeghi@ucl.ac.uk](mailto:k.sadeghi@ucl.ac.uk) Department of Statistical Science University College London London, United Kingdom Terry Soo [math@terrysoo.com](mailto:math@terrysoo.com) Department of Statistical Science University College London London, United Kingdom

**Comment by jdramsey** [comment]
This is all much better and is now in the development branch (see). Clark suggested several relabeling of things for clarity, which have all been done. Also, he requested a Help button to pop up text explaining how to use the tool, which has been added.

Kevin asked that the core of the Markov checker be made available outside of the GUI so it can be run from the command line, so I will work on that before closing this issue.

**Comment by jdramsey** [comment]
@kvb2univpitt Implemented Kevin's request--now there's a MarkovCheck class int he search package that be accessed from Python, or will be as soon as a new jar is put into the py-tetrad repository.
