### ISSUE TITLE
The problem of loading data

### ISSUE THREAD

**Issue by magical-hhc** [cmu-phil/tetrad#1578]
I manually imported a set of time variable DATA and transformed it into correlation coefficient matrix by using data box. What method or principle was used in this process?
There is an additional problem: in tetrad7.3.0, using the Load DATA option of the data box, the data file loader window does not pop up after selecting the txt data text, but there is no reflection. I don't know why. And sometimes this problem exists, and sometimes it doesn't exist.
I hope you can help me solve this problem, QAQ ......

**Comment by jdramsey** [comment]
You mean for the first question, how does one make a correlation matrix?

**Comment by jdramsey** [comment]
For the second question, what type of machine do you have again?

**Comment by magical-hhc** [comment]
First question: Let me give you an example. By importing time series DATA into SVAR model, we can get the matrix of disturbance correlation coefficient between variables. In tetrad7.3, it seems that time series data can be transformed into correlation coefficient matrix through the transformation between data boxes. I am curious about the basis of the transformation.

**Comment by magical-hhc** [comment]
I am using a Nitro AN515-57 laptop.

**Comment by magical-hhc** [comment]
The brand is Acer.

**Comment by cg09** [comment]
Interesting question. Never thought of doing that. Wonder what the code
does.

**Comment by jdramsey** [comment]
I see the issue. So the data are represented in _lag form_, so you have X, Y, Z, then X:1, Y:1, Z:1, which are the same data one time step back. So if the time series has N = 1000, then the lagged data in this case will have N = 999, so that the lags can be represented.

Then the covariance matrix shown is the covariance matrix over this lagged data.

**Comment by cg09** [comment]
Eh??

**Comment by jdramsey** [comment]
@cg09 Please elaborate.

**Comment by magical-hhc** [comment]
The imported data of tetrad7.3.0 is not reflected. Is there a solution to this problem?QAQ

**Comment by jdramsey** [comment]
Oh wait, I think I misunderstood you. If you import a time series, you should not calculate a correlation matrix, even if it lets you. You should first create lagged data from it, and then you can calculate a correlation matrix from that. Let me know if you need help with that. Instead of creating a correlation matrix from the time series data, select "create time lag data" and choose several lags to develop. Then you can run an algorithm on the lagged data, not the raw time series data.

As far as data loading is concerned, do you have a Mac? There were problems with a Mac with data loading. Also, it's necessary to use a version of Java greater than 1.8 (version 8). I wrote some Wiki pages for these problems; let me see if I can find them.

(1) Here's the one about Macs. This is not the right advice. When my machine updated to the latest OS, I had new problems; I figured out the issue and will put it into this file.

https://github.com/cmu-phil/tetrad/wiki/Dealing-with-Tetrad-on-a-Mac:--Security-Issues

(2) Here's the one for setting up Java:

https://github.com/cmu-phil/tetrad/wiki/Setting-up-Java-for-Tetrad

Let me know if these help or if you have some other problem.

**Comment by magical-hhc** [comment]
Thank you for your answer. Can you attach a flow chart about the correct steps of transforming time series data into correlation coefficient matrix?
As for loading data, my Java version is the latest version in official website, which seems to be 1.8.0. I'm not using a MAC, but an ordinary laptop with windows10 system. tetrad7.3.0 has the problem of not loading data, but I won't encounter this problem when I use tetrad7.1.0.
If I really can't find the reason and solution, I think I can only use this version of tetrad7.1.0,: (

**Comment by jdramsey** [comment]
You will need to install a version later than 1.8 to get data loading to work in the interface. Please follow the instructions in the wiki I sent. The instructions were tested on a Windows machine; that doesn't mean you won't have problems, but at least a couple of Windows users were able to follow them.

I'm afraid I don't have time to make a flowchart at the moment, but perhaps I can describe better what you should do, after you've managed to install a recent version of Java and loaded your data in the interface.

**Comment by magical-hhc** [comment]
@jdramsey 
![image](https://user-images.githubusercontent.com/128958272/230559892-05d35c64-c86a-4e81-9e66-61a2637619ce.png)
I installed java20 according to your instructions, and the problem of importing data seems to have been solved.:) 
Now I have imported a set of time series data in the data option box, and now I need to get its correlation coefficient matrix. How can I operate correctly? (Before, I directly used the conversion between data boxes to get it.)

**Comment by jdramsey** [comment]
Oh, nice! Congratulations, it worked! OK, now, leaving aside the question of making a correlation matrix, tell me exactly what it is you want to accomplish with your analysis.

**Comment by magical-hhc** [comment]
In fact, I need to do social network analysis on pajek based on correlation coefficient matrix.
Although other time series models can meet my needs and get the correlation coefficient matrix, it takes a little long. I observed that the correlation coefficient matrix can also be obtained in a short time on tetrad, so I asked the above series of questions (at least I have to know the principle of tetrad's solution).

**Comment by magical-hhc** [comment]
There may be something wrong with my expression. I use MS-VAR model, and the calculation of disturbance correlation coefficient matrix is only the second, so the calculation time is longer.
The matrices calculated by different models are different. I may need to use the most appropriate correlation coefficient matrix for network analysis to get better results, so I want to know the calculation principle of tetrad, but I think I probably know it.

**Comment by jdramsey** [comment]
It's calculating Pearson correlation coefficients for each pair of columns. This Wikipedia page describes the principle:

https://en.wikipedia.org/wiki/Pearson_correlation_coefficient

**Comment by jdramsey** [comment]
Now, if you're using a *VAR* model, that's going to take previous time lags into account, so the previous time lags will need to be represented. For example, you have 

X_0 = a Y_0 + b Y_1 + c Z_1 + X+1

where the indices indicate the lag. This can be represented in Tetrad using a time lag dataset, where these lagged variables are explicitly represented.

I've taken some screenshots to illustrate.

<img width="756" alt="Screenshot 2023-04-07 at 11 39 54 AM" src="https://user-images.githubusercontent.com/9853255/230637265-9c05de02-c320-43b0-a07a-9736c46a6033.png">
<img width="231" alt="Screenshot 2023-04-07 at 11 40 06 AM" src="https://user-images.githubusercontent.com/9853255/230637266-4fb00836-96c3-4899-bd98-8a5dea0106a5.png">
<img width="400" alt="Screenshot 2023-04-07 at 11 40 15 AM" src="https://user-images.githubusercontent.com/9853255/230637268-552ededc-ea6e-49ae-a0ce-debdecd44485.png">
<img width="523" alt="Screenshot 2023-04-07 at 11 40 20 AM" src="https://user-images.githubusercontent.com/9853255/230637271-660d0b4c-10ad-4b55-b9df-3d5515b973a2.png">
<img width="436" alt="Screenshot 2023-04-07 at 11 40 30 AM" src="https://user-images.githubusercontent.com/9853255/230637273-3079ce1d-650f-4e08-a6a6-625ecb09107d.png">
<img width="1" alt="Screenshot 2023-04-07 at 11 40 50 AM" src="https://user-images.githubusercontent.com/9853255/230637274-36a3c5e9-7dfc-4041-833d-c8f421889cce.png">
<img width="166" alt="Screenshot 2023-04-07 at 11 40 56 AM" src="https://user-images.githubusercontent.com/9853255/230637275-addd0c64-183c-44d3-acd6-ac5706c24986.png">
<img width="838" alt="Screenshot 2023-04-07 at 11 41 05 AM" src="https://user-images.githubusercontent.com/9853255/230637276-04e10c67-1541-4bb3-ab08-d67d2bb19beb.png">
<img width="839" alt="Screenshot 2023-04-07 at 11 41 38 AM" src="https://user-images.githubusercontent.com/9853255/230637277-2e70655a-a32b-4312-b3b5-240f7fd6c622.png">

**Comment by jdramsey** [comment]
You could take the correlation matrix of the **lagged** data here, which is what the search will be using. A VAR model (not sure about MS-VAR) would implicitly be using this correlation data.

<img width="356" alt="Screenshot 2023-04-07 at 11 45 17 AM" src="https://user-images.githubusercontent.com/9853255/230637798-58fb2cb9-560b-4437-9327-107ad5f2a5af.png">
<img width="837" alt="Screenshot 2023-04-07 at 11 45 30 AM" src="https://user-images.githubusercontent.com/9853255/230637800-3c45f0d5-007d-4c81-b727-512a9b44d4c2.png">

**Comment by magical-hhc** [comment]
Ok, thank you for your patience. I think the question can be closed. @jdramsey

**Comment by jdramsey** [comment]
Great, I'll close it for you. BTW, I just read a book chapter on ms-var,

https://link.springer.com/chapter/10.1007/978-3-642-51684-9_2 

The above would be not for generating the time series so much as for analyzing its causal structure--i.e. trying to recover the structure of the generating equations.

Anyway, now that I see where you're going, this is an interesting question, thanks!
