### ISSUE TITLE
How to obtain data reflecting the strength of causality

### ISSUE THREAD

**Issue by magical-hhc** [cmu-phil/tetrad#1581]
Tetrad can carry out causality test, whether the generated results include: data reflecting the strength of causality between variables, and where to check this data, which I have not found.
I also have an idea: whether tetrad can combine the correlation coefficient matrix of variables with the data of causality strength to generate a data containing these two important information, and it may be better to conduct empirical research based on this data. Ps: Of course, it's just my idea. I don't know whether it's feasible and how difficult it is to achieve.:) :) :)

**Comment by cg09** [comment]
On Sun, Apr 9, 2023 at 1:35 AM magical-hhc ***@***.***> wrote:

> Tetrad can carry out causality test, whether the generated results
> include: data reflecting the strength of causality between variables, and
> where to check this data, which I have not found.
>
I do not understand what you mean by "data of causal strength."  There are
two senses perhaps: causal effect size for binary variables, and size of
standardized regression coefficients for linear models. The second can be
estimated in tetrad. The first is essentially a difference of means
conditional on the respective values of the causal variables. Did you have
something else in mind.

**Comment by magical-hhc** [comment]
Hum, for example, both A and B are the causes of C. In the independent facts in the comparison box, the same period test shows correlation, and both P are 0. But who is the main cause of C, A and B? I think there should be an indicator to reflect this information. For example, among the causes of C, A accounts for 50% and B only accounts for 10%. PS: It feels a bit like variance decomposition, but I'm not sure if it's the same.
Maybe what I want is the first one you mentioned. Can you teach me how to operate it?

**Comment by cg09** [comment]
So you have a linear model with two causes A, B and an outcome C?  Then 1.
standardized the variables (using a data box). 2. use the standardized data
in the regression box. If the predictors are independent the coefficients
give you the change in the effect for a unit change in the cause. That is
one measure of effect size.
