### ISSUE TITLE
Rename: Display informative exception when singularity exceptions are encountered in all public searches.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1589]

**Comment by cg09** [comment]
At one time we computed correlations "on the fly" as they were needed for
tests. Wouldn't that make looking for non-singular subsets unnecessary?

**Comment by jdramsey** [comment]
No, that was just another method for calculating the correlations for a correlation matrix. The whole correlation matrix could still be singular once all of the correlations are calculated.

**Comment by cg09** [comment]
Of course it could, but why would you care??

**Comment by jdramsey** [comment]
Oh--that leads to singularity exceptions--matrices or submatrices that
can't be inverted. Then you can't do estimations or sometimes can't even
evaluate tests or scores.

**Comment by cg09** [comment]
yes, I forget about parameter estimation.

**Comment by jdramsey** [comment]
Bryan suggested instead doing this to focus on singularity exceptions as they come up in algorithms. We used to do some of this, but perhaps something more systematic could be done for it across all algorithms.

**Comment by cg09** [comment]
What does the title of your email even mean?

**Comment by jdramsey** [comment]
Oh you mean what issue is this in the issues list?

The problem is that if you give me a dataset there may be nonsingularities in the data. Mike had been figuring ut where these were by hand; I was going to automate that procedure. Bryan suggested instead that I focus on the nonsingularities (as I used to) by reporting the tests and scores where they were an issue.

**Comment by jdramsey** [comment]
Done, will be published with the next release.
