### ISSUE TITLE
Literature on tetrad related research

### ISSUE THREAD

**Issue by magical-hhc** [cmu-phil/tetrad#1609]
Recently, I saw a document, which seems to be written by you. The name of the document is Comparing the Performance of Graphic Structure Learning Algorithms with Tetrad, and I think it is very helpful to me. Joseph, if I want to know more about tetrad, is there any literature I can refer to?

**Comment by jdramsey** [comment]
Funny you should ask. I just reorganized the search package and wrote the documentation for every public class. Here:

https://www.phil.cmu.edu/tetrad-javadocs/temp/edu/cmu/tetrad/search/package-summary.html

You can click around and get information. I included lots of paper references. It's possible this might be helpful... curious..

If that doesn't do the trick, I can recommend some other resources. For example, you may want to read Causation, Precision, and Search by Spirtes, Glymour, and Scheines, which is actually all online and free now.

**Comment by jdramsey** [comment]
Here's a quick paper we wrote a few years back:

https://www.atmos.colostate.edu/~iebert/PAPERS/CI2018_paper_35.pdf

Really I should sit down and write a new paper; so much has changed since then.

**Comment by jdramsey** [comment]
Here's some more recent work in Tetrad if you're into reading technical papers:

https://proceedings.mlr.press/v180/lam22a.html

**Comment by jdramsey** [comment]
It also occurred to me maybe you like to watch video lectures. (I should have asked what you liked.) Here are some video lectures on Tetrad:

https://www.ccd.pitt.edu/video-tutorials/

**Comment by magical-hhc** [comment]
Thank you, I will read these materials carefully.
