### ISSUE TITLE
Add tiered knowledge graph layout where knowledge is available.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1641]

**Comment by jdramsey** [comment]
Done.

**Comment by cg09** [comment]
My very long standing TETRAD requests, in order of my priority:

1. Zhang/Madelyn unmixing algorithm.
2. Murray Watters intermediate unobserved variable algorithm
3 CD-Nod
4. Kun's GIN algorithm

**Comment by jdramsey** [comment]
Why did you put this in a closed issue?
