### ISSUE TITLE
time series edges 7.4.0

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1642]
I can't get 7.4.0 to take time series edges.

**Comment by cg09** [comment]
That's with 4 variables. With 2 variables, I can, but it will not allow "simultaneous" edges.

**Comment by cg09** [comment]
Another correction: it isn't the number of variables; it's the interaction between number of lags and edges.  I can't make a lag 1 or 2 edge when I specify a maximum lag 3 graph in "configuration."

**Comment by cg09** [comment]
Never mind. Has to be done from the bottom, I see.

**Comment by jdramsey** [comment]
Ah! Yeah sorry I had fallen asleep. :)

**Comment by jdramsey** [comment]
I take this is fixed :) So I'll close it. :)
