### ISSUE TITLE
Rename: Consider putting BPC, FOFC, FTFC in two algorithm categories.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1643]
1. In the SEARCH box, why are BPC and FOFC not included in the dropdown list of "algorithms that allow latent causes"?

2. What happened to the option to use the distribution free test for tetrads in BPC and FOFC???  It needs to be included.

Clark

**Comment by cg09** [comment]
Once again, what is the (undocumented) "delta test" for tetrads in BPC??

**Comment by jdramsey** [comment]
Oh nuts, for issue 1, the code is set up to put each algorithm into exactly one of these categories:

public enum AlgType {
    forbid_latent_common_causes, // PC_All, PcStableMax, FGES, IMaGES_Discrete, IMaGES_Continuous, FANG, EFANG
    allow_latent_common_causes, // FCI, RFCI, GFCI, SVARFCI, SvarGFCI
    /*DAG, */
    search_for_Markov_blankets, // FGES-MB, PC-MB
    produce_undirected_graphs, // FAS, MGM, GLASSO
    orient_pairwise, // R3, RSkew, Skew
    search_for_structure_over_latents // BPC, FOFC, FTFC
}

@cg09 would you prefer to get rid of the category "allow_latent_common_causes"?

**Comment by jdramsey** [comment]
I think 2's been settled privately.

**Comment by jdramsey** [comment]
On the other hand, that may make a lot of sense. I just don't know how to do it.

**Comment by jdramsey** [comment]
This is a fairly bit change--I'll keep in the back of my mind.
