### ISSUE TITLE
Check Delta test.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1644]
Add this reference for the delta tetrad test and check equation 17 in the code.

[bollen-1990-outlier-screening-and-a-distribution-free-test-for-vanishing-tetrads.pdf](https://github.com/cmu-phil/tetrad/files/11726086/bollen-1990-outlier-screening-and-a-distribution-free-test-for-vanishing-tetrads.pdf)

**Comment by jdramsey** [comment]
Added this reference to the manual.

**Comment by jdramsey** [comment]
Actually, @cg09 I should talk with you about this and show you what Ricardo implemented there.

**Comment by cg09** [comment]
I stand ready to meet with you any day any time.

Clark
