### ISSUE TITLE
Some items from a discussion with Peter.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1646]
I didn't write these down, but let me see what I can remember.

* Add a gadget in the Java interface to let people submit suggestions. DONE! In the Help menu.
* Add an "all sets" option to the Markov Checker for small models, possibly up to a certain depth. DONE!
* Look into adding an exact search (e.g. Tian).
* Start looking into alternative scores/tests for more general than LG. (Kun gave me some papers to review, and there's also BIwei's paper.)
* In general, look for more tools for analyzing real data.
    * I suggested a way to help the user determine for large models how many violations of ground truth there are.
    * Maybe a more streamlined way to modify knowledge to rerun algorithms, looking for a better score.

**Comment by cg09** [comment]
And...Murray Watters and CDNOD. (you can transfer from java to python, but
not in other direction in the interface).

**Comment by jdramsey** [comment]
I thought we weren't into duplicating effort anymore.

**Comment by jdramsey** [comment]
Some options for helping users to analyze real data.

- [ ] A menu item in the interface to show people how to make suggestions. Done.
- [ ] A Markov Checker. This is more or less done, though I'd like to add a sorting feature to the tables of conditional independence facts with the p-values so you can sort the table by dependency or p-values.
- [ ] A dynamic plot matrix, where you can pick the variables to include in the matrix of scatterplots and histograms. I started this on Saturday and will work on it some more today. This has also been requested many times in the past, so it's long overdue.
- [ ] Tools to help users identify singular subsets of variables in continuous data. This has been requested many times in the past, so it makes sense to take up the gauntlet. I now display an informative error message for testing and scoring every time a singular matrix is encountered in the search. I pop up a dialog saying which variables caused the singularities. I also added a routine to identify constant columns in the data (very useful) and to identify singular subsets of size 2 or 3 (beyond that is unwieldy). Beyond that, I need to make a separate tool the user can use where they can control the depth to whatever they want, so long as they're willing to wait.
- [ ] A table of descriptive statistics and a table of non-Gaussian statistics (maybe these could be combined) that spans variables. Currently, you can only look at one variable at a time, which is unhelpful if you have 100 variables. I have not started this. This is low-hanging fruit.
- [ ] Faster scores and tests for "more general" (though perhaps not completely general) cases. We had discussed this. It's not off my radar. Requested multiple times. Kun gave some feedback in this direction that I still need to sort through. This could also be done in Python and incorporated into Java (or vice-versa--whichever makes the most sense algorithmically, I don't care one way or the other).
- [ ] 11. A tool in the search box to store search results and allow the user to show them in sorted order by score. This is not difficult for the DAG or CPDAG cases; PAG cases may take some more thought. I have not started this. As you pointed out, this should only be done if there is support for it aside from you.
- [ ] A tool to help users determine for large models what background knowledge violations exist.

**Comment by jdramsey** [comment]
@ps7z These additional items we talked about I could add to Tetrad-FX if we decide to pursue it:

- A tool in the search box to store search results and allow the user to show them in sorted order by score.
-  A tool to help users determine what background knowledge is violated for large models.
-  Faster scores and tests for "more general" (though perhaps not completely general) cases. We had discussed this. It's not off my radar. Requested multiple times. Kun gave feedback in this direction that I still need to sort through. This could also be done in Python and incorporated into Java (or vice-versa--whichever makes the most sense algorithmically; I don't care one way or the other).

Several other things may make sense in that context as well.

**Comment by jdramsey** [comment]
I think these items should be moved to Tetrad-FX:

- [ ] A tool in the search box to store search results and allow the user to show them in sorted order by score.
- [ ]  A tool to help users determine what background knowledge is violated for large models.
- [ ]  Faster scores and tests for "more general" (though perhaps not completely general) cases. We had discussed this. It's not off my radar. Requested multiple times. Kun gave feedback in this direction that I still need to sort through. This could also be done in Python and incorporated into Java (or vice-versa--whichever makes the most sense algorithmically; I don't care one way or the other).
