### ISSUE TITLE
Saving a Tetrad session following bootstrapping search results a very large file

### ISSUE THREAD

**Issue by MikeKonrad** [cmu-phil/tetrad#1648]
I've sent Joe the dataset I've been using. I run search (BOSS) with default settings except for the number of bootstrap samples.

This is using the tetrad-gui-7.4.0-launch.jar on macOS with Java:
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

(Incidentally searching using BOSS a dataset that's 1600 rows (approx) and 17 numeric-valued columns with 10000 bootstrap samples takes only 35 seconds on my Mac (with whatever the default amount of RAM that running "java -jar *launch.jar" from my terminal takes.

**Comment by cg09** [comment]
Is it confidential? Can Joe pass it to me?

Clark

**Comment by MikeKonrad** [comment]
Hi Clark, Certainly. If you are curious about what the variables represent, I can provide some context later.

Mike
________________________________

**Comment by cg09** [comment]
Mike,

Thanks, you can tell me after I do some guesswork.

**Comment by jdramsey** [comment]
@MikeKonrad According to the profiling, the list of bootstrap graphs is growing in size in the code. It's possible that by not saving these separate bootstrap graphs, space could be conserved in the saved session. Let me refactor all of the bootstrap graph fields in all of the algcomparison algorithm wrappers to be transient.

**Comment by jdramsey** [comment]
Alternatively, I could add a parameter to allow the user to decide whether the separate bootstrap graphs should be saved and set it to false by default.

**Comment by MikeKonrad** [comment]
Thank you, Joe. This will work well for me!

From: Joseph Ramsey ***@***.***>
Reply-To: cmu-phil/tetrad ***@***.***>
Date: Sunday, July 9, 2023 at 2:18 PM
To: cmu-phil/tetrad ***@***.***>
Cc: Michael Konrad ***@***.***>, Mention ***@***.***>
Subject: Re: [cmu-phil/tetrad] Saving a Tetrad session following bootstrapping search results a very large file (Issue #1648)


Alternatively, I could add a parameter to allow the user to decide whether the separate bootstrap graphs should be saved and set it to false by default.

**Comment by jdramsey** [comment]
@MikeKonrad Great! Maybe I'll send you a jar if you want to test it. I just tested it out a few minutes ago with 1000 bootstraps for BOSS for a 60-node graph, and the saved session was a reasonable size. But if you're still having difficulties then there may be another problem lurking as well.

**Comment by jdramsey** [comment]
@MikeKonrad Yeah, that seems to have done the trick. I just loaded your file and did 5000 bootstraps with BOSS with that parameter set to false, and it saves out as a session of 501 KB, which is fine.

I'll make you a jar, though, and send it. You can try it at your convenience and close this issue if you're OK with it.

**Comment by jdramsey** [comment]
Mike checked this--it works
