### ISSUE TITLE
Question regarding "higher" and "negataive" scores

### ISSUE THREAD

**Issue by XuHuang38** [cmu-phil/tetrad#1652]
Hi there! I'm currently using this package for a mixed dataset. When I wastrying to work with the conditional gaussian score, I noticed in your comment that "As for all scores in Tetrad, higher scores mean more dependence, and negative scores indicate independence." I wonder for the phase "higher", are you referring to the absolute value of the score? Or do you mean that the more negative the score of a variable is, the more independence the variable is?

Thank you in advance!

**Comment by cg09** [comment]
In what sense is your data mixed?  As in a combination of data types, or a
pooling of data?

**Comment by XuHuang38** [comment]
Yes, we have a combination of data types, with 2 continuous and 10 discrete
variables. We tried the FGES method and got a score return
of -7115124.013243. I wonder if it implies independence or dependence?

**Comment by jdramsey** [comment]
Well, scores per se don't indicate dependence or independence, though score _differences_ (bumps) may for BIC scores. For example, if you are judging whether X _||_ Y | Z, you could calculate BIC(Y | X, Z) - BIC(Y | Z). If that number is less than zero, then you may judge that X _||_ Y | Z; otherwise, if it's greater than zero, you may judge for conditional dependence instead.

**Comment by jdramsey** [comment]
I'm assuming here that your scores are oriented as they are in Tetrad, so that "higher" is "more dependent," like BIC = 2L - k c k ln N. If they're oriented the other way (like BIC' = L - c (k / 2) ln N as in Schwarz) then the reverse will be true.

**Comment by cg09** [comment]
like BIC = 2L - k c k ln N. If they're oriented the other way (like BIC' =
L - c (k / 2) ln N as in Schwarz)        ???????

**Comment by jdramsey** [comment]
Woops, BIC = 2L - c k ln N.

**Comment by XuHuang38** [comment]
I see. So let's say we have an output of score like this: 
Graph Node Attributes:
Score: [adopt: -21485.30388386646;cnt_dest: -67741.53565166239;weight_algo: -188944.621247786]
So I guess each value is representing the "bumping" for all other variables?

Thank you in advance!

**Comment by jdramsey** [comment]
Hmmm.... I'm embarrassed to say I don't recognize this output. It doesn't look like Tetrad; I can't find "adopt:" or "cnt_dest:" or "weight_algo" anywhere in the Java Tetrad code. Is it causal-learn, maybe, or some other Python package?

My comment about bumps only applies if you're using a BIC score (which in Tetrad is higher for greater dependence). Also, you can't tell what a score "bump" is from a score for one particular node--what's needed is a difference of scores.

**Comment by jdramsey** [comment]
Hmmm... I can't find those strings in the causal-learn code either, so I'm not sure exactly what's being printed here, to be honest. :(

**Comment by XuHuang38** [comment]
Sorry that I didn't make it clear. So basically I used three variables, adopt, cnt_dest, weight_algo, as my dataset, and I use the run_mixed.py in your py-tetrad package. The result is from the FGES with BIC score algorithm I believe :)

**Comment by jdramsey** [comment]
Ah, OK! Well in that case those aren't bumps in scores but single scores. If you run FGES with a BIC score with verbose set to true, bumps in score will be printed as part of the output as edges are added to or removed from the graph. :)

**Comment by XuHuang38** [comment]
I see! Thank you! So I guess if my score is that low, maybe the graph is not great then?

**Comment by jdramsey** [comment]
That's the thing--you can't tell with a single BIC score whether a graph is good or bad; BIC is purely relative. All you can tell is that if one graph gets a higher score than another (in Tetrad using BIC), the one with the higher score is better.

So the game for BIC is to find a model with the highest BIC (i.e., least negative or most positive) score possible.

By the way, you don't need to just use FGES for this; you could also use the GRaSP algorithm, which tends to find higher-scoring models than FGES; an example of that is in that same file. You can compare the GRaSP model to the FGES model to see which has a higher score, provided you use exactly the same score (with the same parameters) for each, on the same exact dataset.

In GRaSP, there is even a parameter that lets you automatically run the search a given number of times and take the best-scoring result for your answer.

**Comment by cg09** [comment]
Joe,

At one time, I think I remember, TETRAD produced BIC scores for
models...not just as a step in GES/FGES. I wonder where that went.

**Comment by XuHuang38** [comment]
I see! Thank you very much! I think I understand it now.

**Comment by XuHuang38** [comment]
One more thing to ask, when you are saying "higher score", you mean the absolute value, right :) Since all the score are negative

**Comment by jdramsey** [comment]
No, if all scores are negative, you'd want the _least negative_ score, which would be the score with the _smallest absolute value_. Sorry, I didn't mean to confuse you.

**Comment by XuHuang38** [comment]
Gotta! Thanks!

**Comment by jdramsey** [comment]
Absolutely!
