### ISSUE TITLE
Knowledge Box Not Functioning Properly 

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1661]
Trying to set the knowledge tiers as shown below:

![Screenshot from 2023-07-17 17-19-40](https://github.com/cmu-phil/tetrad/assets/10729309/27e1d081-9d0d-4717-a556-26c9640759a4)

When double click the knowledge box to reopen up the knowledge box, variable got moved back to "Not in tier":

![Screenshot from 2023-07-17 17-20-24](https://github.com/cmu-phil/tetrad/assets/10729309/24a4a6a9-f848-40f9-8500-e35cb40d16d4)

I think this is because the variable name **_6/4.5_** throws it off.

Here's the sample data: [data.txt](https://github.com/cmu-phil/tetrad/files/12073948/data.txt)

**Comment by cg09** [comment]
Kevin:  When running search with d-sep, data is not necessary, but the
Knowledge box will not work.

**Comment by jdramsey** [comment]
@cg09 I need to watch you do this; I can't get the problem to happen.

**Comment by jdramsey** [comment]
@kvb2univpitt Can you give me a knowledge file with these knowledge names? It's got to have something to do with the names.

**Comment by jdramsey** [comment]
@kvb2univpitt I'm going to close this to get it out of the way--I tested it on your example and the fix works.

**Comment by kvb2univpitt** [comment]
@jdramsey Thanks!  I hope it was an easy fix.

**Comment by jdramsey** [comment]
Very easy. :)
