### ISSUE TITLE
Relevance of Causal Inference/Double ML to tetrad 

### ISSUE THREAD

**Issue by jonBoone** [cmu-phil/tetrad#1662]
I just came across an article that informed me that there was a concept of _Double ML_, where the unfamiliar portion involves Causal Inference.  [Medium article here](https://towardsdatascience.com/double-machine-learning-simplified-part-1-basic-causal-inference-applications-3f7afc9852ee)

Is there an established relationship between tetrad and these CI ML techniques?

**Comment by cg09** [comment]
Good question, sort of. "Tetrad" is a suite of procedures, not a single
procedure, all of which are very different from the "double ML" procedures.

 The original paper provides an empirical application, where unfortunately
the truth is unknown.  It provides no simulation results that could provide
some insight into its accuracy. So far as I can see it assumes all
confounding covariates are measured--which some "tetrad" procedures (e.g..
FCI) do not.

Perhaps, somebody more capable than I should do some serious simulation
comparisons of this procedure with some of the Tetrad search procedures.

**Comment by jonBoone** [comment]
That's very interesting.  I have a couple of follow-up questions:

1. Is there anyone in the CMU ML program that is researching CI ML techniques?  Perhaps they could offer a point of view.
2. Would it be potentially worthwhile to incorporate these types of techniques into the overall tetrad project in order to both
  a. maintain relevance (i.e. people who are potentially interested in tetrad won't forgo exploring it due to lack of the CI ML algorithms), and
  b. offer multiple perspectives on the same data set (I'm assuming that CI ML techniques are essentially focused on "good enough" measures of causality whereas my recollection of tetrad is that it's focused on more stringent measures of causality.

**Comment by jdramsey** [comment]
By the way, we implemented DAGMA because after comparing many continuous optimization algorithms head to head it had the best performance, though again there's still controversy surrounding these methods in general.

**Comment by jdramsey** [comment]
Here is an article on the continuous optimization methods that shows what the weaknesses are. Hopefully it will be published soon:

https://arxiv.org/abs/2304.02146

**Comment by jdramsey** [comment]
Thanks for sending the article BTW, I finally had a chance to read through it (quickly--I'll read it again later for detail and may be try the examples if everything is available for that).

Just as a quick comment, we do have a function in Tetrad to regress our non-i.i.d. influences on a variable and return the residuals. You can analyze those residuals in a number of different ways. We've used that before for some analysis of fMRI data.

**Comment by cg09** [comment]
Thanks. I have seen that paper.  What is "DAGMA"?

**Comment by jdramsey** [comment]
This thread seems to have died. I'll close it. If it's still an issue, please re-open.
