### ISSUE TITLE
Knowledge Not Saved Correctly

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1664]
Assume we have the following knowledge:

![Screenshot from 2023-07-18 20-17-16](https://github.com/cmu-phil/tetrad/assets/10729309/5cee1655-38e0-4ab7-bacb-7f3bfc9e5ccd)

When saving knowledge to a text file, the tiers are written out as index 0, 1,and 2:

```text
/knowledge
addtemporal

0  X1 X2
1  X10 X8 X9
2  X3 X4 X5 X6 X7

forbiddirect

requiredirect
```

However, when reading in the saved knowledge file, an error occured.  Tetrad expects the tier indexes to be 1,2, and 3:

![Screenshot from 2023-07-18 20-17-32](https://github.com/cmu-phil/tetrad/assets/10729309/2b8e1491-fb86-4965-b760-80fa4ef812a5)

The content of the saved knowledge file should be written out like this:

```text
/knowledge
addtemporal

1  X1 X2
2  X10 X8 X9
3  X3 X4 X5 X6 X7

forbiddirect

requiredirect
```

**Comment by jdramsey** [comment]
Hey @kvb2univpitt This has been fixed in the development branch--someone else noticed it the other day as well.

**Comment by kvb2univpitt** [comment]
OK.  I'll close it then.  Sorry for the duplicate issue. Thanks.

**Comment by jdramsey** [comment]
No worries :-)
