### ISSUE TITLE
Some typos in algorithm description about GRaSP. 

### ISSUE THREAD

**Issue by yasu-sh** [cmu-phil/tetrad#1671]
Dear developers,

in the index.html, some confusing typos exist and I guess the latter must be **non-singular depth** since there are consistent descritions in arxiv paper.
![image](https://github.com/cmu-phil/tetrad/assets/89838961/de5ed1d7-ebbb-4816-a7fe-341187518384)

In ESP, it is especially problematic. it lost consistency.  

> ESP corresponds to singular depth > 0, singular depth = 0     <----  ??

Could you tell me which to adopt?

    ESP corresponds to singular depth > 0, non-singular depth = 0

https://github.com/cmu-phil/tetrad/blob/656cee79e3a23c591a51f8a72aaf190476ba0bbb/docs/manual/index.html#L3516-L3521

![image](https://github.com/cmu-phil/tetrad/assets/89838961/2297337d-4619-413f-b638-d1be8ebbb66d)

**Comment by jdramsey** [comment]
Fixed. This should be included in the next update which I plan on publishing today.

**Comment by yasu-sh** [comment]
@jdramsey Thanks for your quick action! I am glad to know.

**Comment by yasu-sh** [comment]
@jdramsey Confirmed the update at 7.5.0. Thanks!
