### ISSUE TITLE
Required edges cannot be deleted in knowledge box after you close the knowledge box once.

### ISSUE THREAD

**Issue by yasu-sh** [cmu-phil/tetrad#1678]
@jdramsey I have noticed when I try different types of knowledges among required edges.
After making settings and closing the knowledge box, you can delete manually forbidden edges, but you cannot required edges. 

![image](https://github.com/cmu-phil/tetrad/assets/89838961/a5a8618f-759e-4c0c-8202-a36caaa1f3c1)

reproduction steps:

1. creating simulation data with simulation box by default.
2. creating knowledge box.
3. select edge and tiers type.
4. creating Required edges.
5. press Done.
6. double-click the same knowledge box.
7. enabling Show Required Explicity check.
8.  select onw required edge
9. pressing delete key in keyboard.
10. pressing Yes and closing Knowledge box by pressing Done.
11. double-click the same knowledge box again.
12. enabling Show Required Explicity check
13. the edges is still there. users might not notice the deletion works. 

workaround:

1. destroying model once
2. set required edges and other settings from beginnings

TETRAD 7.5.0
Windows 10 22H2

**Comment by jdramsey** [comment]
@yasu-sh Oh wow, thanks. I'll have to think about that one.

**Comment by yasu-sh** [comment]
@jdramsey I noticed this yesterday, but if you cannot reproduce it, let me know.
I need to consider some causes also.

**Comment by jdramsey** [comment]
@yasu-sh Hmm... I can reproduce it, it's not just you. Not sure of the cause yet.

**Comment by jdramsey** [comment]
@yasu-sh OK, let me try to fix this today. Sorry for the delay; I've been inordinately busy. I finally had to list everything I needed to do and prioritize--something I don't often do!

**Comment by jdramsey** [comment]
I'll close this since it is fixed in my branch. Let me know if you find anything else in the Tetrad UI that needs to be fixed; I'll do these fixes before October 16.

**Comment by yasu-sh** [comment]
@jdramsey Thanks for your reminding me. I could not find you branch in github.
Could you tell me the branch name? 
Today I have tried by maven build(until compile) and checked UI resposne at some branches as below:  

- development - 0ccc7f130 - Formatted the manual. - jdramsey
- joe-work-2023-8-4 - fbf3b6fcf - Trying to fix time series knowledge with FCI algs. - jdramsey
- jdramsey-patch-4 - 561aa0c5f - Update README.md - Joseph Ramsey

In the same window, Deleting Required Edge -> Toggle Required Explicity twice -> Deleted Required Edge appear again.

![image](https://github.com/cmu-phil/tetrad/assets/89838961/8e698751-148e-4719-9e61-18fa23f20b86)

**Comment by jdramsey** [comment]
Oh you're right, I have divergent branches. Sorry, let me fix that.

Joe

**Comment by jdramsey** [comment]
I've mostly reconciled these branches by pulling stuff from development
manually over to joe-work-2023-8-4. Very sorry, I accidentally edited
development for a few days. The remaining differences between the former
state of joe-work-2023-8-4 and the current state I'll redo. These have to
do with the changes I needed for Tetrad-FX, which I have a record of in the
Tetrad-FX repository.

Apologies; I was not sleeping well for a few days.

OK, so in the joe-work-2023-8-4 branch, I don't see the knowledge-required
edge deletion bug happening. I'll have to go back through and check
previous bugs. Maybe it's not the bug I'm looking for, though. Do you still
see it happening?

**Comment by jdramsey** [comment]
Please hold one minute--let me make a new branch that's reconciled with
development and put the changes there.

One second.

**Comment by jdramsey** [comment]
My new branch is joe-work-2023-10-2. It is almost identical to development.
I'll test recent fixes here.

**Comment by jdramsey** [comment]
Everything seems to be OK. There are some changes I made in Tetrad-FX that I was planning to make in Tetrad as well; I'll do those in the next few days in the new branch.

**Comment by jdramsey** [comment]
BTW thanks for catching that,.

**Comment by yasu-sh** [comment]
@jdramsey I am afraid whether I can confirm the bug fixed or not. The movie is using joe-work-2023-10-2 latest branch.
Java 11 /  Adoptium\jdk-11.0.18.10 / working in IntteliJ 2023.2.2 CE.

This is not urgent. In future you might notice something to be fixed.

![image](https://github.com/cmu-phil/tetrad/assets/89838961/5fca8661-b833-41bf-930b-09f97c22a28b)
![joe-work-2023-10-2](https://github.com/cmu-phil/tetrad/assets/89838961/a0630cdc-8054-4ceb-bd4b-f332690082c3)

used commit 
https://github.com/cmu-phil/tetrad/commit/0ccc7f130d5f1727f7cd9790fc8600b6250201a6

**Comment by fabiopuddu77** [comment]
Hello @jdramsey you can go to file and save knowledge and then delete the required edge from there and then reload the txt :) let me know if you fix like this.

**Comment by yasu-sh** [comment]
@fabiopuddu77 Thanks for your action proposal. 
I checked in this weekend and confirmed that the saved knowledge txt file.

- Before closing the dialog, the deleted edges is correct.
- After closing and re-open the dialog, the deleted edges are appeared again and if you save the knowledge txt, the deleted edges are still there.

**Comment by yasu-sh** [comment]
@fabiopuddu77 @jdramsey I can get the reproduction methods. I will edit the comment above.
![image](https://github.com/cmu-phil/tetrad/assets/89838961/884e9f0d-91a4-47a1-94bb-e1d86786a29e)

**Comment by jdramsey** [comment]
OK let me try to address this. (It's the last of the Tetrad issues I want to address prior to releasing a new version next week, though there are a few py-terad/rpy-tetrad issues as well.) First let me see if I can reproduce if on my Mac. (I was having trouble with that before, but maybe with the additional instructions I could do it.)

**Comment by jdramsey** [comment]
OK I see what you mean now. Let me think about it after my meeting...

**Comment by jdramsey** [comment]
@yasu-sh, I figured out the issue. To fix another issue, we had to change the lists of required and forbidden edges from Sets to Lists, but after the change, when adding edges to one or the other of these lists, it was not checked whether they already belonged. If there were multiple copies, and an edge was removed, it would only remove the one (because it's a list), so another copy still remained.

I think it's fixed now. I'll double-check it and commit the fix in a few minutes.

**Comment by yasu-sh** [comment]
@jdramsey It works! I appreciate your fixing this. 
I checked Required Edges and Forbidden edges as well. [Used commit](https://github.com/cmu-phil/tetrad/commit/640cd0034eee9ec20ec148aa7fa0eefbf0a7fffa)
Both edges are OK. I am closing this.

**Comment by jdramsey** [comment]
Yay!
