### ISSUE TITLE
Knowledge Inconsistency

### ISSUE THREAD

**Issue by scheines** [cmu-phil/tetrad#168]
When you change the variables in the graph for Graph->Knowledge, these variables are not propagated to Knowledge. Sometimes when you close the Knowledge box and run FCI (Knowledge->FCI), a variable may disappear from Knowledge.

**Comment by jdramsey** [comment]
Richard, I updated your comment to what you meant. Have a great evening!

**Comment by jdramsey** [comment]
Just getting back to these, sorry. Busy. I was saving knowledge across runs to allow knowledge to remain constant over simulation runs. I've just written a new Simulation container that can store multiple data sets and will consult with Peter as to whether I can disable the looped simulation facility now. That should solve the problem. Easy come, easy go.

**Comment by jdramsey** [comment]
I think this problem will go away if i stop saving variable names globally for knowledge and just get them from the parents. I will try. There are several bugs reported along these lines.

**Comment by jdramsey** [comment]
OK, this seems to be fixed now. I cleaned up the underlying code, encapsulating the various knowledge objects better. Seems to have cured many ills.

This is in the branch 'experimental'. Once the current round of fixes and upgrades is done I'll push to 'development' and repost.
