### ISSUE TITLE
CPC algorithm not support multi-thread?

### ISSUE THREAD

**Issue by chuhac** [cmu-phil/tetrad#1687]
I have a problem of low CPU usage while using Tetrad 7.5.0 jar, my data is (3500, 56) discrete data, the algorithm used is CPC, the test is Chi Square Test, I confirm that the CPU usage is normal while running other JAVA code, what is the reason for this problem?
I've diffed FGES.java and CPC.java and found that CPC may not support multi-thread in this version, anyone know the reason?

**Comment by jdramsey** [comment]
Ah interesting, I didn't know anyone would want to do that. I had an implementation of the PC adjacency search that was parallelized (by depth) but got complaints that the results weren't stable, even if the adjacency stability option was selected (PC-Stable)--even this does not guarantee consistent results with orientation. So I took that out of the interface. If you're interested in it I can spend some cycles looking at it again; maybe I'll see what to do. Or do you not worry so much about that sort of stability?

I call it the Richardson Principle, after Thomas Richardson's comment to me a while back, that every algorithm should have a mode that guarantees reproducibility. If you're not bound by the Richardson Principle :-) I won't worry about it so muchl :)

**Comment by jdramsey** [comment]
Also, is there a reason you're using CPC? FGES (in Tetrad) gives reliably much better results for large sparse graphs and will scale easily to 3500 nodes. Did you need CPC in particular?

**Comment by jdramsey** [comment]
Also, FGES supports parallelization--for a large sparse graph, you should turn the faithfulness assume flag to false though and set the parallelized flag to true. The step that's embarrassingly parallel in FGES it the initial step of placing a single edge in an empty graph, which for a large sparse model takes most of the running time.

**Comment by jdramsey** [comment]
By the way, the stability problem for the PC adjacency search is solved by this paper:

Colombo, D., & Maathuis, M. H. (2014). Order-independent constraint-based causal structure learning. J. Mach. Learn. Res., 15(1), 3741-3782.

which I would follow for a parallelization. (It's not hard.) The same paper documents the problem with instability in orientation even if the stability problem for adjacencies is solved.

**Comment by chuhac** [comment]
If so, I'll take your advice to try algorithm FGES in place of CPC. I think I should have looked into the parallelism problem before asking in this issue. Thank you again for your explanation and patience !

**Comment by cg09** [comment]
maybe he wants uniform consistency.

**Comment by jdramsey** [comment]
@chuhac I haven't looked at FGES for the discrete case for some time now. When I look at the code, there shouldn't be a problem with the parallelization steps, but maybe there is; I'll have a look.

I guess I should ask you some other questions as well--do you know how many categories your variables have and what the sample size is?

**Comment by chuhac** [comment]
@jdramsey My sample size setting is 3500, and I double checked that all 56 features have no more than 3 discrete caths

**Comment by jdramsey** [comment]
Great--I'll set up a problem like that and watch it. I'm a little busy right now, but I'll do it later. A large sample size, I guess it does without saying, is difficult for a discrete model since it has to do a lot of counting and build tables, but maybe it can do it. I've also got some other algorithms in mind that will handle that problem. (Sorry, I had thought you meant there were 3500 variables, which is more difficult.)

**Comment by jdramsey** [comment]
Alright, I'm trying to get back to issues here. I've been thinking of making a table for a multinomial estimator that stores only rows with nonzero entries in some cell or other in the row. That would mean for 3500 samples, you would need at least 3500 rows in the table, something you could easily store on your computer. 

I will try to focus on updates to the Tetrad library for the next two weeks; maybe I can get this change in. I'll post a new version of Tetrad on October 16 (at least in my imagination). That could make analyzing problems like yours a lot easier.

**Comment by jdramsey** [comment]
This shouldn't even be inherently very difficult--just replacing a double[] array with a map, though it has to be done vewy vewy cawefully...

**Comment by chuhac** [comment]
Sorry about late. Nice work, looking forward to the new version, thank you !
