### ISSUE TITLE
Grasp with time series knowledge misses all edges between lags.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1688]
I made a time series simulationin the Simulation box of Tetrad with 2 lags, thus:

<img width="807" alt="time series simulation 2 lags" src="https://github.com/cmu-phil/tetrad/assets/9853255/8d72995b-bad7-4da1-b9af-b0fe609a80e9">

I ran BOSS on this data (which uses the time series knowledge calculated by the time series simulation, forbidding edge backwards in time) and get a good result, with edges between time lags showing up:

<img width="833" alt="boss default using time series knowledge" src="https://github.com/cmu-phil/tetrad/assets/9853255/672e9d85-0b98-4788-818a-7b925b9e1b15">

However, when I switch to GRaSP with the same dataset/knowledge, the edges between time lags are missing:

<img width="835" alt="grasp default using time series knowledge" src="https://github.com/cmu-phil/tetrad/assets/9853255/db119eab-568a-4296-a848-0f2eabfd09ae">

It seems they should give very similar results.

I got these results using the boss_updates branch, updated as of 2023-9.11 at 5:25 PM.

**Comment by cg09** [comment]
How come there is no BOSS FCI??

**Comment by jdramsey** [comment]
It's called BFCI... We could call it BOSS-FCI,  suppose. Actually, Bryan
had an idea for composing algorithms, so we could have a GFCI wrapper where
the score-based step could be done by FGES, GRaSP, BOSS, or SP.

**Comment by cg09** [comment]
BFCI is not in the interface.

**Comment by bja43** [comment]
Fixed here: https://github.com/cmu-phil/tetrad/pull/1691
