### ISSUE TITLE
How to use version 7.5.0 to open a tet file created in version 6.6.0

### ISSUE THREAD

**Issue by PhilrainV** [cmu-phil/tetrad#1689]
I have a model that used to use version 6.6.0, but now it cannot be opened when updated to version 7.5.0. Is there a solution? Or where can I download 6.6

**Comment by jdramsey** [comment]
Oh, that's a tough question. Unfortunately, the server that had stored those builds stopped working, but in any case, those builds were done under a version of Java that is no longer available, so the code would have to be recompiled. That would have been in 2019 sometime, though, and all of that code is in the GitHub repository and so could, in principle, be recovered and rebuilt under a more recent version of Java. I think it would work. I tried it just now and ran across an issue that could be fixed--the.DS_Store files (bookkeeping files for Mac OS file system) were stored in the repository and conflicted, but I believe this problem could be finessed. So I think this version could be recovered and rebuilt with a few hours' work. I don't have a few hours to spend on it today, but maybe sometime next month, I could help you with it.

To TL;DR I think this can be done, but I can't do it for you today. If you know how to jocky the history of GitHub and how to build Java apps, you could potentially do it, but I can try to do it at some point for you.

**Comment by jdramsey** [comment]
This is the last version in the repository with version 6.6.0 in the POM file, just a as a note:

<img width="1057" alt="Screenshot 2023-09-12 at 8 04 52 AM" src="https://github.com/cmu-phil/tetrad/assets/9853255/4fc03010-b00a-4765-82c6-0eba324fe2d9">

**Comment by jdramsey** [comment]
I think this is no longer of interest. Closing.
