### ISSUE TITLE
Large graphs are too big and render off screen when initially loaded

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1697]
[THIS ISSUE IS IN THE DEVELOPMENT BRANCH]

When loading a large graph, the default circle layout renders it entirely off screen, making it seem like nothing was loaded. The only thing that identifies that a graph has been loaded are the x and y scroll bars. If you use these bars to scroll left, then the graph becomes visible. In the attached images, I loaded a graph with 758 nodes.

After initial load:
<img width="1158" alt="Screenshot 2023-10-09 at 10 09 24 AM" src="https://github.com/cmu-phil/tetrad/assets/16494809/224791a9-3eff-4fed-b98c-294f43f70dab">

After scrolling left:
<img width="1185" alt="Screenshot 2023-10-09 at 10 09 44 AM" src="https://github.com/cmu-phil/tetrad/assets/16494809/d3fdc18a-b4c2-4786-9e56-15da23d1fce5">

**Comment by jdramsey** [comment]
Plan: Make circle layout the default layout for up to 20 variables, and square layout for larger graphs.

**Comment by cg09** [comment]
Lingam will not run with missing data filled with asterisks. Direct lingam
will. How come and can it be fixed?

**Comment by bja43** [comment]
I would guess that's an issue with the ICA implementation, but I think @jdramsey would know for sure. Does LiNG-D work when there are missing data?

**Comment by jdramsey** [comment]
OK I fixed the layout issue in Tetrad by making the default layout circle if # nodes <= 20 and square otherwise, so you don't get apparently empty graphs with the circle layout. Closing.

@cg09 Can you make a separate issue for the missing value problem?
