### ISSUE TITLE
Simulated Random One/Two Factor MIM graph has lost edges b/w latent nodes on indicating Graph at the only first loading.

### ISSUE THREAD

**Issue by yasu-sh** [cmu-phil/tetrad#1725]
This is found by @jdramsey and  @yasu-sh confirmed: https://github.com/cmu-phil/tetrad/issues/1713
TETRAD 7.6.2 release / Windows 10 Pro / Intel i7 Processor / Amazon Corretto 17

1. Places simulation box.
2. Double clicks simulation box
3. Selects Random One(Two) Factor MIM at Type of Graph.
4. Presses Simulate
5. Closes Dialog by press Done.
6. Places  Graph Box
7. Double-click Graph Box
8. Select Graph, Then Press OK.
9. The edges between Latent nodes disappear
10. Closes Dialog by Pressing Done.
11. Double-clicks Graph Box
12. The edges at step 9 come up this time.
13. If you does select 'Direct Acyclic Graph' or 'Structural Equation Model Graph', this symptoms does not come up. 

Random Two Factor MIM case: 
L.X1, L.X2, L.X3 lost and LX1B, L.X2B, L.X3B survived
![image](https://github.com/cmu-phil/tetrad/assets/89838961/fc200e63-f599-43d6-80fc-62c31d0fa5d0)

**Comment by jdramsey** [comment]
Oh boy! I have no idea what the problem might be there. Let me look in the debugger.

**Comment by jdramsey** [comment]
I can reproduce it also by placing a graph box, double clicking, selecting Random Graph from the menu, and selecting a 2-factor MIM.

**Comment by yasu-sh** [comment]
I have confirmed this issue at https://github.com/cmu-phil/tetrad/pull/1727.
Thank you!
