### ISSUE TITLE
MarkovCheck javadocs are incomplete

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1733]
some methods are missing from the javadocs:
https://www.phil.cmu.edu/tetrad-javadocs/7.6.3/edu/cmu/tetrad/search/MarkovCheck.html

**Comment by bja43** [comment]
Hold on... I think it was a bigger issue than just the method missing in the javadocs. I think It was also missing in the 7.6.3 GUI

**Comment by jdramsey** [comment]
This is fixed.
