### ISSUE TITLE
Create a Panel to Show the Search Graph and Its Edge Probabilities Side-by-side.

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1742]
Create a split panel to show the search graph and the edge probabilities side-by-side.

**Comment by jdramsey** [comment]
@kvb2univpitt You know, I think the graph/edge probabilities arrangement is good enough. What do you think?

**Comment by jdramsey** [comment]
I'm going to close it, see if it comes up again...

**Comment by cg09** [comment]
How would you get edge probabilities???

**Comment by jdramsey** [comment]
Click on that tab. I think Kevin was worried that people wouldn't know to click on the edges tab.
