### ISSUE TITLE
Where can I see the p-value and z-statistic in PC algorithm?

### ISSUE THREAD

**Issue by ifidw** [cmu-phil/tetrad#1768]
Hello,I'm doing a research in Tetrad.I want to generate a directed acyclic graph from my dataset by PC algorithm.Now I get a gragh and I feel confused about it.For further research,I want to see how the graph is generated.So I want to see the p-value and the z-statistic, but I can't find how.My version of Tetrad is 7.6.3.Can you show me the way of seeing such statistic?Here are some pictures in my Tetrad.
<img width="284" alt="1" src="https://github.com/cmu-phil/tetrad/assets/169630517/a5aa4bd5-15de-4637-8ca1-931462211d7d">
<img width="623" alt="2" src="https://github.com/cmu-phil/tetrad/assets/169630517/f5b889c6-84f7-4ea4-8ba6-6d5b4372c77c">
<img width="622" alt="3" src="https://github.com/cmu-phil/tetrad/assets/169630517/ceff9bbb-9068-46d0-a3ef-a66e39f3007b">
<img width="1120" alt="4" src="https://github.com/cmu-phil/tetrad/assets/169630517/0e03f3b8-54f1-4ea6-bf47-385e4422a2d2">

**Comment by jdramsey** [comment]
Sure, the way to get the whole list of decisions the algorithm used to produce the results is to turn on the "versbose" parameter (set it to 'yes'). It's in the list of parameters when you run the search.

There are two way to view the verbose output. One is to go to the "Logging" menu and just before you run the algorithm select turn logging on. Then run the output; the verbose output will be displayed in the logging window, and then you can select "turn logging off" and the logging will stop. If you would like to save the logging to a file, you can go to File->Settings->Logging and set that up.

The other way to view logging information is to launch Tetrad from the command line in a terminal:

java -jar [name of Tetrad launch jar].jar

Then if you turn "verbose" to "yes" you will see logging int he terminal window.

Hope this helps!

**Comment by ifidw** [comment]
My problem has been solved.Thank you very much!

Best wishes!













At 2024-05-13 13:12:56, "Joseph Ramsey" ***@***.***> wrote:

Sure, the way to get the whole list of decisions the algorithm used to produce the results is to turn on the "versbose" parameter (set it to 'yes'). It's in the list of parameters when you run the search.

There are two way to view the verbose output. One is to go to the "Logging" menu and just before you run the algorithm select turn logging on. Then run the output; the verbose output will be displayed in the logging window, and then you can select "turn logging off" and the logging will stop. If you would like to save the logging to a file, you can go to File->Settings->Logging and set that up.

The other way to view logging information is to launch Tetrad from the command line in a terminal:

java -jar [name of Tetrad launch jar].jar

Then if you turn "verbose" to "yes" you will see logging int he terminal window.

Hope this helps!

**Comment by jdramsey** [comment]
Great!
