### ISSUE TITLE
The use of Tetrad

### ISSUE THREAD

**Issue by miaomiao-alt** [cmu-phil/tetrad#1795]
Hello, let me explain my operation steps in detail:
Step 1: Enter the data
Step 2: Set the prior knowledge-level constraint (0 level: 47 variables; 1 level: 11 variables)
Step 3: Select the algorithm -BOSS (default parameter Settings)
Step 4: Input the result graphs and data of the previous three steps into the SEM parameter model - the problem of undirected edges occurs
![image](https://github.com/cmu-phil/tetrad/assets/172348150/add3a77a-8f2e-46e3-8963-e70e5bd4e60c)

**Comment by cg09** [comment]
the output is a CPDAG--a collection of DAGs that entail the same
conditional independence relations, a Markov Equivalence class. The
estimator will only take a DAG. To estimate you need to select a DAG from
the output. You can do so by choosing any direction you want for the
undirected edges, as long as you do not introduce a new collider---X -> Y<-
Z.

**Comment by miaomiao-alt** [comment]
So how do I achieve this？

**Comment by cg09** [comment]
Make a Graph box. Draw the DAG you want in the Graph box. Connect the Graph
box to a PM box. Parametrize it in a PM box. Estimate the model in the PM
box by connecting it to an Estimate Box.  Get the estimate. Watch the
tutorial online at the Center for Causal Discovery. Read the manual. Read
the Primer by Pearl and Glymour.

**Comment by miaomiao-alt** [comment]
thank you so much！

**Comment by miaomiao-alt** [comment]
I can understand the advice you gave me: Draw the DAG you want in the Graph box. However, I want to get this DAG graph by setting the prior knowledge and then using the BOSS algorithm. How should I operate this way?

**Comment by jdramsey** [comment]
Hi @miaomiao-alt, would you like to zoom sometime? I can show you.

**Comment by miaomiao-alt** [comment]
yes,I can

**Comment by jdramsey** [comment]
Send me an email.

**Comment by miaomiao-alt** [comment]
Can you give me a few minutes while I get ready?

**Comment by miaomiao-alt** [comment]
hemiao2207@163.com

**Comment by jdramsey** [comment]
I sent you an email.

**Comment by miaomiao-alt** [comment]
How do I know if my model is good or bad？
![image](https://github.com/user-attachments/assets/f8eed617-a7c0-4c47-87cc-9e972c23c491)

**Comment by cg09** [comment]
You don't. All you know is that it was found by a procedure that in the
large sample limit converges to the right answer. That is all you know
about *any* statistical estimator.

**Comment by jdramsey** [comment]
The stats don't look super-good, but on the other hand, you have included a fair amount of background knowledge. P-value and chi-square are tricky statistics for linear models; if the model isn't essentially perfect; these don't register well. A better tool is the Markov checker that we're developing, which you're free to use, though we don't have a paper for it yet. (Working on it.)

For BIC score, you could try different algorithms or different settings for the algorithms and try to get the best score you you can; this method is often used.

Otherwise, Clark is right; you want to pick an algorithm that has a good performance in general. BOSS is a good choice, or GRaSP.

**Comment by jdramsey** [comment]
We could zoom again and discuss this a bit. I was fairly busy for the rest of the day yesterday, but later today may have some more time...

**Comment by jdramsey** [comment]
In my private version of Tetrad I have some tools that could help you choose a good model; I could share this with you if you like. It is an issue I've been thinking about and which is not well-addressed in the current literature.

**Comment by miaomiao-alt** [comment]
OK! What time are you free today? Let's make an appointment for another meeting. I have a few more questions I'd like to ask you.

**Comment by jdramsey** [comment]
I'm free at 2 if that will work.

**Comment by miaomiao-alt** [comment]
Did you say 2:00 p.m., American time? It was two o 'clock in the morning in Beijing. Would you be free in seven or eight hours, that is, at seven or eight o 'clock in the evening US time

---- Replied Message ----
| From | Joseph ***@***.***> |
| Date | 07/12/2024 23:39 |
| To | cmu-phil/tetrad ***@***.***> |
| Cc | miaomiao-alt ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [cmu-phil/tetrad] The use of Tetrad (Issue #1795) |

I'm free at 2 if that will work.

**Comment by jdramsey** [comment]
I see, sorry. I could maybe meet at 8 PM EST, would that work?

**Comment by miaomiao-alt** [comment]
OK！See you in eight hours.

---- Replied Message ----
| From | Joseph ***@***.***> |
| Date | 07/13/2024 00:14 |
| To | cmu-phil/tetrad ***@***.***> |
| Cc | miaomiao-alt ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [cmu-phil/tetrad] The use of Tetrad (Issue #1795) |

I see, sorry. I could maybe meet at 8 PM EST, would that work?

**Comment by jdramsey** [comment]
@miaomiao-alt Can I close this issue?
