### ISSUE TITLE
DG is broken

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1796]
I broke it when I refactored it to wrap sembic so I will fix it... this is a note to myself so I don't forget.

The local score call is incorrect, it should be adding the child variables to the parent set after each regression.

**Comment by jdramsey** [comment]
Thanks :)

**Comment by bja43** [comment]
@jdramsey, I think this was fixed, right?

**Comment by jdramsey** [comment]
You fixed it, yeah, so it's fixed in my branch. The public build is a fair bit behind my branch though--did you need me to publish? I need do some work on that at some poitn anyway...

**Comment by jdramsey** [comment]
Fixed.
