### ISSUE TITLE
Ive been told test-wise deletion is broken

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1797]
Ive been told this but I have not verified it myself. I will comment on this issue after verifying it.

**Comment by jdramsey** [comment]
@bja43 I just did some fixes to testwise deletion for some tests and scores in my local branch and will post those the next time I update Tetrad. Sorry for the delay; I had to experience it for myself.

**Comment by jdramsey** [comment]
In particular, for sem bic score and fisher z test (and I think DG) I got rid of the row subsetting and just do the testwise deletion in the operation of those score/tests from whatever rows the user sets.

**Comment by jdramsey** [comment]
Closing.
