### ISSUE TITLE
Model goodness of fit

### ISSUE THREAD

**Issue by miaomiao-alt** [cmu-phil/tetrad#1815]
This is the result of my model, and I want to know how well does this model fit? Thank you!
![image](https://github.com/user-attachments/assets/644ebaef-dc12-4f0c-b21a-6fb3bc70fe0c)

**Comment by miaomiao-alt** [comment]
The following is my understanding: for this model, whether the chi-square value is the primary criterion for evaluation, and the rest are auxiliary. If the chi-square value is too large, even if other fitting indicators perform better, it cannot be said that the model has a good fit. Is that right?

**Comment by cg09** [comment]
They are all standard statistical measures of agreement between a sample
empirical distribution and an assumption about the family of distributions
from which the sample is drawn. No such measure has any guarantee of
anything about a finite sample. There best use is comparative, not between
these measures but for any particular measure used to compare alternative
hypotheses. Take your choice.

**Comment by miaomiao-alt** [comment]
Could you recommend some relevant literature？

**Comment by cg09** [comment]
The literature is vast and, about fundamentals, not very helpful. Google
scholar is your friend, as is Wikipedia. Go to ChatGPT for a start.

The basic problem is that you are trying to guess an infinite property from
a finite sample. That is the basic problem in most statistical inference.
However good the BIC score or p value for a hypothesis test, there is no
logical guarantee that the results will not be different, or even reversed
in model comparison, in a new, larger sample from the same population. The
only logical guarantees that statistic provides are in the infinite
limit...where you will never be.

**Comment by miaomiao-alt** [comment]
OK！Thank you so much!



At 2024-09-02 08:49:18, "cg09" ***@***.***> wrote:

The literature is vast and, about fundamentals, not very helpful. Google
scholar is your friend, as is Wikipedia. Go to ChatGPT for a start.

The basic problem is that you are trying to guess an infinite property from
a finite sample. That is the basic problem in most statistical inference.
However good the BIC score or p value for a hypothesis test, there is no
logical guarantee that the results will not be different, or even reversed
in model comparison, in a new, larger sample from the same population. The
only logical guarantees that statistic provides are in the infinite
limit...where you will never be.

**Comment by jdramsey** [comment]
Hey @miaomiao-alt ...is this issue done? Can I close it?
