### ISSUE TITLE
Request: Add a lognormal distribution

### ISSUE THREAD

**Issue by atyahoodotcom** [cmu-phil/tetrad#205]
Hello,

Would you be able to add a lognormal option as an option for the error distributions?

**Comment by jdramsey** [comment]
Thanks for reminding me.

On Mon, Jun 13, 2016 at 2:05 PM, atyahoodotcom <notifications@github.com>
wrote:

> Hello,
>
> Would you be able to add a lognormal option as an option for the error
> distributions?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/205>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR2fY-MOZhXlM8ijhs8cjUKhyk77kks5qLZvbgaJpZM4I0lju>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I put it there. It's in the 'experimental' branch at the moment. when I get done with this round of improvements I'll push it to 'development'.
