### ISSUE TITLE
Loading a knowledge file takes forever and you may run out of RAM.

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#207]
Loading a knowledge file in tetrad takes over two minutes to load.  This was tested with the cancer group's mini breast cancer dataset.

**Comment by jdramsey** [comment]
Ouch. How big was the file?

On Tue, Jun 14, 2016 at 6:07 PM, Jeremy Espino <notifications@github.com>
wrote:

> Loading a knowledge file in tetrad takes over two minutes to load. This
> was tested with the cancer group's mini breast cancer dataset.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/207>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR4Xx9_wh85I6s2xtTipGMzCm_ZXkks5qLyYygaJpZM4I1z7s>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Jeremy, could you give me more details about that file that would not load?

**Comment by jdramsey** [comment]
I'm going to close this because I don't know how to test it; re-open if more information comes to light.
