### ISSUE TITLE
In windows, data loading log does not display

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#208]
The data loads (load then save) but the log does not show.

**Comment by jdramsey** [comment]
Thanks.

On Wed, Jun 15, 2016 at 9:11 AM, Jeremy Espino <notifications@github.com>
wrote:

> The data loads (load then save) but the log does not show.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/208>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR4GF0CQTd80sTj6L03V9qkimameAks5qL_oUgaJpZM4I2Vv8>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
This is a puzzle to me. It's not doing anything different.

**Comment by jdramsey** [comment]
This has been fixed in the new GUI.
