### ISSUE TITLE
Variables in regression don't update when changed in graph

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#209]
Reproduce by:
1) use "Simulate Data from LM" template 
2) create a graph, parametric model, and instantiated model
3) open the regression and check the variable name
4) go back to the graph and change a variable name and execute changes
5) variable names will correctly change in all boxes except for regression

**Comment by jdramsey** [comment]
Wow, I never thought to check that! I'll mull it over.

Joe

On Wed, Jun 15, 2016 at 11:05 AM, Bryan Andrews <notifications@github.com>
wrote:

> Reproduce by:
> 1) use "Simulate Data from LM" template
> 2) create a graph, parametric model, and instantiated model
> 3) open the regression and check the variable name
> 4) go back to the graph and change a variable name and execute changes
> 5) variable names will correctly change in all boxes except for regression
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/209>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR8iMWJqo68VJPVg5VC8MsQrVMmeMks5qMBS4gaJpZM4I2dS_>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I think I need to remove global memory of variable names here as with knowledge.

**Comment by jdramsey** [comment]
Yay, fixed! :) OK, it's fixed in the 'experimental branch. There are many more fixes I need to make before I can push this to 'development' or publish it. Working on it though.
