### ISSUE TITLE
Not all variables appear in 'not in tier' box in knowledge box

### ISSUE THREAD

**Issue by jitskeVs** [cmu-phil/tetrad#213]
From the 9 variables in my data box, only 5 appeared in the 'not-in-tier-box' in the knowledge box.
This occurs whether the parent box is a data box or a graph box based on the data box. 
All variables appear in the 'other groups'.
I was able to reproduce this event with 2 different data sets. According to Lizzy this was a bug. Tetrad version used was 5.3.0.

**Comment by jdramsey** [comment]
This I'm going to try to fix now by removing global memory of variables in the knowledge box.

**Comment by jdramsey** [comment]
This seems to be fixed now. I encapsulated the knowledge objects better. If there are still problems, please reopen the issue. This is in the 'experimental' branch; once the current round of fixes and improvements is done I'll push to 'development' and re-post.

**Comment by jitskeVs** [comment]
Thank you Joe,
I will be on vacation to Denver CO as of this afternoon, but when I come
back I will certainly test it.
Jitske

2016-08-18 17:40 GMT-04:00 Joseph Ramsey <notifications@github.com>:
