### ISSUE TITLE
Tetrad gui on Windows 10

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#214]
several short course participants noted that the tetrad gui does not render well on Windows 10, JDK 1.8, as the icons all come out too small.  Seems that this is a known issue with the JDK/Win 10 combination:

https://bugs.openjdk.java.net/browse/JDK-8080153.

Noted here for completeness. 

I found a repo where someone adjusted eclipse to work around this, essentially by doubling the size of the icons: https://github.com/davidglevy/eclipse-icon-enlarger

Would an approach like this provide a useful workaround?

**Comment by jdramsey** [comment]
I think this would make the icons on Mac too big. Maybe there's a way to tell if it's Windows; I haven't thought about that for a long time. Probably Google will tell me.

**Comment by harryhoch** [comment]
I don't think this is something that you will likely to be able to address appropriately. hopefully someone will fix jdk for win 10.

**Comment by jdramsey** [comment]
Fixed.
