### ISSUE TITLE
Tetrad tracker that notifies user of latest version

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#221]

**Comment by jdramsey** [comment]
Cool.

On Wed, Jun 22, 2016 at 1:57 PM, Jeremy Espino <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/221>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR2xBcSEKXG7mrnRQUlGTfuVmPlAsks5qOXeQgaJpZM4I8DU8>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by espinoj** [comment]
Done - at least first version!
