### ISSUE TITLE
include “pc”, "cpc", "fci", "cfci", "ccd", "bayes_est", "randomDag"

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#226]

**Comment by espinoj** [comment]
the command line should a require a switch called --enable-non-big-data if they want to use these algorithms

**Comment by jdramsey** [comment]
Not sure cfci should be added quite yet. I'll check that out. It was throwing nail-on-chalkboard type exceptions. Not sure what about bayes_est or randomDag. Probably the randomDag guys can be substituted with the RandomGraph implementations I just made int he algcomparison/graph package.

**Comment by jdramsey** [comment]
I will check out cfci now. That's been bugging me for a while.

**Comment by chirayukong** [comment]
Joe,

How about Fofc?

Kong

**Comment by jdramsey** [comment]
You mean add a wrapper for that? I thought about it but wasn't quite sure how to do it, since it outputs clusters, not graphs. I'll think for a while though.

**Comment by jdramsey** [comment]
Except for fofc, which puzzles me still, all of these can be included; I just have to finish making wrappers for all fo them. Maybe FOFC too; I just have to think about it.

**Comment by jdramsey** [comment]
The following are now included in the Tetrad interface in the 'experimental' branch: “pc”, "cpc", "fci", "cfci", "ccd".

**Comment by jdramsey** [comment]
I just made wrappers for FOFC, FTFC, BPC, so those can be added now. Kong asked.

**Comment by jdramsey** [comment]
I think this is a duplicate issue, though I'm not sure.

**Comment by jdramsey** [comment]
This is done.
