### ISSUE TITLE
edge set names

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#230]
json serialization does not include a name for the edge set.

**Comment by jdramsey** [comment]
Harry, is this a comment for me? I'm not sure what to do. -Joe

**Comment by harryhoch** [comment]
No, I think this is for @espinoj

**Comment by espinoj** [comment]
Will fix.

**Comment by jdramsey** [comment]
This is fixed, right?

**Comment by espinoj** [comment]
This is fixed with commmit a826d2ea36e505774e87ca8235f0f10ab47dc349
