### ISSUE TITLE
Number of Columns and Rows Reversed In Causal-cmd Log

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#252]
The counts for number of rows and columns are reversed in log file.

```java
fmt.format("cases read in = %s%n", dataSet.getNumColumns());
fmt.format("variables read in = %s%n", dataSet.getNumRows());
```

**Comment by jdramsey** [comment]
Kevin, is this fixed?

**Comment by kvb2univpitt** [comment]
Joe, not yet.  I was planning on fixing this later.  Do you need me to fix this soon?

**Comment by kvb2univpitt** [comment]
Fixed.

**Comment by jdramsey** [comment]
Thanks! Sorry so slow--got involved in a project.
