### ISSUE TITLE
Travis Build fails on Ubuntu Precise

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#296]
errant unit test is:

testNongaussianSums5(edu.cmu.tetrad.test.TestStatUtils)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0.6> but was:<0.7>

**Comment by espinoj** [comment]
on my mac:
Running edu.cmu.tetrad.test.TestStatUtils
s: 0.372805 a1: 0.345030 a2: 0.600877 a3: 0.555072
Failed on trial: 1, samplesize: 10
s: 0.765459 a1: 0.342065 a2: 0.300987 a3: 0.584844
Failed on trial: 3, samplesize: 10
s: 0.432533 a1: 0.606616 a2: 0.569326 a3: 0.253427
Failed on trial: 4, samplesize: 10
s: 0.445499 a1: 0.297765 a2: 0.159829 a3: 0.967561
Failed on trial: 6, samplesize: 10
s: 0.445884 a1: 0.274073 a2: 0.166856 a3: 0.307519
Failed on trial: 7, samplesize: 10
s: 0.624798 a1: 0.261950 a2: 0.318126 a3: 0.763806
Failed on trial: 9, samplesize: 10

on travis:

Running edu.cmu.tetrad.test.TestStatUtils
s: 0.540009 a1: 0.525384 a2: 0.795427 a3: 0.748056
Failed on trial: 1, samplesize: 10
s: 0.765459 a1: 0.342065 a2: 0.300987 a3: 0.584844
Failed on trial: 3, samplesize: 10
s: 0.432533 a1: 0.606616 a2: 0.569326 a3: 0.253427
Failed on trial: 4, samplesize: 10
s: 0.623914 a1: 0.576415 a2: 0.481360 a3: 0.334181
Failed on trial: 5, samplesize: 10
s: 0.445499 a1: 0.297765 a2: 0.159829 a3: 0.967561
Failed on trial: 6, samplesize: 10
s: 1.468345 a1: 0.993009 a2: 0.448019 a3: 1.162455
Failed on trial: 7, samplesize: 10
s: 0.308412 a1: 0.399247 a2: 0.372793 a3: 0.276779
Failed on trial: 9, samplesize: 10

**Comment by jdramsey** [comment]
I think this is fixed, right? Travis is playing nicely now for me. Or does it still fail on Precise?
