### ISSUE TITLE
gui - incomplete models

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#314]
Not sure if this is a bug or not, but if you create a Bayes PM and then manually instantiate it, search (for PC at least) will happily execute even if the IM is incompletely specified.

**Comment by jdramsey** [comment]
That's a bug. I think it's secretly making a random Bayes IM. I think I know why.

**Comment by jdramsey** [comment]
Fixed. I'll push it later this morning.

**Comment by jdramsey** [comment]
OK pushed.
