### ISSUE TITLE
Bugs with IndTestTimeSeries.java and IndTestKciMatlab

### ISSUE THREAD

**Issue by dachylong** [cmu-phil/tetrad#330]
I tried conditional independence test by IndTestTimeSeries for time series variables and IndTestKciMatlab for nonlinear independence test. It seems they do not work normally. Errors pop up. Maybe they are mathematically too difficult for me, can anyone fix them~

**Comment by jdramsey** [comment]
These need to be deprecated; we no longer have anyone who can work on them, sorry.
