### ISSUE TITLE
PC-lingam [help wated]

### ISSUE THREAD

**Issue by alicia2801** [cmu-phil/tetrad#344]
Hello, 
I'm trying to obtain the markov blanket for a dataset as well as the SEM. I thought the right way to do it is to load  my covariance data into a data wrapper, connect it to a search method, then graph manipulation to get the markov blanket as well as the PM and the estimator. However, i need to use the PC-Lingam algorythm for the search method and it is there where it seems to block, i don't really understand why. 
If i connect the data-wrapper to the search it says that there is only one model you can build at this point and that my parents are not permissible. However data wrapper is a permissible parent for   PC-lingam. If i put in between the data and search a DAG graph box, and specify a secific graph or i give some knowledge i get the error that a pattern must be specified. The problem is not with my data though because i've tried with tabular and covariance example you give and the error still the same. I don't know what i'm doing wrong...
Thank you a lot, 
Alicia

**Comment by jdramsey** [comment]
PC-Lingam is not in the current interface; we were having problems with it. When I get a chance I'll try to add it back in, though it's not a priority for us at the moment. I'm going to close this for now, but I'll keep it in mind.

@espinoj
