### ISSUE TITLE
How to read a .tet file

### ISSUE THREAD

**Issue by sndmrc** [cmu-phil/tetrad#350]
Hi. I am trying to read a .tet file of Tetrad using R or Python.
Where can I find documentation/information about the format of these files ?
Any help will be greatly appreciated.
Thank you for your attention.
Marco

**Comment by jdramsey** [comment]
Sorry, I didn't see this. Unfortunately, tet files are binary traces of the state of the object tree as stored in the GUI; there is no fixed format.
