### ISSUE TITLE
PC, CPC, CCD, FCI, CFCI, TsGFCI, FAS don't show any error unless you run Tetrad from IDE

### ISSUE THREAD

**Issue by chirayukong** [cmu-phil/tetrad#351]
I tried to run a mixture dataset on Tetrad GUI and found out that some of the algorithms can't handle it but show no sign of any error. Also, TsFCI shows a "-1" intelligible error and MBFS returns a "shape (0)" error. The dataset is from [the Kaggle Allstates competition](https://www.kaggle.com/c/allstate-claims-severity/download/train.csv.zip).

**Comment by jdramsey** [comment]
@chirayukong I can't seem to download this file; I click download but the file does not appear on my computer. Can you send me the file somehow, dropbox google drive box?

**Comment by jdramsey** [comment]
@chirayukong Actually could you rerun your test using the current API with the mixture data loader?

**Comment by jdramsey** [comment]
@chirayukong This old issue--is this still a problem, in, say, pcausal? If not can we close it?

**Comment by chirayukong** [comment]
Yep. We can close this issue. It was fixed. The pycausal will support in the lagged dataset in the next minor change version. In this point, they can call a jar file directly, manually create a pior knowledge and call the time-series search algorithm.

**Comment by jdramsey** [comment]
Yay! @chirayukong
