### ISSUE TITLE
Updating Tetrad README docs

### ISSUE THREAD

**Issue by yuanzhou** [cmu-phil/tetrad#352]
Can anyone update the README file to reflect the current state of the code structure as well those modules? I'm trying to contribute to the `tetrad-gui` and found out that the main README is outdated. Also adding some instructions to each module will be super helpful.

**Comment by jdramsey** [comment]
Did a quick edit of the README file. Not sure what else was requested. I didn't see any other README's so I wasn't sure what was being referred to. Were these in causal-command or other projects?

@yuanzhou 
@espinoj

**Comment by espinoj** [comment]
Joe addressed
