### ISSUE TITLE
usage clarifications for causal-cmd

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#357]
When I run the causal cmd without any arguments, I don't see all of the usage details. Is it possible to change he default usage code to indicate that "--algorithm xxx" should be specified for usage details on algorithm xxx?

Also, Can we change the --json message to clearly indicate that this will be json output suitable for cytoscape? Even if we don't change this in the usage info, it should be on the docs page.

**Comment by jdramsey** [comment]
@harryhoch Did anyone ever follow up on this? Is it on the right issues list? Can I close it?

**Comment by harryhoch** [comment]
I think this is fine, and yes, will put under causal-cmd in the future.

**Comment by espinoj** [comment]
now is https://github.com/bd2kccd/causal-cmd/issues/22
