### ISSUE TITLE
tiers of variables reverse order upon save in Tetrad GUI

### ISSUE THREAD

**Issue by kingfish777** [cmu-phil/tetrad#358]
**Issue:** Tiers of variables reverse order upon save in Tetrad GUI
**To recreate bug:** Create tier 0 and tier 1 from variables in data. hit save. return or go to search, and vars in either tier have been switched.

**Comment by rubencmu** [comment]
Can you be more specific about the exact pipeline you are following in Tetrad, so I can exactly reproduce the error. 
I tried right now using the knowledge tiers and I am not having the problem you are describing.

Thanks.

**Comment by rubencmu** [comment]
Also, what branch are you compiling the Tetrad GUI from ?

**Comment by kingfish777** [comment]
https://github.com/cmu-phil/tetrad/

**Comment by rubencmu** [comment]
Hi,
I keep trying different used of knowledge tiers and I cannot see the error. I need a more detailed description of how you are running your pipeline to be able to reproduce your error. If you share the .tet file, that would be perfect.

**Comment by kingfish777** [comment]
Wait, wait, it was late at night last night when it happened and it was my first day with IntelliJ-IDEA, freshly compiled on my laptop (after having been more focused on the r-causal API for quite some time). I was looking at the orientation of edges in the "Edges" tab in Knowledge. I misunderstood what was going on with the greyed out edges from my outcome variable to the predictor features. You may close this issue.

**Comment by kingfish777** [comment]
On another note, I am interested, however, in putting using the Java API to put together a pipeline to go from integrating prior/background knowledge in the form of deterministic directed edges, building a preliminary DAG (from FGS, deleting undirected edges), feeding these into a parameterized model and then instantiating it (this would be run in batch mode). Would you happen to have any idea where I could find some pointers on this / starter code examples?

**Comment by rubencmu** [comment]
I am not aware of any example for such task. But you can check the Javadocs for the API here http://cmu-phil.github.io/tetrad/tetrad-lib-apidocs/
You can also check out the command line version of Tetrad 
http://www.ccd.pitt.edu/wiki/index.php?title=Documentation_on_using_the_causal-cmd_software

I think this can give you a starting point for what you are looking for.

**Comment by kingfish777** [comment]
One more question - what do the values mean that directly follow after target nodes? (see below)


2. INSERT medication --> rheumatoid_arthritis [] 262523.66133668274  degree = 2 indegree = 0
3. INSERT hepatic_encephalopathy --> ascites [] 258924.16553162783  degree = 2 indegree = 0
4. INSERT ascites --> splenomegaly [] 40063.7172059454  degree = 2 indegree = 0
5. INSERT psoriasis --> medication [rheumatoid_arthritis] 15530.16499081999  degree = 3 indegree = 1
--- Directing rheumatoid_arthritis --> medication
6. INSERT ascites --> ade [] 8707.630693046376  degree = 3 indegree = 2
7. INSERT hepatic_encephalopathy --> hyperammonemia [] 6152.540932174772  degree = 3 indegree = 2
8. INSERT medication --> polyarthritis [] 5008.711377006024  degree = 4 indegree = 2
9. INSERT medication --> osteosarcoma [] 4761.698256734759  degree = 5 indegree = 2
10. INSERT splenomegaly --> ade [] 2539.178536457941  degree = 5 indegree = 2
11. INSERT medication --> pericarditis [] 1824.3152478560805  degree = 6 indegree = 2
12. INSERT hypercholesterolemia --> ade [] 1606.2038657236844  degree = 6 indegree = 2
13. INSERT hepatic_encephalopathy --> ade [] 1265.3980004228652  degree = 6 indegree = 2
14. INSERT respiratory_insufficiency --> hypoxemia [] 1207.1430989541113  degree = 6 indegree = 2
15. INSERT splenomegaly --> hepatic_encephalopathy [] 888.8794419206679  degree = 6 indegree = 2
16. INSERT acute_heart_failure --> hypoxemia [respiratory_insufficiency] 781.8719430491328  degree = 6 indegree = 2
--- Directing respiratory_insufficiency --> hypoxemia
17. INSERT disease --> ade [] 644.1266106627882  degree = 6 indegree = 6
18. INSERT rheumatoid_arthritis --> ulcerative_colitis [] 570.4134209156036  degree = 6 indegree = 6
19. INSERT psoriasis --> inflammation [] 491.85745634138584  degree = 6 indegree = 6
20. INSERT rheumatoid_arthritis --> pericarditis [] 458.5230525061488  degree = 6 indegree = 6
21. INSERT osteosarcoma --> ulcerative_colitis [rheumatoid_arthritis] 401.7511342763901  degree = 6 indegree = 6
--- Directing rheumatoid_arthritis --> ulcerative_colitis
22. INSERT hypercholesterolemia --> psoriasis [inflammation] 383.0571994371712  degree = 6 indegree = 6
--- Directing inflammation --> psoriasis
23. INSERT ascites --> rheumatoid_arthritis [] 375.89357255771756  degree = 6 indegree = 6
24. INSERT pericarditis --> polyarthritis [] 373.9368289373815  degree = 6 indegree = 6
25. INSERT ulcerative_colitis --> hypoxemia [] 366.9154625236988  degree = 6 indegree = 6
26. INSERT psoriasis --> ade [] 349.2376753631979  degree = 7 indegree = 7
27. INSERT psoriasis --> hypoxemia [] 343.80124907568097  degree = 7 indegree = 7
28. INSERT ulcerative_colitis --> ade [] 328.4911553841084  degree = 8 indegree = 8
29. INSERT psoriasis --> ulcerative_colitis [] 326.51935559883714  degree = 8 indegree = 8
30. INSERT rheumatoid_arthritis --> osteosarcoma [] 260.8312044478953  degree = 8 indegree = 8
31. INSERT inflammation --> ulcerative_colitis [] 247.70622038468719  degree = 8 indegree = 8
32. INSERT pericarditis --> ade [] 238.40872817486525  degree = 9 indegree = 9
33. INSERT rheumatoid_arthritis --> hypoxemia [] 222.31345016509295  degree = 9 indegree = 9
34. INSERT rheumatoid_arthritis --> ade [] 220.332719611004  degree = 10 indegree = 10
35. INSERT hypoxemia --> disease [] 208.97733283415437  degree = 10 indegree = 10
36. INSERT inflammation --> inflammatory_response [] 190.94316716119647  degree = 10 indegree = 10
37. INSERT acute_heart_failure --> rheumatoid_arthritis [] 185.84307184815407  degree = 10 indegree = 10
38. INSERT rheumatoid_arthritis --> polyarthritis [] 181.6279854811728  degree = 10 indegree = 10
39. INSERT psoriasis --> pericarditis [] 173.23090906068683  degree = 10 indegree = 10
40. INSERT inflammation --> pericarditis [] 149.29198768734932  degree = 10 indegree = 10
41. INSERT medication --> disease [] 149.15549637377262  degree = 10 indegree = 10
42. INSERT hyperammonemia --> rheumatoid_arthritis [ascites] 142.1224331073463  degree = 10 indegree = 10
--- Directing ascites --> rheumatoid_arthritis
43. INSERT hypercholesterolemia --> disease [] 132.48846946284175  degree = 10 indegree = 10
44. INSERT splenomegaly --> pericarditis [] 127.69207548722625  degree = 10 indegree = 10
45. INSERT psoriasis --> rheumatoid_arthritis [] 124.07895673811436  degree = 11 indegree = 3
46. INSERT hyperammonemia --> ade [] 84.32646716013551  degree = 11 indegree = 11
47. INSERT medication --> vasospasm [] 75.6643046811223  degree = 11 indegree = 11
48. INSERT splenomegaly --> polyarthritis [] 70.66079630702734  degree = 11 indegree = 11
49. INSERT bilateral_disease --> ulcerative_colitis [] 66.82989877834916  degree = 11 indegree = 11
50. INSERT inflammation --> rheumatoid_arthritis [] 49.016874723136425  degree = 12 indegree = 3
51. INSERT splenomegaly --> acute_heart_failure [] 44.33851692825556  degree = 12 indegree = 3
52. INSERT inflammation --> medication [] 39.561936903744936  degree = 12 indegree = 4
53. INSERT splenomegaly --> medication [] 30.62551511824131  degree = 12 indegree = 5
54. INSERT medication --> ulcerative_colitis [] 20.684937115758657  degree = 12 indegree = 4
55. INSERT hypercholesterolemia --> splenomegaly [hepatic_encephalopathy, ascites] 13.315992962568998  degree = 12 indegree = 4
--- Directing hepatic_encephalopathy --> splenomegaly
--- Directing ascites --> splenomegaly
56. INSERT inflammation --> ascites [hepatic_encephalopathy] 9.962603814899921  degree = 12 indegree = 4
--- Directing hepatic_encephalopathy --> ascites

**Comment by rubencmu** [comment]
The FGS algorithm performs its search by adding edges in a first step and then removing edges in a second step. In order for an edge to be added ("inserted" into the graph), the presence of that edge has to minimize the BIC score of the graph being build.
So, the value following the target nodes is the BIC score after inserting such edge in the graph. As you can see, the BIC score is smaller at each step. In the first insertion, it is 262523.66, in the 56 insertion it is 9.96. The smaller the BIC score the better the model fits the data.

Also, regarding your previous question about tiers. I understood where you confusion arise. In the knowledge tab, if you first define the tiers, and then see the edges, what you are seeing in grey arrows are the "edges FORBIDDEN by the tiers". So, if in your tiers definition you set  Tier1 = X1, Tier2 = X2, this imply that you expect X1 -> X2. But in the edge tab you would see in grey arrow  X2 <- X1, which is the "edge FORBIDDEN by the tiers".

**Comment by kingfish777** [comment]
Exactly. With the greyed out edges, and it being rather late at night and without adjusting the resolution on my 4K screen laptop, it appeared to be troublesome!
On the previous point, to confirm, I take it that that the BIC score (analogous to AIC, Aikake inf criterion) is for the whole model. BICs (which put preference on parsimonious models) can be useful for deciding between models of the same category, where search is an optimization function to minimize BIC (thereby maximizing fit).

**Comment by rubencmu** [comment]
If you are going to use FGS in your research, I recommend you read:
http://www.jmlr.org/papers/volume3/chickering02b/chickering02b.pdf
Which describes the original GES algorithm. 
And:
http://rdcu.be/ncoC
Which describe the FGS implementation.

**Comment by kingfish777** [comment]
Thanks! I've been steadily working through the papers, including Meeks. I shall add the million variables paper to my list! I think for me that it will be very instructive to read the source code and papers at the same time. One final quick question, is it theoretically ever permissible to convert discrete variables (binary) continuous so as to be able to create a (compact) covariance matrix? (as this speeds up i/o time if one literally has millions of observations/rows). Thanks!

**Comment by jdramsey** [comment]
You're probably already done with this, but you can use the numerical discrete to continuous data manipulation to do that conversion. Reopen the issue if you want to discuss more. Right now I'm trying to get rid of old issues. -jdramsey
