### ISSUE TITLE
Add ccd-helpdesk as member of this repository

### ISSUE THREAD

**Issue by ccd-helpdesk** [cmu-phil/tetrad#363]
Hi,

This is Ruben in behalf the CCD-helpdesk. Can you add this github user:  "ccd-helpdesk"  as members of the   cmi-phil/tetrad  repository. We just want to be notified in our gmail account about issues we can response to, for example, problems formatting data, interpretation of algorithm output, etc.

Thanks,

Ruben

**Comment by jdramsey** [comment]
Done.
