### ISSUE TITLE
Build failure due to test error

### ISSUE THREAD

**Issue by jmogarrio** [cmu-phil/tetrad#37]
Attempting to build project, while running tests will get the following error:

    Tests in error:
        test8(edu.cmu.tetrad.test.TestStandradizedSem): non symmetric matrix: the difference between entries at (1,2) and (2,1) is larger than 0

This results in build failure

**Comment by jdramsey** [comment]
It's working for me... just a sec.. I'll paste in the commands I typed..

On Sun, Nov 8, 2015 at 12:26 PM, jmogarrio <notifications@github.com> wrote:

> Attempting to build project, while running tests will get the following
> error:
>
> Tests in error:
>     test8(edu.cmu.tetrad.test.TestStandradizedSem): non symmetric matrix: the difference between entries at (1,2) and (2,1) is larger than 0
>
> This results in build failure
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/37>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I commented this test out. It's another one that depends on random values being in a certain range. Ugh.
