### ISSUE TITLE
can't export as an executable .jar file

### ISSUE THREAD

**Issue by tzcoolman** [cmu-phil/tetrad#376]
Hi Joe,

I was trying to compile my own "causal-cmd.jar" with 'CausalCmdApplication.java' as main class on eclipse. However, here is what I got when exporting to a executable jar file:

"Class files on classpath not found or not accessible for: 'tetrad-lib/src/main/java/edu/cmu/tetrad/search/SemGpScore.java'". 

Do you have any idea what might cause it? Actually there are errors when I tried to load the entire project into eclipse.

Sincerely
Enze

**Comment by jdramsey** [comment]
You may need to run mvn package first. Kevin automatically generated some
of the class files.

**Comment by tzcoolman** [comment]
Thx, I did that. Moreover I made the entire class blank and it's working now.

**Comment by jdramsey** [comment]
Nice. Hope it's working.
