### ISSUE TITLE
parameter learning for continuous data

### ISSUE THREAD

**Issue by haluk** [cmu-phil/tetrad#378]
I've a continuous data, and I was able to learn DAG from that data. I want to serialize BN in bifxml format. I was trying to perform MlBayesEstimator with the same data and learned DAG.  However, parameter learning is not working for continuous type of data. How can I discretize my data?

**Comment by ccd-helpdesk** [comment]
I know that using the TETRAD GUI you can discretize you data very easily.
Open a "Data" process box, load your data. Then connect the Data box to the "Data Manipulation" box, and in the menu choose, Discretize Dataset. It will be the first option in the menu.

In Java, you can look for the Discretizer class.
