### ISSUE TITLE
causal-cmd clarifcation

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#383]
--json                      Create JSON output.
--tetrad-graph-json         Create Tetrad Graph JSON output.

causal-cmd options for FGES are confusing. How do these two differ?

**Comment by espinoj** [comment]
One is Joe's. One is the CCD's.

**Comment by harryhoch** [comment]
ok, so I'm a user and I want to know how to output my graph in a parseable format. Which of these should I use and why?

We need to give users some guidance to help them make sense of the tools...

**Comment by espinoj** [comment]
@jdramsey Do you know if anyone is using the previous json output format from Tetrad?  In the CCD we created a new JSON document that has been also been extended to include parameters for the run by Kong.  Should it be retained or deprecated/removed?

**Comment by jdramsey** [comment]
@espinoj Sorry so late, very busy. I will swear on Andrew Jackson's grave that no one is using that json output format. It should be summarily removed! :) (Sorry, I am always so happy when things can be removed.)

**Comment by espinoj** [comment]
there is an issue in causal-cmd project to address removing 
--tetrad-graph-json Create Tetrad Graph JSON output.

https://github.com/bd2kccd/causal-cmd/issues/22

**Comment by espinoj** [comment]
Kevin investigated this today
--json Create JSON output.
Is the format Harry and I came up with

--tetrad-graph-json Create Tetrad Graph JSON output.
is the format that is a very complete serialization of tetrad graphs (including coordinates) that Kong is using for sync between Tetrad and the HPC setup

@harryhoch if you are no longer using --json to do graph database work I suggest removing --json

@kvb2univpitt

**Comment by harryhoch** [comment]
@espinoj, can we leave --json in and just hide it ? ie, remove it from the usage line?

**Comment by espinoj** [comment]
@harryhoch yes, i'll let kevin know.
@kvb2univpitt

**Comment by espinoj** [comment]
fixed in https://github.com/bd2kccd/causal-cmd/releases/tag/v0.2.1
