### ISSUE TITLE
Invalid error "The parent graph cannot be converted to a DAG."

### ISSUE THREAD

**Issue by ropeless** [cmu-phil/tetrad#402]
The issue appears in the build versions of TETRAD:
    tetrad-gui-6.0.0-launch.jar
    tetrad-gui-6.1.0-launch.jar

Do the following to demonstrate the issue:
1) Start TETRAD (GUI), there will be a blank, untitled workspace.
2) Add a graph to the workspace
3) Double click the graph and select "Graph", click OK
4) Add 2 variables, x1 and x2, and add a directed arc from x1 to x2, click Done
5) Add a parametric model to the workspace, and connect from the graph to the model.
6) Double click the model and select "Bayes Parametric Model", click OK
7) Select "Set up manually", click OK, click Done
8) Double click the graph
9) Reverse the edge connecting x1 and x2, then reverse it back again (i.e., no actual change), click Done, click Execute
11) Double click the model and select "Bayes Parametric Model", click OK
12) Select "Set up manually", click OK

Unexpected error: "The parent graph cannot be converted to a DAG."

**Comment by jdramsey** [comment]
Tricky. Typo. Had nothing to do with the arrow flip. Fixed, closing. Thanks.
