### ISSUE TITLE
Graph comparison functions missing

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#404]
In 6.0.1-0 (cloned from the development branch on April 11), when I use the comparison box on two SEM graphs (or time lag graphs) it automatically opens a Graph Intersection comparison, without giving the options for any other type of comparison. Two DAGs allows only a Graph Intersection or an Independence Facts comparison. General graphs allow all the usual options.

**Comment by jdramsey** [comment]
OK fixed this, in 'fang'. Just need to add a couple of interfaces in the right places.
