### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by kjchalup** [cmu-phil/tetrad#405]
As far as I know, most machine learning on academic level is done in Python (or, unfortunately, Matlab). I wouldn't request porting all of Tetrad to Python, but it'd be great if you had an official wrapper/API. For example, Matlab actually did a great job here: https://www.mathworks.com/help/matlab/matlab-engine-for-python.html.

**Comment by rubencmu** [comment]
@kjchalup  https://github.com/bd2kccd/py-causal
