### ISSUE TITLE
SEM PM does not accept bidirected edges

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#406]
In the Tetrad 6.0.1-0 gui (pulled from development on April 11) the SEM PM box will not open when a graph with a bidirected edge is used as input. The following error message appears: "Attempt to set a label on a model edge that's not in the editor: X3 <-> X2."

After closing the error message, the box opens as normal.

**Comment by jdramsey** [comment]
OK I tracked this down and fixed it, in 'fang'.
