### ISSUE TITLE
Bayes IM box will not reinitialize

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#407]
In Tetrad 6.0.1-0, pulled from development on April 11, if you leave "Pick new random values every time this Bayes IM is re-initialized" unchecked when randomly assigning probabilities, then destroy the model, it is impossible to create a new model in the box; Tetrad creates a blank error message.

**Comment by jdramsey** [comment]
Yay, spelling error! Can you spot it?

        } else if (getParams().getString("initializationMode", "manualRetain").equals("randomRatain")) {
            randomly.setSelected(true);
            randomEveryTime.setEnabled(true);
            randomEveryTime.setSelected(false);
