### ISSUE TITLE
Data Reader whitespace parser doesn't handle single space

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#426]
The new data loader works well - but it doesn't seem to handle covariance data -

Richard

**Comment by espinoj** [comment]
The bug is in the whitespace parser such that even though the delimited is a single space it isn't parsing correctly.  Workaround is to manually select single character->space at least for Richard's datasets

@kvb2univpitt can you check

**Comment by kvb2univpitt** [comment]
Fixed.  Please give it a try now.  Remember to delete the old data-reader from your local maven repository.

**Comment by espinoj** [comment]
fixed
