### ISSUE TITLE
How can I measure program runtime?

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#43]
Hi, 

I am using "tetradcmd-5.1.0-10.jar" in Windows by making batch file to run for multiple input and output files. I am searching causal variables from my input data using FCI algorithm. 

How can I measure the program runtime?  I like to measure the program runtime for each search in each input data set, because some input data sets have very complex models.

Thank you, 
Sanghoon

**Comment by jdramsey** [comment]
If your batch file is in Java, you can do it this way, for each algorithm:
        
long time1 = System.currentTimeMillis();

// Run search      

long time2 = System.currentTimeMillis();
        
long elapsed = time2 - time1;

If your batch is in some other language, the corresponding calls should be available.

Does that help?

**Comment by biotech25** [comment]
Thank you for your answer. 

I didn't put my batch file into Java yet.  I was running my batch file in Windows command line like this. 

FOR %%i IN (0,1,2) DO java -jar tetradcmd-5.1.0-10.jar -data input%%i.txt -datatype discrete -algorithm fci -depth -1 -significance 0.01

I am going to try to run this in Java.  I will update you later.  Meanwhile,  I found some batch code in google to measure runtime. But, it looks complicate as you see below. 
*************************************************************************************************
@echo off
setlocal enabledelayedexpansion
cls

rem ******************  MAIN CODE SECTION
for /l %%A in (0,1,3) do (
    set STARTTIME=!TIME!

   java -jar tetradcmd-5.1.0-10.jar -data input%%A.txt -datatype discrete -algorithm fci -depth -1 -significance 0.01
	
    set ENDTIME=!TIME!
    call :GetDuration !STARTTIME! !ENDTIME!
)

rem ******************  END MAIN CODE SECTION
exit /b

s:GetDuration
set function_starttime=%1
set function_endtime=%2

rem Change formatting for the start and end times
for /F "tokens=1-4 delims=:.," %%a in ("%function_starttime%") do (
   set /A "start=(((%%a*60)+1%%b %% 100)*60+1%%c %% 100)*100+1%%d %% 100"
)

for /F "tokens=1-4 delims=:.," %%a in ("%function_endtime%") do (
   set /A "end=(((%%a*60)+1%%b %% 100)*60+1%%c %% 100)*100+1%%d %% 100"
)

rem Calculate the elapsed time by subtracting values
set /A elapsed=end-start

rem Format the results for output
set /A hh=elapsed/(60*60*100), rest=elapsed%%(60*60*100), mm=rest/(60*100), rest%%=60*100, ss=rest/100, cc=rest%%100
if %hh% lss 10 set hh=0%hh%
if %mm% lss 10 set mm=0%mm%
if %ss% lss 10 set ss=0%ss%
if %cc% lss 10 set cc=0%cc%

set DURATION=%hh%:%mm%:%ss%.%cc%

echo Start    : %function_starttime%
echo Finish   : %function_endtime%
echo          ---------------
echo Duration : %DURATION%
echo.

**Comment by jdramsey** [comment]
You're right that's complicated, though in its defense it's calculating out hours, minutes, seconds, etc. I still think it's simpler in Java, but if it works...

**Comment by jdramsey** [comment]
I'm closing this for now to give myself the illusion of progress. Freel free to repopen it later
