### ISSUE TITLE
Not an edge in this model EX2 -> X2

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#442]
Create a pipeline of Graph -> PM -> IM 
Create the following graph  (use Sem graph) using X1 -> X2, X2 -> X3, X2 -> X4
Double click PM (use Sem)  Param Model)
Double clock IM (use Standardize Sem)
!  Not an edge in this model EX2 -> X2

This doesn't happen if use general graph or SEM instantiated model

**Comment by jdramsey** [comment]
I'll do this.

**Comment by jdramsey** [comment]
This is fixed. https://github.com/cmu-phil/tetrad/pull/452

**Comment by jdramsey** [comment]
Closing.
