### ISSUE TITLE
Tetrad doesn't copy covariance matrix into memory per spec

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#443]
There are excess tabs and row ids in the copied covariance matrix

**Comment by kvb2univpitt** [comment]
I got rid of the extra space at the end of the line.  How did you export a covariance matrix with variable name in the first column of the data row?  I couldn't replicate that.

**Comment by jdramsey** [comment]
Are you copying using control-C in the data editor?

**Comment by espinoj** [comment]
The copy/paste version of the matrix has the extra tabs - leaving that alone.  But the saved version also has extra space so Kevin has fixed that in

https://github.com/cmu-phil/tetrad/pull/454/commits
