### ISSUE TITLE
Pipeline error

### ISSUE THREAD

**Issue by scheines** [cmu-phil/tetrad#445]
The "Search and then estimate" pipeline creates a data, search, graph, pm and estimator, which is fine.  But it adds an arrow from the data box to the PM box, which is wrong.

**Comment by jdramsey** [comment]
This is not an error. For the discrete case, this serves as a way to get the variables with their categories into the PM box.

**Comment by jdramsey** [comment]
Closing, not a bug. Reopen if you want to do something different, although you still have to solve the same problem.
