### ISSUE TITLE
Simulate doesn't use displayed settings after destroy

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#458]
Make a graph - regular Graph	
Simulate from graph - using SEM
Destroy Simulation Model
Simulate from graph again
! even though SEM is still selected in Simulate interface it performs a BN simulation i.e., discrete

In the display - even though SEM is selected, the BN simulation parameters are seen

**Comment by jdramsey** [comment]
I guess I thought "destroy" meant to forget everything. Do we not want "destroy" to be an option?

**Comment by jdramsey** [comment]
Need to coordinate on this one--I need to refactor this code.

**Comment by jdramsey** [comment]
@espinoj This is fixed!!!!!!!!! :)
