### ISSUE TITLE
instantiate data sets and save them in command line method?

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#46]
Hi, 

This question was asked in the Goggle group, but it was not asnwered. 

In TETRAD, I used the template, "Simulate data from IM" and instantiated 100 data sets in the IM box.  I know that I can save the data sets to .txt file in the Data box.  But, I don't want to save the 100 data set files manually.  

Is there command line method that I generate/instantiate data sets like I did in IM box, and save the data sets?  I think using command line to simulate and instantiate data sets will be very complicated because it will be difficult in command line to set 'Graph type', such as which variable is direct and which variable is target, and to set 'Parametric model' giving probabilities for each variable in every condition,  Therefore, I was curious if there is command line method at least to save data sets automatically after I instantiated 100 or 1000 data sets in TETRAD workspace. (But, also I thought that there would be no method to extract the instantiated data sets from TETRAD in order to save the data sets using command line methods).  I like to know if there is command line method to save the instantiated data sets.  

Thank you,
Sanghoon

**Comment by jdramsey** [comment]
There is not. It's a good idea, though. If I weren't slammed with work
right now, I'd just do it. But hopefully, I can do it shortly.

On Wed, Nov 11, 2015 at 1:33 PM, biotech25 <notifications@github.com> wrote:

> Hi,
>
> This question was asked in the Goggle group, but it was not asnwered.
>
> In TETRAD, I used the template, "Simulate data from IM" and instantiated
> 100 data sets in the IM box. I know that I can save the data sets to .txt
> file in the Data box. But, I don't want to save the 100 data set files
> manually.
>
> Is there command line method that I generate/instantiate data sets like I
> did in IM box, and save the data sets? I think using command line to
> simulate and instantiate data sets will be very complicated because it will
> be difficult in command line to set 'Graph type', such as which variable is
> direct and which variable is target, and to set 'Parametric model' giving
> probabilities for each variable in every condition, Therefore, I was
> curious if there is command line method at least to save data sets
> automatically after I instantiated 100 or 1000 data sets in TETRAD
> workspace. (But, also I thought that there would be no method to extract
> the instantiated data sets from TETRAD in order to save the data sets using
> command line methods). I like to know if there is command line method to
> save the instantiated data sets.
>
> Thank you,
> Sanghoon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/46>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by biotech25** [comment]
Thank you for your answer. I am going to think more about it, too.  

Sanghoon

**Comment by jdramsey** [comment]
I don't think having a command line method to save the data sets after they've been created in the interface makes sense, but maybe a method to save all of the data sets you've created in the data box would make sense. That's something that could be done "relatively" quickly and would be useful I think. What do you think?

I'm thinking of a menu item in the data box, "Save All...".

**Comment by biotech25** [comment]
I agree with you. If we can have 'save all' function in the Data box, it will be great. I wonder if you can set the 'save all' function to save every data set in each separate file. If I generated 100 data sets, I would expect that I get 100 .txt files. If I can assign increment number to the file names to distinguish file names, it will be great. (I think number is the best way to distinguish 100 or 1000 file names.)    

I appreciate your help and consideration. 
Sanghoon
