### ISSUE TITLE
Can't indicate which variables are discrete/continuous in graph for simulation

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#460]
It would be goot to be able to indicate which variables in a simulation should be discrete vs. continuous.

Setup:
  Graph -> Simulation

**Comment by jdramsey** [comment]
This is a stale issue--I will wait to see if anyone wants to handle mixed cases like this in the GUI and if so I'll open up a new issue for it. It's going to be a lot of work making mixed PM's, IM's, though Kong has done preliminary work on this in a branch (that is very old and out of data now). Before launching into this effort, I need to see if there is a need for it. -JR

**Comment by cg09** [comment]
Lots of biomedical applications have mixed variable types, so year it's
important.

Clark

**Comment by jdramsey** [comment]
This is for simulation though, not analysis. We already have tools to analyze mixed data; I haven't gotten any end-user requests for an ability to simulate mixed data from particular models yet. Anyway, it's still in the wish list.
