### ISSUE TITLE
What happened to calculation of empirical bayes calculation?

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#462]
in Search module you used to be able to see things like bayes factor calculation.

**Comment by jdramsey** [comment]
@espinoj I think this was a casualty of the interface revisions. It could be put into a separate box under Comparison though; the code is still there.

**Comment by jdramsey** [comment]
Hmm.... now of course FGES outputs this at the console:

Model Score = -6584.72144338059
X4 Score = -1317.1697022611224
X1 Score = -906.9774782116037
X2 Score = -189.21162271446448
X5 Score = -249.40233831044182
X8 Score = -640.0180236400199
X3 Score = -1192.49653482074
X7 Score = -1307.00931272019
X9 Score = -1151.7162359461818
X6 Score = -1205.2605926012343
X10 Score = -1501.5691306222843

These aren't Bayes factors, but they're BIC scores, also very useful. I think one could go a long way here by just adding a model under Compare with Data or Simulation and Graph (DAG) as parents in which just this is output in a text box. Maybe you could additionally estimate the DAG as a SEM model and print out the p-value, chi square, etc.

This would be very popular.

**Comment by espinoj** [comment]
We now output BIC scores in log output and graph box dialogue when available (FGES, etc)
