### ISSUE TITLE
Bootstrapping sample size

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#463]
In addition to how many bootstraps, it would be good to have the number of bootstraps AND the bootstrapped sample size.

Also change the label from "the number of bootstrapping sample size" to "Number of Bootstraps"
The bootstrapped sample size label should be "Bootstrapped sample size" which would default to the size of the number of instances in the original dataset.

Also would be good to be able to set the seed.

Also given the number of bootstraps and sample size could we calculate how much disk space is needed?  A student with not a lot of disk space had Tetrad just not run the search but didn't know why.

**Comment by chirayukong** [comment]
Quick fix: changed the label of a number of bootstraps. The rest would do later.
