### ISSUE TITLE
maximum number of categories for discrete variable

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#466]
the data loader has a field for maximum number of categories for a discrete variable, but it looks like it only applies to mixed data sets. This should be clarified - the option should be clearly available for both discrete and mixed data sets.

**Comment by kvb2univpitt** [comment]
@harryhoch The field "maximum number of variable" should only apply to mixed data sets.  That field is used to determine which column should be treated as discrete variable.  For the discrete data, it's obvious that all columns are discrete.  Therefore, we don't need it for discrete variable.  Maybe we should come up with a better description for that field.

**Comment by harryhoch** [comment]
understood, but causal-cmd will complain about too many values for a discrete variable if the "skip category limit" flag is not set. Does tetrad skip the category limit by default?

**Comment by kvb2univpitt** [comment]
@harryhoch We are talking about two different things here.  The switch in causal-cmd is to ensure that the discrete data does not have more than 10 categories.  The max num of categories is used for determine which column is discrete. Tetrad does not have any validation to ensure that number of categories does not exceed 10.  I just talked to @jdramsey about it.  One of the suggestion was to put the validation in the independence test.

**Comment by harryhoch** [comment]
@kvb2univpitt , in that case I might be misunderstanding the switch. What if the discrete data does have more than 10 categories? What happens in causal-cmd in that case? In Tetrad?

**Comment by kvb2univpitt** [comment]
@harryhoch In that case, causal-cmd would scream at you and stop running.  If you want to ignore it and run the data any way, use the switch `--skip-category-limit`.  In Tetrad nothing happens because there's no validation for it.  Early in the project, Joe suggested we should have this kind of validation.  That's why causal-cmd has it.

**Comment by kvb2univpitt** [comment]
@harryhoch Can we close this issue?

**Comment by harryhoch** [comment]
I think so.
