### ISSUE TITLE
Problem with loading data sets

### ISSUE THREAD

**Issue by frangose** [cmu-phil/tetrad#47]
Dear Experts, 

I’m trying to load 12 text files into the data box and after I press "load all”, the loading log remains blank.  After pressing save, I see all 12 tabs but they all have the same data (subject 1’s data set, as opposed to each subject’s unique data).  I am using version 5.2.1-3 on mac.  Has anyone else experienced this? I would greatly appreciate any advice.  

Thanks, 
Eleni

**Comment by jdramsey** [comment]
I thought I fixed that. Just for sanity's sake, try the "snapshot" link on the downloads page, 

http://www.phil.cmu.edu/tetrad/current.html

Joe

**Comment by frangose** [comment]
Hi Joe, 

Thank you. The snapshot version worked --I appreciate your help! Now I'm get an error saying "Matrix is singular" when I click on the Estimator.  I'm not exactly sure what that means.

Eleni

**Comment by jdramsey** [comment]
It probably tried to invert a singular matrix (i.e. one where some column
is a linear combination of the others). You can find a discussion in any
linear algebra text. :)

On Thu, Nov 12, 2015 at 10:48 AM, frangose <notifications@github.com> wrote:

> Hi Joe,
>
> Thank you. The snapshot version worked --I appreciate your help! Now I'm
> get an error saying "Matrix is singular" when I click on the Estimator. I'm
> not exactly sure what that means.
>
> Eleni
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/47#issuecomment-156144917>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by frangose** [comment]
Ok, I'll look that up.  Thanks again!

**Comment by jdramsey** [comment]
Hold on I just responded to you somewhere else--I think it was another issue--was that that same problem?

**Comment by Shreeja7Sheth** [comment]
yes its solved thanks. I had downloaded just jre instead of a jdk and that's why it was not working. Thanks it works now.
