### ISSUE TITLE
Load Empty Data File

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#470]
Tetrad should not allow user to load data file that are empty.  Tetrad freezes when trying to load empty data file.

**Comment by yuanzhou** [comment]
@kvb2univpitt  I tested with an empty file and I could load it into the data loader and the validation result page. How can I reproduce the hanging?

![capture](https://user-images.githubusercontent.com/195873/27288359-828460c2-54d4-11e7-823a-73686ff5cf06.PNG)
![capture2](https://user-images.githubusercontent.com/195873/27288363-83a97dac-54d4-11e7-8649-ce5c367c0217.PNG)

**Comment by yuanzhou** [comment]
Nvm, I noticed the hanging after clicking "Load" button. Fixing it now.

**Comment by yuanzhou** [comment]
Just fixed. Users won't be able to load the empty data file and the validation will notify this as well.

![capture](https://user-images.githubusercontent.com/195873/27291701-099225e0-54df-11e7-98ac-fc99891c3da6.PNG)
