### ISSUE TITLE
Blocking "executing" dialogs prevents you from switching to another application.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#472]
Some of the users found this annoying. Not sure what to instead.

**Comment by jdramsey** [comment]
This is a UI issue. The question is how in the UI to represent algorithms executing and to handle stupid interventions by the use like deleting the data, etc, without blocking other applications.

**Comment by amurrayw** [comment]
If I remember correctly, minimizing the Tetrad window in Linux let you use other applications (assuming you are referring to Tetrad seizing input from the keyboard). Not sure what happens on windows/mac. Might work as a stop-gap.

**Comment by amurrayw** [comment]
Never mind, minimizing only allows you to use other applications with the mouse. It doesn't give back access to the keyboard.

**Comment by jdramsey** [comment]
Fixed a long time ago.
