### ISSUE TITLE
Unable to Delete Selected Column From Data Box

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#477]
User unable to delete selected column via "Delete Selected Rows or Columns" from the "Edit" menu.

**Comment by jdramsey** [comment]
This used to work. I wonder how it got broken?

**Comment by yuanzhou** [comment]
I tested this and couldn't "Delete Selected Rows or Columns".  I saw some errors in the console. I'll work on the fix.

**Comment by yuanzhou** [comment]
@jdramsey the broken code was calling `removeCols()` at https://github.com/cmu-phil/tetrad/blob/data-box-fix/tetrad-lib/src/main/java/edu/cmu/tetrad/data/BoxDataSet.java#L1109 and there's index out of range error which I couldn't figure out.

I fixed the bug by switching to `removeColumn()` to remove each selected individual column. https://github.com/cmu-phil/tetrad/blob/data-box-fix/tetrad-lib/src/main/java/edu/cmu/tetrad/data/BoxDataSet.java#L596

I've commented the old code here: https://github.com/cmu-phil/tetrad/blob/data-box-fix/tetrad-gui/src/main/java/edu/cmu/tetradapp/editor/TabularDataJTable.java#L296

But I don't see any issue with `removeCols()`  during debugging. Can you also take a look just so we are on the safe side. Thanks.

**Comment by jdramsey** [comment]
@yuanzhou That's a perfectly good fix. I'll look at the removeCols method, though now that you've fixed it I'll have to think of a newly clever way to break it. :)
