### ISSUE TITLE
Error message while running TetradCmd with PC algorithm. 

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#48]
Hi, 

I was running TetradCmd in Windows for PC algorithm, but I got an error message. Please see below. 

*****************************************************************************************
java -jar tetradcmd-5.1.0-10.jar -data input.txt -datatype discrete -algorithm pc -depth -1 -significance 0.01

Exception in thread "main" java.lang.IllegalStateException: No algorithm was specified.
  at edu.cmu.tetradapp.TetradCmd.runAlgorithm<TetradCmd.java:508>
  at edu.cmu.tetradapp.TetradCmd.<init><TetradCmd.java:80>
  at edu.cmu.tetradapp.TetradCmd.main<Tetrad.java:945>
*******************************************************************************************

When I ran it for FCI or other algorithms, I didn't get any error message. Only PC algorithm is giving error message. Even if I got the error message while running for PC algorithm, I could get an output. When I compared the PC output and other algorithm outputs, they are different so I think PC algorithm is working and the error message doesn't seem critical. But, I am not sure whether PC algorithm is working appropriately. Could you explain what the error message means and if I can fix it. 

Thank you, 
Sanghoon

**Comment by jdramsey** [comment]
Hold on, I have to get back to the point where I can create the tetradcmd jar in the new repository. May take a bit.

**Comment by jdramsey** [comment]
First of all, edu.cmu.tetradapp.TetradCmd is in the wrong place! It should be in tetrad, not tetradapp. It refers only to classes in tetrad.

**Comment by jdramsey** [comment]
OK, I have a jar that runs TetradCmd. It's not called tetradcmd anymore because I can't figure out how to get Maven to name jars the way I want. But it works.

When I get a chance, I'll try it with some data.

**Comment by jdramsey** [comment]
I found the problem. A missing else statement. Not sure when the next snapshot release will be but it will be up then.
