### ISSUE TITLE
can't change datattype after the reading data

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#481]
can we change the datatype after parse on indicate manually what columns are discrete/continuous

**Comment by yuanzhou** [comment]
But how can you manually indicate mixed data? It requires to specify the max number of discrete categories when loading mixed data.

**Comment by chirayukong** [comment]
You can add another Data box and convert data type on selected columns.

**Comment by espinoj** [comment]
Closing since there is data box workaround
