### ISSUE TITLE
Switch to a conflict resolution rule for PC-style algorithms that doesn't produce bidirected edges

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#495]
We have three conflict resolution rules:

Priority X->Y<-Z--W, Y->Z<-W ==> X->Y<-Z--W
Overwrite (pcalg's) X->Y<-Z--W, Y->Z<-W ==> X--Y->Z<-W
Bidirected X->Y<Z--W, Y->Z<-W ==> X->Y<->Z<-W

Currently we're using bidirected, which generates issues for the R wrapper. I suggest we switch to priority instead, Dan's rule.

**Comment by jdramsey** [comment]
Since no one has opined on this, I will make a unilateral decision: We will use Dan's rule (Priority). If anyone wants to object, we can change it. But I just committed code in which Dan's rule is used for all PC-style algorithms. It will be in the next release unless someone objects. There will be no bidirected edges, and the output will be expressible in R.

**Comment by jdramsey** [comment]
Clark requested we put a version of the PC algorithms in the interface where the user has a choice. The combiation

**Comment by jdramsey** [comment]
Reopening this.

Clark requested we put a version of PC in the interface where the user has a choice between conflict rules. The combination PC algorithm (PcAll) is such an algorithm. I suggest we put that in the GUI.

Whether we allow the user to pick a conflict rule for the version of PC that can go into R is up to @espinoj  and @chirayukong. Can the R output support bidirected edges now? I still would prefer not, to avoid confusion, but can easily adjust the code to allow a choice, even for R.

**Comment by jdramsey** [comment]
Also, for the GUI, @yuanzhou. PcAll supports the option now. The individual algorithms, PC, CPC, etc., all call PcAll. They could allow a choice is you wanted to put the individual algorithms in the GUI, though this would affect R. @chirayukong.

**Comment by chirayukong** [comment]
The graph in R can't visualize on a combination of directed (arrow type) and undirected (no end point) graph. We now can only produce the textual results.

**Comment by jdramsey** [comment]
@chirayukong I think that will have to suffice then.

**Comment by jdramsey** [comment]
@espinoj This has been fixed for a while now. PCAll lets you choose a rule for resolving collider conflicts.
