### ISSUE TITLE
Cut/copy/paste of cells in data box broken

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#497]
When I attempt to copy and paste a column of cells from one data box to another, I sometimes get an off-by-one error (the wrong column is copied), and sometimes fail to paste altogether. In some cases, the correct column will be cut, but then the column next to it is what pastes, losing the data in that column entirely.

I'm using a version downloaded from development on 07/10/2017.

**Comment by jdramsey** [comment]
Add this fix to https://github.com/cmu-phil/tetrad/pull/703.
