### ISSUE TITLE
AlgorithmDescriptionFactory Needs Refactoring and Moved to Tetrad Lib

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#507]
@yuanzhou @espinoj @chirayukong AlgorithmDescriptionFactory needs to be in tetrad-lib to so that causal-cmd can use it.  It also needs refactoring into a singleton instead of a factory.

@yuanzhou This will affect your code in the GUI.  We can go through it once I am done.

**Comment by yuanzhou** [comment]
Thanks @kvb2univpitt
