### ISSUE TITLE
Forever loop on FCI continuous data

### ISSUE THREAD

**Issue by chirayukong** [cmu-phil/tetrad#518]
@jdramsey, try this:
`

		int penaltyDiscount = 2;
		int depth = -1;
		int maxPathLength = -1;
		int numVars = 20;
		int edgesPerNode = 2;
		int numLatentConfounders = 2;
		int numCases = 100;
		int numBootstrapSamples = 5;
		boolean verbose = true;

		final int numEdges = (int) (numVars * edgesPerNode);

		List<Node> vars = new ArrayList<>();

		for (int i = 0; i < numVars; i++) {
			vars.add(new ContinuousVariable(Integer.toString(i)));
		}

		Graph dag =  GraphUtils.randomGraph(vars, numLatentConfounders, numEdges, 30, 15, 15, false);
		
		DagToPag dagToPag = new DagToPag(dag);
		Graph truePag = dagToPag.convert();

		System.out.println("Truth PAG_of_the_true_DAG Graph:");
		System.out.println(truePag.toString());

		int[] causalOrdering = new int[numVars];

		for (int i = 0; i < numVars; i++) {
			causalOrdering[i] = i;
		}

		LargeScaleSimulation simulator = new LargeScaleSimulation(dag, dag.getNodes(), causalOrdering);

		DataSet data = simulator.simulateDataFisher(numCases);

		IndependenceTest test = new IndTestFisherZ(data, 0.05);
		edu.cmu.tetrad.search.Fci search = new edu.cmu.tetrad.search.Fci(test);
		search.setDepth(depth);
		search.setMaxPathLength(maxPathLength);
		search.setPenaltyDiscount(penaltyDiscount);
		search.setVerbose(verbose);
		
		Graph resultGraph = search.search();
		System.out.println("Estimated PAG_of_the_true_DAG Graph:");
		System.out.println(resultGraph.toString());
`.

It will generate the result like this:
`
...
Determinism detected: [10, 18, 19, 5, 9] -> 2
Determinism detected: [10, 18, 19, 6, 7] -> 2
Determinism detected: [10, 18, 19, 6, 9] -> 2
Determinism detected: [10, 18, 19, 7, 9] -> 2
Determinism detected: [10, 18, 3, 4, 5] -> 2
Determinism detected: [10, 18, 3, 4, 6] -> 2
Determinism detected: [10, 18, 3, 4, 7] -> 2
Determinism detected: [10, 18, 3, 4, 9] -> 2
Determinism detected: [10, 18, 3, 5, 6] -> 2
Determinism detected: [10, 18, 3, 5, 7] -> 2
Determinism detected: [10, 18, 3, 5, 9] -> 2
...
`.
Did I do something wrong?

**Comment by jdramsey** [comment]
Those are all different judgments of determinism. I'm guessing you genuinely have a lot of determinism in your data. 

This may be the problem:

	int numCases = 100;

Maybe try limiting the depth of search?

**Comment by chirayukong** [comment]
Tried on limiting a depth to 3 and it works. The number of cases seems not affecting the determinism detected problems. :-)
