### ISSUE TITLE
Feedback from clinicians on GFCI output

### ISSUE THREAD

**Issue by ekummerfeld** [cmu-phil/tetrad#522]
This is relevant to the GUI representation of graphs output by GFCI and probably anything else that makes a PAG. After discussing some findings with clinicians they reported some confusion that the more definitive causal arrows had dotted lines while the less definitive causal arrows had solid lines. For users unfamiliar with interpreting these graphs, it would be nice if this was reversed by default: the green dotted lines should be green solid lines, and the blue solid lines should be dotted lines.

**Comment by jdramsey** [comment]
That's an easy fix. I second it.

**Comment by espinoj** [comment]
#558 Addresses this.  Closing
