### ISSUE TITLE
Loading Correlation Matrices doesn't work in GUI

### ISSUE THREAD

**Issue by ekummerfeld** [cmu-phil/tetrad#525]
I might be doing something wrong, but I'm a relatively experienced Tetrad user so this shouldn't be hard.

Whenever I try to load a correlation matrix into a data box in the Tetrad GUI I get validation errors. This should not be a formatting issue on my end, because even if I create and save a correlation matrix within the Tetrad GUI, save it to file, and then try to load that file, I still get these validation errors.

![csave](https://user-images.githubusercontent.com/15657873/30927502-499c7eea-a37e-11e7-85bc-37f6da0bb31a.png)
![cload1](https://user-images.githubusercontent.com/15657873/30927503-49ad6214-a37e-11e7-8085-ca8688f815f5.png)
![cload2](https://user-images.githubusercontent.com/15657873/30927501-499c0348-a37e-11e7-99cc-003d80b35ae0.png)

**Comment by yuanzhou** [comment]
@ekummerfeld can you paste your dataset here so I can reproduce this error?

**Comment by ekummerfeld** [comment]
I pasted the data below. This happens with all data sets for me, though. In the example I generated a simulated data set in the standard way, using default values for everything. You can see the process in the first image. I can redo that process and upload the whole as well .tet if you like, but this is not specific to any data set.

[data2.txt](https://github.com/cmu-phil/tetrad/files/1344656/data2.txt)

**Comment by yuanzhou** [comment]
Debugged with @kvb2univpitt and we noticed that you have an extra tab at the end of each line:

![capture](https://user-images.githubusercontent.com/195873/31030560-bdd54174-a523-11e7-92c3-f253ce65c2ec.PNG)

The validation will treat that extra tab as missing value, that's why you got the errors.

It passes the validation after removing all the ending tabs:

![captur2e](https://user-images.githubusercontent.com/195873/31030618-01534cca-a524-11e7-9d71-cf4b7933d18c.PNG)

So you'll need to make sure there's no extra delimiters get added when generating the dataset.

**Comment by yuanzhou** [comment]
@jdramsey looks like the covariance matrix was generated by the simulation. And simulation adds an extra delimiter at the end of each line. This needs to be fixed.

**Comment by jdramsey** [comment]
Are you sure? I thought Erich said he got this covariance matrix by saving out from the interface... I'll bet it's this code in CovarainceMatrix...

    public final String toString() {
        NumberFormat nf = NumberFormatUtil.getInstance().getNumberFormat();

        StringBuilder buf = new StringBuilder();

        int numVars = getVariableNames().size();
        buf.append(getSampleSize()).append("\n");

        for (int i = 0; i < numVars; i++) {
            String name = getVariableNames().get(i);
            buf.append(name).append("\t");
        }

        buf.append("\n");

        for (int j = 0; j < numVars; j++) {
            for (int i = 0; i <= j; i++) {
                buf.append(nf.format(getValue(i, j))).append("\t");
            }
            buf.append("\n");
        }


//        buf.append("\nCovariance matrix:");
//        buf.append("\n\tVariables = ").append(getVariable());
//        buf.append("\n\tSample size = ").append(getSampleSize());
//        buf.append("\n");
//        buf.append(MatrixUtils.toString(matrixC.toArray()));
//
//        if (getKnowledge() != null && !getKnowledge().isEmpty()) {
//            buf.append(getKnowledge());
//        }

        return buf.toString();
    }
If so there's an easy fix, but I have a meeting right now...

**Comment by yuanzhou** [comment]
@jdramsey I think you are right.

**Comment by jdramsey** [comment]
@yuanzhou 

This code:

    for (int j = 0; j < numVars; j++) {
        for (int i = 0; i <= j; i++) {
            buf.append(nf.format(getValue(i, j))).append("\t");
        }
        buf.append("\n");
    }

I think substituting this should do it...

        for (int j = 0; j < numVars; j++) {
            for (int i = 0; i <= j; i++) {
                buf.append(nf.format(getValue(i, j)));
                
                if (i < j) {
                    buf.append("\t");
                }
            }
            
            buf.append("\n");
        }

**Comment by yuanzhou** [comment]
@jdramsey Thanks, I'll make the change and test it out then push to development branch if everything is good.

**Comment by yuanzhou** [comment]
@ekummerfeld can you pull the fix from development branch and try again? I tested and it's working now.

**Comment by ekummerfeld** [comment]
Thanks!
