### ISSUE TITLE
Add R3 post-processor to IMagES in R-Python

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#530]
I got a note from the folks we did the R-Python version of IMaGES for--they are grateful and say it works great! They are wondering if one more thing could be done, which is to add a post-processor for R3, in general, some pairwise orientation algorithm. I'm happy to do any of the coding I can from end, but is there a good way to proceed?

Thanks!

**Comment by jdramsey** [comment]
@chirayukong Was *this* one fixed? I saw you reference it... :)

**Comment by chirayukong** [comment]
Yep. I did it a long time ago under the lofs algorithm.
