### ISSUE TITLE
http://www.phil.cmu.edu/tetrad/downloads.html points to old version

### ISSUE THREAD

**Issue by The-Alchemist** [cmu-phil/tetrad#531]
`Install Latest` points to https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/cmu/tetrad-gui/6.2.0/tetrad-gui-6.2.0-launch.jar, which is an old version

**Comment by jdramsey** [comment]
@espinoj Am I supposed to be updating the philserv web page with each release? Would it be feasible to have a link that automatically points to the latest version? Can I just point to your website?

**Comment by espinoj** [comment]
My problem is that I don't have direct control either of the web page.  I'll let you know.

**Comment by espinoj** [comment]
links have been updated along with javascript code to download latest version
