### ISSUE TITLE
Text at bottom of algo chooser UI is cut off

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#533]
On mac the text (last line)  at the bottom of the algo chooser UI algorithm description is not visible.  Maybe the text box is bigger than the frame?

![screen shot 2017-10-16 at 3 02 35 pm](https://user-images.githubusercontent.com/313721/31613374-373bd598-b283-11e7-9a61-21f77681501c.png)

**Comment by harryhoch** [comment]
I've seen something similar on the data  loader/vallidation UI
