### ISSUE TITLE
In development, the algorithm editor seems always to revert to the first score in the list.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#538]
So when running FGES, it always uses Conditional Gaussian. I checked this by adding a stop in SEM BIC and selecting SEM BIC, but it never stops there, and then the list reverts back to Conditional Gaussian.

@yuanzhou @espinoj

**Comment by chirayukong** [comment]
@jdramsey, 

I can take a look on this issue.

**Comment by jdramsey** [comment]
@chirayukong Thanks. Let me know. I looked at the code for a while and couldn't figure it out. I figured you'd have a better chance. :)

**Comment by jdramsey** [comment]
@chirayukong Now it's working for me. I don't know what I'm doing differently. If I can get it to break again, I'll let you know.

**Comment by chirayukong** [comment]
@jdramsey try on this branch [https://github.com/cmu-phil/tetrad/tree/fix-issue-538](fix-issue-538). 
The problem was the UI would only set the algorithm up with the score and the test only when the algorithm selection changed. I moved that algorithm initialization to a part before the search.

**Comment by jdramsey** [comment]
@chirayukong OK. Let me try that.

**Comment by jdramsey** [comment]
@chirayukong So now I have this problem. I select FGES from the algorithms dropdown, then I select the SEM BIC score. But then when I go to edit the parameters for the SEM BIC score, they aren't the right parameters. It wants me to specify a "structure prior" which means it's got to be the parameters for Conditional Gaussian, which is the first score in the list. It should ask for a "penalty discount".

**Comment by chirayukong** [comment]
@jdramsey that needs to update the parameter panel. I'll let you know when it is done.

**Comment by chirayukong** [comment]
@jdramsey and @espinoj, could you guys give it a try again on the [https://github.com/cmu-phil/tetrad/tree/fix-issue-538](fix-issue-538) branch?

**Comment by jdramsey** [comment]
That works, thanks!
