### ISSUE TITLE
If you add a new algorithm, you need to close the session and make a new session.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#549]
I noticed various problems occur if you add a new algorithm through annotation. The algorithm shows up, but sometimes the parameters aren't the right ones. Also, sometimes buttons disappear from the search editor and don't reappear even if you close the search editor an re-open it. The button to editor parameters in particular disappears.

The workaround is to close the session and re-launch the GUI and make a new session.

**Comment by chirayukong** [comment]
@jdramsey Do you mean that the saved session would correctly display the newly-added algorithm? I try to simulate the same situation.

**Comment by jdramsey** [comment]
I didn't far ahead to a solution. :) If when you opened up a saved session, it shows the newly-added algorithm, that would be fantastic. As it is, I have to throw all or my work away every time an algorithm is added.

**Comment by jdramsey** [comment]
@chirayukong But it _shows_ the algorithm; the problem it has some unexpected behaviors as if the algorithm weren't being treated correctly everywhere in the interface.

**Comment by jdramsey** [comment]
@espinoj This appears to have been fixed for a while now.
