### ISSUE TITLE
FgesMb doesn't work with the conditional Gaussian BIC score 

### ISSUE THREAD

**Issue by chirayukong** [cmu-phil/tetrad#552]
I tried it on both continuous/discrete dataset. It keeps saying the "Target is not one of the variables for the fgesScore". @jdramsey

**Comment by jdramsey** [comment]
@chirayukong  You typed the name of the variable in the box? I noticed when I didn't type the name of the variable it said that...

**Comment by chirayukong** [comment]
But I did. :-( It worked for other scores except for this one.

**Comment by jdramsey** [comment]
This fixes it: @chirayukong 

https://github.com/cmu-phil/tetrad/tree/Issue552Fix
