### ISSUE TITLE
background knowledge and bootstrap orientations

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#554]
I've been playing around with bootstrapped fGES and gFCI using tiered prior knowledge and have noticed the following things:

1. When I run bootstrapped fGES, there are resulting edges that conflict with the prior knowledge I have provided.  However, if I were to interpret all reported edge directions in the opposite direction then the output is faithful to the prior knowledge.  For this reason, I believe the reported bootstrap edges are reversed.

2. When I run gFCI under the same conditions and interpret the edge orientations as reversed, I still get a few conflicts.  Hypothesis: the prior knowledge is working for the first phase of the algorithm (fGES), but for the second phase (FCI latent variable identification) the prior knowledge is not (or not correctly) used and thus a few conflicts are able to arise.

I am happy to provide screenshots and code if it would be helpful.

**Comment by chirayukong** [comment]
I'll take a look this. I'll be back when I got something. @bja43

**Comment by chirayukong** [comment]
@bja43 try this: [issue 554](https://github.com/cmu-phil/tetrad/tree/fix-issue-554).

**Comment by chirayukong** [comment]
The new GUI and the textual result will be more verbose as shown belows:

<img width="546" alt="screen shot 2017-11-08 at 4 25 58 pm" src="https://user-images.githubusercontent.com/4652250/32576022-b170a776-c4a3-11e7-851b-b04d838ff6fd.png">

Bootstrapping on the FCI (Fast Causal Inference) using Conditional Correlation Test
Running Bootstraps in Parallel Mode, numBoostrap = 10
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
thread started ... 
knowledge being set ... 
processing time of bootstrap for a thread was: 0.158 sec
thread started ... 
knowledge being set ... 
processing time of bootstrap for a thread was: 0.18 sec
thread started ... 
knowledge being set ... 
processing time of bootstrap for a thread was: 0.204 sec
processing time of bootstrap for a thread was: 0.214 sec
processing time of bootstrap for a thread was: 0.217 sec
processing time of bootstrap for a thread was: 0.238 sec
processing time of bootstrap for a thread was: 0.239 sec
processing time of bootstrap for a thread was: 0.082 sec
processing time of bootstrap for a thread was: 0.068 sec
processing time of bootstrap for a thread was: 0.25 sec
Bootstrap size is : 10
Processing time of total bootstrapping : 1.007 sec
PAGs: 10
Ensemble: Highest

Sampling Search Result (0):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. Imaginability o-o Impact
2. Impact o-> Sympathy
3. TangibilityCondition o-> Sympathy


Sampling Search Result (1):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. Imaginability o-> Impact
2. Sympathy o-> Impact
3. TangibilityCondition o-o Sympathy


Sampling Search Result (2):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. AmountDonated <-> Impact
2. AmountDonated <-> Sympathy
3. Imaginability o-> Impact
4. Imaginability o-> Sympathy


Sampling Search Result (3):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. Imaginability o-o Impact
2. Sympathy o-o Impact
3. TangibilityCondition o-o Sympathy


Sampling Search Result (4):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. AmountDonated o-> TangibilityCondition
2. Impact o-> Imaginability
3. Sympathy o-o Impact
4. TangibilityCondition <-> Imaginability


Sampling Search Result (5):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. AmountDonated o-> Impact
2. Imaginability o-> Impact
3. Impact --> Sympathy nl dd
4. TangibilityCondition o-> Sympathy


Sampling Search Result (6):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. AmountDonated o-o Imaginability
2. AmountDonated o-o Impact
3. Sympathy o-o Impact
4. TangibilityCondition o-o Sympathy


Sampling Search Result (7):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. Sympathy o-o Impact
2. TangibilityCondition o-o Sympathy


Sampling Search Result (8):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. Imaginability o-o Impact
2. Sympathy o-o Imaginability
3. Sympathy o-o Impact


Sampling Search Result (9):
Graph Nodes:
TangibilityCondition,AmountDonated,Sympathy,Imaginability,Impact

Graph Edges:
1. AmountDonated o-> Impact
2. Imaginability o-> Impact
3. Imaginability o-> TangibilityCondition
4. Impact --> Sympathy nl dd
5. TangibilityCondition <-> Sympathy


AmountDonated [no edge] Impact : 0.6
AmountDonated --> Impact : 0.0
Impact --> AmountDonated : 0.0
AmountDonated o-> Impact : 0.2
Impact o-> AmountDonated : 0.0
AmountDonated o-o Impact : 0.1
AmountDonated <-> Impact : 0.1
AmountDonated --- Impact : 0.0

Imaginability [no edge] Sympathy : 0.8
Imaginability --> Sympathy : 0.0
Sympathy --> Imaginability : 0.0
Imaginability o-> Sympathy : 0.1
Sympathy o-> Imaginability : 0.0
Imaginability o-o Sympathy : 0.1
Imaginability <-> Sympathy : 0.0
Imaginability --- Sympathy : 0.0

AmountDonated [no edge] Imaginability : 0.9
AmountDonated --> Imaginability : 0.0
Imaginability --> AmountDonated : 0.0
AmountDonated o-> Imaginability : 0.0
Imaginability o-> AmountDonated : 0.0
AmountDonated o-o Imaginability : 0.1
AmountDonated <-> Imaginability : 0.0
AmountDonated --- Imaginability : 0.0

Impact [no edge] Sympathy : 0.1
Impact --> Sympathy : 0.2
Sympathy --> Impact : 0.0
Impact o-> Sympathy : 0.1
Sympathy o-> Impact : 0.1
Impact o-o Sympathy : 0.5
Impact <-> Sympathy : 0.0
Impact --- Sympathy : 0.0
Final result: Impact o-o Sympathy : 0.5

AmountDonated [no edge] Sympathy : 0.9
AmountDonated --> Sympathy : 0.0
Sympathy --> AmountDonated : 0.0
AmountDonated o-> Sympathy : 0.0
Sympathy o-> AmountDonated : 0.0
AmountDonated o-o Sympathy : 0.0
AmountDonated <-> Sympathy : 0.1
AmountDonated --- Sympathy : 0.0

Imaginability [no edge] Impact : 0.2
Imaginability --> Impact : 0.0
Impact --> Imaginability : 0.0
Imaginability o-> Impact : 0.4
Impact o-> Imaginability : 0.1
Imaginability o-o Impact : 0.3
Imaginability <-> Impact : 0.0
Imaginability --- Impact : 0.0
Final result: Imaginability o-> Impact : 0.4

AmountDonated [no edge] TangibilityCondition : 0.9
AmountDonated --> TangibilityCondition : 0.0
TangibilityCondition --> AmountDonated : 0.0
AmountDonated o-> TangibilityCondition : 0.1
TangibilityCondition o-> AmountDonated : 0.0
AmountDonated o-o TangibilityCondition : 0.0
AmountDonated <-> TangibilityCondition : 0.0
AmountDonated --- TangibilityCondition : 0.0

Imaginability [no edge] TangibilityCondition : 0.8
Imaginability --> TangibilityCondition : 0.0
TangibilityCondition --> Imaginability : 0.0
Imaginability o-> TangibilityCondition : 0.1
TangibilityCondition o-> Imaginability : 0.0
Imaginability o-o TangibilityCondition : 0.0
Imaginability <-> TangibilityCondition : 0.1
Imaginability --- TangibilityCondition : 0.0

Impact [no edge] TangibilityCondition : 1.0
Impact --> TangibilityCondition : 0.0
TangibilityCondition --> Impact : 0.0
Impact o-> TangibilityCondition : 0.0
TangibilityCondition o-> Impact : 0.0
Impact o-o TangibilityCondition : 0.0
Impact <-> TangibilityCondition : 0.0
Impact --- TangibilityCondition : 0.0

Sympathy [no edge] TangibilityCondition : 0.3
Sympathy --> TangibilityCondition : 0.0
TangibilityCondition --> Sympathy : 0.0
Sympathy o-> TangibilityCondition : 0.0
TangibilityCondition o-> Sympathy : 0.2
Sympathy o-o TangibilityCondition : 0.4
Sympathy <-> TangibilityCondition : 0.1
Sympathy --- TangibilityCondition : 0.0
Final result: Sympathy o-o TangibilityCondition : 0.4

Final Bootstrapping Search Result:
Graph Nodes:
AmountDonated,Imaginability,Impact,Sympathy,TangibilityCondition

Graph Edges:
1. Imaginability o-> Impact [no edge]:0.2000[-->]:0.0000[<--]:0.0000[o->]:0.4000[<-o]:0.1000[o-o]:0.3000[<->]:0.0000[---]:0.0000
2. Impact o-o Sympathy [no edge]:0.1000[-->]:0.2000[<--]:0.0000[o->]:0.1000[<-o]:0.1000[o-o]:0.5000[<->]:0.0000[---]:0.0000 nl dd
3. Sympathy o-o TangibilityCondition [no edge]:0.3000[-->]:0.0000[<--]:0.0000[o->]:0.0000[<-o]:0.2000[o-o]:0.4000[<->]:0.1000[---]:0.0000


probDistribution finished in 8 ms
