### ISSUE TITLE
Simulation not using manually entered mean

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#555]
In 6.4.0-0, pulled from development ~2 weeks ago (I tried to download a newer version to check, but there's some sort of error preventing me from using the GUI), I've created a generalized SEM IM with error terms with non-zero means. However, the simulation box outputs simulated data in which every variable has a mean of zero. Previous versions of Tetrad do not demonstrate this error.

I've saved the session in which the problem occurred, and can provide it in an email if necessary.

**Comment by jdramsey** [comment]
@mglymour This isn't happening for me. Can you give more info? Screenshots?

**Comment by jdramsey** [comment]
Here's my screenshot.

<img width="1413" alt="means" src="https://user-images.githubusercontent.com/9853255/32377630-b23cc5c8-c07e-11e7-86fe-a4435ec876ec.png">

**Comment by jdramsey** [comment]
Can't reproduce.
