### ISSUE TITLE
PAG colors revision

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#558]
There was a discussion about PAG coloration to make it clearer for users.  Internally the thread led to this:

Green: no latent confounder
Blue (traditional Tetrad color): there is possibly a latent confounder.
 
Bold line: definitely direct. 
Regular (traditional Tetrad thickness) line: it is possibly indirect.
 
Dashed lines would not be used.

But there was advisement to ask some more users beyond the _n_ of 1

**Comment by jdramsey** [comment]
@espinoj Just, to be honest, the original choices were off the cuff ones I made on my own, so those were N = 1. Peter just said to have two cross-cutting visual gestures, for 4 combinations; those were the first ones that came to mind.

**Comment by espinoj** [comment]
This was approved by algorithms

**Comment by espinoj** [comment]
![how to display directed arcs in pags](https://user-images.githubusercontent.com/313721/32749931-fb121196-c88e-11e7-88f6-37cf2c0a326d.JPG)

**Comment by espinoj** [comment]
Should be updated in Tetrad/causal web and accompanying online help

**Comment by espinoj** [comment]
fixed in #607

**Comment by espinoj** [comment]
Tetrad's behavior is currently the opposite of what was described.  Current behavior:
No Latent - Thick 
Definitely Direct - Green

This needs to be fixed.

**Comment by jdramsey** [comment]
@espinoj Peter and I went through and made corrections against the development branch. The branch is 'coloring-adjustment'. I just sent a jar to Greg and Peter, a build of that branch. If they approve, I'll submit a pull request, and that should fix it.

I did notice when I built the jar that there were some annotation duplications that caused the tests to fail. Sounds easy to fix.

**Comment by jdramsey** [comment]
@espinoj There were more problems than just reversal of gestures; I added a new method to handle them.

**Comment by jdramsey** [comment]
@espinoj Also, the gestures in 'coloring-adjustment' are now the way I think that Greg wants them. It's possible the manual may need to be correct, I'm not sure.

**Comment by espinoj** [comment]
@jdramsey thanks. I'll pull @kvb2univpitt  in to adjust causal web rendering.
