### ISSUE TITLE
Matrix Toolkits for Java (MTK) doesn't play well with 64 bit Windows

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#59]
If imports starting with no.uib.cipr.matrix are commented out, the problem code is put in red in IntelliJ. Classes affected are IndTestHsic, KernelUtils, Ling, Lingam.

The compiled classes seem to run OK, but the relevant tests break when run in Maven.

I think we should support 64 bit Windows. If so, need to translate this matrix algebra to a different library.

**Comment by jdramsey** [comment]
I've worked on Ling and now Lingam, trying to substitute the Apache matrix library for the MTJ library. The only thing missing is a QL decomposition; I've substituted QR, but I have to think that through.

**Comment by ekummerfeld** [comment]
IndTestHsic appears to be using the following from those imports:
Matrix objects made either with Matrix or DenseMatrix, e.g. "Matrix Kyx = new DenseMatrix(m, m);"
some functions built into the Matrix object class, such as matrix multiplications, e.g. "Ky.mult(Kx, Kyx);" and .get and .numcolumns and .transpose and .copy and .set and .solve
Matrices is also used e.g. "Gztzr.solve(Matrices.identity(kz), ZI);"

**Comment by jdramsey** [comment]
Actually all of those are doable; that might be easier than Ling to translate, although I recall there being a lot more red stuff.

**Comment by jdramsey** [comment]
Solve is just in

**Comment by ekummerfeld** [comment]
That's all the red stuff that I found but I might have messed something up. Gonna do a fresh clone and intelliJ project and look again.

**Comment by jdramsey** [comment]
Hold on, I didn't push the stuff I just did. Give me a couple of minute.

**Comment by jdramsey** [comment]
OK should be there.

**Comment by ekummerfeld** [comment]
I just reran the maven tests and this was the result:

Tests in error: 
  testIncompleteCholesky(edu.cmu.tetrad.test.TestIndTestHsic): unable to load from [netlib-native_system-win-x86_64.dll]
  test6(edu.cmu.tetrad.test.TestLing): column index (5)

Tests run: 439, Failures: 0, Errors: 2, Skipped: 0

**Comment by ekummerfeld** [comment]
In addition to the no.ui etc. imports that get red, TestIndTestHsic has another import that gets red.

import junit.framework.TestCase;
import no.uib.cipr.matrix.DenseMatrix;
import no.uib.cipr.matrix.Matrices;
import no.uib.cipr.matrix.Matrix;

All of those imports get redded out.

**Comment by jdramsey** [comment]
I think I fixed everything. Could you try cloning again and running mvn test? It passes for me but hoping it passes for you.

**Comment by ekummerfeld** [comment]
[INFO] BUILD SUCCESS

nice :)

**Comment by jdramsey** [comment]
I think this is closed.
