### ISSUE TITLE
Clark - RSkew and RSkewE

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#592]
RSKew and RskewE

Rskew should be removed. Only RskewE is empirically applicable. Description needs to be altered to explain why.

**Comment by yuanzhou** [comment]
Same as what I did with EB (#645 ) and R4 (#650 ), I'll just add the `@Experimental` annotation to hide it from the algo chooser and leave the class file there.

**Comment by jdramsey** [comment]
Wait, RSkew works! It's really good! The best of the lot! RSkewE is worse! I can explain!

Joe

@espinoj @yuanzhou

**Comment by yuanzhou** [comment]
RShew is back now https://github.com/cmu-phil/tetrad/commit/89a6a301a0fcee36fe9da021d2bb7d810f9f6f0d

Currently we have R1, R2, R3, RSkew, RShewE, Skew, SkewE under the pairwise category.

**Comment by jdramsey** [comment]
That sounds OK. Like I said, I can send a reference if you like; we wrote all of this up with simulation results and published it in NeuroImage.

**Comment by espinoj** [comment]
Closing this.  Clark erroneously said to remove RSkew
