### ISSUE TITLE
Clark - tsFCI Description

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#593]
tsFCI The description confuses tsFCI and tsGFCI, and is incomplete and has no reference. Note that "T" is capitalized in the list but not in the explanatory text.

"The tsFCI algorithm is a version of GFCI for time series data. See the GFCI documentation for a description of the GFCI algorithm, which allows for unmeasured (hidden, latent) variables in the data-generating process and produces a PAG (partial ancestral graph). tsGFCI takes as input a “time lag data set,” i.e., a data set which includes time series observations of variables X1, X2, X3, ..., and their lags X1:1, X2:1, X3:1, ..., X1:2, X2:2,X3:2, ... and so on. X1:n is the nth-lag of the variable X1. To create a time lag data set from a standard tabular data set (i.e., a matrix of observations of X1, X2, X3, ...), use the “create time lag data” function in the data manipulation toolbox. The user will be prompted to specify the number of lags (n), and a new data set will be created with the above naming convention. The new sample size will be the old sample size minus n.
Input Assumptions: The (continuous) data has been generated by a time series. Output Format: (Need to get this from Dan.)"

**Comment by dmalinsk** [comment]
I'm not sure who is the one editing all these descriptions in the manual
but... in this paragraph just replace tsGFCI with tsFCI. The names of the
algorithms tsFCI and tsGFCI start with lowercase "ts" (following earlier
convention in the literature) but the convention in in Java for naming
classes is CamelCase hence the capital T. I think in the GUI the
capitalization is just inherited from the Java code but there is no reason
this is the case, and perhaps capitalization could be made consistent with
the literature thoughout: tsFCI, PC (not Pc), fGES (not FGES) etc.

I don't personally do any work on the GUI though so I'm not sure how easy
this is!

**Comment by yuanzhou** [comment]
This is related to #594 so I just link it here.
