### ISSUE TITLE
Clark - Missing Algorithms Mimbuild and Lingam

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#595]
Mimbuild      This is absolutely essential
Lingam 	 Good for very large samples

**Comment by jdramsey** [comment]
@espinoj Mimbuild is done.

**Comment by jdramsey** [comment]
@espinoj I'm working on LiNGAM.

**Comment by jdramsey** [comment]
https://github.com/cmu-phil/tetrad/pull/714

**Comment by jdramsey** [comment]
I have re-added LiNGAM as an algorithm in the interface (by adding the appropriate annotation to the LiNGAM wrapper. I have cleaned up the implementation of LiNGAM (in the search package). I implement precisely algorithm A from http://www.jmlr.org/papers/volume7/shimizu06a/shimizu06a.pdf

p. 2007, using our translation of FastICA from like a decade ago. For the 'pruning' step I use FGES with the causal order found by Algorithm A.

This could be improved. The above paper has suggestions for further refining the algorithm. We could try another implementation of ICA. But the above is correct.

@cg09

**Comment by jdramsey** [comment]
@cg09 Clark, once this is is merged you can try it.

@kvb2univpitt Can you merge it?

**Comment by espinoj** [comment]
this is merged in development for @cg09 to try

**Comment by isadreev** [comment]
Is there any chance LinGAM could be added to the list of algorithms in the command version of TETRAD 6.4.0 available at:
https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/cmu/tetrad-lib/6.4.0/ ?
