### ISSUE TITLE
Clark - New algorithms that are needed 

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#596]
A. Kun's algorithm for data from multiple structures. Madelyn has coded it and given it preliminary testing. Need to test further and put description on Arxiv.

B. Fask  Ramsey algorithm for fMRI time series.

C. Two-Step Kun algorithm for fmri time series.

D. FGES without one-edge faithfulness

**Comment by espinoj** [comment]
FGES has an option for one-edge faithfulness 

![image](https://user-images.githubusercontent.com/313721/32787735-4bb766aa-c925-11e7-83d6-74b49214a8fd.png)

**Comment by jdramsey** [comment]
@espinoj FASK is done.

**Comment by cg09** [comment]
Probably in matlab on his computer.

**Comment by cg09** [comment]
Hi Jeremy (CC: Clark),


Exactly as Clark said, I have MATLAB source code on my computer. Do you need it? If so, please let me know exactly what function you need so that I can update the interface for you.


Best,

Kun


________________________________

**Comment by jdramsey** [comment]
@espinoj @cg09 Regarding Two-Step, which we have a Matlab java jar for, I recall the problem we were having with it, putting in the interface, was that you couldn't stop it once you started it, and it took a very long time. the only way to stop it was to quit the program. However, in the spirit of realizing things, that doesn't matter at all if you put it in the command line version or the R or Pascal versions, where you'd want to top the program anyway if you want to stop it. Proposal: Don't put Two-Step in the interface; instead, put it in the command-line Tetrad (and R and Pascal).

**Comment by jdramsey** [comment]
This is a nonstarter. Accessing Matlab from Java is not stable. Closing.
