### ISSUE TITLE
Clark - use of Data vs Simulation box

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#599]
You cannot start with a pipeline graph, connect to a different (e.g., to a Bayes Net) parameterization and connect to a DATA box--only to a simulation box. Highly misleading.

**Comment by jdramsey** [comment]
@cg09 Data boxes and simulation boxes behave very differently; they shouldn't be confused. Now simulations can have many parameters that vary from simulation model to simulation model. It used to be that simulations had only one parameter--sample size; this is no longer the case, so you could just pop up a little box for sample size and be done with it. This got more complicated. @espinoj

**Comment by jdramsey** [comment]
This issue has been long settled.
