### ISSUE TITLE
Recode Ling.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#60]
The algorithm is unstable, giving radically different answers each time the execute button is pressed. FastICA seems to be more unstable than it should be. Need to recode FastICA first. See Issue #61 and Issue #62.

**Comment by jdramsey** [comment]
This implementation depends on some really screwed up looking code. The Hungarian algorithm code is not clean, and it's unclear whether it's correct. So first FastICA and LiNGAM need to be recoded, and then something like the Hungarian Algorithm needs to be coded up. LiNG should follow quite directly from this and should be more stable.

**Comment by jdramsey** [comment]
Kun has a better idea.

**Comment by Diviyan-Kalainathan** [comment]
Hi, 
I wondered if the Ling algorithm is usable again, there is this mention : 
https://github.com/cmu-phil/tetrad/blob/6fc8d654d366dbd4e8e2af9872dbf0acc6396d4e/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Ling.java#L56-L61

But I don't know if this is related to this issue, or if that comment is still relevant.

Thanks a lot!
Best regards,
Diviyan
