### ISSUE TITLE
Clark - MGM DOES NOT WORK (ON CONTINUOUS DATA)

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#605]
MGM DOES NOT WORK (ON CONTINUOUS DATA)

**Comment by jdramsey** [comment]
There is a question as to whether it is _supposed_ to work on continuous data. AJ had said not.

**Comment by espinoj** [comment]
@chirayukong was this clarified?

**Comment by chirayukong** [comment]
@espinoj I have no idea how to fix this. Need @jdramsey to jump in.

**Comment by jdramsey** [comment]
I think the thing to do is pull up the original article for MGM and look to see if all continuous variables is something it can do. It can't the way the code is written. I recall AJ (who wrote the code) telling me it needed at least one continuous and at least one discrete variable to run. Here's the paper:

https://web.stanford.edu/~hastie/Papers/structmgm.pdf

Looking at the paper I don't see why it can't run with all continuous variables, but I can't see in the code what could be causing the problem. Could be  HIOPP problem.

**Comment by jdramsey** [comment]
It does throw an exception. The problem is this line in VerticalDoubleDataBox, which tries to get the number of rows in the dataset from the length of the first column. This is ok...unless there is no first column! :)

    public int numRows() {
        return data[0].length;
    }

Any ideas? If the VerticalDoubleDataBox is constructed with known dimensions, I suppose those could be stored and returned.

**Comment by jdramsey** [comment]
The problem is, even if the VerticalDoubleDataBox isn't constructed with known dimension, this should return something. I recommend we return 0. I'm not sure that will work, though.

@espinoj @chirayukong

**Comment by yuanzhou** [comment]
According to the fix of #649, MGM runs on mixed data. Should this issue be closed?

**Comment by espinoj** [comment]
I just tested the required inputs (at least one discrete and at least one continuous) and it works.  All discrete and all continuous fails which is correct behavior.

Closing
