### ISSUE TITLE
Change Ensemble method description

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#606]
![image](https://user-images.githubusercontent.com/313721/32798768-b5de8c0c-c943-11e7-8cfc-c9c77774f974.png)

Change from "Ensemble Method" to "Bootstrap edge visibility"

Should also augment with parameter description

**Comment by chirayukong** [comment]
The new description is "Bootstrap edge visibility: Preserving All Edges (0), Keep Edges having prob. >= no edge's (1), Keep Edges having prob. > 0.5 (2)". @espinoj and it is in this [fix issue 606](https://github.com/cmu-phil/tetrad/tree/fix-issue-606) branch.
