### ISSUE TITLE
UI fails to scale on high res screens

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#609]
This is related to a previous Windows/Java bug wherein DPI is not reported to Java.  Should see if workaround exists that is universally usable

**Comment by espinoj** [comment]
Top result on google is now this
https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

Will test.

**Comment by espinoj** [comment]
Tried all the proposed solutions in the previous link.   The only solution (Windows 10 on a Surface Pro with high resolution screen) that worked was to setup windows to prefer external manifests and then create manifest files for java.exe and javaw.exe as described in https://stackoverflow.com/questions/30555401/java-disable-dpi-aware-not-working/39372897#39372897

**Comment by espinoj** [comment]
BTW:  you will also need administrator privileges to copy the manifest files to the java bin directory

**Comment by chirayukong** [comment]
One comment said that there is a less intrusive solution:
1) Create a shortcut for command java -jar myJarFile.jar
2) Right click on a shortcut -> Properties
3) Go to Compatibility tab
4) Check Override high DPI scaling behavior.
5) Choose System for Scaling performed by:

**Comment by espinoj** [comment]
Tried - doesn't work on updated Win10 latest Java 8.

**Comment by espinoj** [comment]
#441

**Comment by espinoj** [comment]
Reopening to see if there is a new solution besides having users lower their resolution

**Comment by espinoj** [comment]
on windows Java 9+ works now to scale resolutions!
