### ISSUE TITLE
Recode LiNGAM.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#61]
See Issue #60.

**Comment by jdramsey** [comment]
First FastICA needs to be recoded and recalibrated. Then we need to get Matlab code for LiNGAM and calibrate a Java version of that to the Matlab code. We need an actual unit test of this so it doesn't break.

**Comment by jdramsey** [comment]
Kun has a better idea.

**Comment by jdramsey** [comment]
OK, I am looking at LiNGAM. After some work I'm getting pretty good results orienting a 3-variable collider model, which wasn't happening before. I went back to the original paper and once again tried to put the code in line with that paper. I think I did a better job this time. This is a trace. X2 is the child; the order of the variables here is not randomized; I'll try that next.

Here is the paper.

[shimizu06a.pdf](https://github.com/cmu-phil/tetrad/files/3535500/shimizu06a.pdf)

Here is the trace (for the algorithm in Section 4, algorithm A:

Simulating dataset #1
W = 
       V1       V2       V3
  -0.9724   0.0972  -0.4970
  -0.5890  -0.0349   0.9793
  -0.4109   1.1341   0.7451

** 30.992942547104565 [0, 1, 2]
** 2.9312993708222947 [0, 2, 1]
perm1 = [0, 2, 1]
WTilde before normalization = 
       V1       V2       V3
  -0.9724   0.0972  -0.4970
  -0.4109   1.1341   0.7451
  -0.5890  -0.0349   0.9793

WPrime = 
       V1       V2       V3
   1.0000  -0.1000   0.5111
  -0.3623   1.0000   0.6570
  -0.6014  -0.0357   1.0000

BHat = 
       V1       V2       V3
            0.1000  -0.5111
   0.3623           -0.6570
   0.6014   0.0357         

*** 0.4942973056906238 [0, 1, 2]
*** 0.924698559828673 [0, 2, 1]
BTilde = 
       V1       V2       V3
           -0.5111   0.1000
   0.6014            0.0357
   0.3623  -0.6570         

perm2 = [0, 2, 1]
[X1, X2, X3]
/knowledge
addtemporal

1  X1
2  X3
3  X2

forbiddirect

requiredirect
graph Returning this graph: Graph Nodes:
X1;X2;X3

Graph Edges:
1. X1 --> X2
2. X3 --> X2

Graph Attributes:
BIC: 698.522617

Graph Node Attributes:
BIC: [X1: 200.177757;X2: 238.222708;X3: 260.122153]

I found some index errors and other such silly errors in the code. (Sorry this was coded very badly originally, not by me. I had fixed a lot but not everything apparently.) As you can see, if W is right (that comes from ICA), WTilde is doing the right thing (permuting the rows of W so that the biggest guys are along the diagonal), WPrime is right (normalizing each row by its diagonal element), BHat is right (I - WPrime), and BTilde is right (permuting both rows and column s of BHat so that the elements in the lower triangle squared is largest). So that part of the algorithm is right.

So then it comes down to ICA. The problem with ICA is that it's representing data internally in the "European" way, with variables as rows and cases as columns, and Tetrad has that flipped. Some transpositions were done internally to try to adjust for this. I took all of those out, so it just does the European idea. I'll document that. So to use it you need to first transpose the data, which is fine; transposing doesn't make a copy of the data, so it's not expensive. So now all the matrices should be in the right orientation.

I just tried scrambling the order of the variables in the dataset; it still has pretty good signal but does screw up more often then when the variables are unscrambled. I *think* that's a problem with ICA. I'll try to think if there's any bias in ICA.

**Comment by jdramsey** [comment]
Current performance, compared to FASK.

N = 1000
10 nodes, 10 edges, DAG
Linear Fisher simulation using non-Gaussian errors.
Columns in data set randomly reordered.

For ICA:

Max iterations = 1000
Deflation algorithm
Log cosh function
Tolerance 1e-6.

Algorithms:

1. LiNGAM (Linear Non-Gaussian Acyclic Model
2. FASK using Fisher Z test

Graphs are being compared to the true DAG.

AVERAGE STATISTICS

All edges

  Sim  Alg  sampleSize  penaltyDiscount    alpha  thresholdAlpha    AP    AR   AHP   AHR  F1All  ExactlyRight     E
    1    1     1000.00             1.00        *               *  0.92  1.00  0.86  0.93   0.80          0.30  2.14
    1    2     1000.00                *  1.00E-3               *  1.00  1.00  0.99  0.99   0.99          0.90  0.01

There's clearly a signal for LiNGAM; it does pretty well. But it's much, much slower, and this is only 10 nodes. It probably can't go much more than 12 nodes. Also, it's not as accurate as FASK.

@cg09

**Comment by jdramsey** [comment]
New clue. Raising coefficient range to +/-(.5, 1.2). Now (our) LiNGAM and FASK are very close in performance. So (our) LiNGAM just doesn't do well with smaller coefficients. (Or, FASK does worse with larger coefficients.)

10 nodes, 10 edges, random DAG
10 runs averaged
Linear Fisher simulation using non-Gaussian errors.
Columns in data set randomly reordered.

For ICA:

Max iterations = 1000
Deflation algorithm
Log cosh function
Tolerance 1e-6.

Algorithms:

1. LiNGAM (Linear Non-Gaussian Acyclic Model
2. FASK using Fisher Z test


Graphs are being compared to the true DAG.

AVERAGE STATISTICS

All edges

  Sim  Alg  sampleSize  penaltyDiscount    alpha  thresholdAlpha    AP    AR   AHP   AHR     E
    1    1     1000.00             1.00        *               *  0.85  1.00  0.74  0.86  2.40
    1    2     1000.00                *  1.00E-3               *  0.94  0.91  0.75  0.73  0.01

**Comment by cg09** [comment]
Since there is a kind of trade-off between estimated associations and
sample sizes, and LinGam famously requires large sample sizes for accuracy,
this is not surprising.

Clark

**Comment by cg09** [comment]
Try it with different non-Gaussian noises?

**Comment by jdramsey** [comment]
Yay, we can finally close this issue! It's in development and has been checked!
