### ISSUE TITLE
Logging and unlogging data.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#611]
We need a gadget to take the log of a dataset. It should take in a dataset and apply the function f(x) = log(a + x) to each data point, where a can be specified. It would be helpful also if there were a gadget to allow the data to be unlogged as well, that is, for the function g(x) = exp(x) - a to be applied. These can be the same gadget with a switch, I suppose.

**Comment by espinoj** [comment]
@jdramsey I added the log unlog gadget to branch enhance.611 

Let me know if there is something I should change i.e., labels, default a value.

**Comment by jdramsey** [comment]
@espinoj I'll check it out now.

**Comment by jdramsey** [comment]
Beautiful. One small thing--could you put it in the list right before Nonparanormal transform? I.e.:

Convert to AR Residuals
Whiten
Logarithmic Transform
Nonparanormal Transform
..

I forget how to do that; maybe it's obvious.

Clark had mentioned wanting to set the base of the logarithm. I'll ask him about that. Normally that's not done.

**Comment by espinoj** [comment]
Thanks.  Ok I'll move it and add option for setting the base with the default base being e.

**Comment by jdramsey** [comment]
Nice.
