### ISSUE TITLE
Update Tetrad HPC to use updated REST API and Causal Cmd

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#614]
Tetrad HPC is hardcoded to allow HPC usage of GFCI and FGES but given that we have updated Causal-cmd to do almost any algorithm we can now allow HPC access to most algorithms

**Comment by espinoj** [comment]
Since @yuanzhou worked on REST API can keep tabs on his completion of that update

**Comment by yuanzhou** [comment]
The REST API has been updated to accommodate the new causal cmd. @chirayukong please let me know if you need me to make any other changes to the API to work with your HPC changes.

**Comment by azzaea** [comment]
Hello there,
Thank you for putting together such a powerful tool.
I'm new to Tetrad, so pardon me for maybe asking about the obvious- 

Where can I find documentation for cmd and the HPC usage you discuss here? The [wiki](https://github.com/cmu-phil/tetrad/wiki/Command-Line-Tetrad) lists other algorithms than what you mention, and doesn't touch on HPC at all. I'm particularly interested in the Markov Blanket algorithms currently implemented in GUI version 6.7.0; with mixed data (and my dataset is rather large, hence need to submit to a cluster). 

Thanks again!
Azza

**Comment by azzaea** [comment]
I think I found useful pointers here: https://bd2kccd.github.io/docs/causal-cmd/ (very elegant, btw); but no mention of how to submit jobs to a cluster.
I mean, does it imply the tetrad job will expand upon whatever resources I reserve as part of my  submissions script (eg via sbatch script on a slurm cluster); or that I should tell tetrad which queue, how many nodes, cores, .. etc explicitly?
Thanks again,
Azza

**Comment by chirayukong** [comment]
@azzaea you need to set up the REST API server on the HPC side in order to submit a job. Once, there is infrastructure ready, you can POST a job to the HPC node via API: https://bd2kccd.github.io/docs/causal-rest-api/ or Tetrad application.

**Comment by azzaea** [comment]
I see- thank you! 
Will ask my sys admin to set that up.
