### ISSUE TITLE
Loading a simulation in the GUI and trying to run a search on it results in an error

### ISSUE THREAD

**Issue by tzimiskes** [cmu-phil/tetrad#616]
I generated some data in the GUI using these parameters

![simparameters](https://user-images.githubusercontent.com/22644852/33561453-48a01e40-d8d8-11e7-80b8-6c10a9707548.png)

Then, I saved the simulation. Afterwards, I tried loading it and running a search; see Sumulation2 below

![tetraderror1](https://user-images.githubusercontent.com/22644852/33561352-0eca4ee8-d8d8-11e7-997b-b5e0b9128f06.png)

here is what stderr spat out [stderr.txt](https://github.com/cmu-phil/tetrad/files/1527773/stderr.txt)

Also, when TETRAD loads in the simulation it says the sample size is 1000 in stdout, but the GUI shows all 1500 samples being there.  What I'm referring to is also in stderr.txt. I don't know if this is a bug or something isn't being printed correctly.

I'm running TETRAD 6.3.4-0 and  openjdk version "1.8.0_151"

**Comment by espinoj** [comment]
Ok.  This is a confusing condition based on revision of the simulation/data boxes.  When saving a simulation it will only save the data and not the parameters of the simulation.  

Workaround:   Save the simulation
Place a databox in the worksspace
Load the simulation data into the databox
Conduct your search

We need to eliminate load simulation in the simulation databox and rephrase "Save Simulation" to "Save simulated data"

**Comment by jdramsey** [comment]
This is a non-issue now that loading simulations has been eliminated.
