### ISSUE TITLE
Sometimes simulation data changes if you search twice.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#630]
Sometimes if you have simulation->search and you simulate a dataset, then search twice on it, the dataset changes. So far I can't find the cause of it, but I thought I'd note it here.

For instance, if you make a Linear Fisher simulation, then search using FGES, then search again using FGES, the dataset changes.

**Comment by jdramsey** [comment]
Here's the problem I think. In VerticalDoubleDataBox, line 138,

        return new VerticalDoubleDataBox(data);

should be

        return new VerticalDoubleDataBox(copy);

I'll make a branch with that change if I remember.

**Comment by jdramsey** [comment]
@jeremy I included this fix in https://github.com/cmu-phil/tetrad/pull/703. I tested it previously; it solved the problem.

**Comment by jeremy** [comment]
Looks like Jeremy is @espinoj. CCing.

**Comment by jdramsey** [comment]
Thanks.

**Comment by jdramsey** [comment]
Fixed.
