### ISSUE TITLE
From the CCD Helpdesk

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#631]
Hi, a user (vincent.lous@gmail.com) send the next Tetrad problems:

*****
I have the following issues when working with the newest Tetrad (6.3.4-0) :
- when linking a knowledge box to a search box the knowledge tab in the search box does not reflect the knowledge box 
- the estimator box says "could not create a model" when i create a SEM PM on mixed data.  What are some possible causes for that error to appear? 

![sessiongraphimage](https://user-images.githubusercontent.com/32989853/34574325-1129ba7c-f145-11e7-9b92-4bd6fa2a5c77.png)

*****

@espinoj @jdramsey

**Comment by espinoj** [comment]
Think we can close this now with the latest development version?

**Comment by cabal-cmu** [comment]
Yep.
