### ISSUE TITLE
Laplace edit.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#632]
GeneralizedTemplateEditor, line 556, this:

                {"Laplace(mu, beta)", "Beta(%, %)"},

should be

                {"Laplace(mu, beta)", "Laplace(%, %)"},

I can do this when I'm in an appropriate branch, or anyone else can.

**Comment by yuanzhou** [comment]
I'll go ahead fix this in a separate branch and send the pull request to merge.
