### ISSUE TITLE
Simulation box does not use input graph

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#633]
In 6.4.0-0, downloaded today, the simulation box will not simulate data based on an input graph. Simulation boxes with graph input boxes act as though they are parentless simulation boxes.
<img width="1430" alt="screen shot 2018-01-07 at 2 04 24 pm" src="https://user-images.githubusercontent.com/15677053/34653042-30536350-f3b4-11e7-970b-1b3afd2a3159.png">

**Comment by kvb2univpitt** [comment]
Fixed.
