### ISSUE TITLE
"Replace Missing Values With Regression Predictions" never finishes

### ISSUE THREAD

**Issue by pschaldenbrand** [cmu-phil/tetrad#635]
When I use the data component to fill in missing values with regression predictions, the executing box pops up but never finishes.  Sometimes while trying to cancel this operation, the program all together crashes or stops responding.

**Comment by jdramsey** [comment]
It's doing a separate regression for each row given all of the other variables. It's possible this is just too large a task for it, though it could be put into a thread to keep from crashing.

**Comment by jdramsey** [comment]
@pschaldenbrand I'm wondering, could you say what the dimensions of your problem were? How many samples, now many variables?

**Comment by pschaldenbrand** [comment]
@jdramsey I was using a few datasets that had around five variables and 1000 samples.  I made a tiny dataset (below) to try to get this feature to finish executing, but it still did not complete.  I'm using the 6.3.4-launch.jar by the way.

X1	X2	X3
0	*	1
1	0	1
0	0	0

**Comment by jdramsey** [comment]
@pschaldenbrand Interesting. I'll ponder it. I'll try your dataset. There may not be enough data to regress on, or it may be singular, but even so, it doesn't help to just hang.
