### ISSUE TITLE
Error in DAG to PAG procedure and possibly in FCI orientation rules

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#636]
In the latest release of Tetrad, I created the following graph:

![image](https://user-images.githubusercontent.com/16494809/34738233-66d2178a-f546-11e7-9d09-83ad19e21e23.png)

I believe the correct PAG for the above DAG is:

![image](https://user-images.githubusercontent.com/16494809/34738342-b6bb57a2-f546-11e7-84a0-ef9ea1ba8c00.png)

However, using the DAG to PAG procedure, Tetrad outputs the following incorrect PAG (note the incorrect edge between C and D):

![image](https://user-images.githubusercontent.com/16494809/34738385-d40ec49c-f546-11e7-98d2-047257d8abd5.png)

To test if this is an error in FCIs orientation rules, I simulated 20,000 samples using the SEM simulation; here are the parameters:

![image](https://user-images.githubusercontent.com/16494809/34738484-1e2dcb54-f547-11e7-8f5b-0a817eeb2785.png)

FCI was run with Fisher's Z test; here are the parameters:

![image](https://user-images.githubusercontent.com/16494809/34738565-644df136-f547-11e7-9376-3353bf48ba92.png)

The result of FCI (which suggests something is wrong with the orientation rules, note C to D) is as follows:

![image](https://user-images.githubusercontent.com/16494809/34738609-8b10ad9a-f547-11e7-9532-f23d40f24eae.png)

**Comment by bja43** [comment]
Actually, C is an indirect cause of D, so the FCI output is correct.  However, the DAG to PAG procedure still appears to be incorrect to me.

**Comment by dmalinsk** [comment]
Brian,

Can you tell which orientation rule is being used to orient that circle
mark / are you sure that it isn't behaving correctly? I think it might be
using R4 in FCI, which orients the Co->D circle because of a discriminating
path. The definition is a bit confusing so double-check on that.

DAG2PAG uses those same orientation rules so if it is R4 then both are
correct.

--Dan

**Comment by dmalinsk** [comment]
that is: <A,B,C,D> is a discriminating path for C

**Comment by bja43** [comment]
I see, thanks for clarifying. It seems that the only issue is that the DAG2PAG procedure does color or dash the output edges which need to be colored and or dashed.  I'll look into it.
