### ISSUE TITLE
Clark: search box shouldn't require scrolling to get to set parameters

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#637]
In Search box move set parameters choose algorithm and run search to where the done button is.

**Comment by kvb2univpitt** [comment]
![screenshot at 2018-01-12 11-36-28](https://user-images.githubusercontent.com/10729309/34885384-d33b8a5c-f78d-11e7-9fc0-856e89e0ed92.png)

Done.

**Comment by espinoj** [comment]
confirmed moved the button
