### ISSUE TITLE
Clark: R1,R2, and R3 do not work.  Remove R4

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#650]
R1 does not work.

R2 does not work, R3 does not work

R4 should be removed

**Comment by yuanzhou** [comment]
Do we want to remove the R4 class file or just the annotation but still keep the class?

**Comment by espinoj** [comment]
for R4 and EB keep the class.  Check with @kvb2univpitt about the experimental annotation which we will use later as an option to show all available algorithms.

**Comment by yuanzhou** [comment]
Fixed via pull request #667
