### ISSUE TITLE
Time Series Simulation needs coefficients to be set

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#655]

**Comment by jdramsey** [comment]
@espinoj You can already set coefficient for time series graphs--see the attached image. However, the range is wrong I recommend setting "coefficient low" and "coefficient high" in ParamDescriptions to 0.2 and 0.9, respectively, to prevent time series from exploding, as shown.

@espinoj @cg09 

<img width="1292" alt="screen shot 2018-01-31 at 9 35 07 am" src="https://user-images.githubusercontent.com/9853255/35628500-184f6cc2-066a-11e8-9dcb-6f9821d48df9.png">

**Comment by jdramsey** [comment]
Fixed these ranges.
