### ISSUE TITLE
MIMBUILD and covariance matrix

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#656]
Feature request - obtain inferred covariance matrix from the latents from the MIMBUILD from a data box attached to mimbuild (parent).

**Comment by espinoj** [comment]
Data box will have get covariance boxes from cluster (just FOFC, BPC for now).  Covariance matrix then will feed to any search procedure (PC, FGES etc)

**Comment by jdramsey** [comment]
@espinoj @kvb2univpitt  It already does this. We just couldn't get Mimbuild to work before Kevin's recent fixes. Attaching image.

<img width="971" alt="screen shot 2018-01-31 at 9 30 03 am" src="https://user-images.githubusercontent.com/9853255/35628293-74576304-0669-11e8-88fb-d6957ff149be.png">

**Comment by kvb2univpitt** [comment]
@jdramsey So, this is not an issue anymore, right?

**Comment by jdramsey** [comment]
@kvb2univpitt Right.

**Comment by kvb2univpitt** [comment]
@jdramsey Ok.  I'll close it.  Another easy fix. ;)
