### ISSUE TITLE
Estimating SEM from correlation matrix

### ISSUE THREAD

**Issue by scheines** [cmu-phil/tetrad#658]
The estimator refused to do its thing when the data is a correlation matrix for a SEM PM.  Below the data file - but I can't attach a .tet file.  Graph is Pre--> Final, Pre --> Print --> Vol --> Quiz --> Final
[pitt_newer.txt](https://github.com/cmu-phil/tetrad/files/1626321/pitt_newer.txt)

**Comment by espinoj** [comment]
In development branch covariance file loads ok.  I recall that we did some bug fixes in covariance loading on this round.

**Comment by espinoj** [comment]
Discussed with @jdramsey.  I'm making a ScoreType enum class that will be used everywhere.

**Comment by espinoj** [comment]
@scheines today's development build has the fix
https://cloud.ccd.pitt.edu/nexus/content/repositories/snapshots/edu/cmu/tetrad-gui/6.4.0-SNAPSHOT/tetrad-gui-6.4.0-20180116.180138-162-launch.jar
