### ISSUE TITLE
Clark: red-green arrow stickiness

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#677]
The red - green arrow manipulation needs to stay on until another tool (left column) is clicked.

**Comment by yuanzhou** [comment]
I just tested and the arrow button box stays clicked until I click another box in the pipeline.

**Comment by espinoj** [comment]
I think Clark was referring to the knowledge box editor for required and forbidden edges.  I tested in the knowledge box editor and the tool stays sticky. 

Looks like this is not broken.
