### ISSUE TITLE
Clark: Updater takes a SEM IM but does nothing with it

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#680]
The Updater takes a SEM IM but does nothing with it.  What should it do?

**Comment by jdramsey** [comment]
The problem I think is that the SEM update modifies the _means_ of the model, but the means of the model are not being displayed for some reason.

@espinoj

**Comment by kvb2univpitt** [comment]
@espinoj @jdramsey I'll take a stab at it.

**Comment by kvb2univpitt** [comment]
Fixed.

**Comment by espinoj** [comment]
Works but as Kevin has reported we should revisit the redraw of the graph image at some point
