### ISSUE TITLE
Clark:  Estimator does not work with latent variable models

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#681]
The Estimator does not work with latent variable models--complains that the data matrix does not have the same dimension as the PM.

**Comment by jdramsey** [comment]
I *think* the only estimator we have for the continuous case that can handle a latent variable model is RICF, but you first have to turn the (DAG) latent variable model into a MAG.

Need input on this from Clark, Peter.

@kvb2univpitt

**Comment by kvb2univpitt** [comment]
@jdramsey We fixed the bug.  Should we merge to the development branch or wait until you get more information from Clark/Peter?

**Comment by jdramsey** [comment]
@kvb2univpitt I'll talk to Clark tomorrow. Also, can you send me the branch name? Maybe I'll look at it as well.

**Comment by kvb2univpitt** [comment]
@jdramsey The branch is v6.4.0-fix-estimator.

**Comment by jdramsey** [comment]
@kvb2univpitt Thanks, I'll discuss it with Clark this afternoon.

**Comment by kvb2univpitt** [comment]
Done.

**Comment by jdramsey** [comment]
If it's of any help, I talked about that with Clark, and he agreed with your analysis.
