### ISSUE TITLE
Clark: There is no information about what classifier is being used.

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#682]
There is no information about what classifier is being used.

**Comment by kvb2univpitt** [comment]
@espinoj Need more description for this issue.  Where should the information about the classifier appear when doing what?

**Comment by espinoj** [comment]
From the source code it is using a discrete Bayes updating interface of which there are 6 instantiations but by default it is using RowSummingExactUpdater.

![image](https://user-images.githubusercontent.com/313721/35290282-c018df58-0037-11e8-876f-fa17b7713cb7.png)

Is this the type of information wanted in the classifier output i.e., text output?

**Comment by espinoj** [comment]
Do we want an option for choosing a different BayesUpdater besides RowSumming?

**Comment by espinoj** [comment]
Clark says no recoding needed just a description needed.

**Comment by jdramsey** [comment]
This has been taken out of the interface by popular demand.
