### ISSUE TITLE
Clark: can't save output graph image within a SEARCH box

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#684]
An output graph image within a SEARCH box cannot be saved. Instead an image of the main workspace is saved

**Comment by espinoj** [comment]
This is the correct behavior but label for saving the workspace image is confusing.  If one wants to save the graph attach a graph box and then "Save Graph Image."

![image](https://user-images.githubusercontent.com/313721/35296704-e768e072-004a-11e8-9c6f-aca7434fc6dd.png)

Suggest changing "Save Session Graph Image" to "Save session workspace image"

**Comment by yuanzhou** [comment]
I just tested and the "Save Graph Image" option works if you open the Graph editor.

![capture](https://user-images.githubusercontent.com/195873/35296920-81de6424-004b-11e8-83d4-d35e09e889d4.PNG)

I agree with @espinoj that we should rephrase the selection.

**Comment by espinoj** [comment]
pushed and merged the label change
