### ISSUE TITLE
Clark: Changes in the PM box made with the Expression Editor are not propagated to the IM Box

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#688]
Tetrad file attached - zipped.

[PM to IM propagation.tet.zip](https://github.com/cmu-phil/tetrad/files/1652763/PM.to.IM.propagation.tet.zip)

**Comment by espinoj** [comment]
Looks like expressions are working in current development version.  Here Kevin added a pow function in the PM box which we later saw in the IM box.  Are we missing something here?


![edit_expression](https://user-images.githubusercontent.com/313721/35288942-031b9da8-0034-11e8-8989-08290dafb02c.png)

![im_result](https://user-images.githubusercontent.com/313721/35288949-09e46f34-0034-11e8-8384-c3f3331bdd04.png)

**Comment by jdramsey** [comment]
Is it possible Clark is referring to the relationship between the generalized SEM PM and generalized SEM IM?

**Comment by espinoj** [comment]
I think you're right @jdramsey - Generalized SEM.  So is this a propagate changes bug or do we have to do something smarter?

**Comment by jdramsey** [comment]
I think it must just be a propagate changes problem. I think if you make changes in the Generalized SEM PM, it should force the Generalized SEM IM to reinitialize. I think you just need to fire more of these:

**Comment by jdramsey** [comment]
Sorry, more of these:

firePropertyChange("modelChanged", null, null);

At the appropriate point where stuff is changed.

Joe

**Comment by espinoj** [comment]
This is working in our current development branch.  6.3.4 not so much.
