### ISSUE TITLE
Feature Request/Maybe Bug: Saving Multiple Graphs at once

### ISSUE THREAD

**Issue by tzimiskes** [cmu-phil/tetrad#696]
When using Tetrad 6.3.4, you can simulate multiple data sets by modifying the number of runs in the simulation box, and you can save the entire simulation to disk. Now, if I run a search on the input from from the simulation box, the search will automatically run my chosen algorithm on all the datasets, but I can't save all the output graphs at once. I know I could just run everything through algcomparison, but doing so through the GUI would make my life easier.

**Comment by espinoj** [comment]
The intent on simulating multiple datasets in a single simulation was for algorithms like ImaGES that take as input multiple datasets generated from a canonical graph and generate a single graph.  Your use case wasn't something we were considering.

This is definitely a feature request that we can consider to include in future development- i.e., save multiple graphs generated through a single pipeline from a multiple run simulation. 

Thanks

**Comment by jdramsey** [comment]
@espinoj With Zhou's help, I just solved https://github.com/cmu-phil/tetrad/issues/952, so now you can save out all datasets and graphs plus parameters from the simulation box. Is this good enough?

**Comment by jdramsey** [comment]
OK, I'm going to interpret stunned silence on this issue as a yes. :) Closing.

**Comment by tzimiskes** [comment]
Ha! I was busy planning a move and job switch, so I don't think I ever followed up with this.
