### ISSUE TITLE
Pass knowledge from data to search if available.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#698]
This is particularly relevant to time lag data. The generalized algorithm editor used to do this. The time lag data creates knowledge that the future doesn't cause the past. I added a few lines of code so that if you attach a Knowledge box to a Time Lag Data box you can see the knowledge and manually give it to a search if you want. The pull request is here:

https://github.com/cmu-phil/tetrad/pull/697

But this connection should be automatic if the data creates a knowledge object on its own--i.e. implements the HasKnowledge interface.

**Comment by jdramsey** [comment]
This is what it's supposed to do:

<img width="577" alt="screen shot 2018-01-29 at 11 00 05 am" src="https://user-images.githubusercontent.com/9853255/35519923-9d8d74ca-04e3-11e8-8428-0bd87e707e49.png">
<img width="984" alt="screen shot 2018-01-29 at 10 59 53 am" src="https://user-images.githubusercontent.com/9853255/35519924-9dd830e6-04e3-11e8-861a-2fca24aa4830.png">
<img width="581" alt="screen shot 2018-01-29 at 10 59 39 am" src="https://user-images.githubusercontent.com/9853255/35519925-9dea41a0-04e3-11e8-82a2-2f636157cb6c.png">
<img width="622" alt="screen shot 2018-01-29 at 10 59 23 am" src="https://user-images.githubusercontent.com/9853255/35519926-9df49bfa-04e3-11e8-819c-2132342a946f.png">

**Comment by jdramsey** [comment]
This session.

<img width="329" alt="screen shot 2018-01-29 at 11 04 48 am" src="https://user-images.githubusercontent.com/9853255/35520165-40939a3c-04e4-11e8-9fad-225d36eec467.png">

**Comment by cg09** [comment]
@cg09

**Comment by jdramsey** [comment]
Duplicate:

https://github.com/cmu-phil/tetrad/issues/704
