### ISSUE TITLE
time index column in time series data generation 

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#700]
Currrently the time series column in the midst of the data columns is mislabeled--the entries in that column are not the times. There is a correct data column at the end of the file.

**Comment by jdramsey** [comment]
I was working on this, so I self-assigned it. I have fixed the mislabeling problem by removing the variable sorting operation from the time lag filter. (That was a bad idea anyway.) The Time Lag with Index I replaced with just an Add Index manipulation. It's usually not reasonable for someone to add an index to the data and then also lag it. (Why would you do that? The Time variable will be disconnected anyway.) But if someone _wants_ to do that they can add another box to lag the data with the index variable in it.

I fixed the problem where if you put TimeLag->Knowledge double click knowledge, showing the time lag knowledge, then destroy and recreate the knowledge, it wouldn't give you back the knowledge. Still, if you destroy and recreate the time lag data, then double-click knowledge, there are no tiers. But if you then destroy and recreate the knowledge the tiers appear again. Not sure what's happening.

**Comment by jdramsey** [comment]
Pull request https://github.com/cmu-phil/tetrad/pull/703

Here is a session that does the desired behavior:

[timelagsearchexample2.tet.zip](https://github.com/cmu-phil/tetrad/files/1675063/timelagsearchexample2.tet.zip)

**Comment by espinoj** [comment]
Great
