### ISSUE TITLE
Fix capitalization of these algorithms...

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#705]
In the Search box.

Bpc -> BPC
FgesMb -> FGES-MB
Fofc -> FOFC
Ftfc -> FTFC
TsImage -> TsIMaGES

@cg09 @espinoj

**Comment by yuanzhou** [comment]
I'll work on this renaming and sync with @kvb2univpitt  on the API and Causal CMD.

**Comment by yuanzhou** [comment]
Fixed via pull request #708
