### ISSUE TITLE
Error message with TsIMaGES

### ISSUE THREAD

**Issue by yuanzhou** [cmu-phil/tetrad#709]
When I ran TsIMaGES on a single continuous or discrete dataset, I got this error message:

 
![capture1](https://user-images.githubusercontent.com/195873/35644674-96cae568-0697-11e8-8bdd-d00718b7d0a7.PNG)

![capture2](https://user-images.githubusercontent.com/195873/35644677-98c2ae64-0697-11e8-9205-e137ac43dbd2.PNG)

**Comment by yuanzhou** [comment]
Any suggestions @jdramsey ?

**Comment by jdramsey** [comment]
@yuanzhou Well here's a mistake; I wonder if this would fix it? This code block:

        if (score instanceof SemBicScore) {
            SemBicScoreImages gesScore = new SemBicScoreImages(dataModels);
            gesScore.setPenaltyDiscount(parameters.getDouble("penaltyDiscount"));
            IndependenceTest test = new IndTestScore(gesScore);
            search = new TsGFci(test, gesScore);
        } else if (score instanceof BDeScore) {
            double samplePrior = parameters.getDouble("samplePrior", 1);
            double structurePrior = parameters.getDouble("structurePrior", 1);
            BdeuScoreImages score = new BdeuScoreImages(dataModels);
            score.setSamplePrior(samplePrior);
            score.setStructurePrior(structurePrior);
            IndependenceTest test = new IndTestScore(score);
            search = new TsGFci(test, score);
        } else {
            throw new IllegalStateException("Sorry, data must either be all continuous or all discrete.");
        }

When it says  if (score instanceof BDeScore), that should be BdeuScore. You can see down further Bdeu is meant.

**Comment by yuanzhou** [comment]
Thanks @jdramsey, you have eagle eyes. I'll test it out.

**Comment by kvb2univpitt** [comment]
@yuanzhou  @jdramsey This issue is fixed.  However, TsIMaGES is still not able to run because there's a bug in edu.cmu.tetrad.search.TsFges2.  I will create a different issue for this bug.

**Comment by jdramsey** [comment]
Thanks!

**Comment by yuanzhou** [comment]
I noticed some bugs during testing, posted in the pull request thread #721 

Also link this issue to #722

**Comment by kvb2univpitt** [comment]
@yuanzhou That bug is not related to this issue.  That bug is has to do with algorithm handing invalid indices.

**Comment by yuanzhou** [comment]
This issue has been addressed via pull request #721
