### ISSUE TITLE
graph display in knowledge

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#713]
The knowledge box is supposed to take a directed graph specified as "required"--when a graph box is connected to it, the names of the variables appear, but no edges appear.

**Comment by kvb2univpitt** [comment]
@cg09 Can you please elaborate on that?  Can you attach a screenshot or a session file?

**Comment by jdramsey** [comment]
@kvb2univpitt I can give a description later. I'm going to a talk at 12 but after that. -Joe  @cg09

**Comment by kvb2univpitt** [comment]
Done.
