### ISSUE TITLE
Comparison Box Error

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#715]
The comparison box makes errors when a search returns two edges X -> Y and X<-Y when the true graph has only one direction, e.g., X -> Y. The comparison box does not in such cases recognize X <- Y as an error.

**Comment by jdramsey** [comment]
True. It should ding the adjacency precision number. If I remember, I will adjust that.

@cg09

**Comment by jdramsey** [comment]
I think we agreed that the error counting for this was OK. There are no adjacency errors and one 2-cycle error. I'll close this, and if someone thinks that's a mistake they can reopen it.
