### ISSUE TITLE
Random graph control

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#726]
In the graph box, selecting "graph" then "random graph" and specifying indegree, outdegree, total degree and connectivity etc. inconsistently produces some graph or other. There should be some error warning instead.

**Comment by yuanzhou** [comment]
I noticed that too. When I decreased the number of nodes from 10 to 3, but forgot to change the default max number of edges (10), I don't see any graph or error messages.

@jdramsey there are three tabs in the Random Graph panel: DAG, MIM, and Scale Free. Can you please list some of the common validation rules between those settings? One of the obvious is thenumber of nodes can not be smaller than the number of edges. I'm not sure if you want to add any additional rules?

**Comment by cg09** [comment]
SINCE THE PARAMETERS ARE IN TERMS OF "MAX" EDGES OF VARIOUS KINDS, THERE ARE NO INCONSISTENCIES, JUST ODDITIES.  JOE, PLEASE HELP WITH THE QUESTION ABOUT SETTINGS FOR DAG, MIM AND SCALE FREE.

**Comment by cg09** [comment]
There are possible inconsistencies if "Connected" is specified, e.g.  if the max degree is say 10 and there are 10 nodes, the graph cannot be connected.  I am not sure it is worth fixing  the possible inconsistencies.  The user should maybe use some sense?

**Comment by cg09** [comment]
Parameter consistentcy in IM

Joe, this does not look consistent.  Look for example at the parameters for X3 = b1 X1 + E3 so the mean of X3 should be b1 (mean X1) + mean(E3) =. 0 + 1.54 ...but mean( X3) was fixed at 1.0.
<img width="403" alt="screen shot 2018-02-12 at 12 59 00 pm" src="https://user-images.githubusercontent.com/16354745/36112946-36f42b2a-0ff9-11e8-901f-0ba3afc4f6cc.png">

**Comment by cg09** [comment]
The mean of X3 is supposed here to be fixed at 1 and this is what the tabular view says--but since the expected value of X1 is 0 and of E3 is 1.54, and b1 is 1.0, this seems impossible.  It looks as if the interface is just taking whatever arbitrary numbers are given to it for the means, with no regard for consistency.



<img width="521" alt="screen shot 2018-02-12 at 1 28 32 pm" src="https://user-images.githubusercontent.com/16354745/36113053-8a82a9a6-0ff9-11e8-935d-5c1d985f1ecb.png">

<img width="500" alt="screen shot 2018-02-12 at 1 37 04 pm" src="https://user-images.githubusercontent.com/16354745/36113157-e959277a-0ff9-11e8-93a4-5ed203632c5c.png">

**Comment by jdramsey** [comment]
@cg09 @yuanzhou Can you tell me the state of this? Sorry, it somehow escaped my attention.

The total number of adjacencies in the graph cannot exceed n ( n + 1 ) / 2, where n is the number of nodes. That's one rule.
