### ISSUE TITLE
right clicking graph box

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#727]
right clicking "graph box" brings up "edit parameters" option--which seems to do nothing.

**Comment by kvb2univpitt** [comment]
@jdramsey What would be the correct behavior for this?

**Comment by jdramsey** [comment]
@kvb2univpitt I guess if there are no parameters to edit, that menu item shouldn't show...

**Comment by cg09** [comment]
I agree.

**Comment by kvb2univpitt** [comment]
@jdramsey If there are no parameters to edit, a pop-up appears with the message "There are no parameterization for this model."  If there are parameters, it says "Should I over the contents of this box and all delete the contents of all boxes downstream?"  All the children boxes are destroyed.  Right now this is what it's doing.  I am still confused to what's wrong.

**Comment by kvb2univpitt** [comment]
Basically, remove the menu item "Edit Parameters" if there are no parameters to edit.

**Comment by cg09** [comment]
Yep.

**Comment by kvb2univpitt** [comment]
@jdramsey @cg09 I made the fix.  However, I am still not confident that I have cover all edge cases.  Can you please checkout the branch [v6.4.0-fix-graph-box](https://github.com/cmu-phil/tetrad/tree/v6.4.0-fix-graph-box) and try it?

The method below still return true even if there are no children.  So, I had to check the number of children.
```java
getSessionNode().existsParameterizedConstructor(modelClass)
```

**Comment by jdramsey** [comment]
@kvb2univpitt I looked at what you did and thought maybe there's an easier way to get at the idea. I just use reflection to see if I can construct the parameterized editor, and if I can't, I don't show the menu item. I think it should be foolproof. Can you check my work? I made the change in your branch, v6.4.0-fix-graph-box.

**Comment by kvb2univpitt** [comment]
@jdramsey I thought the method ``` existsParameterizedConstructor() ``` already does that?  That's why I used that method.  OK.  Let me take a look at what you did.

**Comment by kvb2univpitt** [comment]
@jdramsey I checked out the changes you made.  It seems like the "parameterized editor" option is not showing up anymore, even when it should.

**Comment by kvb2univpitt** [comment]
@jdramsey Thanks for clarifying this.  Done.
