### ISSUE TITLE
"meek orientations"

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#729]
in Graph graph popup "meek orientations" does nothing. What is it supposed to do?

**Comment by jdramsey** [comment]
@cg09 If you have X->Y<-Z, Y--Z, for example, it will orient Y->Z. If you graph allows for no further Meek orientation, it will do nothing.

I'm not committed to keeping the function there if it's confusing.

**Comment by cg09** [comment]
If you input graph Z -> X <- Y; X 0-0 W,  (you cannot put in simple
undirected edges in the graph box), nothing is done to the X 0-0 edge. Meek
rules say what should happen.

Clark

**Comment by jdramsey** [comment]
This is too confusing. I say we remove that menu item. For instance, to make undirected edges manually, you need to control-click on the endpoints. To add an undirected edge button we'd need to go back and make an icon for it and add another edge button to the Graph box.

**Comment by cg09** [comment]
Ok with me to delete it.

**Comment by jdramsey** [comment]
@kvb2univpitt @cg09 I commented out all of the "Meek Orientations" menu items, as per Clark's suggestion, in this pull request: https://github.com/cmu-phil/tetrad/pull/746. No actual Meek orientation functionality was harmed by this procedure.
