### ISSUE TITLE
command line "tetrad.jar" doesn't work. 

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#73]
Hi, 

I followed the introduction for command line tetrad here,
https://github.com/cmu-phil/tetrad/wiki/Command-Line-Tetrad

But, it doesn't seem to work well for me.  I am using linux server, and I think my java version is fine. Please look at below the java version checking and 'tetrad.jar' running, and error message.  I attached my sample input file.    Could you help me?

[Simulated_example.txt](https://github.com/cmu-phil/tetrad/files/47814/Simulated_example.txt)

[user167@login0 8_TETRAD]$ java -version
java version "1.6.0_24"
OpenJDK Runtime Environment (IcedTea6 1.11.1) (rhel-1.45.1.11.1.el6-x86_64)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)
[user167@login0 8_TETRAD]$ java -jar lib-tetrad-5.3.0-20151113.150857-1-tetracmd.jar -data Simulated_example.txt -datatype discrete -algorithm pc -depth -1 significance 0.01
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/cmu/tetrad/cmd/TetradCmd : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: edu.cmu.tetrad.cmd.TetradCmd. Program will exit.
[user167@login0 8_TETRAD]$

**Comment by jdramsey** [comment]
I don't understand--you compiled this yourself but get a class conflict
when you try to use it? Is it possible you're using a different Java to
compile than to run?

-J

On Mon, Nov 30, 2015 at 4:14 PM, biotech25 <notifications@github.com> wrote:

> Hi,
>
> I followed the introduction for command line tetrad here,
> https://github.com/cmu-phil/tetrad/wiki/Command-Line-Tetrad
>
> But, it doesn't seem to work well for me. I am using linux server, and I
> think my java version is fine. Please look at below the java version
> checking and 'tetrad.jar' running, and error message. I attached my sample
> input file. Could you help me?
>
> Simulated_example.txt
> <https://github.com/cmu-phil/tetrad/files/47814/Simulated_example.txt>
>
> [user167@login0 8_TETRAD]$ java -version
> java version "1.6.0_24"
> OpenJDK Runtime Environment (IcedTea6 1.11.1) (rhel-1.45.1.11.1.el6-x86_64)
> OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)
> [user167@login0 8_TETRAD]$ java -jar
> lib-tetrad-5.3.0-20151113.150857-1-tetracmd.jar -data Simulated_example.txt
> -datatype discrete -algorithm pc -depth -1 significance 0.5
> Exception in thread "main" java.lang.UnsupportedClassVersionError:
> edu/cmu/tetrad/cmd/TetradCmd : Unsupported major.minor version 51.0
> at java.lang.ClassLoader.defineClass1(Native Method)
> at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
> at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
> at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
> Could not find the main class: edu.cmu.tetrad.cmd.TetradCmd. Program will
> exit.
> [user167@login0 8_TETRAD]$
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/73>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Oh wait, I have a better hypothesis--you're using the tetrad cmd you downloaded from the website and tried using it on your machine. That one was compiled using Oracle Java but you're using Open JDK, a conflict. In that case, the solution is to compile it yourself. Run (in the tetrad repository directory) this command:

mvn package

then find the jar that you just compiled with the same kind of name (it's in one of the target directories), and use it.

Let me know.

**Comment by biotech25** [comment]
I typed the command 'mvn package', but I got this message.

[user167@login0 8_TETRAD]$ mvn pacakgage
-bash: mvn: command not found

It seems like I need to install maven.  I am sorry that I am a beginner of this maven thing.  Do I need to install maven first?  

Thank you, 
Sanghoon

**Comment by jdramsey** [comment]
Yes, but you're on a linux box so it should be easy.

J

On Mon, Nov 30, 2015 at 5:03 PM, biotech25 <notifications@github.com> wrote:

> I typed the command 'mvn package', but I got this message.
>
> [user167@login0 8_TETRAD]$ mvn pacakgage
> -bash: mvn: command not found
>
> It seems like I need to install maven. I am sorry that I am a beginner of
> this maven thing. Do I need to install maven first?
>
> Thank you,
> Sanghoon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/73#issuecomment-160776022>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Actually type this instead:

mvn package -DskipTests

The tests take a while.

**Comment by biotech25** [comment]
I installed Maven and typed "mvn package -DskipTests" as you explained, but I got the similar error message. Please see below. I am going to use another Linux server in my lab, and update you later. Thank you!


[user167@login0 8_TETRAD]$ mvn package -DskipTests
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by jdramsey** [comment]
Sorry to ask dumb questions, but when you type java -version, what does it
say? Is your system up to date? What Linux do you have? If it's Ubuntu,
have you recently typed

sudo apt-get upgrade

? I know these are dumb questions, but I don't understand why your Maven is
out of sync with your java. If you're using a standard distro that
shouldn't be possible, unless the distro screwed up.

It's possible it's some other kind of problem I haven't thought of yet, but
we've been using maven and OpenJDK on our Ubuntu Linux machines without a
hitch with this repository, if that's of any help.

J

On Mon, Nov 30, 2015 at 7:08 PM, biotech25 <notifications@github.com> wrote:

> I installed Maven and typed "mvn package -DskipTests" as you explained,
> but I got the similar error message. Please see below. I am going to use
> another Linux server in my lab, and update you later. Thank you!
>
> [user167@login0 8_TETRAD]$ mvn package -DskipTests
> Exception in thread "main" java.lang.UnsupportedClassVersionError:
> org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
> at java.lang.ClassLoader.defineClass1(Native Method)
> at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
> at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
> at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
> at
> org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
> at
> org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
> at
> org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
> at
> org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
> at
> org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/73#issuecomment-160804497>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
It just occurred to me that maybe you're using Redhat Enterprise, in which case the Maven that you get is 2.2, and the Tetad project is using 2.3. To see, type

mvn --version

I'm not sure how you can get 2.3 except to download and compile it. I noticed that on a server that have yesterday.

Sorry to just keep coming up with options; I can't see your server. You may have to debug this yourself. Maybe one of the ideas I suggested will work, though.

If you're behind on OpenJDK versions because the distro is conservative, maybe there's a way to bring the server up to a more recent OpenJDK. You'd have to google it.

**Comment by jdramsey** [comment]
Sorry, I just looked back at your message; your Java version on the server is 1.6; we're compiling to 1.7 (already behind since the current version is 1.8). That could be the source of the problem. See if you can find a way to bring Java up to 1.7.

**Comment by jdramsey** [comment]
Here's what java -version gives me on the latest Ubuntu:

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

so there is an OpenJDK that will work.

**Comment by biotech25** [comment]
Thank you so much for your eamils.  I was using a public linux server with my personal account. So, I don't have sudo authority. I think the linux server is Red Hat as you see below. 

When I typed "alternatives --config java" and chose one, I got a message, 'permission denied', as you see below.  

My lab has a linux workstation and I have sudo authority. I am going to update java in the lab linux workstation, and try to use TETRAD cmd. I am going to update you soon. 

Sanghoon

******************************************************************************************
[user167@login0 bin]$ update-alternatives -config java
alternatives version 1.3.49.3 - Copyright (C) 2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.

usage: alternatives --install <link> <name> <path> <priority>
                    [--initscript <service>]
                    [--slave <link> <name> <path>]*
       alternatives --remove <name> <path>
       alternatives --auto <name>
       alternatives --config <name>
       alternatives --display <name>
       alternatives --set <name> <path>

common options: --verbose --test --help --usage --version
                --altdir <directory> --admindir <directory>
[user167@login0 bin]$

*****************************************************************************************
[user167@login0 ~]$ alternatives --config java

There are 2 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           /usr/lib/jvm/jre-1.5.0-gcj/bin/java
*+ 2           /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java

Enter to keep the current selection[+], or type selection number: 2
failed to create /var/lib/alternatives/java.new: Permission denied
[user167@login0 ~]$

**Comment by biotech25** [comment]
I tested TETRAD cmd in another Linux server. (This is not the Linux workstation in my lab. The Linux workstation has a small problem so I am solving it)  The linux server has java version 1.7.0_85 as seen below.  Now, it is working well. Please see below.  As you anticipated, I think I need java 1.7.0 at least to run TETRAD.   

Thank you so much!
Sanghoon

*****************************************************************************************

[u0607770@ember1 ~/8_TETRAD]$ java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

[u0607770@ember1 ~/8_TETRAD]$ java -jar lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar -data tgen_40SNPs_1411cases_3bins.txt -datatype discrete -algorithm pc -depth -1 -significance 0.01
Loading data from tgen_40SNPs_1411cases_3bins.txt.
Dec 01, 2015 8:03:57 AM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /uufs/chpc.utah.edu/common/home/u0607770/.java/.userPrefs/prefs.xml
# variables = 41, # cases = 1411

Result graph:

Graph Nodes:
SNP_A-1999417_2 SNP_A-1999418_3 SNP_A-4192853_4 SNP_A-2125845_3 SNP_A-2115216_4 SNP_A-2228997_3 SNP_A-2105786_2 SNP_A-2127756_3 SNP_A-2271390_2 SNP_A-2134365_1 SNP_A-1999524_1 SNP_A-1840727_3 SNP_A-1938816_4 SNP_A-4202256_2 SNP_A-4205973_3 SNP_A-1839049_2 SNP_A-2278207_2 SNP_A-2240781_2 SNP_A-2015050_4 SNP_A-1829356_4 SNP_A-1892946_3 SNP_A-2209876_2 SNP_A-1783218_4 SNP_A-2212110_4 SNP_A-2015053_3 SNP_A-2252628_3 SNP_A-2113000_4 SNP_A-2113126_4 SNP_A-4213863_4 SNP_A-4293137_1
SNP_A-2227832_3 SNP_A-4267982_1 SNP_A-2210063_4 SNP_A-4281580_2 SNP_A-2103840_3 SNP_A-2160694_2 SNP_A-2046895_2 SNP_A-1999636_2 SNP_A-1926614_1 APOE class

Graph Edges:
1. APOE --- class
2. SNP_A-1829356_4 --- SNP_A-2015053_3
3. SNP_A-1829356_4 --> SNP_A-2212110_4
4. SNP_A-1840727_3 --> SNP_A-1999524_1
5. SNP_A-1892946_3 --> SNP_A-1783218_4
6. SNP_A-1892946_3 --> SNP_A-2212110_4
7. SNP_A-1938816_4 --> SNP_A-2278207_2
8. SNP_A-1999417_2 --- SNP_A-1999418_3
9. SNP_A-1999636_2 --- SNP_A-1926614_1
10. SNP_A-2015053_3 --> SNP_A-2212110_4
11. SNP_A-2103840_3 --- SNP_A-2046895_2
12. SNP_A-2103840_3 --- SNP_A-2160694_2
13. SNP_A-2113126_4 --- SNP_A-4213863_4
14. SNP_A-2113126_4 --- SNP_A-4293137_1
15. SNP_A-2115216_4 --- SNP_A-2113000_4
16. SNP_A-2125845_3 --- SNP_A-2134365_1
17. SNP_A-2127756_3 --- SNP_A-1839049_2
18. SNP_A-2160694_2 --- SNP_A-2046895_2
19. SNP_A-2209876_2 --- SNP_A-2015053_3
20. SNP_A-2209876_2 --> SNP_A-2212110_4
21. SNP_A-2212110_4 --> SNP_A-1783218_4
22. SNP_A-2228997_3 --> SNP_A-2278207_2
23. SNP_A-2240781_2 --- SNP_A-2015050_4
24. SNP_A-4192853_4 --> SNP_A-1999524_1
25. SNP_A-4202256_2 --- SNP_A-4205973_3
26. SNP_A-4213863_4 --- SNP_A-4293137_1
27. SNP_A-4267982_1 --- SNP_A-2210063_4

**Comment by jdramsey** [comment]
Nice! Thanks for documenting--should be helpful to others.

Joe

On Tue, Dec 1, 2015 at 10:29 AM, biotech25 <notifications@github.com> wrote:

> I tested TETRAD cmd in another Linux server. (This is not the Linux
> workstation in my lab. The Linux workstation has a small problem so I am
> solving it) The linux server has java version 1.7.0_85 as seen below. Now,
> it is working well. Please see below. As you anticipated, I think I need
> java 1.7.0 at least to run TETRAD.
>
> Thank you so much!
> Sanghoon
> ------------------------------
>
> [u0607770@ember1 ~/8_TETRAD]$ java -version
> java version "1.7.0_85"
> OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
> OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
>
> [u0607770@ember1 ~/8_TETRAD]$ java -jar
> lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar -data
> tgen_40SNPs_1411cases_3bins.txt -datatype discrete -algorithm pc -depth -1
> -significance 0.01
> Loading data from tgen_40SNPs_1411cases_3bins.txt.
> Dec 01, 2015 8:03:57 AM java.util.prefs.FileSystemPreferences$6 run
> WARNING: Prefs file removed in background /uufs/
> chpc.utah.edu/common/home/u0607770/.java/.userPrefs/prefs.xml
> variables = 41, # cases = 1411
>
> Result graph:
>
> Graph Nodes:
> SNP_A-1999417_2 SNP_A-1999418_3 SNP_A-4192853_4 SNP_A-2125845_3
> SNP_A-2115216_4 SNP_A-2228997_3 SNP_A-2105786_2 SNP_A-2127756_3
> SNP_A-2271390_2 SNP_A-2134365_1 SNP_A-1999524_1 SNP_A-1840727_3
> SNP_A-1938816_4 SNP_A-4202256_2 SNP_A-4205973_3 SNP_A-1839049_2
> SNP_A-2278207_2 SNP_A-2240781_2 SNP_A-2015050_4 SNP_A-1829356_4
> SNP_A-1892946_3 SNP_A-2209876_2 SNP_A-1783218_4 SNP_A-2212110_4
> SNP_A-2015053_3 SNP_A-2252628_3 SNP_A-2113000_4 SNP_A-2113126_4
> SNP_A-4213863_4 SNP_A-4293137_1
> SNP_A-2227832_3 SNP_A-4267982_1 SNP_A-2210063_4 SNP_A-4281580_2
> SNP_A-2103840_3 SNP_A-2160694_2 SNP_A-2046895_2 SNP_A-1999636_2
> SNP_A-1926614_1 APOE class
>
> Graph Edges:
> 1. APOE --- class
> 2. SNP_A-1829356_4 --- SNP_A-2015053_3
> 3. SNP_A-1829356_4 --> SNP_A-2212110_4
> 4. SNP_A-1840727_3 --> SNP_A-1999524_1
> 5. SNP_A-1892946_3 --> SNP_A-1783218_4
> 6. SNP_A-1892946_3 --> SNP_A-2212110_4
> 7. SNP_A-1938816_4 --> SNP_A-2278207_2
> 8. SNP_A-1999417_2 --- SNP_A-1999418_3
> 9. SNP_A-1999636_2 --- SNP_A-1926614_1
> 10. SNP_A-2015053_3 --> SNP_A-2212110_4
> 11. SNP_A-2103840_3 --- SNP_A-2046895_2
> 12. SNP_A-2103840_3 --- SNP_A-2160694_2
> 13. SNP_A-2113126_4 --- SNP_A-4213863_4
> 14. SNP_A-2113126_4 --- SNP_A-4293137_1
> 15. SNP_A-2115216_4 --- SNP_A-2113000_4
> 16. SNP_A-2125845_3 --- SNP_A-2134365_1
> 17. SNP_A-2127756_3 --- SNP_A-1839049_2
> 18. SNP_A-2160694_2 --- SNP_A-2046895_2
> 19. SNP_A-2209876_2 --- SNP_A-2015053_3
> 20. SNP_A-2209876_2 --> SNP_A-2212110_4
> 21. SNP_A-2212110_4 --> SNP_A-1783218_4
> 22. SNP_A-2228997_3 --> SNP_A-2278207_2
> 23. SNP_A-2240781_2 --- SNP_A-2015050_4
> 24. SNP_A-4192853_4 --> SNP_A-1999524_1
> 25. SNP_A-4202256_2 --- SNP_A-4205973_3
> 26. SNP_A-4213863_4 --- SNP_A-4293137_1
> 27. SNP_A-4267982_1 --- SNP_A-2210063_4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/73#issuecomment-161001739>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey
