### ISSUE TITLE
Labels of Search Output

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#731]
I think this is a repeat request:  the output of a search should contain the name of the algorithm used in the search.

**Comment by yuanzhou** [comment]
This turned out to be not just a simple label change. I'll discuss with @kvb2univpitt to come up with a good plan.

**Comment by kvb2univpitt** [comment]
Done.  I also added algorithm in the parameter panel.

![algo](https://user-images.githubusercontent.com/10729309/36175075-48a98048-10dc-11e8-8158-4b18c86d82ee.png)
![param](https://user-images.githubusercontent.com/10729309/36175076-48b89646-10dc-11e8-9a09-8212f0418222.png)

**Comment by cg09** [comment]
great! many thanks.

**Comment by jdramsey** [comment]
This looks great!  Joe
