### ISSUE TITLE
Running search from graph, pm or IM

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#733]
Joe,

In principle, PC and FCI should run from any of: directed graph, PM or IM.  I believe you had set it up so that they should run from a directed graph, but none of the above are possible now. The common error response is the misleading "Sorry, I was expecting a discrete data set"

**Comment by jdramsey** [comment]
@cg09 When you say PC and FCI should be runnable from a PM, do you mean from the graph in the PM?

**Comment by cg09** [comment]
Yes

**Comment by jdramsey** [comment]
@cg09 I thought about this issue, https://github.com/cmu-phil/tetrad/issues/733. I think it's ambiguous to do a search from a PM or an IM; it makes you think it has more information to appeal to than just the graph. You can always hang a graph off of a PM or an IM and search that using d-separation.

 I checked, searching on a graph works now.

**Comment by jdramsey** [comment]
I'm going to close this; there's an easy workaround. Triage level low.
