### ISSUE TITLE
Difference between 'tetradcmd-5.1.0-10' and 'lib-tetrad-5.3.0.20151113.150857-1-tetradcmd.jar'

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#74]
Hi, 
I was using "tetradcmd-5.1.0-10.jar" in windows batch. I like to make sure if the results of pc or fci search algorithm between "tetradcmd-5.1.0-10" vs. "lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar" are different in terms of graph edges?  When I ran both tetrad cmd, I got 32 edges by 'tetradcmd-5.1.0-10.jar', but I got just 27 edges by 'lib-etrad-5.3.0-20151113.150857-1-tetradcmd.jar'.   Also, I found that some edge directions and interacting nodes are different between two results. For example, 
SNP_A-2127756_3 --- SNP_A-1839049_2    vs.    SNP_A-2127756_3 <->SNP_A-1999524_1. 

Do you recommend to use the latest version of TETRAD cmd for accurate(?) search result? 

Thank you, 
Sanghoon

**Comment by jdramsey** [comment]
I recommend using the latest. We had a grad student do some performance
testing on the PC adjacency search and a couple of adjustments were made.

On Tue, Dec 1, 2015 at 10:43 AM, biotech25 <notifications@github.com> wrote:

> Hi,
> I was using "tetradcmd-5.1.0-10.jar" in windows batch. I like to make sure
> if the results of pc or fci search algorithm between "tetradcmd-5.1.0-10"
> vs. "lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar" are different in
> terms of graph edges? When I ran both tetrad cmd, I got 32 edges by
> 'tetradcmd-5.1.0-10.jar', but I got just 27 edges by
> 'lib-etrad-5.3.0-20151113.150857-1-tetradcmd.jar'. Also, I found that some
> edge directions and interacting nodes are different between two results.
> For example,
> SNP_A-2127756_3 --- SNP_A-1839049_2 vs. SNP_A-2127756_3
> <->SNP_A-1999524_1.
>
> Do you recommend to use the latest version of TETRAD cmd for accurate(?)
> search result?
>
> Thank you,
> Sanghoon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/74>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by biotech25** [comment]
Thank you for your answer!

Sanghoon
