### ISSUE TITLE
"graph" and "edit" tabs in time series graph window

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#740]
The "edit" and "graph" tabs in the time series graph box are illogically arranged. Some of them  are to control the graph that is generated and some of them ("properties") are properties of a graph that has already been created.  For example, first thing someone creating a time series model wants is to specify the number of lags. Right now how to do that is hidden.  To specify the number of lags the user has to go to "Edit" in the window, then to "Configuration" then finally gets a tab to specify the number of lags. '

When a time series graph is selected, the first thing in the box should be a window allowing the user to specify everything in the current  "graph" and "edit" tabs except the options under "properties."  The present tabs can be left in, just in case the user wants to revise what is specified it such a window.  "Configuration" should be changed everywhere to "Lags"

Further, there is no "copy selected graph" or "paste" option in the time series graph window. There should be.

Finally

Please contact me if this is unclear, including by phone if that would help: 850-292-8386

**Comment by jdramsey** [comment]
@cg09 I remember thinking to myself before when I coded that, that I wasn't sure what a copy/paste operation should look like for time lag graphs. If you copy a graph from a lag 2 graph and paste it into a general graph box, should that even be allowed? The variables aren't in fact lagged unless you parse their names. What if you paste it into a lag 1 graph box and there are lag 2 edges? Etc. One thing I can think of to do is a lag p variable is a variable of the form "X:p". If you paste a lagged graph into a window with no lags, all lag information should be lost. If you paste a lagged graph into a graph window with lag m, all lagged edges from variables V:n->V will be lost for n > m. That would be consistent. Is that what you had in mind? It would take a wee bit of work to code that up.

**Comment by jdramsey** [comment]
@yuanzhou @cg09  Some comments. The graph menu was irrelevant to this; none of the items in it applied to time lag graphs. (Maybe a new menu should be added with items that do apply, but new feature I guess.) I had commented the graph menu out.

I suppose it wouldn't hurt if the configuration menu item in the Edit menu were made a button instead, if that's a cause of confusion. Then the edit menu could go away; that's the only item there.

I still don't know what copy/paste looks like for time lag graphs.

**Comment by jdramsey** [comment]
I believe these are all fixed now.
