### ISSUE TITLE
IM for time series with latent variables

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#741]
The tabular results for a specified lag model with latent variables seems correct, but the implied covariance matrix gives 0.00 for all latent covariances.  See attached. picture
<img width="1365" alt="screen shot 2018-02-19 at 1 01 55 pm" src="https://user-images.githubusercontent.com/16354745/36391589-24abe0b2-1575-11e8-91bb-a8ab4aba7868.png">

Further, there should not be a "model statistics" tab for the IM...model statistics requires that the model be compared with data, and there is no data for the IM.

**Comment by jdramsey** [comment]
This suggests a more general facility in Compare where you give it a model and a dataset and it gives you back the stats. We discussed this for conditional Gaussian.

**Comment by jdramsey** [comment]
OK, a full-featured stats list editor was added. Also, I don't see any latent variables in the covariance matrix. Perhaps the covariance matrix should be disallowed for time series, as the structure is repeating and coefficients are only available for edges into the current time lag. I'll think about this. But this is a stale issue; close for now--if I can think of a more precise way to put the issue I'll make a new issue.
