### ISSUE TITLE
In the search editor, if knowledge tiers are available from knowledge for the algorithm, by default layout by tiers.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#744]
In the general algorithm editor code somewhere or maybe in some adjacency class, graphs are being laid out by default in a circle. But if the search has knowledge defined with at least two tiers, this layout should be applied instead by default.

SearchGraphUtils.arrangeByKnowledgeTiers(graph, knowledge);

This issue is mentioned in the comments of https://github.com/cmu-phil/tetrad/issues/722/. This is critical for time series searches.

@yuanzhou @kvb2univpitt @chirayukong @espinoj @cg09

**Comment by kvb2univpitt** [comment]
Fixed.
