### ISSUE TITLE
pipeline with time series graph

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#748]
This is tricky.  If pipeline "simulate from a given graph then search" is specified, the following sequence of boxes is produced Graph-> PM -> IM -> Simulation -> Search.  This sequence will not work if in the graph box a time series graph is specified...because a time series cannot be searched from the Simulation output--that output has to first be run through a Data box and the data reformulated in staggered copies. Then a search can be run.  I don't know exactly what the fix should be.  Joe???

**Comment by jdramsey** [comment]
Currently those TS algorithms pop up a warning that they need Time Lag data as input, which is a step in the right direction.

**Comment by jdramsey** [comment]
@cg09 How about this. This is for the problem of TsFCI needing time-lagged data, which you don't have if you follow the usual pipeline. The error message is "Time-series algorithm needs lagged data." This can instead read, "Time-series algorithm needs lagged data; try using the 'Convert to Time Lag Data' data manipulation."

**Comment by jdramsey** [comment]
I think this is fine now... I propose we see if anyone still complains about it and re-open it if they do...
