### ISSUE TITLE
Definition for edge directions 

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#75]
I ran TETRA cmd and got some information of interacting nodes and edge directions between the edges.  I found this definition of edge direction in the manual of TETRAD v.4 

1)  directed (-->),   2) undirected (---),   3) unoriented (o-o), and   4) bidirected (o->)

But, I couldn't find good definition of this in the manual of TETRAD v.5.   Also, personally, I don't understand the difference between undirected (---) and unoriented (o-o).  I think they sound the same.  And, I think symbol of 'bidirected' should be <->, rather than o->.    Could you teach me where I can find a good and clear definition of the edge directions?  I need to define it for my lab's manuscript. 

Thank you, 
Sanghoon

**Comment by jdramsey** [comment]
Sure, see Spirtes, Glymour and Scheines, 2000, Causation, Prediction and
Search. You should be able to find it online.

On Tue, Dec 1, 2015 at 10:45 AM, biotech25 <notifications@github.com> wrote:

> I ran TETRA cmd and got some information of interacting nodes and edge
> directions between the edges. I found this definition of edge direction in
> the manual of TETRAD v.4
>
> 1) directed (-->), 2) undirected (---), 3) unoriented (o-o), and 4)
> bidirected (o->)
>
> But, I couldn't find good definition of this in the manual of TETRAD v.5.
> Also, personally, I don't understand the difference between undirected
> (---) and unoriented (o-o). I think they sound the same. And, I think
> symbol of 'bidirected' should be <->, rather than o->. Could you teach me
> where I can find a good and clear definition of the edge directions? I need
> to define it for my lab's manuscript.
>
> Thank you,
> Sanghoon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/75>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by biotech25** [comment]
Thank you for your reply. I think you mean this book:  

http://www.cs.cmu.edu/afs/cs.cmu.edu/project/learn-43/lib/photoz/.g/scottd/fullbook.pdf

**Comment by jdramsey** [comment]
That's the one.

On Tue, Dec 1, 2015 at 11:07 AM, biotech25 <notifications@github.com> wrote:

> Thank you for your reply. I think you mean this book:
>
>
> http://www.cs.cmu.edu/afs/cs.cmu.edu/project/learn-43/lib/photoz/.g/scottd/fullbook.pdf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/75#issuecomment-161014768>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey
