### ISSUE TITLE
Ling Algorithm broken ? 

### ISSUE THREAD

**Issue by Diviyan-Kalainathan** [cmu-phil/tetrad#752]
Hi, 
I wondered if the Ling algorithm is usable, because of this mention : 
https://github.com/cmu-phil/tetrad/blob/6fc8d654d366dbd4e8e2af9872dbf0acc6396d4e/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Ling.java#L56-L61

But I don't know if this is related to #60, and if it is still relevant.

Thanks a lot!
Best regards,
Diviyan

**Comment by jdramsey** [comment]
I did have some time to look at the ICA implementation some time ago. I concluded that was working. It could probably be updated; it's not a translation of the current ICA but of one from several years ago.

That said, the algorithm is still, last I checked, very unstable. I'll look at it again if I can get some time though.

**Comment by Diviyan-Kalainathan** [comment]
Thanks a lot !
