### ISSUE TITLE
Putting ION in TETRRAD

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#755]
This is an extension: Once upon a time we had versions of the ION algorithm, which ran PC or FCI etc. on multiple data sets that share some but not all variables.  We should reimplement that algorithm. In connection, we need the ability to construct such data sets from a given data set, which we cannot now do.

**Comment by jdramsey** [comment]
We do have ION. It's a technical problem to put it into the interface; putting it in using the old method (which is available) will mess up the search interface, so something else is needed I think.

@cg09

**Comment by jdramsey** [comment]
I'll re-add this if it comes up again...
