### ISSUE TITLE
Bootstrap tests needed

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#757]
We need bootstrap tests that give p values.  We have the ability to subsample any data set at random, but only one subsample at a time. That needs to be automatically repeatable with a user specified number of repetitions and connected to bootstrap tests.

**Comment by jdramsey** [comment]
The only thing that's missing at the point for these are the p-values. Can these be added? Or are they there? @chirayukong

**Comment by chirayukong** [comment]
Yes, I think so.

**Comment by jdramsey** [comment]
Oh, you mean the edgewise p-values? Yeah that seems good. So this can basically be closed, then.
