### ISSUE TITLE
"lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar" is working in Windows, too. 

### ISSUE THREAD

**Issue by biotech25** [cmu-phil/tetrad#76]
Hi, 

I just tested to use "lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar" in Windows  (I am using Windows Server 2008 R2 Enterprise), and it is working, too.  In the Wiki, you explained that it should be Unix-type machine..  I am confused.  Do I know something wrong?  Is it okay to use it in Windows, and may I expect the same performance?  

Thank you, 
Sanghoon

**Comment by jdramsey** [comment]
That's news to me; I did not know that would actually work. I haven't had a
Windows machine in about 15 years. I'll change the Wiki.

Thanks,

Joe

On Tue, Dec 1, 2015 at 4:39 PM, biotech25 <notifications@github.com> wrote:

> Hi,
>
> I just tested to use "lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar" in
> Windows (I am using Windows Server 2008 R2 Enterprise), and it is working,
> too. In the Wiki, you explained that it should be Unix-type machine.. I am
> confused. Do I know something wrong? Is it okay to use it in Windows, and
> may I expect the same performance?
>
> Thank you,
> Sanghoon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/76>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I also noticed I had the wrong JDK version listed there too; that's fixed.

**Comment by jdramsey** [comment]
Performance should be the same, since it's running virtual byte code.

**Comment by biotech25** [comment]
Thank you so much for your quick update. 

Sanghoon
