### ISSUE TITLE
Optimum Cut-off for p-value

### ISSUE THREAD

**Issue by PanikaValecha** [cmu-phil/tetrad#760]
How do i know what  cut-off for p-value is optimum for the using FCI search algorithm?
For one of my dataset, I tried to find causal relationship by using p-values 0.01, 0.05, 0.08 and 0.09. Since no causal relationship was shown, I set p-value as 1 to see what happens, it shows executing for hardly a second and returns to the parameter window itself. It would be great if I could be explained the same. Thanks.

**Comment by jdramsey** [comment]
What kind of data is it? Are the variables in question correlated?

**Comment by PanikaValecha** [comment]
I have to find the causal relationship. The dataset consists of 2 id's (say id1 and id2) and the number of occurrences per month for each id1 and id2 combination. The id's are strings and not numbers.

**Comment by PanikaValecha** [comment]
Is the p-value here similar to the probability value i.e a p-value <=0.05 is considered trustworthy? If not, can you explain that.

Thanks.

**Comment by jdramsey** [comment]
In general, that depends on your sample size. for a very small sample size a high alpha level is needed, but as the sample size increases, that alpha level should be decreased. As a general rule, if N = 1000, for continuous data, an alpha level, of 0.001 is appropriate, whereas if N = 200, alpha = 0.05 is appropriate. But what test are you using?

**Comment by PanikaValecha** [comment]
The dataset is discrete because it is linked to the number of occurrences. The default test selected for FCI algorithm was ChiSquare Test, so I didn't change it as of now. I used the alpha level as 0.05 for one dataset. The second data set that I talked about above has N=428 (including month and number of occurrences both).
The dataset is somewhat like below:

id1 id2 combinations | aa - 01 | aa - 01 | ba - 02 | ba - 03
month | 4 | 9 | 2 | 3
number of occurrences | 21 | 5 | 2 | 9

 and so on.
I need to find if there exists any causal relationship between different id pairs. Like, (aa-01) and (ba-02) or (aa-01) and (ba-03), etc.

**Comment by cg09** [comment]
From his description he has a messed up data set. He has categorical
variable with Lots of values.

**Comment by PanikaValecha** [comment]
@cg09 
*her description.
It would be nice if you could suggest something.
Thanks!!

**Comment by cg09** [comment]
So little as I understand it, you have a variable, call it X, that takes as
values pairs of attributes...I assume as many pairs as you have pairs of
individuals, which may be a lot. So X is a purely categorical variables.
You have another variable, call it, Y, which seems to take integers as
values; I don't know how many integers. That variable is categorical or
ordinal. You may have other variables.   The problem is that you have
categorical variables with a large range of values. I know of no methods to
deal with that sort of problem if I understand it correctly. Certainly,
none of the methods in the TETRAD software will be statistically correct.

Sorry I cannot help you more.

Clark Glymour

**Comment by jdramsey** [comment]
I'm still unclear. Do you have a table of data, like this:

           (aa, 1)  (bb, 2)
July        19        5
Aug          2       20
Sep         20      10
...

Joe

**Comment by PanikaValecha** [comment]
The data is like:

X-Y | aa - 01 | aa - 01 | ab- 02 | ab - 02
-- | -- | -- | -- | --
month | 5 | 8 | 3 | 9
number of   incidents | 25 | 100 | 10 | 525

**Comment by jdramsey** [comment]
Your tables look better mine. Question: Do you know when an incident occurs for both aa - 01 and aa - 02, or does that never happen?

**Comment by PanikaValecha** [comment]
Yes, I know the timestamp of occurrence.

**Comment by jdramsey** [comment]
So what you need is a dataset like this:

Occurrence | aa.01 | aa.02
1 | 1 | 0
2 | 1 | 1
3 | 0 | 1
4 | 0 | 0
5 | 1 | 0

Occurrence | aa.01 | aa.02
-- | -- | --
1 | 1 | 0
2 | 1 | 1
3 | 0 | 1
4 | 0 | 0
5 | 1 | 0



Occurrence | aa.01 | aa.02
-- | -- | --
1 | 1 | 0
2 | 1 | 1
3 | 0 | 1
4 | 0 | 0
5 | 1 | 0



where 1 means occurs for that case and 0 means does not occur for that case

**Comment by PanikaValecha** [comment]
That seems reasonable. I understand it now. Do you think I don't need the number of occurrences( the count)? I have the data for like an year and the time is in day-month-year format. 

So, which algorithm will you recommend for this? Should I continue using the FCI algorithm.

Thank you for all your guidance.

**Comment by jdramsey** [comment]
No problem! Sorry about my poor pasting skills; it seems I pasted three copies of the same thing.

Once you get data in that format, I would try PC first an then FGES. If those give sensible results but you're worried about latent variables, then I would try FCI. or GFCI.

If you can put your data into the format I suggested, the counts should be implied.

**Comment by PanikaValecha** [comment]
That is okay.
Yes, I am unsure of the latent variables. There could be some, there could not be. I don't have any information about it. So, that is why I though of using FCI.

 I would go ahead and give this another try. Thank you so much for all your help!! I really appreciate it.
