### ISSUE TITLE
Bootstrapping Result in Command Prompt Window

### ISSUE THREAD

**Issue by wylam055** [cmu-phil/tetrad#768]
I found an issue in outputting the bootstrapping result in the command prompt window. For RFCI, the bootstrapping result is perfect. It shows the confidence level for each edge among different variables. However, there is no result shown in the command prompt window when I use algorithms like PC All and FGES. 

I've been restarting TETRAD several times, but the problem remains. Please advise. Thanks!

**Comment by chirayukong** [comment]
I'll take a look at it. Do you mind sharing the dataset?

**Comment by wylam055** [comment]
Sure. Thanks!

Wayne

**Comment by chirayukong** [comment]
@wylam055 Could you try it again on the [issue_768](https://github.com/cmu-phil/tetrad/tree/issue_768) branch?

**Comment by espinoj** [comment]
Resolved?
