### ISSUE TITLE
Estimator does not give model fit statistics

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#772]
This is really annoying in practice.  The estimator gives p values for tests of edges, but it does not give an overall model fit value, e.g., a BIC score where calculable.

**Comment by jdramsey** [comment]
@espinoj Wait, hasn't this been fixed as well? I'm getting the impression that a lot of these issues have been fixed already. The BIC score pops up in the window when I estimate.

**Comment by espinoj** [comment]
This is available in the corner of the graph.
