### ISSUE TITLE
Algorithm running info dialog

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#774]
When running an algorithm can we output algorithm info e.g., creating skeleton, 100 edges added, java heap 80%

**Comment by cg09** [comment]
Sure, for those users who know what a heap is.

**Comment by jdramsey** [comment]
Actually some of this is already output in the logging; we could add more logging info. This is a good idea.

**Comment by jdramsey** [comment]
I think the thing to do is add more logging output, not make a new dialog for this...closing...

**Comment by cg09** [comment]
Take a break.
