### ISSUE TITLE
Tetrad graph output txt file

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#776]
The tetrad graph output in txt file, ie. the list of edges; has two extra blank lines at the end. Is it possible to fix the code to avoid those blank lines ?

**Comment by espinoj** [comment]
I see one extra blank line and can fix that.  Can you confirm that it is two extra blank lines?

**Comment by cabal-cmu** [comment]
Hi,
There are two blank lines when you save it as text file.

Find attached an example.
[graph2.txt](https://github.com/cmu-phil/tetrad/files/2055316/graph2.txt)

**Comment by cabal-cmu** [comment]
This is good. Thanks a lot.
