### ISSUE TITLE
edges, PM and IM

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#780]
With the new thingy that shows the edge label: X --> Y when you hover on top of the edge in the graph. If you do this in a PM or IM box, the label of the coefficients sometimes disappear.

**Comment by espinoj** [comment]
#784

**Comment by espinoj** [comment]
Kevin and I tried this on linux and mac on 6.5 and development and were unable to replicate.  @chirayukong do you see this issue still?

**Comment by chirayukong** [comment]
I can't mimic this disappearing effects, too.
