### ISSUE TITLE
Writeup of the Knowledge file format.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#781]
Clark would like a write-up of the format of the Knowledge file to include in the manual. Is there one somewhere? -Joe

**Comment by cabal-cmu** [comment]
I got this from: https://bd2kccd.github.io/docs/causal-cmd/

Sample Prior Knowledge File

From the above usage guide, we see the option of --knowledge <arg>, with which we can specify the prior knowledge file. Below is the content of a sample prior knowledge file.

The first line of the prior knowledge file must say /knowledge. And a prior knowledge file consists of three sections:

    addtemporal - tiers of variables where the first tier preceeds the last. Adding a asterisk next to the tier id prohibits edges between tier variables
    forbiddirect - forbidden edges indicated by a list of pairs of variables
    requireddirect - required edges indicated by a list of pairs of variables



*****************************************
/knowledge

addtemporal
1 spending_per_stdt fac_salary stdt_tchr_ratio 
2 rjct_rate stdt_accept_rate 
3 tst_scores stdt_clss_stndng 
4* grad_rate 

forbiddirect
x3 x4

requiredirect
x1 x2

******************************************

**Comment by jdramsey** [comment]
Thanks guys. I will send this to Clark.
