### ISSUE TITLE
an example of covariance matrix data?

### ISSUE THREAD

**Issue by ykim379** [cmu-phil/tetrad#783]
I like to load covariance matrix data (instead of raw tabular data) but the required format of such data is not clear in the manual. What does the matrix data look like?

**Comment by ykim379** [comment]
Oh, I found an example. 

72
po fi en cv
1.0
-.175  1.0
-.480  0.330   1.0
0.868 -.391  -.430  1.0

**Comment by cg09** [comment]
Yikes, should have been in there. Sorrty and thanks. Try this


/covariance
Sample size [no words just a number]
Lower triangular covariance matrix [entries space separated]

Don't put spaces between the lines or periods or semi-colons or commas at
the end of a line.

Cg

**Comment by cg09** [comment]
Good, because I forgot the line with the variable names after the sample
size.
