### ISSUE TITLE
LiNGAM missing in command-line versions of TETRAD

### ISSUE THREAD

**Issue by isadreev** [cmu-phil/tetrad#789]
It seems that LiNGAM is currently not available for the 6.4.0 and 6.4.1 command-line versions of TETRAD although it is present in the gui-version. Is there any chance it could be added to the list of available algorithms in a TETRAD command-line version?

**Comment by jdramsey** [comment]
LiNGAM has been mysteriously broken for quite some time. It's being marked as experimental until it can be fixed.
