### ISSUE TITLE
IMaGES tetrad gui

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#791]
When running IMaGES continuous, it does not work when selecting more than 1 dataset for the run (last option in the parameters setting).

Example: 
Simulate 10 datatsets with the simulation box.  
Pass the simulation box to a data box.
Pass the data box to a search box with IMaGES continuous, selecting 10 datasets in the last parameter option.

**Comment by espinoj** [comment]
This seems to be working in development but not in 6.4.
We'll be releasing 6.5 from development Tuesday.

Can you try the latest development branch to confirm?
https://cloud.ccd.pitt.edu/latest-dev-tetrad.html

**Comment by cabal-cmu** [comment]
Confirmed. IMaGES works properly in the development.
