### ISSUE TITLE
CCD web

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#793]
For the mixed versions of the algorithms, during:

Step 1: Select Dataset

The second option is:

Number of Discrete Categories.

This number is in fact is the number of discrete variables in the dataset.

A user expressed confusion about it. I proposed we should change it to:

Number of discrete variables in the dataset
 or   

Number of categorical variables in the dataset

**Comment by cg09** [comment]
Good, either change will do.  Clark

**Comment by cabal-cmu** [comment]
I was wrong, in conversation with Joe, he explained me that this parameter corresponds to the maximum number of categories that the dataloader will accept for considering a variable discrete. If the variable has more than that maximum number of categories, then it will be consider continuous.

Can we be more explicit about this parameter, it is somehow confusing.

**Comment by kvb2univpitt** [comment]
Yes.  That's correct.  I was going to say that parameter is also found in Tetrad.  We need to change that in Tetrad if needed.
