### ISSUE TITLE
Confusing parameter.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#796]
According to a trustworthy source, users find the "maximum number of discrete categories" parameter for loading mixed data to be confusing. Obviously, we need that parameter, but is there a way to attach an instruction for it somehow? One user, for instance, thought that it meant the number of discrete variables.

**Comment by cg09** [comment]
I think the user will have to be confused and the manual revision will have
to handle it.  Why we need good connections to a good manual.
