### ISSUE TITLE
PM box reverses category names

### ISSUE THREAD

**Issue by yuanzhou** [cmu-phil/tetrad#803]
During the short course, an attendee noticed that the PM box resets the category names after renaming the category names in the PM box.

By default the categories are 0 and 1, it's common that we rename 0 to NO, and 1 to Yes.
![1](https://user-images.githubusercontent.com/195873/41240172-e789aa2a-6d67-11e8-99d5-118dc82fe4e7.PNG)

![2](https://user-images.githubusercontent.com/195873/41240176-e8d326cc-6d67-11e8-87de-067b073be5d5.PNG)

Click Done button, and reopen the PM box, it reversed the category names.

![3](https://user-images.githubusercontent.com/195873/41240185-eb4a6fb4-6d67-11e8-8abf-1833db8d2157.PNG)

And I tried different category names, like A and B, sometimes I gets reversed as well.

**Comment by yuanzhou** [comment]
This is so interesting that sometimes I can reproduce this behavior and sometimes I can't. It's not consistent.

**Comment by jdramsey** [comment]
@yuanzhou I can't reproduce this; it looks to be fixed! Something somebody did must have fixed it. I think this can be closed.

**Comment by yuanzhou** [comment]
I just tested again and couldn't reproduce. I assume it has been magically fixed :)
