### ISSUE TITLE
inconsistency in values from data back to estimation

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#809]
see screenshot. I can provide a .tet file if needed

![image](https://user-images.githubusercontent.com/174707/41267897-719a943c-6dcb-11e8-9b97-832d34c0ab7c.png)

**Comment by cg09** [comment]
Harry,

What inconsistency?  You expect estimators to be perfect? Or something else
I missed?

Clark

On Mon, Jun 11, 2018 at 11:02 PM, Harry Hochheiser <notifications@github.com

**Comment by harryhoch** [comment]
Clark, just reporting a comment from a short course attendee. Completely agreed it might be inappropriate for users to expect perfection, but folks might get confused nonetheless. Not at all clear how to address this problem..
