### ISSUE TITLE
Unable to Re-simulation Data

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#812]
Unable to re-simulate data by choosing a different data simulation type.

**Comment by yuanzhou** [comment]
I tested and I could re-simulate data with a different simulation type. What's the steps to reproduce this error?

**Comment by yuanzhou** [comment]
@kvb2univpitt this is the issue that was fixed earlier but seems it caused the new issue. https://github.com/cmu-phil/tetrad/issues/786
