### ISSUE TITLE
In Conditional Gaussian, comment out lines 147-149.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#813]
In Conditional Gaussian, these lines need to be commented out:

//        if (!discretize) {
//            return mixedDataSet;
//        }

This was an optimization, but it breaks stuff.

**Comment by yuanzhou** [comment]
I don't seem to find the corresponding source code. Can you please paste a link to the class?

**Comment by jdramsey** [comment]
Sorry about that. Jeremy couldn't find it either. It must not be in the development branch, which is perfect.

I just verified that it's working correctly in the published version. Perfect. I can demo it.

Thanks.
