### ISSUE TITLE
default SEM BIC for continuous data as an independence test vs. fisher z for PC.

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#821]
SEM BIC for continuous data as an independence test vs. fisher z for PC.

**Comment by jdramsey** [comment]
@yuanzhou @espinoj I'm trying this in the interface right now and Fisher Z seems to be doing better than SEM BIC! SEM BIC seems to be off, not sure why; I'll look at it. In any case, Fisher Z seems the better default!

**Comment by jdramsey** [comment]
@yuanzhou @espinoj Yep, unless things change, this adjustment shouldn't definitely not be done. For PC Variants, Fisher Z should be the default, as it currently is. I'll try to figure out what the issue is.

So think this one is...won't fix.

**Comment by jdramsey** [comment]
Just a note; with the new covariance calculation @kvb2univpitt did, for GES, SEM BIC score always beats Fisher Z Score the best and for constraint-based, Fisher Z test always beats SEM BIC test, so the worse test and score are removed in Tetrad 7.
