### ISSUE TITLE
Search doesn't remember parameters

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#822]
after break edges or re execute warning

**Comment by kvb2univpitt** [comment]
@espinoj I don't see the problem.  Can you please elaborate on this?

**Comment by espinoj** [comment]
try editing the workflow when there is a bootstrap option selected - it fails to remember

**Comment by yuanzhou** [comment]
Tested and everything looks good. I also remember we probably have fixed this earlier.
