### ISSUE TITLE
Bootstrap doesn’t execute after clicking on graph it multiple times

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#832]

**Comment by yuanzhou** [comment]
I reproduced this error by following these steps:

1. Do a search on a dataset, set bootstrap parameters and run the search.
2. Verify the generated bootstrap edge probabilities on the graph.
3. Click "Graph it" then go back to do the bootstrap again.
4. Now the edge probabilities are gone from the graph.

**Comment by yuanzhou** [comment]
Actually we don't have to click "Graph It" to reproduce this error. Once a graph with bootstrap info generated, go back to the parameters panel and run the search again without any changes, the bootstrap info will be gone from graph.

**Comment by yuanzhou** [comment]
What I discovered is after running the bootstrap search, the `bootstrapSampleSize` parameter gets to set as 0 regardless of what the input filed value is. That's why the next time you run the search without any parameters, you won't see the bootstrap.

**Comment by chirayukong** [comment]
I'll take a look at it then. Thanks a lot @yuanzhou
