### ISSUE TITLE
estimator for mags

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#836]

**Comment by espinoj** [comment]
https://arxiv.org/pdf/math/0601631.pdf

**Comment by jdramsey** [comment]
We have this. It's called RICF and it's in the SEM Estimator box. This confuses everybody but me. Maybe it should be put in a separate box?

**Comment by cg09** [comment]
Leave it in the estimator box. Insert a description of it when someone
clicks on it.

**Comment by jdramsey** [comment]
@yuanzhou @chirayukong Clark is talking here about the RICF estimator that is currently located inside the SEM estimator as an option People need to know what they're selecting when they select this; it's different from the other estimators. Is it possible to have the following text come up when they select it? Or have this explained somehow in the estimator window?

"Please note that the RICF estimator is an estimator for mixed ancestral graphs (MAGs). Please see the manual for more details."

Other than giving the user a message, Clark did not think the interface for this needed to be changed.

@cg09 Is this OK? Here is the link to this issue: https://github.com/cmu-phil/tetrad/issues/836.

**Comment by cg09** [comment]
OK.
