### ISSUE TITLE
Generating synthetic data using Tetrad

### ISSUE THREAD

**Issue by adambouras** [cmu-phil/tetrad#842]
Hi,

I am trying to use Tetrad to generate synthetic data. In the project, I only know the demographics distribution of my population and I would like to generate the individual-level data using those frequency distributions. Would you kindly let me know if this possible using Tetrad?

Adam

**Comment by jdramsey** [comment]
Do you mean that you have a population of discrete variables?

**Comment by jdramsey** [comment]
@adambouras Did you get my previous note? Can you give me more information on this?
