### ISSUE TITLE
Adding Multi-FASK to interface

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#852]
Currently, Multi-FASK is not available in Tetrad; it would be a huge help if it could be incorporated in future versions!

**Comment by espinoj** [comment]
Is multifask in a particular branch or just needs to be exposed.  What is the class name?

**Comment by mglymour** [comment]
I believe I emailed the code to you and Joe directly. (The class name was MultiFask.) If you need the code in a branch/need me to resend, let me know!
