### ISSUE TITLE
BPC algorithm doesn't take a covariance matrix as input

### ISSUE THREAD

**Issue by rosechialin** [cmu-phil/tetrad#856]
In BPC algorithm, an input of a covariance matrix generates an error message "edu.cmu.tetrad.data.CovarianceMatrix cannot be cast to edu.cmu.tetrad.data.DataSet." A raw dataset doesn't. I thought Tetrad could take both raw datasets and covariance matrices. Correct?

**Comment by cabal-cmu** [comment]
Can you send the covariance matrix file you are using ? To reproduce the problem.

**Comment by rosechialin** [comment]
Here is the covariance matrix file. Thank you for you help.
[Data.txt](https://github.com/cmu-phil/tetrad/files/2181336/Data.txt)

**Comment by cg09** [comment]
Dear RoseChain

I have in the attached run your file in TETRAD 6.2. I find what you find
with BPC, but I also find the same results (no latent variables) with FOFC.
For comparison, I ran a simulated data set from a single common cause of
four measured variables, and as you can see (I hope), BPC works as it
should, finding the correct model.

I also ran your data through FGES. As you can see, it returns a highly
connected graph.

Possible explanations for the BPC and FOFC behavior on your data:

1. There are no latent confounders
2. There are latent confounders but most pairs of measured variables having
a latent confounder also have direct connections between the measured
variables.

Clark

**Comment by espinoj** [comment]
Covariance input is working
