### ISSUE TITLE
BPC algorithm: No edges in the Output Graphs

### ISSUE THREAD

**Issue by rosechialin** [cmu-phil/tetrad#857]
When the BPC algorithm is applied, no edges are shown in the Output Graphs. Only the fofc and ftfc showed edges in the Output Graphs. What is the way to fix th BPC results?

**Comment by cg09** [comment]
Works fine for me, using 6.2 . See attached.

Clark

**Comment by rosechialin** [comment]
Thanks for your response! I used 6.2 too, but the attached is what I've seen on my screen. Could you re-send your attached please? It looks like it didn't go through. 
![tetrad bpc](https://user-images.githubusercontent.com/41021941/42525182-069c13ba-8462-11e8-9c63-b75a505dbcc9.png)

**Comment by espinoj** [comment]
closing as #856 replicates no edges with the data
