### ISSUE TITLE
Command Line Tetrad doesn't display graph edges 

### ISSUE THREAD

**Issue by PanikaValecha** [cmu-phil/tetrad#859]
When I run command line tetrad, it just shows the graph nodes and not graph edges. I need to run tetrad for about 100 csv files, I was wondering if there is a way that the graph edges can be displayed by using command line itself.

**Comment by rubencmu** [comment]
Can you share the output you are getting,  and your input file for replication.



It should list the list of edges, unless the output did not infer any edges.


Thanks.




________________________________

**Comment by PanikaValecha** [comment]
**Input File: data.csv**


month | Device1 | Device2 | Device3 | Device4 | Device5 | Device6 | Device7
-- | -- | -- | -- | -- | -- | -- | --
1 | 0 | 0 | 0 | 0 | 0 | 0 | 0
2 | 94 | 0 | 0 | 0 | 0 | 0 | 0
3 | 0 | 0 | 0 | 0 | 0 | 0 | 0
4 | 0 | 0 | 0 | 0 | 0 | 0 | 0
5 | 132 | 0 | 0 | 0 | 0 | 0 | 0
6 | 0 | 4 | 16 | 0 | 0 | 0 | 0
7 | 0 | 0 | 0 | 4 | 0 | 0 | 0
8 | 160 | 0 | 0 | 0 | 80 | 2 | 0
9 | 0 | 218 | 0 | 0 | 0 | 0 | 0
10 | 0 | 0 | 0 | 0 | 0 | 0 | 196
11 | 0 | 0 | 0 | 0 | 0 | 0 | 0
12 | 0 | 0 | 0 | 0 | 0 | 0 | 0

**Command used:**
java -jar lib-tetrad-5.3.0-20151113.150857-1-tetradcmd.jar -data data.csv  -datatype continuous -algorithm fci -significance 0.05 -graphtxt result.txt

**Output:**
Loading data from data.csv.
# variables = 1, # cases = 12
R0 start
R0 start
Epoch

Result graph:

Graph Nodes:
0a.53.0L2,0a.51.23L1,9b.53.22L1,3a.56.23L1,9b.53.23L1,9b.54.22L1,0a.55.20L1 

Graph Edges: 

**Algortithm:** FCI
**P-value:** 0.05

**Output obtained using Tetrad GUI:**
Device1 o--o Device6
Device1 o--o Device5
Device5 o--o Device6

The above should be the expected output. But through command line, I don't get the graph edges. Also, I have to ignore first column.

**Comment by rubencmu** [comment]
Hi, the first thing I noticed is that you are using an old version of command line.



Try the one indicated here, and follow the instructions in the user guide for causal command.


https://www.ccd.pitt.edu/tools/


You will see that the call for runs have change, and now you have to specify more parameters regarding the data and the runs, for example the significance test used, etc. Now you have more control on the parameters of the run, and more algorithms are implemented.



For example, a run for FCI with your data will now looks like this. Calling from the directory where the files were downloaded, and where the data is.


java -jar causal-cmd-0.3.2-jar-with-dependencies.jar --algorithm fci --data-type continuous --dataset data.csv --delimiter comma --test fisher-z --alpha 0.05


This will run the FCI algorithm with a Fisher-z test for the conditional independence tests and an alpha of 0.05 for the significance.


It will output a file with the information of the run (algorithm and parameters used) and the output graph at the end.


I attached the file I got from your data using the current version of command line Tetrad. You will see that the graph is the one you got from Tetrad Gui, what you mentioned is the expected output.


Please, let me know if it works for you.










________________________________

**Comment by rubencmu** [comment]
One more thing, in the new command line Tetrad, you can access all the options available by typing:



java -jar causal-cmd-0.3.2-jar-with-dependencies.jar --help-all




________________________________

**Comment by PanikaValecha** [comment]
Thank you for your help. 
I ran the command and it gives me the below results:
Determinism detected: [Device6] -> Device1
Determinism detected: [Device5] -> Device1
Determinism detected: [Device5] -> Device6
Determinism detected: [Device6] -> Device1
Determinism detected: [Device5] -> Device1
Determinism detected: [Device5] -> Device6

A txt file is also created which shows the edges as follows:
Graph Edges:
1. Device1 o-o Device5
2. Device1 o-o Device6
3. Device5 o-o Device6

I don't understand why the determinism results are 6 in number. i assumed that it is possibly because Device1 o-o Device5 means that device1 could be a cause or device5 and vice versa. However, there is no rule that shows device1->device5 relationship.

**Comment by PanikaValecha** [comment]
I have a few other questions too, it would be great if you could answer those:
1. What is the need of the Fisher Z Test?
2. Can you explain briefly about FCI algorithm? I read the manual but I still don't understand the algorithm completely (esp. the terminology used). The documentation is too less for the algorithm. 

I would appreciate your help.

Thanks!!

**Comment by PanikaValecha** [comment]
Also, I can't find the attachment that you sent.

Thanks!!

**Comment by cabal-cmu** [comment]
[fci_1531600789136.txt](https://github.com/cmu-phil/tetrad/files/2195304/fci_1531600789136.txt)

**Comment by rubencmu** [comment]
This paper introduces FCI


https://arxiv.org/abs/1302.4983



The determinism flag you are getting in the output, is because the algorithm identify a deterministic relationship between the variables. For example,  X = bY    or  X = Y + 3        , any relationship without random noise of the from  X = bY + n, where n is random noise.










________________________________

**Comment by PanikaValecha** [comment]
Thanks!! I'll read the paper.

**Comment by PanikaValecha** [comment]
I have another quick question. What is the significance of the tests while running the algorithms? For example, Fisher Z Test for FCI.

**Comment by cg09** [comment]
The user sets it in the interface.

**Comment by rubencmu** [comment]
It is defined with the parameter  --alpha




________________________________

**Comment by PanikaValecha** [comment]
I still don't get it. My question is Why do we use these tests? I am new to this tool and am trying to understand it as much as possible.

**Comment by cg09** [comment]
The algorithms work by making decisions about which variables are or are
not independent of one another, conditional on other sets of variables (the
ingenious thing about the algorithms is how they choose which sets of
variables to condition on). Those decisions are made, in one version of the
algorithms, by a series of statistical tests of null hypotheses of
conditional independence.  See Spirtes, et al. Causation, Prediction and
Search, MIT Press, 2000.

Cg

**Comment by PanikaValecha** [comment]
Thank you!! I appreciate your guidance. :)

**Comment by cg09** [comment]
Dear Mr. Valicha,

We are here to help with operating the program or fixing bugs, but not for
teaching algorithms that are explicit in the open literature.  I previously
directed you to Spirtes, et al., Causation, Prediction and Search. The
algorithm you ask about is described there and its proof of correctness
given.  If you study it and find it not comprehensible, I don't think we
can help you further.

Cg

**Comment by PanikaValecha** [comment]
I asked about the tests later and not the algorithm. I was just confused about the tests. I understand this is not for help with the algorithm, but just normal issues. I am sorry for having asked the other questions. I express my gratitude towards all for their help!!

**Comment by rubencmu** [comment]
Dear Panika,



As metioned before this Github is not the proper channel for theoretical inquiries about the search methods.


I invite you to contact the CCD helpdesk at ccd.user.helpdesk@gmail.com ,  where you can forward all your general questions about these methods, and we will gladly answer all your doubts.

















________________________________

**Comment by PanikaValecha** [comment]
Thanks a lot. I appreciate it!!

**Comment by cg09** [comment]
Ruben,

Thanks. What will we do without you?
