### ISSUE TITLE
Solution for concatenating multiple datasets with discrete variables

### ISSUE THREAD

**Issue by yuanzhou** [cmu-phil/tetrad#861]
This is an issue that @kvb2univpitt discovered when he was trying to merge multiple discrete datasets (same issue with mixed datasets).

![img_4504](https://user-images.githubusercontent.com/195873/42957592-2a03f200-8b51-11e8-9a80-56c6d729f0b6.jpg)

From this drawing, we can see that each dataset gets encoded when it's being read into tetrad, and by the time we merge these two encoded datasets, we lose the context of the original data. In the combined data, the column of X2 becomes 0-1-0-1. However, it is supposed to be 0-1-1-0 based on the original data.

Another example is if we change the values of X1 in Data2 from A-A to B-B, we'll still have the same encoded categories. And even in the combined data, the X1 column still reads as 0-1-0-0, but it actually should be 0-1-1-1.

We need a solution to resolve this merge problem, and there are two places that will need to apply this solution. One is when combining datasets with added interventional variables, and the other is the existing data concatenation feature:

![capture](https://user-images.githubusercontent.com/195873/42958089-9b0c1d8c-8b52-11e8-9e3b-cd1105e70aac.PNG)

**Comment by kvb2univpitt** [comment]
@yuanzhou Just to be clear, the problem that I discussed with your was for interventional datasets only.  I am not sure what is the intent of the "Concatenate Datasets" function is in Tetrad.  If the "Concatenate Datasets" function is to combine multiple datasets into one big dataset, the code for combine the regular datasets will be different than that of the code for combining datasets for interventional datasets.  We will need to create two separate issues for combining interventional datasets and regular datasets.

**Comment by yuanzhou** [comment]
I'm pulling @jdramsey into this discussion. Is the "Concatenate Datasets" function supposed to combine multiple datasets into one big dataset? 

@kvb2univpitt I agree with you that combining the interventional variables together with other datasets is different from the "Concatenate Datasets" function if it means to only combine multiple datasets into one big dataset. Is there a chance that we can tackle them together and reuse the code?

**Comment by jdramsey** [comment]
@yuanzhou @kvb2univpitt Yeah that's what it's supposed to do, combine multiple datasets into one big dataset. If it's messing up, it should be fixed. Kevin, I seem to remember talking to you about this once.

**Comment by kvb2univpitt** [comment]
@jdramsey Yes, we did discussed about merging discrete multiple datasets into one.  However, it was for combining datasets with interventional variables.   I didn't know about the "Concatenate Datasets" function at that time.  It seems like I need to generalize my function for combining discrete dataset.  Still thinking.

**Comment by jdramsey** [comment]
@kvb2univpitt OK.

**Comment by yuanzhou** [comment]
The fixes that @kvb2univpitt made have been merged into branch `obs_exp_data_zhou`, I'm closing this issue.
