### ISSUE TITLE
R implementation error

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#862]
Hi, from the ccd helpdesk, a user encounter this problem:

I'm having a problem with the R implementation of your tool
when I try to run the example for continuous dataset it gives me this error

Error in .jnew("edu/cmu/tetrad/search/Fges", score) : java.lang.NoClassDefFoundError: Could not initialize class edu.cmu.tetrad.util.TetradLogger

I'm running Ubuntu 16.04. 

Any idea about the reason of this error ?

**Comment by chirayukong** [comment]
I think it is because of the Java path configuration. Try `R CMD javareconf`. Btw, they use the older version of r-causal library. We don't directly call Fges but through the TetradRunner class.

**Comment by cabal-cmu** [comment]
I pass the message send by @chirayukong but the user still had the problem. Here his original message:

Hello, unfortunately it didn't work. I also tried to install that older version you mentioned but I also can't work with it. Had to try on a Windows machine and it worked (for the version that uses Fges)

**Comment by chirayukong** [comment]
@cabal-cmu could you relay a message to the user to try on the docker pre-install R-causal and rstudio container at [https://hub.docker.com/r/chirayukong/r-causal-rstudio/](https://hub.docker.com/r/chirayukong/r-causal-rstudio/)?

**Comment by jdramsey** [comment]
@chirayukong @cabal-cmu Can this be closed? There was no further feedback. It's been over a year now.
