### ISSUE TITLE
implement non-linear tests

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#867]
Including Non parametric independence tests
CCI, RCIT, Kuhn’s KCI test, Jonas Peter’s GCM
Review those that are available
Find out the best

**Comment by espinoj** [comment]
Joe is looking at non-java implementations first prior to java implementation

**Comment by jdramsey** [comment]
I did a presentation on this for the algorithms group (attached). The conclusion we came to was that CCI and KCI should be put in the interface, and we should try to figure out why RCIT and RCoT were giving low recall. I submitted a pull request for CCI, latest version. It includes the fast FDR adjustment.

For KCI, we have Kun's version (Matlab) and mine and Vineet's (Java). The code for both of these is in my branch, but there's the Matlab issue to solve, so I'll move the Java version over when I get a chance. It's already in the interface; this will (like CCI) merely update the underlying algorithm.

For fast FDR, I would like to put that option in every test that takes an alpha value as an argument, but I'll consult on that first.

[NonparametricPresentation.pptx](https://github.com/cmu-phil/tetrad/files/2319287/NonparametricPresentation.pptx)

**Comment by cg09** [comment]
Something I don't understand. On page 15, you find KCI misses one adjacency
out of fifty and misses two orientations out of 24, but has a structural
hamming distance of 24.  How is that possible?

**Comment by jdramsey** [comment]
@espinoj Wow, I had totally forgotten about that presentation. I'd say we stick to the KCI and CCI options, which we already have. They perform the best.

**Comment by jdramsey** [comment]
@espinoj Talking with Clark just now--CCI and KCI are enough. We can close this I think.
