### ISSUE TITLE
Madelyn's (Kuhn's) unmixing algorithm

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#868]

**Comment by jdramsey** [comment]
@mglymour Can you remind me where the unmixing code is living? I think ICA is right now so maybe it will magically improve if given the chance.

**Comment by mglymour** [comment]
The most up-to-date version lives... somewhere on my computer. Want me to dig it up and try it out with the new improved ICA?

**Comment by cg09** [comment]
Absolutely.

**Comment by jdramsey** [comment]
Oh I just found it! It's in the branch demixernongaussian. I pulled all of the code from development into it, as a heavy handed way to get the updated Fast ICA, and adjust the data loading code.

I honestly think it's better. One thing that needs attention though is the orienation of each matrix. The new FAstICA is variables x cases; before it was cases x variables. (I finally gave into the European way of doing things.) So all of the math needs to be adjusted for that.

**Comment by jdramsey** [comment]
@mglymour Oh, sorry, I just registered that you have an even more up to date version--awesome! I'm wondering if you can reconcile that with what's in the branch? That is, whenever you have time. I'm not in a rush, just trying to tie up some loose ends.

**Comment by jdramsey** [comment]
Stale issue--in any case, the old branch with this in it is there, so if we clean up branches I'll look to see if the algorithm can be moved over and quickly debugged, though the codebase is very different now.

Closing for now.
