### ISSUE TITLE
with mixed data set Tetrad 6.5.3-0 forces 1/0 binary to continuous variable

### ISSUE THREAD

**Issue by davidnboone** [cmu-phil/tetrad#880]
[AllgenesTumorTetrad.txt](https://github.com/cmu-phil/tetrad/files/2267380/AllgenesTumorTetrad.txt)
When importing mixed data (all continuous gene expression data except one clinical data column) the importer converts 1/0 binary variable to continuous even when I specify it is a mixed dataset with one discrete variable.

**Comment by espinoj** [comment]
we will have a metadata file option to override automatic determination of variable type in a future release

**Comment by jdramsey** [comment]
@espinoj I think this has been fixed. The 0/1 variables have 2 categories; if you specify that and load as mixed, it gets it right.

**Comment by yuanzhou** [comment]
The metadata file now takes care of this overwriting for each variable.

**Comment by cg09** [comment]
??? Please explain.

**Comment by yuanzhou** [comment]
@cg09 during the development of handling interventional data, Keivn and I added the metadata JSON file reading as part of the data loading. We can specify the data type of each variable in the metadata file, which also means we can overwrite if we want to treat a continuous variable as discrete for a later search algorithm.

**Comment by cg09** [comment]
Thanks.
