### ISSUE TITLE
Data naming or sorting affecting SEARCH results

### ISSUE THREAD

**Issue by hank7v** [cmu-phil/tetrad#881]
I created 3 test.txt files containing the same 6 variables dataset but with differently named or sorted columns. Search (PC All) algorithms using same settings, those 3 datasets + same prior knowledge, gave different results, not dramatically different, but different. May it be the result of stop criteria in searching procedure "cycles" on data and/or knowledge indices?

thanks a lot for any suggestion,

Fabrizio

the pipelines:
![screen shot 2018-08-10 at 12 34 17 2](https://user-images.githubusercontent.com/42272460/43958954-03d0fc62-9ca5-11e8-8fe8-ecf99375637b.png)

the data and results. 
![screen shot 2018-08-10 at 12 30 25 2](https://user-images.githubusercontent.com/42272460/43958958-06593b7a-9ca5-11e8-8a3f-eb577934f8a9.png)

**Comment by cabal-cmu** [comment]
Hi Fabrizio,

Can you send me the tet file for these experiments. Go to File and click on save session. That should generate the tet file. Also, can you let me know which version of Tetrad are you using. 

Thanks.

**Comment by cabal-cmu** [comment]
You can send it to ccd.user.helpdesk@gmail.com

**Comment by cg09** [comment]
Sounds like an order dependence.

**Comment by rubencmu** [comment]
If it is in fact an order dependence, you should try PC-stable, which correct for that problem.




________________________________

**Comment by hank7v** [comment]
Thanks all, 

As suggested, I tried the PC-stable, and it worked for the renamed data (I had to re-inserted the knowledge), but not for the resorted and renamed ones. I eliminated the knowledge, and the results didn't change. 

Fabrizio

PS
I also sent the .tet file to the Help Desk.
