### ISSUE TITLE
Properly Combining Multiple Dataset

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#885]
Need to properly combining multiple discrete datasets or multiple mixed datasets for the "Concatenate Dataset" function.  See issue #861.

**Comment by kvb2univpitt** [comment]
Done.

**Comment by yuanzhou** [comment]
The fixes that @kvb2univpitt made have been merged into branch obs_exp_data_zhou, I'm closing this issue.
