### ISSUE TITLE
Tetrad plugin that allows for experimental external Matlab/R/Python algorithms

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#887]

**Comment by espinoj** [comment]
I think pf4j should be ok for this.

There are three classes for which we will get additional implementations via plugins:
edu.cmu.tetrad.algcomparison.algorithm.Algorithm
edu.cmu.tetrad.algcomparison.score.ScoreWrapper
edu.cmu.tetrad.algcomparison.independence.IndependenceWrapper

We'll also need to add any additional parameters provided in an above implementation not already in edu.cmu.tetrad.util.ParamDescriptions using ParamDescriptions.put(String name, ParamDescription paramDescription) so that the UI has all of the params and descriptions appear at runtime.  Additional param descriptions can be provided by classes by which the plugin manager is able to retrieve and object of Map<String, ParamDescription> and feed into the edu.cmu.tetrad.util.ParamDescriptions singleton at runtime via put().

**Comment by jdramsey** [comment]
Bad idea. Asking for trouble where none exists.
