### ISSUE TITLE
Maybe Bug: SemBicScore.java seems to be missing k in localScore

### ISSUE THREAD

**Issue by tzimiskes** [cmu-phil/tetrad#896]
https://github.com/cmu-phil/tetrad/blob/46a27ae52e18d052f248becce45b2f669eba120b/tetrad-lib/src/main/java/edu/cmu/tetrad/search/SemBicScore.java#L110

I don't know if  `SemBicScore.java` is being used anymore, but it disagrees with how it defined in the FGES paper and in  `SemBicScoreDeterministic.java.`

https://github.com/cmu-phil/tetrad/blob/46a27ae52e18d052f248becce45b2f669eba120b/tetrad-lib/src/main/java/edu/cmu/tetrad/search/SemBicScoreDeterministic.java#L119

Cheers,
Alex Rix

**Comment by jdramsey** [comment]
This is fixed.
