### ISSUE TITLE
Loading csv data gives last row as empty

### ISSUE THREAD

**Issue by cottrell** [cmu-phil/tetrad#902]
There is no extra line at the end of the file. Tried both dos and unix version of file and I consistently get a blank last line in Tetrad after loading the data.

**Comment by jdramsey** [comment]
I noticed this as well. There's a newline at the end of data file. If you delete the newline, the extra line disappears.

**Comment by jdramsey** [comment]
@kvb2univpitt Would it be possible to detect if there's a newline at the end of the data file and ignore it?

**Comment by jdramsey** [comment]
This is not longer an issue.
