### ISSUE TITLE
Put KCI into the development branch

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#908]
This is Kun's nonparametric test. I finally figured out what the difference was between the Java and Matlab versions of KCI and closed the gap. The Matlab version cannot be parallelized, so since it's slow, there's strong motivation to use the Java version. I have the Java version ready to go now and will create a branch to move it to as soon as the CCI branch is merged. It parallelizes fine, with the new fixes to the concurrent FAS.

In general, CCI performs as well or better than KCI in terms of accuracy, but KCI is still needed for the case where errors are multiplicative. Even with adjustments to CCI, KCI still performs much better in this case.

After much deep thought, I have come to the conclusion that the "verbose" parameter should by default be set to "true". This is necessary, in any case for KCI, so the user can watch the tests as they are being done. (The wait is significant, even with two cores.)

@cg09 @espinoj

**Comment by espinoj** [comment]
#910
