### ISSUE TITLE
When is knowledge applied (PC algorithm)?

### ISSUE THREAD

**Issue by bill-raynor** [cmu-phil/tetrad#913]
If this is the wrong place to ask, my apologies. 

I don't read java well, but in looking at the PCstable.java code, it appears that the knowledge is applied to the initial graph (the one with links between all codes). Is this correct?   This would be in contrast to, say, applying it after the skeleton has been developed or after the v-structures and Meek rules have been applied. The latter is the tack chosen in the R pcalg package.

Thanks

**Comment by jdramsey** [comment]
First of all, if edges are required by knowledge, they need to be put in straight away, before anything else, and never taken out.  This needs to be done before the adjacency phase has begun. Also, when trying to remove an edge X--Y by condition on some set S, say X _||_ Y | S, S cannot contain variables that are not at least potential parents of X or Y (depending on whether S is taken to be a subset of X or of Y). Let Z be such a variable. If the edge Z->X is forbidden or Z->Y (depending on which side you're looking at), then Z cannot be in S. It can't be a parent of X, so you can't condition on it.

I take it pcalg doesn't take these subtleties into account?

**Comment by cg09** [comment]
Ouch! I guess we should have noted that about pcalg in your review.

Clark

**Comment by cg09** [comment]
So, why not use the TETRAD version of PC?

cg

**Comment by bill-raynor** [comment]
Good question. I'm asking myself that right now!

Driven by two things: 
1. The paired comparisons are ordinal trinomial, where each person is a block (choose option A, not much difference, choose option B). The options are bundles, not univariate. 

It is straightforward to demonstrate that the Pearson r or Kendall tau varies across strata, where each person is a block within the strata, so the usual gaussian result that the conditional correlation is constant across the conditioning variables does not hold. That also shows up as lots of negative partial correlations that are known to be physically positive when I close my eyes and pretend the data are gaussian.  Also standard correlations (between people) are cross-sectional, while is the data and the questions are longitudinal. (How many people will change their choices if...)

The "monadic" ratings are implicit paired comparisons since we know each subject's regular product. The five point scale in this latter case is also wildly different between people. (not a simple shift as in a location family for, say, an RCB or BIB) 

2.  I'm doing this for someone else to who needs a plug and chug standard analysis that doesn't require a high level stats person (me) to estimate attributable effects along with various what-if questions. (e.g. changing market structure, or what if we make these three changes). I'm retired and wouldn't want to spend all my time doing this. 

So I need package in which I can easily modify the CI tests. and that I can drop as a package into a functioning system, usable by, say, a typical market research analyst or an  IT guy. As I mentioned at the beginning, I don't understand Java that well, but have a better understanding of data handling with R (and SAS of course).  I've done different systems (not causal models) using SAS in the past. SAS' cost is a sticking point.  

TETRAD was my main tool for search when I was one the doing the analyses. I particularly  liked the Tiers and constraints in TETRAD. I wrote custom SAS code to estimate the effects in a fashion that could be used by normal users, typically some form of ordinal logistic or Cox model.  The graph was very useful for explaining the interrelationships of items or cliques of items.

**Comment by cg09** [comment]
We are about to implement some non-Gaussian conditional independence tests,
which might be of use in a problem like yours, so far as I understand it. I
guess we should implement a logistic regression estimator...which we have
only done impeded in a search over data with mixed variable types.

Cg
