### ISSUE TITLE
Additional parameter type to handle integer and boolean 

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#916]

**Comment by espinoj** [comment]
Example is max degree where -1 signifies infinite but integers indicate the max degree value.  We could break this out into two parameters but need to extend the parameter object to properly handle this (i.e., not a hack)

**Comment by jdramsey** [comment]
Will re-add this if anyone complains about it among our actual users. :) Closing.

**Comment by cg09** [comment]
Boolean would be useful for instruction and the occasional computer
scientist might use it.
