### ISSUE TITLE
Example CPC with arrays from program code - instantiating class and passing arguments directly

### ISSUE THREAD

**Issue by betrw** [cmu-phil/tetrad#926]
I would like to include the CPC algorithm with a graph in my java project. Could you give me an example how to use the algorithm with double[] or double[][] directly please?

**Comment by bja43** [comment]
The PC algorithm requires an independence test and an initial graph. The initial graph may be set to null in the case where you do not have one, but you will have to define the test.  For argument's sake, let's say you want to use the FisherZ test. This test requires a DataSet object and an alpha level. The DataSet object may be constructed from a double[][] and a list of String objects (your variable names). The alpha level needs to be a double. After these objects have been created, you may use edu.cmu.tetrad.search.PcAll, and set its rules such that it performs the CPC search. Please see an example below: 


        double[][] data;
        List<String> variables;
        double alpha = 0.01;

        DataModel dataSet = new BoxDataSet(new DoubleDataBox(data), variables);

        IndTestFisherZ test = new IndTestFisherZ(((DataSet) dataSet), alpha);
        PcAll algorithm = new PcAll(test, null);
        algorithm.setFasType(edu.cmu.tetrad.search.PcAll.FasType.REGULAR);
        algorithm.setConcurrent(edu.cmu.tetrad.search.PcAll.Concurrent.NO);
        algorithm.setColliderDiscovery(PcAll.ColliderDiscovery.CONSERVATIVE);
        algorithm.setConflictRule(edu.cmu.tetrad.search.PcAll.ConflictRule.PRIORITY);
        
        Graph output = algorithm.search();

**Comment by bja43** [comment]
My mistake, the variables object should be a list of Node objects. Suppose you have a list of String objects, then you may create the variables object as follows:

        List<String> nodes;
        
        List<Node> variables = new ArrayList<>();
        for (String node : nodes) {
            variables.add(new ContinuousVariable(node));
        }
