### ISSUE TITLE
Command line Tetrad

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#937]
Hi,

Is it possible to choose a DAG in a pattern (eg, from a fGES run) in command line tetrad ?

Ruben

**Comment by kvb2univpitt** [comment]
@rubenSaro Can you please show me how you would do that in tetrad-gui via screenshots?

**Comment by rubenSaro** [comment]
Sure. 

I made a graph, simulated data, search with fGES which output a pattern, and then choose a Graph box with option "choose dag in pattern"

<img width="1440" alt="screen shot 2018-11-30 at 3 43 21 pm" src="https://user-images.githubusercontent.com/40474901/49314022-257de400-f4b7-11e8-861e-6acf5dfe48df.png">
<img width="1440" alt="screen shot 2018-11-30 at 3 43 30 pm" src="https://user-images.githubusercontent.com/40474901/49314024-2747a780-f4b7-11e8-9574-ed11a2585f77.png">
<img width="1440" alt="screen shot 2018-11-30 at 3 43 33 pm" src="https://user-images.githubusercontent.com/40474901/49314035-2c0c5b80-f4b7-11e8-8850-e97e1535a470.png">

**Comment by chirayukong** [comment]
https://github.com/bd2kccd/causal-cmd/pull/39

**Comment by chirayukong** [comment]
Just another option --choose-dag-in-pattern and you should get a dag.
