### ISSUE TITLE
Is it possible to batch train?

### ISSUE THREAD

**Issue by marchezinixd** [cmu-phil/tetrad#940]
Hello, i'd like to know if it's possible to learn the structure using the CMD but in batches. I have a dataset with 400 columns and 20 Million rows. Apparently 40GB of ram is not enough so i'd like to batch train it if possible.
I know that the method work with probability and D-separation and because of this we can't sample the data, but i'm not sure if it's possible or if it's already implemented to batch train it

**Comment by marchezinixd** [comment]
Hello again, just to confirm should I use the covariance matrix or the correlation matrix? In your text you said covariance, but the image looks pretty much with correlation.

**Comment by cg09** [comment]
Should make no difference.

**Comment by jdramsey** [comment]
What algorithm is this for? If for FGES, probably covariance is better. -Joe

**Comment by marchezinixd** [comment]
Thank you very much. I'm using FGES. I'll try it and give feedback soon

**Comment by marchezinixd** [comment]
Hello, I'll close this issue. Using the covariance matrix for the FGES method is a lot faster and use almost nothing of RAM, i don't need to batch train anymore. Everything worked right.
