### ISSUE TITLE
Additional data reader inferences

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#945]
We should be able to provide additional guesses by reading the first few lines of an input file. i.e.,  quote character usage,  comment characters,  continuous vs. discrete data

**Comment by jdramsey** [comment]
@kvb2univpitt It seems this has all been done, no?

**Comment by kvb2univpitt** [comment]
I think we settled with file delimiter inference, which is done.

**Comment by jdramsey** [comment]
@espinoj I guess this is up to you; can we close this?

**Comment by jdramsey** [comment]
@espinoj Sorry to close so many issues, but I'm getting lost in the issues list. I'm only closing ones I know can be close.

**Comment by jdramsey** [comment]
This has been done.
