### ISSUE TITLE
Revise bootstrap table 

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#946]
Use mutually exclusive exhaustive columns:

```
none
-->  
<--  
-G>  pd nl
<G-  pd nl
=G>  dd nl
<G=  dd nl
o->
<-o
o-o
<->
---
```

**Comment by chirayukong** [comment]
https://github.com/cmu-phil/tetrad/tree/fix-issue-946
The session file having a new bootstrapping table was also attached.
[new_bootstapping_table.tet.zip](https://github.com/cmu-phil/tetrad/files/2641183/new_bootstapping_table.tet.zip)
