### ISSUE TITLE
output graph png of low quality

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#951]
Hi,
In the Tetrad GUI, when saving as png an instantiated graph from the IM box, the file is of very poor quality. See attached. Can the quality be improved.

Thanks

Ruben
![image4](https://user-images.githubusercontent.com/40474901/49312283-b5b92a80-f4b1-11e8-8ea1-ad9c8bf9097f.png)

**Comment by jdramsey** [comment]
Fixed.
