### ISSUE TITLE
Need to eliminate the old DataReader from the code.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#953]
I've noticed some thorny problems coming up for people because this (deprecated) API is still in the code, and they're tempted to use it. For instance, the getDoubleData() method does odd things now. Probably best to just get rid of it.

**Comment by yuanzhou** [comment]
I'll mention this to the team today since @kvb2univpitt updated the data reader with metadata support and I've been using that in my branch for interventional data handling. Soon we'll merge the new data reader to development and it's a good time to eliminate the old data reader.

**Comment by yuanzhou** [comment]
@jdramsey I talked to @kvb2univpitt and the current development is using his fast data reader as dependency. Can you point us to the deprecated data reader API in the code so we know exactly what the code is?

**Comment by jdramsey** [comment]
Sure, it's edu.cmu.tetrad.data.DataReader. It's already deprecated. If there are any uses due to me, let me know and I'll recode them.

Like I said, the problem is, it doesn't behave correctly anymore, and we have a good data reader, so there's no point allowing the errors.

Thanks!

**Comment by yuanzhou** [comment]
After looking at the deprecated DataReader and its usage, I think we can come up with a plan like this:

1. Rename this DataReader to a different name, even though it has the `@Deprecated` annotation, just to avoid any mis-use with the new `edu.pitt.dbmi.data.reader.DataReader` interface.

2. We first merge the new data reader into development for the upcoming release.

3. Replace some of the functionalities of this old data reader with the new data reader. Also because this data reader is being used in a bunch of classes including reading knowledge file, we'll need to migrate carefully.

4. Create a new reader for parsing knowledge files, it also requires to finalize the format of knowledge file.

**Comment by yuanzhou** [comment]
@jdramsey can we clean up the deprecated `edu.cmu.tetrad.data.DataReader` for the release purpose?

I still see the following places are using this old DataReader.

![Capture](https://user-images.githubusercontent.com/195873/56967927-3008dc00-6b30-11e9-8b88-5582c23cc4cb.PNG)

**Comment by kvb2univpitt** [comment]
@yuanzhou We still need the old data reader to parse knowledge file.  We haven't isolated the knowledge file parsing function out of the old data reader yet.

**Comment by yuanzhou** [comment]
So I went through those files and found the following usage of this old DataReader:

````
DataReader reader = new DataReader();
 IKnowledge knowledge = reader.parseKnowledge(file);
````

````
DataReader reader = new DataReader();
data = reader.parseTabular(new File(name));
````

````
DataReader reader = new DataReader();
reader.setVariablesSupplied(false);
````

````
DataReader reader = new DataReader();
reader.setDelimiter(DelimiterType.WHITESPACE);
````

````
DataReader reader = new DataReader();
reader.setMissingValueMarker("-99");
reader.setMaxIntegralDiscrete(5);
````

@kvb2univpitt you are right we still need it for parsing knowledge file and I'm not sure if `reader.parseTabular` can be replaced by the new DataReader, probably not? The rest of the places seem to be not to hard to recode. @jdramsey any suggestions?

**Comment by jdramsey** [comment]
@yuanzhou I was going to say, some of those imports could just be deleted.

**Comment by jdramsey** [comment]
@yuanzhou Do you remember which files those (actual) usages were in?

**Comment by jdramsey** [comment]
@yuanzhou @kvb2univpitt Also, I don't remember what the problem was with moving the old data parser. Do you see a problem?

**Comment by kvb2univpitt** [comment]
@jdramsey I don't see a problem.  As the matter of fact, I suggested we should rename it to Knowledge parser, because that's what it will become after we remove all the tabular data functions.

**Comment by yuanzhou** [comment]
Currently we use this old DataReader in:

1. KnowledgeBoxEditor
2. LoadKnowledgeAction
3. YeastPcCcdSearchWrapper
4. ExternalAlgorithmBNTPc
5. ExternalAlgorithmPcalgPc
6. LoadContinuousDataAndGraphs
7. LoadContinuousDataAndSingleGraph
8. LoadContinuousDataSmithSim
9. LoadDataAndGraphs
10. LoadDataFromFileWithoutGraph
11. MbClassify
12. MixedUtils
13. ExploreAutisticsNeurotypicals
14. FaskGraphs
15. LoadContinuousDataAndSingleGraph
16. LoadContinuousDataAndSingleGraphKun
17. LoadContinuousDataSmithSim
18. LoadMadelynData

And a bunch of test files. I did see some are just imports. But the ones I listed above are calling this DataReader. So you can find the usage in your IDE.

**Comment by jdramsey** [comment]
@yuanzhou I'll try to resolve these today, at least all but the parseKnowledge issue.

**Comment by jdramsey** [comment]
Done.
