### ISSUE TITLE
Problem with subsetting mixed data

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#957]
When I try to use the subsetRows() method on a mixed dataset in tetrad-development, downloaded 11/08/18, instead of subsetting the dataset, it just deletes the values from all the other rows, leaving them with missing values. I can't get rid of those rows no matter what I do, even by using the removeRows() method. The problem doesn't show up with continuous or discrete data.

**Comment by chirayukong** [comment]
https://github.com/cmu-phil/tetrad/pull/978

**Comment by jdramsey** [comment]
Actually this is fixed and can be closed.
