### ISSUE TITLE
estimator --> updater, why it doesn't work?

### ISSUE THREAD

**Issue by hank7v** [cmu-phil/tetrad#958]
I would aspect an updater to be able to receive the output of an EM Bayes Estimator, as it happens for the output of an Instantiated Model. Instead, it doesn't work. Is it correct?

**Comment by cg09** [comment]
Can you be more specific about the problem, and Tetrad version, please?

**Comment by hank7v** [comment]
Sure,

tetrad 6.5.4

![screen shot 2018-12-09 at 19 19 11](https://user-images.githubusercontent.com/42272460/49701689-4ea12180-fbe7-11e8-9f4e-637e2959d14e.png)

**Comment by cg09** [comment]
Try connecting the Estimation Box to an IM Box and the IM Box to the
Updater.

**Comment by hank7v** [comment]
Thanks,
yes, I tried it, but unfortunately, it didn't work as well.

![screen shot 2018-12-09 at 20 56 12](https://user-images.githubusercontent.com/42272460/49702828-fa04a300-fbf4-11e8-8c2b-ef02d1bf3396.png)
dn't work

**Comment by cg09** [comment]
Delete the Estimator -> Updater connection and substitute an IM -> Updator
connection.

**Comment by hank7v** [comment]
As mentioned, IM --> updater works, but if I use an IM instead of an Estimator, I have to manually (or randomly) populate the probability tables, instead, I would like to estimate from data and model the table, and then simulate intervention (updater) ln the estimated table. Isn't it possible?

**Comment by cg09** [comment]
The IM should be automatically populated from  an estimated model, as
described previously.

**Comment by hank7v** [comment]
Thus, do you think the software is not working properly? If I connect the IM to the PM it is not populated (my options are random or manual), and if I connect it to the Estimator it returns an error. 

![screen shot 2018-12-10 at 16 09 22](https://user-images.githubusercontent.com/42272460/49745125-2a504e00-fc96-11e8-860a-5e17259cf1e2.png)

**Comment by hank7v** [comment]
I downloaded TETRAD version 4.3.9 and it works, do you have any idea how is it?

![screen shot 2018-12-10 at 18 06 00](https://user-images.githubusercontent.com/42272460/49751805-4a880900-fca6-11e8-9c56-907ee4e69f87.png)

**Comment by hank7v** [comment]
And it also works in version 6.4.0

**Comment by hank7v** [comment]
downloaded again version 6.5.4-0, and it worked with a newly created session. Loaded old session, it doesn't work. Something got corrupted in my previous session. Sorry for having discovered it only now, and thanks for the support,
