### ISSUE TITLE
data wrapper

### ISSUE THREAD

**Issue by abbasalipour** [cmu-phil/tetrad#962]
how do I convert a continuous variable to discrete in data wrapper? When I enter the numbers manually, it is continuous default and I want it to be discrete. I can't find it in sitting or everywhere....?

**Comment by cg09** [comment]
Connect your data wrapper to a data box, open it, there is a link for converting continuous variables to categorical.

**Comment by abbasalipour** [comment]
> Connect your data wrapper to a data box, open it, there is a link for converting continuous variables to categorical.

thanks dear
I have two questionnaires which have 100 data and 60 data between 1 to 5, the first question is: can I use from tetrad for analysis my data or no? and second is: if these discrete numeral are (1,2,3,4,5) valid; I have two problems which attaches them
thanks
![2019-01-07 2](https://user-images.githubusercontent.com/46406150/50742402-e3676100-121f-11e9-8a8a-156014bcde54.png)
![2019-01-07 1](https://user-images.githubusercontent.com/46406150/50742404-eeba8c80-121f-11e9-8e59-8720c572522b.png)
