### ISSUE TITLE
Print out BIC scores per node

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#971]
This may already be planned, but in discussions with Jinling, it would be helpful not only to print BIC scores for entire models but also BIC scores for each node given its parents in a model.

**Comment by espinoj** [comment]
I spoke to Jinling about this feature and we will promote it.  We've put the BIC score output in development branch (i.e., outputs to the log in tetrad and causal cmd).  Is the score given the parents for each node in there but also not printed out?

**Comment by jdramsey** [comment]
Well, it's part of the algorithm; if it's not exposed, it can easily be exposed. Let me know if I can help.

For example, if you calculate the BIC for a DAG, that's the sum of the BIC scores for each node given its parents. You just need to get the part of that method that calculates the BIC score for a node given its parents and call it for each node.

**Comment by chirayukong** [comment]
Here we go: https://github.com/cmu-phil/tetrad/pull/975
