### ISSUE TITLE
estimator

### ISSUE THREAD

**Issue by abbasalipour** [cmu-phil/tetrad#974]

**Comment by abbasalipour** [comment]
I wanted to know why the probabilities of this part of the estimator that I used to send my photo,
![tet](https://user-images.githubusercontent.com/46406150/52920663-6e11a480-3324-11e9-8bc3-308fc1be2c70.PNG)
 are unbalanced and, for example, the probabilities did not go up or down from top to bottom ... Is this a problem with my software or data?

**Comment by jdramsey** [comment]
There's no need for them to be sorted within each column, but they should add to 1 in each row, which they do. The order of the L1-L6 columns is as it is in a  truth table.
