### ISSUE TITLE
Command line version 0.5.0 development bug

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#982]
There is a bug in the resampling option  --percentResampleSize

It still takes integers, as the old version, properly, the number of datapoints of the resamples.

I assumed this new version was intended to take fractions as 0.1 (10%)  up to 1 (100% of the sample)

Ruben

**Comment by jdramsey** [comment]
It may be helpful to say which algorithm you're having trouble with; I noticed a couple of the algorithms hadn't been converted over to the new system.

**Comment by rubenSaro** [comment]
pc-all

**Comment by chirayukong** [comment]
It should take double as input for percentResampleSize and 10 means 10%. You can go beyond 100%.

**Comment by rubenSaro** [comment]
Thanks. This should go in the description to avoid confusion.

**Comment by rubenSaro** [comment]
So, if I want my resamples to be the same size of the sample I should input
--percentResampleSize 100  ?


R.

**Comment by chirayukong** [comment]
Yep.

**Comment by rubenSaro** [comment]
What is wierd is that I tried it, and I am getting results with number of
edges as if I were taking only 100 datapoints and not 100% of the
datapoints of the original dataset.

That is why I thought the parameter had a bug or was actually taking the
number of datapoints as before.

**Comment by rubenSaro** [comment]
My mistake, I was using a very high penalty, that is why the graphs were so
sparse and not because the percentResampleSize,

oops, I owe you guys a beer.

**Comment by rubenSaro** [comment]
one more question, what is an error of -9

**Comment by jdramsey** [comment]
@rubenSaro I don't know who you were offering the beer to, but I didn't get one. Just saying. Maybe it's because I didn't now what error -9 was? :)

**Comment by espinoj** [comment]
this will remain open until Ruben buys us beer.

**Comment by rubenSaro** [comment]
hahah I will get you guys beer next time I visit Pittsburgh.
