### ISSUE TITLE
Java error message question 

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#990]
@jdramsey @espinoj 

HI, I am running Tetrad command line in a supercomputer... After a day of running many FGES instances corresponding to different datasets, I start to get the next messages:

WARNING: Prefs file removed in background /home/rs1739/.java/.userPrefs/prefs.xml
Mar 08, 2019 1:10:07 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 2.
Mar 08, 2019 1:10:07 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.

Any idea what could be happening ? Thanks.

**Comment by jdramsey** [comment]
I don't know, sorry. -Joe

**Comment by kvb2univpitt** [comment]
@rubenSaro Maybe it has to do with the filesystem.  Do you know what's the filesystem is on the server?  Also, what version of tetrad command line are you using?

**Comment by jdramsey** [comment]
@rubenSaro Can we close this?

**Comment by rubenSaro** [comment]
yes

**Comment by jdramsey** [comment]
Yay!
