### ISSUE TITLE
Multiple Graphs Not Shown for non-MultiDataSetAlgorithm.

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#991]
When running FGES, a non-MultiDataSetAlgorithm, on multiple imported datasets, multiple graphs (one graph for each dataset) are not shown.

**Comment by kvb2univpitt** [comment]
Fixed.  See branch v6.7.0-multiple_graph_display

![Screenshot from 2019-03-25 16-36-50](https://user-images.githubusercontent.com/10729309/54952617-cc7e0400-4f1c-11e9-893a-b4a8e99a9f06.png)

**Comment by jdramsey** [comment]
Thanks!
