### ISSUE TITLE
Text search algorithm explanation now showing in field within search dialog box

### ISSUE THREAD

**Issue by rws2** [cmu-phil/tetrad#993]
Although my peers see the explanatory text within the right text box within the Search Algorithm dialog window, my text box remains blank for all algorithms and for all Tetrad GUI releases that I have on my computer.

**Comment by kvb2univpitt** [comment]
What version of Tetrad are you using?

**Comment by yuanzhou** [comment]
I think I've addressed this issue by ALWAYS using the HTML manual within the jar. Previously we were going to the github pages for the algorithm descriptions.
