### ISSUE TITLE
Cannot copy the output of Bayes estimator into an IM

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#995]

**Comment by jdramsey** [comment]
It works for me, but I get this dialogue coming up that makes me thinks it's going to rewrite the IM. The dialog needs to go; when you open it up, it's right right IM, just the copy of the original.

<img width="565" alt="Screen Shot 2019-03-30 at 3 21 32 PM" src="https://user-images.githubusercontent.com/9853255/55280705-8c919500-52ff-11e9-94db-32bf50d0452a.png">

**Comment by jdramsey** [comment]
Hold it, that's not a bug; select manual and the parameters are copied over. With a little work, the "Randomly" option could be removed, or the "manual" option renamed for this context. But, no bug here.
