### ISSUE TITLE
Cannot generate data from an estimation box

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#998]
We need to be able to do this in order to generate new samples from an estimated model to repeat searches for how stably they recover the structure from data generated from it.  The PM box will not fill from an Estimation box.

**Comment by cg09** [comment]
I meant IM box, not PM box

**Comment by jdramsey** [comment]
You need to use a Simulate box, not a Data box, then it works, at least for me. I.e.,

Estimate->Simulate

not

Estimate->Data

This is an issue for the manual maybe--everywhere in Tetrad where data is being simulated, a Simulate box needs to be used. Data is only for data loaded from a file, or for manipulations of data.
