### ISSUE TITLE
Estimate box will not populate updater

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#999]
REferencing TETRAd 6.7.0-0. The output in the Estimator box will not populate the Update box (which makes the estimates useless for prediction.) Neither will the Simulation box be populated, as noted previously.

**Comment by jdramsey** [comment]
I think this should be easy to fix.

**Comment by cg09** [comment]
But not as easily done as said!

**Comment by jdramsey** [comment]
Sorry, I just reported this. This is working for me, so I think it was fixed.
